registerWordbook('scene_fitness', {
    name: "运动健身",
    emoji: "🏋️",
    group: 'scene',
    description: "球类、健身器材、运动动作相关词汇",
    levels: {
        all: {
            name: "🏋️ 全部",
            words: [
                { word: "abs", meaning: "腹肌", audio: "abs.wav" },
                { word: "aerobic", meaning: "有氧运动", audio: "aerobic.wav" },
                { word: "agile", meaning: "敏捷的", audio: "agile.wav" },
                { word: "arch", meaning: "弓步; 拱背", audio: "arch.wav" },
                { word: "athletics", meaning: "田径运动", audio: "athletics.wav" },
                { word: "balance", meaning: "平衡", audio: "balance.wav" },
                { word: "ball", meaning: "球", audio: "ball.wav" },
                { word: "band", meaning: "弹力带; 阻力带", audio: "band.wav" },
                { word: "bar", meaning: "杠; 单杠", audio: "bar.wav" },
                { word: "barbell", meaning: "杠铃", audio: "barbell.wav" },
                { word: "basketball", meaning: "篮球", audio: "basketball.wav" },
                { word: "bat", meaning: "球棒", audio: "bat.wav" },
                { word: "bench", meaning: "卧推凳", audio: "bench.wav" },
                { word: "bend", meaning: "弯曲", audio: "bend.wav" },
                { word: "bicycle", meaning: "自行车", audio: "bicycle.wav" },
                { word: "block", meaning: "拦截", audio: "block.wav" },
                { word: "body", meaning: "身体", audio: "body.wav" },
                { word: "bounce", meaning: "弹跳", audio: "bounce.wav" },
                { word: "bowl", meaning: "投球; 保龄球", audio: "bowl.wav" },
                { word: "box", meaning: "拳击", audio: "box.wav" },
                { word: "breathe", meaning: "呼吸", audio: "breathe.wav" },
                { word: "burn", meaning: "燃烧(卡路里)", audio: "burn.wav" },
                { word: "cardio", meaning: "有氧运动", audio: "cardio.wav" },
                { word: "catch", meaning: "抓住", audio: "catch.wav" },
                { word: "chase", meaning: "追赶", audio: "chase.wav" },
                { word: "chest", meaning: "胸部", audio: "chest.wav" },
                { word: "circuit", meaning: "循环训练", audio: "circuit.wav" },
                { word: "climb", meaning: "攀爬; 攀岩", audio: "climb.wav" },
                { word: "club", meaning: "球杆; 俱乐部", audio: "club.wav" },
                { word: "coach", meaning: "教练", audio: "coach.wav" },
                { word: "compete", meaning: "比赛; 参赛", audio: "compete.wav" },
                { word: "cool", meaning: "放松整理; 冷身", audio: "cool.wav" },
                { word: "core", meaning: "核心肌群", audio: "core.wav" },
                { word: "court", meaning: "球场", audio: "court.wav" },
                { word: "cramp", meaning: "抽筋", audio: "cramp.wav" },
                { word: "cross", meaning: "交叉训练", audio: "cross.wav" },
                { word: "curl", meaning: "弯举", audio: "curl.wav" },
                { word: "cycle", meaning: "骑车", audio: "cycle.wav" },
                { word: "dash", meaning: "冲刺", audio: "dash.wav" },
                { word: "defend", meaning: "防守", audio: "defend.wav" },
                { word: "dive", meaning: "潜水", audio: "dive.wav" },
                { word: "dodge", meaning: "闪避", audio: "dodge.wav" },
                { word: "drill", meaning: "训练", audio: "drill.wav" },
                { word: "dumbbell", meaning: "哑铃", audio: "dumbbell.wav" },
                { word: "endurance", meaning: "耐力", audio: "endurance.wav" },
                { word: "energy", meaning: "活力", audio: "energy.wav" },
                { word: "equipment", meaning: "器材; 运动装备", audio: "equipment.wav" },
                { word: "exercise", meaning: "锻炼", audio: "exercise.wav" },
                { word: "extend", meaning: "伸展", audio: "extend.wav" },
                { word: "fat", meaning: "脂肪", audio: "fat.wav" },
                { word: "field", meaning: "场地", audio: "field.wav" },
                { word: "fit", meaning: "健康的; 健壮的", audio: "fit.wav" },
                { word: "fitness", meaning: "健身", audio: "fitness.wav" },
                { word: "flex", meaning: "屈伸", audio: "flex.wav" },
                { word: "football", meaning: "足球", audio: "football.wav" },
                { word: "goal", meaning: "进球; 目标", audio: "goal.wav" },
                { word: "golf", meaning: "高尔夫球", audio: "golf.wav" },
                { word: "grip", meaning: "紧握", audio: "grip.wav" },
                { word: "gym", meaning: "健身房", audio: "gym.wav" },
                { word: "handball", meaning: "手球", audio: "handball.wav" },
                { word: "health", meaning: "健康", audio: "health.wav" },
                { word: "heart", meaning: "心率", audio: "heart.wav" },
                { word: "hockey", meaning: "曲棍球", audio: "hockey.wav" },
                { word: "hydrate", meaning: "补水", audio: "hydrate.wav" },
                { word: "injury", meaning: "受伤", audio: "injury.wav" },
                { word: "instructor", meaning: "教练; 指导员", audio: "instructor.wav" },
                { word: "interval", meaning: "间歇训练", audio: "interval.wav" },
                { word: "jog", meaning: "慢跑", audio: "jog.wav" },
                { word: "jump", meaning: "跳", audio: "jump.wav" },
                { word: "kick", meaning: "踢", audio: "kick.wav" },
                { word: "knee", meaning: "膝盖", audio: "knee.wav" },
                { word: "lap", meaning: "圈", audio: "lap.wav" },
                { word: "lean", meaning: "精瘦的; 倾身", audio: "lean.wav" },
                { word: "leg", meaning: "腿", audio: "leg.wav" },
                { word: "lift", meaning: "举起", audio: "lift.wav" },
                { word: "lunge", meaning: "弓步", audio: "lunge.wav" },
                { word: "marathon", meaning: "马拉松", audio: "marathon.wav" },
                { word: "mat", meaning: "垫子", audio: "mat.wav" },
                { word: "match", meaning: "比赛", audio: "match.wav" },
                { word: "medal", meaning: "奖牌", audio: "medal.wav" },
                { word: "motion", meaning: "动作", audio: "motion.wav" },
                { word: "muscle", meaning: "肌肉", audio: "muscle.wav" },
                { word: "net", meaning: "网", audio: "net.wav" },
                { word: "pace", meaning: "步伐", audio: "pace.wav" },
                { word: "paddle", meaning: "球拍", audio: "paddle.wav" },
                { word: "pass", meaning: "传球", audio: "pass.wav" },
                { word: "pedal", meaning: "踏板", audio: "pedal.wav" },
                { word: "pitch", meaning: "球场", audio: "pitch.wav" },
                { word: "plank", meaning: "平板支撑", audio: "plank.wav" },
                { word: "play", meaning: "参赛; 打(球)", audio: "play.wav" },
                { word: "pool", meaning: "泳池", audio: "pool.wav" },
                { word: "pose", meaning: "姿势", audio: "pose.wav" },
                { word: "press", meaning: "推举", audio: "press.wav" },
                { word: "protein", meaning: "蛋白质", audio: "protein.wav" },
                { word: "pull", meaning: "拉", audio: "pull.wav" },
                { word: "pulse", meaning: "脉搏", audio: "pulse.wav" },
                { word: "punch", meaning: "拳打", audio: "punch.wav" },
                { word: "push", meaning: "推", audio: "push.wav" },
                { word: "race", meaning: "赛跑; 比赛", audio: "race.wav" },
                { word: "racket", meaning: "球拍", audio: "racket.wav" },
                { word: "recover", meaning: "恢复", audio: "recover.wav" },
                { word: "rep", meaning: "次数", audio: "rep.wav" },
                { word: "rest", meaning: "休息", audio: "rest.wav" },
                { word: "ring", meaning: "拳击场; 吊环", audio: "ring.wav" },
                { word: "rope", meaning: "绳索", audio: "rope.wav" },
                { word: "row", meaning: "划船运动; 划船机", audio: "row.wav" },
                { word: "rugby", meaning: "橄榄球", audio: "rugby.wav" },
                { word: "run", meaning: "跑步", audio: "run.wav" },
                { word: "serve", meaning: "发球", audio: "serve.wav" },
                { word: "set", meaning: "组(一组动作)", audio: "set.wav" },
                { word: "shoot", meaning: "投篮; 射门", audio: "shoot.wav" },
                { word: "ski", meaning: "滑雪", audio: "ski.wav" },
                { word: "skip", meaning: "跳绳", audio: "skip.wav" },
                { word: "slam", meaning: "猛扣; 大力扣杀", audio: "slam.wav" },
                { word: "soccer", meaning: "足球", audio: "soccer.wav" },
                { word: "speed", meaning: "速度", audio: "speed.wav" },
                { word: "spin", meaning: "旋转", audio: "spin.wav" },
                { word: "sprint", meaning: "冲刺", audio: "sprint.wav" },
                { word: "squat", meaning: "深蹲", audio: "squat.wav" },
                { word: "stadium", meaning: "体育场", audio: "stadium.wav" },
                { word: "stamina", meaning: "耐力", audio: "stamina.wav" },
                { word: "step", meaning: "步", audio: "step.wav" },
                { word: "stretch", meaning: "拉伸", audio: "stretch.wav" },
                { word: "stride", meaning: "步幅", audio: "stride.wav" },
                { word: "strike", meaning: "击打", audio: "strike.wav" },
                { word: "stroke", meaning: "划水动作", audio: "stroke.wav" },
                { word: "surf", meaning: "冲浪", audio: "surf.wav" },
                { word: "sweat", meaning: "汗水", audio: "sweat.wav" },
                { word: "swim", meaning: "游泳", audio: "swim.wav" },
                { word: "swing", meaning: "挥动; 挥拍", audio: "swing.wav" },
                { word: "team", meaning: "团队", audio: "team.wav" },
                { word: "tennis", meaning: "网球", audio: "tennis.wav" },
                { word: "throw", meaning: "扔", audio: "throw.wav" },
                { word: "track", meaning: "跑道", audio: "track.wav" },
                { word: "train", meaning: "训练", audio: "train.wav" },
                { word: "trainer", meaning: "教练员", audio: "trainer.wav" },
                { word: "treadmill", meaning: "跑步机", audio: "treadmill.wav" },
                { word: "trophy", meaning: "奖杯", audio: "trophy.wav" },
                { word: "volleyball", meaning: "排球", audio: "volleyball.wav" },
                { word: "walk", meaning: "走", audio: "walk.wav" },
                { word: "warm", meaning: "热身(warm up)", audio: "warm.wav" },
                { word: "weight", meaning: "哑铃; 负重", audio: "weight.wav" },
                { word: "wrestle", meaning: "摔跤", audio: "wrestle.wav" },
                { word: "yoga", meaning: "瑜伽", audio: "yoga.wav" }
            ]
        }
    }
});
