registerWordbook('scene_music', {
    name: "音乐乐器",
    emoji: "🎵",
    group: 'scene',
    description: "乐器名称、音乐术语、流派相关词汇",
    levels: {
        all: {
            name: "🎵 全部",
            words: [
                { word: "acoustic", meaning: "原声的", audio: "acoustic.wav" },
                { word: "album", meaning: "专辑", audio: "album.wav" },
                { word: "alto", meaning: "中音", audio: "alto.wav" },
                { word: "amplifier", meaning: "放大器", audio: "amplifier.wav" },
                { word: "applause", meaning: "掌声", audio: "applause.wav" },
                { word: "arrange", meaning: "安排", audio: "arrange.wav" },
                { word: "audience", meaning: "观众", audio: "audience.wav" },
                { word: "auditorium", meaning: "音乐厅", audio: "auditorium.wav" },
                { word: "band", meaning: "乐队", audio: "band.wav" },
                { word: "bass", meaning: "低音", audio: "bass.wav" },
                { word: "beat", meaning: "打", audio: "beat.wav" },
                { word: "bell", meaning: "钟", audio: "bell.wav" },
                { word: "blow", meaning: "吹", audio: "blow.wav" },
                { word: "blues", meaning: "蓝调", audio: "blues.wav" },
                { word: "bow", meaning: "弓", audio: "bow.wav" },
                { word: "brass", meaning: "铜管乐器", audio: "brass.wav" },
                { word: "broadcast", meaning: "播送", audio: "broadcast.wav" },
                { word: "carol", meaning: "颂歌", audio: "carol.wav" },
                { word: "cello", meaning: "大提琴", audio: "cello.wav" },
                { word: "chamber", meaning: "室", audio: "chamber.wav" },
                { word: "channel", meaning: "渠道", audio: "channel.wav" },
                { word: "choir", meaning: "唱诗班", audio: "choir.wav" },
                { word: "chord", meaning: "和弦", audio: "chord.wav" },
                { word: "chorus", meaning: "合唱", audio: "chorus.wav" },
                { word: "clarinet", meaning: "单簧管", audio: "clarinet.wav" },
                { word: "classic", meaning: "经典的", audio: "classic.wav" },
                { word: "classical", meaning: "古典", audio: "classical.wav" },
                { word: "clap", meaning: "鼓掌", audio: "clap.wav" },
                { word: "compose", meaning: "撰写", audio: "compose.wav" },
                { word: "composer", meaning: "作曲家", audio: "composer.wav" },
                { word: "composition", meaning: "作品", audio: "composition.wav" },
                { word: "concert", meaning: "音乐会", audio: "concert.wav" },
                { word: "conduct", meaning: "执行", audio: "conduct.wav" },
                { word: "conductor", meaning: "指挥", audio: "conductor.wav" },
                { word: "dance", meaning: "舞蹈", audio: "dance.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "disc", meaning: "光盘", audio: "disc.wav" },
                { word: "download", meaning: "下载", audio: "download.wav" },
                { word: "drum", meaning: "鼓", audio: "drum.wav" },
                { word: "duet", meaning: "二重奏", audio: "duet.wav" },
                { word: "dynamic", meaning: "动态的", audio: "dynamic.wav" },
                { word: "echo", meaning: "回声", audio: "echo.wav" },
                { word: "electric", meaning: "电的", audio: "electric.wav" },
                { word: "electronic", meaning: "电子的", audio: "electronic.wav" },
                { word: "encore", meaning: "返场", audio: "encore.wav" },
                { word: "ensemble", meaning: "合奏", audio: "ensemble.wav" },
                { word: "fade", meaning: "褪色", audio: "fade.wav" },
                { word: "fan", meaning: "扇子", audio: "fan.wav" },
                { word: "festival", meaning: "节日", audio: "festival.wav" },
                { word: "flute", meaning: "长笛", audio: "flute.wav" },
                { word: "folk", meaning: "民间", audio: "folk.wav" },
                { word: "frequency", meaning: "频率", audio: "frequency.wav" },
                { word: "genre", meaning: "类型", audio: "genre.wav" },
                { word: "gig", meaning: "演出", audio: "gig.wav" },
                { word: "guitar", meaning: "吉他", audio: "guitar.wav" },
                { word: "harmony", meaning: "和谐", audio: "harmony.wav" },
                { word: "harp", meaning: "竖琴", audio: "harp.wav" },
                { word: "headphone", meaning: "耳机", audio: "headphone.wav" },
                { word: "hip", meaning: "臀部", audio: "hip.wav" },
                { word: "horn", meaning: "喇叭", audio: "horn.wav" },
                { word: "hymn", meaning: "赞美诗", audio: "hymn.wav" },
                { word: "instrument", meaning: "乐器", audio: "instrument.wav" },
                { word: "jazz", meaning: "爵士乐", audio: "jazz.wav" },
                { word: "key", meaning: "钥匙", audio: "key.wav" },
                { word: "keyboard", meaning: "键盘", audio: "keyboard.wav" },
                { word: "live", meaning: "直播", audio: "live.wav" },
                { word: "loop", meaning: "环形", audio: "loop.wav" },
                { word: "loud", meaning: "大声", audio: "loud.wav" },
                { word: "lyric", meaning: "歌词", audio: "lyric.wav" },
                { word: "march", meaning: "行进", audio: "march.wav" },
                { word: "master", meaning: "掌握", audio: "master.wav" },
                { word: "melody", meaning: "旋律", audio: "melody.wav" },
                { word: "microphone", meaning: "麦克风", audio: "microphone.wav" },
                { word: "mix", meaning: "混合", audio: "mix.wav" },
                { word: "note", meaning: "笔记", audio: "note.wav" },
                { word: "opera", meaning: "歌剧", audio: "opera.wav" },
                { word: "orchestra", meaning: "乐队", audio: "orchestra.wav" },
                { word: "organ", meaning: "器官", audio: "organ.wav" },
                { word: "original", meaning: "原来的", audio: "original.wav" },
                { word: "percussion", meaning: "打击乐", audio: "percussion.wav" },
                { word: "perform", meaning: "履行", audio: "perform.wav" },
                { word: "performance", meaning: "表现", audio: "performance.wav" },
                { word: "performer", meaning: "表演者", audio: "performer.wav" },
                { word: "piano", meaning: "钢琴", audio: "piano.wav" },
                { word: "pitch", meaning: "沥青", audio: "pitch.wav" },
                { word: "play", meaning: "玩", audio: "play.wav" },
                { word: "playlist", meaning: "播放列表", audio: "playlist.wav" },
                { word: "pop", meaning: "流行音乐", audio: "pop.wav" },
                { word: "practice", meaning: "实践", audio: "practice.wav" },
                { word: "producer", meaning: "制片人", audio: "producer.wav" },
                { word: "punk", meaning: "朋克", audio: "punk.wav" },
                { word: "rap", meaning: "说唱", audio: "rap.wav" },
                { word: "record", meaning: "记录", audio: "record.wav" },
                { word: "recording", meaning: "记录", audio: "recording.wav" },
                { word: "rehearsal", meaning: "排练", audio: "rehearsal.wav" },
                { word: "release", meaning: "发布", audio: "release.wav" },
                { word: "remix", meaning: "混音", audio: "remix.wav" },
                { word: "rhythm", meaning: "韵律", audio: "rhythm.wav" },
                { word: "rock", meaning: "岩石", audio: "rock.wav" },
                { word: "scale", meaning: "规模", audio: "scale.wav" },
                { word: "score", meaning: "分数", audio: "score.wav" },
                { word: "sing", meaning: "唱歌", audio: "sing.wav" },
                { word: "singer", meaning: "歌手", audio: "singer.wav" },
                { word: "solo", meaning: "独奏", audio: "solo.wav" },
                { word: "song", meaning: "歌曲", audio: "song.wav" },
                { word: "soprano", meaning: "女高音", audio: "soprano.wav" },
                { word: "soul", meaning: "灵魂", audio: "soul.wav" },
                { word: "sound", meaning: "声音", audio: "sound.wav" },
                { word: "speaker", meaning: "扬声器", audio: "speaker.wav" },
                { word: "stage", meaning: "阶段", audio: "stage.wav" },
                { word: "stream", meaning: "溪流", audio: "stream.wav" },
                { word: "string", meaning: "细绳", audio: "string.wav" },
                { word: "studio", meaning: "工作室", audio: "studio.wav" },
                { word: "symphony", meaning: "交响曲", audio: "symphony.wav" },
                { word: "tempo", meaning: "节拍", audio: "tempo.wav" },
                { word: "tenor", meaning: "男高音", audio: "tenor.wav" },
                { word: "tone", meaning: "语气", audio: "tone.wav" },
                { word: "tour", meaning: "旅游", audio: "tour.wav" },
                { word: "track", meaning: "追踪", audio: "track.wav" },
                { word: "tune", meaning: "调", audio: "tune.wav" },
                { word: "violin", meaning: "小提琴", audio: "violin.wav" },
                { word: "vocal", meaning: "声音的", audio: "vocal.wav" },
                { word: "voice", meaning: "嗓音", audio: "voice.wav" },
                { word: "volume", meaning: "体积", audio: "volume.wav" }
            ]
        }
    }
});
