registerWordbook('scene_festivals', {
    name: "节日文化",
    emoji: "🎄",
    group: 'scene',
    description: "中西方节日、习俗、庆典相关词汇",
    levels: {
        all: {
            name: "🎄 全部",
            words: [
                { word: "ancestor", meaning: "祖先", audio: "ancestor.wav" },
                { word: "anniversary", meaning: "周年纪念日", audio: "anniversary.wav" },
                { word: "annual", meaning: "年度的", audio: "annual.wav" },
                { word: "applause", meaning: "掌声", audio: "applause.wav" },
                { word: "assembly", meaning: "集会", audio: "assembly.wav" },
                { word: "atmosphere", meaning: "气氛", audio: "atmosphere.wav" },
                { word: "balloon", meaning: "气球", audio: "balloon.wav" },
                { word: "banquet", meaning: "宴会", audio: "banquet.wav" },
                { word: "barbecue", meaning: "烧烤", audio: "barbecue.wav" },
                { word: "bell", meaning: "钟", audio: "bell.wav" },
                { word: "bless", meaning: "保佑", audio: "bless.wav" },
                { word: "bow", meaning: "鞠躬", audio: "bow.wav" },
                { word: "bride", meaning: "新娘", audio: "bride.wav" },
                { word: "calendar", meaning: "日历", audio: "calendar.wav" },
                { word: "candle", meaning: "蜡烛", audio: "candle.wav" },
                { word: "candy", meaning: "糖果", audio: "candy.wav" },
                { word: "carol", meaning: "颂歌", audio: "carol.wav" },
                { word: "carnival", meaning: "嘉年华", audio: "carnival.wav" },
                { word: "celebrate", meaning: "庆祝", audio: "celebrate.wav" },
                { word: "celebration", meaning: "庆典", audio: "celebration.wav" },
                { word: "ceremony", meaning: "仪式", audio: "ceremony.wav" },
                { word: "charity", meaning: "慈善事业", audio: "charity.wav" },
                { word: "cheer", meaning: "欢呼", audio: "cheer.wav" },
                { word: "chocolate", meaning: "巧克力", audio: "chocolate.wav" },
                { word: "church", meaning: "教会", audio: "church.wav" },
                { word: "clap", meaning: "鼓掌", audio: "clap.wav" },
                { word: "concert", meaning: "音乐会", audio: "concert.wav" },
                { word: "confetti", meaning: "彩纸", audio: "confetti.wav" },
                { word: "congratulate", meaning: "祝贺", audio: "congratulate.wav" },
                { word: "costume", meaning: "戏服", audio: "costume.wav" },
                { word: "countdown", meaning: "倒计时", audio: "countdown.wav" },
                { word: "crown", meaning: "王冠", audio: "crown.wav" },
                { word: "culture", meaning: "文化", audio: "culture.wav" },
                { word: "custom", meaning: "风俗", audio: "custom.wav" },
                { word: "dance", meaning: "舞蹈", audio: "dance.wav" },
                { word: "decorate", meaning: "装饰", audio: "decorate.wav" },
                { word: "decoration", meaning: "装饰", audio: "decoration.wav" },
                { word: "dessert", meaning: "甜点", audio: "dessert.wav" },
                { word: "display", meaning: "展示", audio: "display.wav" },
                { word: "donation", meaning: "捐款", audio: "donation.wav" },
                { word: "dragon", meaning: "龙", audio: "dragon.wav" },
                { word: "dress", meaning: "裙子", audio: "dress.wav" },
                { word: "drum", meaning: "鼓", audio: "drum.wav" },
                { word: "eve", meaning: "前夕", audio: "eve.wav" },
                { word: "event", meaning: "事件", audio: "event.wav" },
                { word: "exchange", meaning: "交换", audio: "exchange.wav" },
                { word: "fairy", meaning: "仙女", audio: "fairy.wav" },
                { word: "family", meaning: "家庭", audio: "family.wav" },
                { word: "fan", meaning: "爱好者; 粉丝", audio: "fan.wav" },
                { word: "feast", meaning: "盛宴", audio: "feast.wav" },
                { word: "festival", meaning: "节日", audio: "festival.wav" },
                { word: "firework", meaning: "焰火", audio: "firework.wav" },
                { word: "flag", meaning: "旗帜", audio: "flag.wav" },
                { word: "float", meaning: "漂浮", audio: "float.wav" },
                { word: "flower", meaning: "花", audio: "flower.wav" },
                { word: "folk", meaning: "民间", audio: "folk.wav" },
                { word: "fortune", meaning: "好运; 福气", audio: "fortune.wav" },
                { word: "fun", meaning: "乐趣", audio: "fun.wav" },
                { word: "gather", meaning: "收集", audio: "gather.wav" },
                { word: "gift", meaning: "礼物", audio: "gift.wav" },
                { word: "glow", meaning: "发光", audio: "glow.wav" },
                { word: "god", meaning: "上帝", audio: "god.wav" },
                { word: "greet", meaning: "迎接", audio: "greet.wav" },
                { word: "guest", meaning: "客人", audio: "guest.wav" },
                { word: "halloween", meaning: "万圣节", audio: "halloween.wav" },
                { word: "harvest", meaning: "收成", audio: "harvest.wav" },
                { word: "heritage", meaning: "遗产", audio: "heritage.wav" },
                { word: "holiday", meaning: "假期", audio: "holiday.wav" },
                { word: "honour", meaning: "荣誉", audio: "honour.wav" },
                { word: "hymn", meaning: "赞美诗", audio: "hymn.wav" },
                { word: "invite", meaning: "邀请", audio: "invite.wav" },
                { word: "joy", meaning: "喜悦", audio: "joy.wav" },
                { word: "lantern", meaning: "灯笼", audio: "lantern.wav" },
                { word: "legend", meaning: "传奇", audio: "legend.wav" },
                { word: "light", meaning: "光", audio: "light.wav" },
                { word: "luck", meaning: "运气", audio: "luck.wav" },
                { word: "magic", meaning: "魔法", audio: "magic.wav" },
                { word: "march", meaning: "行进", audio: "march.wav" },
                { word: "mask", meaning: "面具", audio: "mask.wav" },
                { word: "memorial", meaning: "纪念馆", audio: "memorial.wav" },
                { word: "memory", meaning: "记忆", audio: "memory.wav" },
                { word: "miracle", meaning: "奇迹", audio: "miracle.wav" },
                { word: "moon", meaning: "月亮", audio: "moon.wav" },
                { word: "music", meaning: "音乐", audio: "music.wav" },
                { word: "myth", meaning: "神话", audio: "myth.wav" },
                { word: "occasion", meaning: "场合", audio: "occasion.wav" },
                { word: "offering", meaning: "奉献", audio: "offering.wav" },
                { word: "parade", meaning: "游行", audio: "parade.wav" },
                { word: "party", meaning: "派对", audio: "party.wav" },
                { word: "peace", meaning: "和平", audio: "peace.wav" },
                { word: "photograph", meaning: "照片", audio: "photograph.wav" },
                { word: "picnic", meaning: "野餐", audio: "picnic.wav" },
                { word: "prayer", meaning: "祷告", audio: "prayer.wav" },
                { word: "present", meaning: "礼物", audio: "present.wav" },
                { word: "procession", meaning: "游行队伍", audio: "procession.wav" },
                { word: "pumpkin", meaning: "南瓜", audio: "pumpkin.wav" },
                { word: "receive", meaning: "收到", audio: "receive.wav" },
                { word: "reception", meaning: "接待", audio: "reception.wav" },
                { word: "reunion", meaning: "团聚", audio: "reunion.wav" },
                { word: "ribbon", meaning: "丝带", audio: "ribbon.wav" },
                { word: "ritual", meaning: "仪式", audio: "ritual.wav" },
                { word: "saint", meaning: "圣人", audio: "saint.wav" },
                { word: "season", meaning: "季节", audio: "season.wav" },
                { word: "sing", meaning: "唱歌", audio: "sing.wav" },
                { word: "spirit", meaning: "精神", audio: "spirit.wav" },
                { word: "star", meaning: "星星", audio: "star.wav" },
                { word: "symbol", meaning: "象征", audio: "symbol.wav" },
                { word: "temple", meaning: "寺庙", audio: "temple.wav" },
                { word: "thanksgiving", meaning: "感恩节", audio: "thanksgiving.wav" },
                { word: "toast", meaning: "祝酒; 干杯", audio: "toast.wav" },
                { word: "torch", meaning: "火炬", audio: "torch.wav" },
                { word: "tradition", meaning: "传统", audio: "tradition.wav" },
                { word: "treat", meaning: "款待; 小礼物", audio: "treat.wav" },
                { word: "tribute", meaning: "致敬", audio: "tribute.wav" },
                { word: "turkey", meaning: "火鸡", audio: "turkey.wav" },
                { word: "valentine", meaning: "情人节", audio: "valentine.wav" },
                { word: "volunteer", meaning: "志愿者", audio: "volunteer.wav" },
                { word: "wedding", meaning: "婚礼", audio: "wedding.wav" },
                { word: "wish", meaning: "希望", audio: "wish.wav" },
                { word: "worship", meaning: "崇拜", audio: "worship.wav" },
                { word: "wrap", meaning: "裹", audio: "wrap.wav" }
            ]
        }
    }
});
