registerWordbook('scene_nature', {
    name: "天气自然",
    emoji: "🌤️",
    group: 'scene',
    description: "天气、动植物、环境相关词汇",
    levels: {
        all: {
            name: "🌤️ 全部",
            words: [
                { word: "air", meaning: "空气", audio: "air.wav" },
                { word: "animal", meaning: "动物", audio: "animal.wav" },
                { word: "atmosphere", meaning: "大气层", audio: "atmosphere.wav" },
                { word: "autumn", meaning: "秋天", audio: "autumn.wav" },
                { word: "bay", meaning: "湾", audio: "bay.wav" },
                { word: "beach", meaning: "海滩", audio: "beach.wav" },
                { word: "bear", meaning: "熊", audio: "bear.wav" },
                { word: "bee", meaning: "蜜蜂", audio: "bee.wav" },
                { word: "bird", meaning: "鸟", audio: "bird.wav" },
                { word: "blow", meaning: "吹", audio: "blow.wav" },
                { word: "branch", meaning: "树枝", audio: "branch.wav" },
                { word: "breeze", meaning: "微风", audio: "breeze.wav" },
                { word: "butterfly", meaning: "蝴蝶", audio: "butterfly.wav" },
                { word: "cat", meaning: "猫", audio: "cat.wav" },
                { word: "cattle", meaning: "牛", audio: "cattle.wav" },
                { word: "cave", meaning: "洞穴", audio: "cave.wav" },
                { word: "chicken", meaning: "鸡", audio: "chicken.wav" },
                { word: "climate", meaning: "气候", audio: "climate.wav" },
                { word: "cloud", meaning: "云", audio: "cloud.wav" },
                { word: "coast", meaning: "海岸", audio: "coast.wav" },
                { word: "cold", meaning: "寒冷的", audio: "cold.wav" },
                { word: "continent", meaning: "大陆", audio: "continent.wav" },
                { word: "cow", meaning: "奶牛", audio: "cow.wav" },
                { word: "creature", meaning: "生物", audio: "creature.wav" },
                { word: "crop", meaning: "庄稼", audio: "crop.wav" },
                { word: "deer", meaning: "鹿", audio: "deer.wav" },
                { word: "desert", meaning: "沙漠", audio: "desert.wav" },
                { word: "dog", meaning: "狗", audio: "dog.wav" },
                { word: "dolphin", meaning: "海豚", audio: "dolphin.wav" },
                { word: "drought", meaning: "干旱", audio: "drought.wav" },
                { word: "dust", meaning: "灰尘", audio: "dust.wav" },
                { word: "earth", meaning: "地球", audio: "earth.wav" },
                { word: "earthquake", meaning: "地震", audio: "earthquake.wav" },
                { word: "ecology", meaning: "生态学", audio: "ecology.wav" },
                { word: "elephant", meaning: "大象", audio: "elephant.wav" },
                { word: "emission", meaning: "排放", audio: "emission.wav" },
                { word: "environment", meaning: "环境", audio: "environment.wav" },
                { word: "eruption", meaning: "喷发", audio: "eruption.wav" },
                { word: "evolution", meaning: "进化", audio: "evolution.wav" },
                { word: "farm", meaning: "农场", audio: "farm.wav" },
                { word: "feather", meaning: "羽毛", audio: "feather.wav" },
                { word: "field", meaning: "场地", audio: "field.wav" },
                { word: "fish", meaning: "鱼", audio: "fish.wav" },
                { word: "flood", meaning: "洪水", audio: "flood.wav" },
                { word: "flower", meaning: "花", audio: "flower.wav" },
                { word: "fly", meaning: "飞", audio: "fly.wav" },
                { word: "fog", meaning: "雾", audio: "fog.wav" },
                { word: "forest", meaning: "森林", audio: "forest.wav" },
                { word: "freeze", meaning: "冻结", audio: "freeze.wav" },
                { word: "frost", meaning: "霜", audio: "frost.wav" },
                { word: "garden", meaning: "花园", audio: "garden.wav" },
                { word: "globe", meaning: "地球", audio: "globe.wav" },
                { word: "goat", meaning: "山羊", audio: "goat.wav" },
                { word: "grass", meaning: "草", audio: "grass.wav" },
                { word: "harvest", meaning: "收成", audio: "harvest.wav" },
                { word: "heat", meaning: "热", audio: "heat.wav" },
                { word: "hill", meaning: "小山; 山丘", audio: "hill.wav" },
                { word: "horse", meaning: "马", audio: "horse.wav" },
                { word: "hurricane", meaning: "飓风", audio: "hurricane.wav" },
                { word: "ice", meaning: "冰", audio: "ice.wav" },
                { word: "insect", meaning: "昆虫", audio: "insect.wav" },
                { word: "island", meaning: "岛", audio: "island.wav" },
                { word: "jungle", meaning: "丛林", audio: "jungle.wav" },
                { word: "lake", meaning: "湖", audio: "lake.wav" },
                { word: "landscape", meaning: "景观", audio: "landscape.wav" },
                { word: "leaf", meaning: "叶子", audio: "leaf.wav" },
                { word: "lion", meaning: "狮子", audio: "lion.wav" },
                { word: "mammal", meaning: "哺乳动物", audio: "mammal.wav" },
                { word: "monkey", meaning: "猴", audio: "monkey.wav" },
                { word: "moon", meaning: "月亮", audio: "moon.wav" },
                { word: "mountain", meaning: "山", audio: "mountain.wav" },
                { word: "mud", meaning: "泥", audio: "mud.wav" },
                { word: "nature", meaning: "自然", audio: "nature.wav" },
                { word: "ocean", meaning: "海洋", audio: "ocean.wav" },
                { word: "pet", meaning: "宠物", audio: "pet.wav" },
                { word: "pig", meaning: "猪", audio: "pig.wav" },
                { word: "planet", meaning: "行星", audio: "planet.wav" },
                { word: "plant", meaning: "植物", audio: "plant.wav" },
                { word: "pollution", meaning: "污染", audio: "pollution.wav" },
                { word: "pond", meaning: "池塘", audio: "pond.wav" },
                { word: "rabbit", meaning: "兔子", audio: "rabbit.wav" },
                { word: "rain", meaning: "雨", audio: "rain.wav" },
                { word: "rainbow", meaning: "彩虹", audio: "rainbow.wav" },
                { word: "recycle", meaning: "回收", audio: "recycle.wav" },
                { word: "reef", meaning: "礁石", audio: "reef.wav" },
                { word: "river", meaning: "河", audio: "river.wav" },
                { word: "rock", meaning: "岩石", audio: "rock.wav" },
                { word: "root", meaning: "根", audio: "root.wav" },
                { word: "sand", meaning: "沙", audio: "sand.wav" },
                { word: "sea", meaning: "海", audio: "sea.wav" },
                { word: "season", meaning: "季节", audio: "season.wav" },
                { word: "seed", meaning: "种子", audio: "seed.wav" },
                { word: "shark", meaning: "鲨鱼", audio: "shark.wav" },
                { word: "sheep", meaning: "羊", audio: "sheep.wav" },
                { word: "shell", meaning: "壳", audio: "shell.wav" },
                { word: "shore", meaning: "岸; 海岸", audio: "shore.wav" },
                { word: "sky", meaning: "天空", audio: "sky.wav" },
                { word: "snake", meaning: "蛇", audio: "snake.wav" },
                { word: "snow", meaning: "雪", audio: "snow.wav" },
                { word: "soil", meaning: "土壤", audio: "soil.wav" },
                { word: "species", meaning: "物种", audio: "species.wav" },
                { word: "spring", meaning: "春天", audio: "spring.wav" },
                { word: "star", meaning: "星星", audio: "star.wav" },
                { word: "storm", meaning: "风暴", audio: "storm.wav" },
                { word: "stream", meaning: "溪流", audio: "stream.wav" },
                { word: "summer", meaning: "夏天", audio: "summer.wav" },
                { word: "sun", meaning: "太阳", audio: "sun.wav" },
                { word: "sunshine", meaning: "阳光", audio: "sunshine.wav" },
                { word: "temperature", meaning: "温度", audio: "temperature.wav" },
                { word: "thunder", meaning: "雷", audio: "thunder.wav" },
                { word: "tide", meaning: "潮汐", audio: "tide.wav" },
                { word: "tiger", meaning: "老虎", audio: "tiger.wav" },
                { word: "tree", meaning: "树", audio: "tree.wav" },
                { word: "tropical", meaning: "热带", audio: "tropical.wav" },
                { word: "valley", meaning: "谷", audio: "valley.wav" },
                { word: "volcano", meaning: "火山", audio: "volcano.wav" },
                { word: "warm", meaning: "温暖的", audio: "warm.wav" },
                { word: "waste", meaning: "浪费", audio: "waste.wav" },
                { word: "wave", meaning: "海浪", audio: "wave.wav" },
                { word: "weather", meaning: "天气", audio: "weather.wav" },
                { word: "whale", meaning: "鲸鱼", audio: "whale.wav" },
                { word: "wildlife", meaning: "野生动物", audio: "wildlife.wav" },
                { word: "wind", meaning: "风", audio: "wind.wav" },
                { word: "winter", meaning: "冬天", audio: "winter.wav" },
                { word: "wolf", meaning: "狼", audio: "wolf.wav" },
                { word: "wood", meaning: "木头", audio: "wood.wav" },
                { word: "worm", meaning: "蠕虫", audio: "worm.wav" }
            ]
        }
    }
});
