registerWordbook('scene_home', {
    name: "家居房屋",
    emoji: "🏠",
    group: 'scene',
    description: "房屋、家具、家电相关词汇",
    levels: {
        all: {
            name: "🏠 全部",
            words: [
                { word: "apartment", meaning: "公寓", audio: "apartment.wav" },
                { word: "attic", meaning: "阁楼", audio: "attic.wav" },
                { word: "balcony", meaning: "阳台", audio: "balcony.wav" },
                { word: "basement", meaning: "地下室", audio: "basement.wav" },
                { word: "bathroom", meaning: "浴室", audio: "bathroom.wav" },
                { word: "bed", meaning: "床", audio: "bed.wav" },
                { word: "bedroom", meaning: "卧室", audio: "bedroom.wav" },
                { word: "blanket", meaning: "毯子", audio: "blanket.wav" },
                { word: "blind", meaning: "瞎的", audio: "blind.wav" },
                { word: "brick", meaning: "砖", audio: "brick.wav" },
                { word: "brush", meaning: "刷子", audio: "brush.wav" },
                { word: "build", meaning: "建造", audio: "build.wav" },
                { word: "carpet", meaning: "地毯", audio: "carpet.wav" },
                { word: "ceiling", meaning: "天花板", audio: "ceiling.wav" },
                { word: "chair", meaning: "椅子", audio: "chair.wav" },
                { word: "chimney", meaning: "烟囱", audio: "chimney.wav" },
                { word: "clean", meaning: "干净的", audio: "clean.wav" },
                { word: "clock", meaning: "钟", audio: "clock.wav" },
                { word: "corridor", meaning: "走廊", audio: "corridor.wav" },
                { word: "couch", meaning: "沙发", audio: "couch.wav" },
                { word: "cupboard", meaning: "橱柜", audio: "cupboard.wav" },
                { word: "curtain", meaning: "窗帘", audio: "curtain.wav" },
                { word: "cushion", meaning: "垫子", audio: "cushion.wav" },
                { word: "decoration", meaning: "装饰", audio: "decoration.wav" },
                { word: "desk", meaning: "桌子", audio: "desk.wav" },
                { word: "door", meaning: "门", audio: "door.wav" },
                { word: "doorway", meaning: "门口", audio: "doorway.wav" },
                { word: "drawer", meaning: "抽屉", audio: "drawer.wav" },
                { word: "dust", meaning: "灰尘", audio: "dust.wav" },
                { word: "electricity", meaning: "电", audio: "electricity.wav" },
                { word: "entrance", meaning: "入口", audio: "entrance.wav" },
                { word: "estate", meaning: "财产", audio: "estate.wav" },
                { word: "fence", meaning: "栅栏", audio: "fence.wav" },
                { word: "fireplace", meaning: "壁炉", audio: "fireplace.wav" },
                { word: "flat", meaning: "平坦的", audio: "flat.wav" },
                { word: "floor", meaning: "地面", audio: "floor.wav" },
                { word: "furniture", meaning: "家具", audio: "furniture.wav" },
                { word: "garage", meaning: "车库", audio: "garage.wav" },
                { word: "garden", meaning: "花园", audio: "garden.wav" },
                { word: "gate", meaning: "门", audio: "gate.wav" },
                { word: "hall", meaning: "大厅", audio: "hall.wav" },
                { word: "heater", meaning: "加热器", audio: "heater.wav" },
                { word: "home", meaning: "家", audio: "home.wav" },
                { word: "house", meaning: "房子", audio: "house.wav" },
                { word: "household", meaning: "家庭", audio: "household.wav" },
                { word: "housing", meaning: "住房", audio: "housing.wav" },
                { word: "iron", meaning: "铁", audio: "iron.wav" },
                { word: "key", meaning: "钥匙", audio: "key.wav" },
                { word: "kitchen", meaning: "厨房", audio: "kitchen.wav" },
                { word: "lamp", meaning: "灯", audio: "lamp.wav" },
                { word: "landlord", meaning: "房东", audio: "landlord.wav" },
                { word: "lawn", meaning: "草地", audio: "lawn.wav" },
                { word: "light", meaning: "光", audio: "light.wav" },
                { word: "living", meaning: "活的", audio: "living.wav" },
                { word: "lock", meaning: "锁", audio: "lock.wav" },
                { word: "mat", meaning: "垫子", audio: "mat.wav" },
                { word: "mirror", meaning: "镜子", audio: "mirror.wav" },
                { word: "mortgage", meaning: "抵押", audio: "mortgage.wav" },
                { word: "neighbour", meaning: "邻居", audio: "neighbour.wav" },
                { word: "oven", meaning: "烤箱", audio: "oven.wav" },
                { word: "paint", meaning: "画", audio: "paint.wav" },
                { word: "path", meaning: "小路", audio: "path.wav" },
                { word: "pillow", meaning: "枕头", audio: "pillow.wav" },
                { word: "pipe", meaning: "管道", audio: "pipe.wav" },
                { word: "plug", meaning: "插头", audio: "plug.wav" },
                { word: "property", meaning: "财产", audio: "property.wav" },
                { word: "rent", meaning: "租", audio: "rent.wav" },
                { word: "repair", meaning: "维修", audio: "repair.wav" },
                { word: "roof", meaning: "屋顶", audio: "roof.wav" },
                { word: "room", meaning: "房间", audio: "room.wav" },
                { word: "rug", meaning: "地毯", audio: "rug.wav" },
                { word: "shelf", meaning: "架子", audio: "shelf.wav" },
                { word: "shower", meaning: "淋浴", audio: "shower.wav" },
                { word: "sink", meaning: "下沉", audio: "sink.wav" },
                { word: "sofa", meaning: "沙发", audio: "sofa.wav" },
                { word: "stairs", meaning: "楼梯", audio: "stairs.wav" },
                { word: "tap", meaning: "轻敲", audio: "tap.wav" },
                { word: "tenant", meaning: "租户", audio: "tenant.wav" },
                { word: "terrace", meaning: "露台", audio: "terrace.wav" },
                { word: "tile", meaning: "瓷砖", audio: "tile.wav" },
                { word: "toilet", meaning: "洗手间", audio: "toilet.wav" },
                { word: "vacuum", meaning: "真空", audio: "vacuum.wav" },
                { word: "wall", meaning: "墙", audio: "wall.wav" },
                { word: "wardrobe", meaning: "衣柜", audio: "wardrobe.wav" },
                { word: "wash", meaning: "洗", audio: "wash.wav" },
                { word: "window", meaning: "窗户", audio: "window.wav" },
                { word: "yard", meaning: "院子", audio: "yard.wav" }
            ]
        }
    }
});
