registerWordbook('scene_shopping', {
    name: "购物消费",
    emoji: "🛒",
    group: 'scene',
    description: "购物、消费、金钱相关词汇",
    levels: {
        all: {
            name: "🛒 全部",
            words: [
                { word: "account", meaning: "帐户", audio: "account.wav" },
                { word: "afford", meaning: "买得起", audio: "afford.wav" },
                { word: "bargain", meaning: "便宜货", audio: "bargain.wav" },
                { word: "bill", meaning: "账单", audio: "bill.wav" },
                { word: "brand", meaning: "品牌", audio: "brand.wav" },
                { word: "budget", meaning: "预算", audio: "budget.wav" },
                { word: "buy", meaning: "买", audio: "buy.wav" },
                { word: "cash", meaning: "现金", audio: "cash.wav" },
                { word: "cent", meaning: "分", audio: "cent.wav" },
                { word: "change", meaning: "找零", audio: "change.wav" },
                { word: "charge", meaning: "收费", audio: "charge.wav" },
                { word: "cheap", meaning: "便宜的", audio: "cheap.wav" },
                { word: "cheque", meaning: "支票", audio: "cheque.wav" },
                { word: "coin", meaning: "硬币", audio: "coin.wav" },
                { word: "consumer", meaning: "消费者", audio: "consumer.wav" },
                { word: "cost", meaning: "花费; 价钱", audio: "cost.wav" },
                { word: "coupon", meaning: "优惠券", audio: "coupon.wav" },
                { word: "credit", meaning: "信用", audio: "credit.wav" },
                { word: "currency", meaning: "货币", audio: "currency.wav" },
                { word: "customer", meaning: "顾客", audio: "customer.wav" },
                { word: "deal", meaning: "交易", audio: "deal.wav" },
                { word: "debt", meaning: "债务", audio: "debt.wav" },
                { word: "deliver", meaning: "递送", audio: "deliver.wav" },
                { word: "delivery", meaning: "送货", audio: "delivery.wav" },
                { word: "demand", meaning: "需求", audio: "demand.wav" },
                { word: "department", meaning: "百货商场; 柜台", audio: "department.wav" },
                { word: "deposit", meaning: "订金", audio: "deposit.wav" },
                { word: "discount", meaning: "折扣", audio: "discount.wav" },
                { word: "dollar", meaning: "美元", audio: "dollar.wav" },
                { word: "earn", meaning: "赚", audio: "earn.wav" },
                { word: "exchange", meaning: "退换; 兑换", audio: "exchange.wav" },
                { word: "expensive", meaning: "昂贵的", audio: "expensive.wav" },
                { word: "export", meaning: "出口商品; 出口", audio: "export.wav" },
                { word: "fee", meaning: "费用", audio: "fee.wav" },
                { word: "goods", meaning: "商品", audio: "goods.wav" },
                { word: "guarantee", meaning: "保修; 质保", audio: "guarantee.wav" },
                { word: "import", meaning: "进口", audio: "import.wav" },
                { word: "income", meaning: "收入", audio: "income.wav" },
                { word: "insurance", meaning: "保险", audio: "insurance.wav" },
                { word: "invest", meaning: "投资", audio: "invest.wav" },
                { word: "investment", meaning: "投资", audio: "investment.wav" },
                { word: "item", meaning: "物品", audio: "item.wav" },
                { word: "loan", meaning: "贷款", audio: "loan.wav" },
                { word: "luxury", meaning: "奢侈品", audio: "luxury.wav" },
                { word: "mall", meaning: "购物中心", audio: "mall.wav" },
                { word: "market", meaning: "市场", audio: "market.wav" },
                { word: "merchant", meaning: "商人", audio: "merchant.wav" },
                { word: "offer", meaning: "优惠; 特价", audio: "offer.wav" },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "order", meaning: "订单; 下单", audio: "order.wav" },
                { word: "owe", meaning: "欠", audio: "owe.wav" },
                { word: "own", meaning: "拥有", audio: "own.wav" },
                { word: "package", meaning: "包裹", audio: "package.wav" },
                { word: "pay", meaning: "支付", audio: "pay.wav" },
                { word: "payment", meaning: "支付", audio: "payment.wav" },
                { word: "penny", meaning: "一分钱", audio: "penny.wav" },
                { word: "pound", meaning: "英镑", audio: "pound.wav" },
                { word: "price", meaning: "价格", audio: "price.wav" },
                { word: "produce", meaning: "生产", audio: "produce.wav" },
                { word: "product", meaning: "产品", audio: "product.wav" },
                { word: "profit", meaning: "利润", audio: "profit.wav" },
                { word: "purchase", meaning: "购买", audio: "purchase.wav" },
                { word: "quality", meaning: "质量", audio: "quality.wav" },
                { word: "quantity", meaning: "数量", audio: "quantity.wav" },
                { word: "receipt", meaning: "收据", audio: "receipt.wav" },
                { word: "refund", meaning: "退款", audio: "refund.wav" },
                { word: "retail", meaning: "零售", audio: "retail.wav" },
                { word: "sale", meaning: "销售", audio: "sale.wav" },
                { word: "save", meaning: "节省", audio: "save.wav" },
                { word: "sell", meaning: "卖", audio: "sell.wav" },
                { word: "service", meaning: "服务", audio: "service.wav" },
                { word: "shelf", meaning: "货架", audio: "shelf.wav" },
                { word: "shop", meaning: "店铺", audio: "shop.wav" },
                { word: "shopping", meaning: "购物", audio: "shopping.wav" },
                { word: "spend", meaning: "花费", audio: "spend.wav" },
                { word: "store", meaning: "店铺", audio: "store.wav" },
                { word: "supply", meaning: "供应", audio: "supply.wav" },
                { word: "tax", meaning: "税", audio: "tax.wav" },
                { word: "trade", meaning: "贸易", audio: "trade.wav" },
                { word: "value", meaning: "价值", audio: "value.wav" },
                { word: "wallet", meaning: "钱包", audio: "wallet.wav" },
                { word: "wholesale", meaning: "批发", audio: "wholesale.wav" },
                { word: "worth", meaning: "值…钱; 价值", audio: "worth.wav" }
            ]
        }
    }
});
