registerWordbook('scene_travel', {
    name: "旅行酒店",
    emoji: "✈️",
    group: 'scene',
    description: "旅游、住宿、观光相关词汇",
    levels: {
        all: {
            name: "✈️ 全部",
            words: [
                { word: "abroad", meaning: "国外", audio: "abroad.wav" },
                { word: "accommodation", meaning: "住宿", audio: "accommodation.wav" },
                { word: "adventure", meaning: "探险旅行", audio: "adventure.wav" },
                { word: "airline", meaning: "航空公司", audio: "airline.wav" },
                { word: "airport", meaning: "飞机场", audio: "airport.wav" },
                { word: "arrival", meaning: "到达", audio: "arrival.wav" },
                { word: "attraction", meaning: "景点", audio: "attraction.wav" },
                { word: "backpack", meaning: "背包", audio: "backpack.wav" },
                { word: "baggage", meaning: "行李", audio: "baggage.wav" },
                { word: "beach", meaning: "海滩", audio: "beach.wav" },
                { word: "board", meaning: "登机; 上船", audio: "board.wav" },
                { word: "book", meaning: "预订", audio: "book.wav" },
                { word: "border", meaning: "边界", audio: "border.wav" },
                { word: "brochure", meaning: "旅游宣传册", audio: "brochure.wav" },
                { word: "cabin", meaning: "客舱; 小木屋", audio: "cabin.wav" },
                { word: "camera", meaning: "相机", audio: "camera.wav" },
                { word: "camp", meaning: "露营", audio: "camp.wav" },
                { word: "cancel", meaning: "取消", audio: "cancel.wav" },
                { word: "check-in", meaning: "登记入住", audio: "check-in.wav" },
                { word: "coast", meaning: "海岸", audio: "coast.wav" },
                { word: "confirm", meaning: "确认", audio: "confirm.wav" },
                { word: "cruise", meaning: "邮轮旅行", audio: "cruise.wav" },
                { word: "culture", meaning: "文化", audio: "culture.wav" },
                { word: "currency", meaning: "货币", audio: "currency.wav" },
                { word: "customs", meaning: "海关", audio: "customs.wav" },
                { word: "delay", meaning: "延迟", audio: "delay.wav" },
                { word: "depart", meaning: "离开", audio: "depart.wav" },
                { word: "departure", meaning: "出发; 启程", audio: "departure.wav" },
                { word: "destination", meaning: "目的地", audio: "destination.wav" },
                { word: "embassy", meaning: "大使馆", audio: "embassy.wav" },
                { word: "excursion", meaning: "短途旅行", audio: "excursion.wav" },
                { word: "explore", meaning: "探索", audio: "explore.wav" },
                { word: "fare", meaning: "票价", audio: "fare.wav" },
                { word: "ferry", meaning: "渡轮", audio: "ferry.wav" },
                { word: "flight", meaning: "航班", audio: "flight.wav" },
                { word: "foreign", meaning: "外国的", audio: "foreign.wav" },
                { word: "guide", meaning: "导游", audio: "guide.wav" },
                { word: "harbour", meaning: "港口", audio: "harbour.wav" },
                { word: "heritage", meaning: "文化遗产", audio: "heritage.wav" },
                { word: "hiking", meaning: "远足", audio: "hiking.wav" },
                { word: "holiday", meaning: "假期", audio: "holiday.wav" },
                { word: "hostel", meaning: "旅社", audio: "hostel.wav" },
                { word: "hotel", meaning: "酒店", audio: "hotel.wav" },
                { word: "inn", meaning: "旅馆", audio: "inn.wav" },
                { word: "island", meaning: "岛", audio: "island.wav" },
                { word: "itinerary", meaning: "行程", audio: "itinerary.wav" },
                { word: "journey", meaning: "旅行", audio: "journey.wav" },
                { word: "landmark", meaning: "地标", audio: "landmark.wav" },
                { word: "language", meaning: "语言", audio: "language.wav" },
                { word: "leisure", meaning: "闲暇", audio: "leisure.wav" },
                { word: "local", meaning: "当地的", audio: "local.wav" },
                { word: "luggage", meaning: "行李", audio: "luggage.wav" },
                { word: "map", meaning: "地图", audio: "map.wav" },
                { word: "monument", meaning: "纪念碑", audio: "monument.wav" },
                { word: "motel", meaning: "汽车旅馆", audio: "motel.wav" },
                { word: "museum", meaning: "博物馆", audio: "museum.wav" },
                { word: "overseas", meaning: "海外", audio: "overseas.wav" },
                { word: "pack", meaning: "打包; 收拾行李", audio: "pack.wav" },
                { word: "palace", meaning: "宫殿", audio: "palace.wav" },
                { word: "paradise", meaning: "度假胜地; 人间天堂", audio: "paradise.wav" },
                { word: "passenger", meaning: "乘客", audio: "passenger.wav" },
                { word: "passport", meaning: "护照", audio: "passport.wav" },
                { word: "photo", meaning: "照片", audio: "photo.wav" },
                { word: "pilgrimage", meaning: "朝圣", audio: "pilgrimage.wav" },
                { word: "port", meaning: "港口", audio: "port.wav" },
                { word: "postcard", meaning: "明信片", audio: "postcard.wav" },
                { word: "reception", meaning: "前台; 接待处", audio: "reception.wav" },
                { word: "reservation", meaning: "预订", audio: "reservation.wav" },
                { word: "resort", meaning: "度假村", audio: "resort.wav" },
                { word: "return", meaning: "返回", audio: "return.wav" },
                { word: "route", meaning: "路线", audio: "route.wav" },
                { word: "ruin", meaning: "废墟", audio: "ruin.wav" },
                { word: "safari", meaning: "狩猎旅行", audio: "safari.wav" },
                { word: "scenery", meaning: "风景", audio: "scenery.wav" },
                { word: "sightseeing", meaning: "观光", audio: "sightseeing.wav" },
                { word: "souvenir", meaning: "纪念品", audio: "souvenir.wav" },
                { word: "suitcase", meaning: "手提箱", audio: "suitcase.wav" },
                { word: "temple", meaning: "寺庙", audio: "temple.wav" },
                { word: "terminal", meaning: "航站楼", audio: "terminal.wav" },
                { word: "ticket", meaning: "票", audio: "ticket.wav" },
                { word: "tour", meaning: "旅游", audio: "tour.wav" },
                { word: "tourism", meaning: "旅游", audio: "tourism.wav" },
                { word: "tourist", meaning: "游客", audio: "tourist.wav" },
                { word: "translate", meaning: "翻译", audio: "translate.wav" },
                { word: "trip", meaning: "旅行", audio: "trip.wav" },
                { word: "vacation", meaning: "假期", audio: "vacation.wav" },
                { word: "visa", meaning: "签证", audio: "visa.wav" },
                { word: "visit", meaning: "游览; 参观", audio: "visit.wav" },
                { word: "voyage", meaning: "航行", audio: "voyage.wav" },
                { word: "wander", meaning: "漫步", audio: "wander.wav" }
            ]
        }
    }
});
