registerWordbook('scene_clothing', {
    name: "服饰穿着",
    emoji: "👕",
    group: 'scene',
    description: "衣服、鞋帽、配饰相关词汇",
    levels: {
        all: {
            name: "👕 全部",
            words: [
                { word: "belt", meaning: "腰带", audio: "belt.wav" },
                { word: "boot", meaning: "靴子", audio: "boot.wav" },
                { word: "button", meaning: "纽扣", audio: "button.wav" },
                { word: "cap", meaning: "便帽", audio: "cap.wav" },
                { word: "clothes", meaning: "衣服", audio: "clothes.wav" },
                { word: "clothing", meaning: "衣服", audio: "clothing.wav" },
                { word: "coat", meaning: "外套", audio: "coat.wav" },
                { word: "collar", meaning: "衣领", audio: "collar.wav" },
                { word: "comfortable", meaning: "舒服的", audio: "comfortable.wav" },
                { word: "cotton", meaning: "棉布", audio: "cotton.wav" },
                { word: "costume", meaning: "服装", audio: "costume.wav" },
                { word: "designer", meaning: "设计师", audio: "designer.wav" },
                { word: "dress", meaning: "裙子", audio: "dress.wav" },
                { word: "elegant", meaning: "优雅的", audio: "elegant.wav" },
                { word: "fabric", meaning: "织物", audio: "fabric.wav" },
                { word: "fashion", meaning: "时尚", audio: "fashion.wav" },
                { word: "fit", meaning: "合身", audio: "fit.wav" },
                { word: "formal", meaning: "正式的", audio: "formal.wav" },
                { word: "glove", meaning: "手套", audio: "glove.wav" },
                { word: "handbag", meaning: "手提包", audio: "handbag.wav" },
                { word: "hat", meaning: "帽子", audio: "hat.wav" },
                { word: "heel", meaning: "高跟鞋", audio: "heel.wav" },
                { word: "jacket", meaning: "夹克", audio: "jacket.wav" },
                { word: "jeans", meaning: "牛仔裤", audio: "jeans.wav" },
                { word: "jewellery", meaning: "首饰", audio: "jewellery.wav" },
                { word: "jumper", meaning: "毛衣", audio: "jumper.wav" },
                { word: "label", meaning: "品牌标签", audio: "label.wav" },
                { word: "leather", meaning: "皮革", audio: "leather.wav" },
                { word: "material", meaning: "面料", audio: "material.wav" },
                { word: "outfit", meaning: "全套服装", audio: "outfit.wav" },
                { word: "pair", meaning: "一对", audio: "pair.wav" },
                { word: "pants", meaning: "裤子", audio: "pants.wav" },
                { word: "pattern", meaning: "图案", audio: "pattern.wav" },
                { word: "pocket", meaning: "口袋", audio: "pocket.wav" },
                { word: "purse", meaning: "钱包", audio: "purse.wav" },
                { word: "ring", meaning: "戒指", audio: "ring.wav" },
                { word: "scarf", meaning: "围巾", audio: "scarf.wav" },
                { word: "shirt", meaning: "衬衫", audio: "shirt.wav" },
                { word: "shoe", meaning: "鞋", audio: "shoe.wav" },
                { word: "shop", meaning: "店铺", audio: "shop.wav" },
                { word: "shorts", meaning: "短裤", audio: "shorts.wav" },
                { word: "silk", meaning: "丝绸", audio: "silk.wav" },
                { word: "size", meaning: "尺寸", audio: "size.wav" },
                { word: "skirt", meaning: "裙子", audio: "skirt.wav" },
                { word: "sleeve", meaning: "袖子", audio: "sleeve.wav" },
                { word: "sock", meaning: "短袜", audio: "sock.wav" },
                { word: "stain", meaning: "污渍", audio: "stain.wav" },
                { word: "stripe", meaning: "条纹", audio: "stripe.wav" },
                { word: "style", meaning: "风格", audio: "style.wav" },
                { word: "suit", meaning: "套装", audio: "suit.wav" },
                { word: "sunglasses", meaning: "太阳镜", audio: "sunglasses.wav" },
                { word: "sweater", meaning: "毛衣", audio: "sweater.wav" },
                { word: "tie", meaning: "领带", audio: "tie.wav" },
                { word: "tight", meaning: "紧的", audio: "tight.wav" },
                { word: "top", meaning: "上衣", audio: "top.wav" },
                { word: "towel", meaning: "毛巾", audio: "towel.wav" },
                { word: "trousers", meaning: "裤子", audio: "trousers.wav" },
                { word: "underwear", meaning: "内衣", audio: "underwear.wav" },
                { word: "uniform", meaning: "制服", audio: "uniform.wav" },
                { word: "vest", meaning: "背心", audio: "vest.wav" },
                { word: "wallet", meaning: "钱包", audio: "wallet.wav" },
                { word: "wear", meaning: "穿", audio: "wear.wav" },
                { word: "wool", meaning: "羊毛", audio: "wool.wav" },
                { word: "zip", meaning: "拉链", audio: "zip.wav" }
            ]
        }
    }
});
