registerWordbook('scene_school', {
    name: "学校教育",
    emoji: "🏫",
    group: 'scene',
    description: "学校、学习、考试相关词汇",
    levels: {
        all: {
            name: "🏫 全部",
            words: [
                { word: "academic", meaning: "学术的", audio: "academic.wav" },
                { word: "academy", meaning: "学院", audio: "academy.wav" },
                { word: "algebra", meaning: "代数", audio: null },
                { word: "arithmetic", meaning: "算术", audio: null },
                { word: "assignment", meaning: "任务", audio: "assignment.wav" },
                { word: "biology", meaning: "生物学", audio: "biology.wav" },
                { word: "blackboard", meaning: "黑板", audio: null },
                { word: "book", meaning: "书", audio: "book.wav" },
                { word: "campus", meaning: "校园", audio: "campus.wav" },
                { word: "certificate", meaning: "证书", audio: "certificate.wav" },
                { word: "chapter", meaning: "章", audio: "chapter.wav" },
                { word: "chemistry", meaning: "化学", audio: "chemistry.wav" },
                { word: "class", meaning: "班级", audio: "class.wav" },
                { word: "classroom", meaning: "课堂", audio: "classroom.wav" },
                { word: "college", meaning: "大学", audio: "college.wav" },
                { word: "composition", meaning: "作品", audio: "composition.wav" },
                { word: "concentrate", meaning: "集中", audio: "concentrate.wav" },
                { word: "course", meaning: "课程", audio: "course.wav" },
                { word: "curriculum", meaning: "课程", audio: "curriculum.wav" },
                { word: "debate", meaning: "辩论", audio: "debate.wav" },
                { word: "degree", meaning: "程度", audio: "degree.wav" },
                { word: "dictionary", meaning: "字典", audio: "dictionary.wav" },
                { word: "diploma", meaning: "文凭", audio: null },
                { word: "discipline", meaning: "纪律", audio: "discipline.wav" },
                { word: "education", meaning: "教育", audio: null },
                { word: "elementary", meaning: "初级", audio: "elementary.wav" },
                { word: "encyclopedia", meaning: "百科全书", audio: null },
                { word: "engineering", meaning: "工程", audio: "engineering.wav" },
                { word: "essay", meaning: "散文", audio: "essay.wav" },
                { word: "exam", meaning: "考试", audio: "exam.wav" },
                { word: "examination", meaning: "考试", audio: "examination.wav" },
                { word: "exercise", meaning: "锻炼", audio: "exercise.wav" },
                { word: "experiment", meaning: "实验", audio: "experiment.wav" },
                { word: "faculty", meaning: "学院", audio: "faculty.wav" },
                { word: "fail", meaning: "失败", audio: "fail.wav" },
                { word: "geography", meaning: "地理", audio: "geography.wav" },
                { word: "grade", meaning: "年级", audio: "grade.wav" },
                { word: "graduate", meaning: "毕业", audio: "graduate.wav" },
                { word: "graduation", meaning: "毕业", audio: null },
                { word: "grammar", meaning: "语法", audio: null },
                { word: "handwriting", meaning: "笔迹", audio: null },
                { word: "headmaster", meaning: "校长", audio: null },
                { word: "history", meaning: "历史", audio: "history.wav" },
                { word: "homework", meaning: "家庭作业", audio: "homework.wav" },
                { word: "instruction", meaning: "操作说明", audio: "instruction.wav" },
                { word: "knowledge", meaning: "知识", audio: "knowledge.wav" },
                { word: "language", meaning: "语言", audio: "language.wav" },
                { word: "learn", meaning: "学习", audio: "learn.wav" },
                { word: "lecture", meaning: "演讲", audio: "lecture.wav" },
                { word: "lesson", meaning: "课", audio: "lesson.wav" },
                { word: "level", meaning: "等级", audio: "level.wav" },
                { word: "library", meaning: "图书馆", audio: "library.wav" },
                { word: "literature", meaning: "文学", audio: "literature.wav" },
                { word: "major", meaning: "主要的", audio: "major.wav" },
                { word: "mark", meaning: "标记", audio: "mark.wav" },
                { word: "master", meaning: "掌握", audio: "master.wav" },
                { word: "mathematics", meaning: "数学", audio: "mathematics.wav" },
                { word: "memory", meaning: "记忆", audio: "memory.wav" },
                { word: "minor", meaning: "次要的", audio: "minor.wav" },
                { word: "note", meaning: "笔记", audio: "note.wav" },
                { word: "notebook", meaning: "笔记本", audio: "notebook.wav" },
                { word: "paragraph", meaning: "段落", audio: "paragraph.wav" },
                { word: "pass", meaning: "经过", audio: "pass.wav" },
                { word: "pen", meaning: "笔", audio: "pen.wav" },
                { word: "pencil", meaning: "铅笔", audio: "pencil.wav" },
                { word: "philosophy", meaning: "哲学", audio: "philosophy.wav" },
                { word: "physics", meaning: "物理", audio: "physics.wav" },
                { word: "practice", meaning: "实践", audio: "practice.wav" },
                { word: "primary", meaning: "基本的", audio: "primary.wav" },
                { word: "principal", meaning: "主要的", audio: "principal.wav" },
                { word: "professor", meaning: "教授", audio: "professor.wav" },
                { word: "program", meaning: "程序", audio: "program.wav" },
                { word: "progress", meaning: "进步", audio: "progress.wav" },
                { word: "project", meaning: "项目", audio: "project.wav" },
                { word: "pupil", meaning: "瞳孔", audio: "pupil.wav" },
                { word: "qualification", meaning: "资质", audio: "qualification.wav" },
                { word: "quiz", meaning: "测验", audio: null },
                { word: "read", meaning: "读", audio: "read.wav" },
                { word: "reading", meaning: "阅读", audio: "reading.wav" },
                { word: "register", meaning: "登记", audio: "register.wav" },
                { word: "research", meaning: "研究", audio: "research.wav" },
                { word: "result", meaning: "结果", audio: "result.wav" },
                { word: "review", meaning: "审查", audio: "review.wav" },
                { word: "revision", meaning: "修订", audio: "revision.wav" },
                { word: "scholar", meaning: "学者", audio: "scholar.wav" },
                { word: "scholarship", meaning: "奖学金", audio: "scholarship.wav" },
                { word: "school", meaning: "学校", audio: "school.wav" },
                { word: "science", meaning: "科学", audio: "science.wav" },
                { word: "secondary", meaning: "中学", audio: "secondary.wav" },
                { word: "semester", meaning: "学期", audio: null },
                { word: "skill", meaning: "技能", audio: "skill.wav" },
                { word: "student", meaning: "学生", audio: "student.wav" },
                { word: "study", meaning: "学习", audio: "study.wav" },
                { word: "subject", meaning: "主题", audio: "subject.wav" },
                { word: "teach", meaning: "教", audio: "teach.wav" },
                { word: "teacher", meaning: "老师", audio: "teacher.wav" },
                { word: "term", meaning: "学期", audio: "term.wav" },
                { word: "test", meaning: "测试", audio: "test.wav" },
                { word: "textbook", meaning: "教科书", audio: "textbook.wav" },
                { word: "theory", meaning: "理论", audio: "theory.wav" },
                { word: "tutor", meaning: "家教", audio: null },
                { word: "undergraduate", meaning: "本科生", audio: "undergraduate.wav" },
                { word: "university", meaning: "大学", audio: "university.wav" },
                { word: "vocabulary", meaning: "词汇", audio: null },
                { word: "write", meaning: "写", audio: "write.wav" },
                { word: "writing", meaning: "写作", audio: "writing.wav" }
            ]
        }
    }
});
