registerWordbook('scene_social', {
    name: "社交情感",
    emoji: "💬",
    group: 'scene',
    description: "情感、社交、人际关系相关词汇",
    levels: {
        all: {
            name: "💬 全部",
            words: [
                { word: "admire", meaning: "钦佩", audio: "admire.wav" },
                { word: "affection", meaning: "感情", audio: "affection.wav" },
                { word: "afraid", meaning: "害怕的", audio: "afraid.wav" },
                { word: "agree", meaning: "同意", audio: "agree.wav" },
                { word: "alone", meaning: "单独", audio: "alone.wav" },
                { word: "anger", meaning: "愤怒", audio: "anger.wav" },
                { word: "angry", meaning: "生气的", audio: "angry.wav" },
                { word: "annoy", meaning: "惹恼", audio: "annoy.wav" },
                { word: "anxious", meaning: "焦虑的", audio: "anxious.wav" },
                { word: "apologize", meaning: "道歉", audio: "apologize.wav" },
                { word: "argue", meaning: "争论", audio: "argue.wav" },
                { word: "argument", meaning: "争论", audio: "argument.wav" },
                { word: "ashamed", meaning: "羞愧", audio: "ashamed.wav" },
                { word: "attitude", meaning: "态度", audio: "attitude.wav" },
                { word: "attract", meaning: "吸引", audio: "attract.wav" },
                { word: "awkward", meaning: "尴尬的", audio: "awkward.wav" },
                { word: "blame", meaning: "责备", audio: "blame.wav" },
                { word: "bore", meaning: "使厌烦", audio: "bore.wav" },
                { word: "bother", meaning: "打扰", audio: "bother.wav" },
                { word: "brave", meaning: "勇敢的", audio: "brave.wav" },
                { word: "calm", meaning: "冷静的", audio: "calm.wav" },
                { word: "care", meaning: "关心", audio: "care.wav" },
                { word: "celebrate", meaning: "庆祝", audio: "celebrate.wav" },
                { word: "cheer", meaning: "欢呼", audio: "cheer.wav" },
                { word: "comfort", meaning: "安慰", audio: "comfort.wav" },
                { word: "communicate", meaning: "交流", audio: "communicate.wav" },
                { word: "communication", meaning: "沟通", audio: "communication.wav" },
                { word: "community", meaning: "社区", audio: "community.wav" },
                { word: "companion", meaning: "同伴; 伙伴", audio: "companion.wav" },
                { word: "complain", meaning: "抱怨", audio: "complain.wav" },
                { word: "compliment", meaning: "赞美", audio: "compliment.wav" },
                { word: "concern", meaning: "关心; 担忧", audio: "concern.wav" },
                { word: "confidence", meaning: "信心", audio: "confidence.wav" },
                { word: "confident", meaning: "自信的", audio: "confident.wav" },
                { word: "confuse", meaning: "使困惑", audio: "confuse.wav" },
                { word: "congratulate", meaning: "祝贺", audio: "congratulate.wav" },
                { word: "conversation", meaning: "对话", audio: "conversation.wav" },
                { word: "cry", meaning: "哭", audio: "cry.wav" },
                { word: "culture", meaning: "文化", audio: "culture.wav" },
                { word: "curious", meaning: "好奇的", audio: "curious.wav" },
                { word: "date", meaning: "约会", audio: "date.wav" },
                { word: "delight", meaning: "高兴; 愉快", audio: "delight.wav" },
                { word: "depressed", meaning: "沮丧的; 消沉的", audio: "depressed.wav" },
                { word: "desire", meaning: "渴望; 愿望", audio: "desire.wav" },
                { word: "disappoint", meaning: "使失望", audio: "disappoint.wav" },
                { word: "emotion", meaning: "情感", audio: "emotion.wav" },
                { word: "emotional", meaning: "情绪化的", audio: "emotional.wav" },
                { word: "empathy", meaning: "共情; 同理心", audio: "empathy.wav" },
                { word: "encourage", meaning: "鼓励", audio: "encourage.wav" },
                { word: "enthusiasm", meaning: "热情", audio: "enthusiasm.wav" },
                { word: "envy", meaning: "嫉妒", audio: "envy.wav" },
                { word: "excuse", meaning: "借口; 请原谅", audio: "excuse.wav" },
                { word: "family", meaning: "家庭", audio: "family.wav" },
                { word: "fear", meaning: "害怕", audio: "fear.wav" },
                { word: "feel", meaning: "感觉", audio: "feel.wav" },
                { word: "feeling", meaning: "感觉", audio: "feeling.wav" },
                { word: "forgive", meaning: "原谅", audio: "forgive.wav" },
                { word: "friend", meaning: "朋友", audio: "friend.wav" },
                { word: "friendly", meaning: "友好的", audio: "friendly.wav" },
                { word: "friendship", meaning: "友谊", audio: "friendship.wav" },
                { word: "frustrate", meaning: "使沮丧; 使受挫", audio: "frustrate.wav" },
                { word: "generous", meaning: "慷慨的", audio: "generous.wav" },
                { word: "gentle", meaning: "温和的", audio: "gentle.wav" },
                { word: "grateful", meaning: "感激的", audio: "grateful.wav" },
                { word: "greet", meaning: "打招呼; 问候", audio: "greet.wav" },
                { word: "grief", meaning: "悲伤", audio: "grief.wav" },
                { word: "guilt", meaning: "内疚; 愧疚", audio: "guilt.wav" },
                { word: "happiness", meaning: "幸福", audio: "happiness.wav" },
                { word: "happy", meaning: "快乐的", audio: "happy.wav" },
                { word: "hate", meaning: "恨", audio: "hate.wav" },
                { word: "honest", meaning: "诚实的", audio: "honest.wav" },
                { word: "hope", meaning: "希望", audio: "hope.wav" },
                { word: "hug", meaning: "拥抱", audio: "hug.wav" },
                { word: "humour", meaning: "幽默", audio: "humour.wav" },
                { word: "impress", meaning: "留下深刻印象", audio: "impress.wav" },
                { word: "inspire", meaning: "启发", audio: "inspire.wav" },
                { word: "introduce", meaning: "介绍", audio: "introduce.wav" },
                { word: "invite", meaning: "邀请", audio: "invite.wav" },
                { word: "irritate", meaning: "激怒", audio: "irritate.wav" },
                { word: "jealous", meaning: "嫉妒的", audio: "jealous.wav" },
                { word: "joy", meaning: "喜悦", audio: "joy.wav" },
                { word: "kind", meaning: "善良的; 友好的", audio: "kind.wav" },
                { word: "kiss", meaning: "吻", audio: "kiss.wav" },
                { word: "laugh", meaning: "笑", audio: "laugh.wav" },
                { word: "lonely", meaning: "孤独", audio: "lonely.wav" },
                { word: "love", meaning: "爱", audio: "love.wav" },
                { word: "marry", meaning: "结婚", audio: "marry.wav" },
                { word: "mood", meaning: "情绪", audio: "mood.wav" },
                { word: "neighbour", meaning: "邻居", audio: "neighbour.wav" },
                { word: "nervous", meaning: "紧张的", audio: "nervous.wav" },
                { word: "offend", meaning: "得罪", audio: "offend.wav" },
                { word: "opinion", meaning: "观点", audio: "opinion.wav" },
                { word: "passion", meaning: "热情", audio: "passion.wav" },
                { word: "patient", meaning: "耐心的", audio: "patient.wav" },
                { word: "personality", meaning: "性格", audio: "personality.wav" },
                { word: "pity", meaning: "同情; 怜悯", audio: "pity.wav" },
                { word: "pleased", meaning: "高兴", audio: "pleased.wav" },
                { word: "polite", meaning: "有礼貌的", audio: "polite.wav" },
                { word: "praise", meaning: "称赞", audio: "praise.wav" },
                { word: "pride", meaning: "自豪", audio: "pride.wav" },
                { word: "promise", meaning: "承诺", audio: "promise.wav" },
                { word: "proud", meaning: "自豪的", audio: "proud.wav" },
                { word: "quarrel", meaning: "争吵", audio: "quarrel.wav" },
                { word: "regret", meaning: "后悔", audio: "regret.wav" },
                { word: "reject", meaning: "拒绝", audio: "reject.wav" },
                { word: "relationship", meaning: "关系", audio: "relationship.wav" },
                { word: "relief", meaning: "宽慰", audio: "relief.wav" },
                { word: "respect", meaning: "尊重", audio: "respect.wav" },
                { word: "romance", meaning: "浪漫", audio: "romance.wav" },
                { word: "romantic", meaning: "浪漫的", audio: "romantic.wav" },
                { word: "rude", meaning: "粗鲁的", audio: "rude.wav" },
                { word: "sad", meaning: "伤心", audio: "sad.wav" },
                { word: "satisfy", meaning: "满足", audio: "satisfy.wav" },
                { word: "shame", meaning: "耻辱", audio: "shame.wav" },
                { word: "share", meaning: "分享", audio: "share.wav" },
                { word: "shock", meaning: "震惊", audio: "shock.wav" },
                { word: "shy", meaning: "害羞的", audio: "shy.wav" },
                { word: "sincere", meaning: "真诚", audio: "sincere.wav" },
                { word: "smile", meaning: "微笑", audio: "smile.wav" },
                { word: "social", meaning: "社交的", audio: "social.wav" },
                { word: "sorrow", meaning: "悲伤", audio: "sorrow.wav" },
                { word: "sorry", meaning: "对不起", audio: "sorry.wav" },
                { word: "sympathy", meaning: "同情", audio: "sympathy.wav" },
                { word: "tease", meaning: "取笑", audio: "tease.wav" },
                { word: "temper", meaning: "脾气", audio: "temper.wav" },
                { word: "tender", meaning: "温柔的", audio: "tender.wav" },
                { word: "thankful", meaning: "感激的", audio: "thankful.wav" },
                { word: "trust", meaning: "信任", audio: "trust.wav" },
                { word: "upset", meaning: "沮丧的", audio: "upset.wav" },
                { word: "welcome", meaning: "欢迎", audio: "welcome.wav" },
                { word: "wish", meaning: "希望", audio: "wish.wav" },
                { word: "worry", meaning: "担心", audio: "worry.wav" }
            ]
        }
    }
});
