registerWordbook('scene_school', {
    name: "学校教育",
    emoji: "🏫",
    group: 'scene',
    description: "学校、学习、考试相关词汇",
    levels: {
        all: {
            name: "🏫 全部",
            words: [
                { word: "academic", meaning: "学术的", audio: "academic.wav" },
                { word: "academy", meaning: "学院", audio: "academy.wav" },
                { word: "algebra", meaning: "代数", audio: "algebra.wav" },
                { word: "arithmetic", meaning: "算术", audio: "arithmetic.wav" },
                { word: "assignment", meaning: "作业", audio: "assignment.wav" },
                { word: "biology", meaning: "生物学", audio: "biology.wav" },
                { word: "blackboard", meaning: "黑板", audio: "blackboard.wav" },
                { word: "book", meaning: "书", audio: "book.wav" },
                { word: "campus", meaning: "校园", audio: "campus.wav" },
                { word: "certificate", meaning: "证书", audio: "certificate.wav" },
                { word: "chapter", meaning: "章", audio: "chapter.wav" },
                { word: "chemistry", meaning: "化学", audio: "chemistry.wav" },
                { word: "class", meaning: "班级", audio: "class.wav" },
                { word: "classroom", meaning: "教室", audio: "classroom.wav" },
                { word: "college", meaning: "大学", audio: "college.wav" },
                { word: "composition", meaning: "作文", audio: "composition.wav" },
                { word: "concentrate", meaning: "集中注意力; 专心", audio: "concentrate.wav" },
                { word: "course", meaning: "课程", audio: "course.wav" },
                { word: "curriculum", meaning: "课程", audio: "curriculum.wav" },
                { word: "debate", meaning: "辩论", audio: "debate.wav" },
                { word: "degree", meaning: "学位", audio: "degree.wav" },
                { word: "dictionary", meaning: "字典", audio: "dictionary.wav" },
                { word: "diploma", meaning: "文凭", audio: "diploma.wav" },
                { word: "discipline", meaning: "纪律", audio: "discipline.wav" },
                { word: "education", meaning: "教育", audio: "education.wav" },
                { word: "elementary", meaning: "小学的", audio: "elementary.wav" },
                { word: "encyclopedia", meaning: "百科全书", audio: "encyclopedia.wav" },
                { word: "engineering", meaning: "工程", audio: "engineering.wav" },
                { word: "essay", meaning: "论文; 作文", audio: "essay.wav" },
                { word: "exam", meaning: "考试", audio: "exam.wav" },
                { word: "examination", meaning: "考试", audio: "examination.wav" },
                { word: "exercise", meaning: "练习; 习题", audio: "exercise.wav" },
                { word: "experiment", meaning: "实验", audio: "experiment.wav" },
                { word: "faculty", meaning: "全体教员", audio: "faculty.wav" },
                { word: "fail", meaning: "不及格; 挂科", audio: "fail.wav" },
                { word: "geography", meaning: "地理", audio: "geography.wav" },
                { word: "grade", meaning: "成绩; 分数", audio: "grade.wav" },
                { word: "graduate", meaning: "毕业", audio: "graduate.wav" },
                { word: "graduation", meaning: "毕业", audio: "graduation.wav" },
                { word: "grammar", meaning: "语法", audio: "grammar.wav" },
                { word: "handwriting", meaning: "书写; 书法", audio: "handwriting.wav" },
                { word: "headmaster", meaning: "校长", audio: "headmaster.wav" },
                { word: "history", meaning: "历史", audio: "history.wav" },
                { word: "homework", meaning: "家庭作业", audio: "homework.wav" },
                { word: "instruction", meaning: "教学; 讲授", audio: "instruction.wav" },
                { word: "knowledge", meaning: "知识", audio: "knowledge.wav" },
                { word: "language", meaning: "语言", audio: "language.wav" },
                { word: "learn", meaning: "学习", audio: "learn.wav" },
                { word: "lecture", meaning: "讲座; 课", audio: "lecture.wav" },
                { word: "lesson", meaning: "课", audio: "lesson.wav" },
                { word: "level", meaning: "水平; 程度", audio: "level.wav" },
                { word: "library", meaning: "图书馆", audio: "library.wav" },
                { word: "literature", meaning: "文学", audio: "literature.wav" },
                { word: "major", meaning: "专业", audio: "major.wav" },
                { word: "mark", meaning: "分数; 评分", audio: "mark.wav" },
                { word: "master", meaning: "硕士", audio: "master.wav" },
                { word: "mathematics", meaning: "数学", audio: "mathematics.wav" },
                { word: "memory", meaning: "记忆", audio: "memory.wav" },
                { word: "minor", meaning: "辅修(专业)", audio: "minor.wav" },
                { word: "note", meaning: "笔记", audio: "note.wav" },
                { word: "notebook", meaning: "笔记本", audio: "notebook.wav" },
                { word: "paragraph", meaning: "段落", audio: "paragraph.wav" },
                { word: "pass", meaning: "及格; 通过", audio: "pass.wav" },
                { word: "pen", meaning: "笔", audio: "pen.wav" },
                { word: "pencil", meaning: "铅笔", audio: "pencil.wav" },
                { word: "philosophy", meaning: "哲学", audio: "philosophy.wav" },
                { word: "physics", meaning: "物理", audio: "physics.wav" },
                { word: "practice", meaning: "练习", audio: "practice.wav" },
                { word: "primary", meaning: "小学的; 初等的", audio: "primary.wav" },
                { word: "principal", meaning: "校长", audio: "principal.wav" },
                { word: "professor", meaning: "教授", audio: "professor.wav" },
                { word: "program", meaning: "课程; 教学计划", audio: "program.wav" },
                { word: "progress", meaning: "进步", audio: "progress.wav" },
                { word: "project", meaning: "课题; 研究项目", audio: "project.wav" },
                { word: "pupil", meaning: "学生; 小学生", audio: "pupil.wav" },
                { word: "qualification", meaning: "学历; 资格证书", audio: "qualification.wav" },
                { word: "quiz", meaning: "测验", audio: "quiz.wav" },
                { word: "read", meaning: "读", audio: "read.wav" },
                { word: "reading", meaning: "阅读", audio: "reading.wav" },
                { word: "register", meaning: "注册; 报到", audio: "register.wav" },
                { word: "research", meaning: "研究", audio: "research.wav" },
                { word: "result", meaning: "成绩; 考试结果", audio: "result.wav" },
                { word: "review", meaning: "复习", audio: "review.wav" },
                { word: "revision", meaning: "复习", audio: "revision.wav" },
                { word: "scholar", meaning: "学者", audio: "scholar.wav" },
                { word: "scholarship", meaning: "奖学金", audio: "scholarship.wav" },
                { word: "school", meaning: "学校", audio: "school.wav" },
                { word: "science", meaning: "科学", audio: "science.wav" },
                { word: "secondary", meaning: "中学的; 中等的", audio: "secondary.wav" },
                { word: "semester", meaning: "学期", audio: "semester.wav" },
                { word: "skill", meaning: "技能", audio: "skill.wav" },
                { word: "student", meaning: "学生", audio: "student.wav" },
                { word: "study", meaning: "学习", audio: "study.wav" },
                { word: "subject", meaning: "学科; 科目", audio: "subject.wav" },
                { word: "teach", meaning: "教", audio: "teach.wav" },
                { word: "teacher", meaning: "老师", audio: "teacher.wav" },
                { word: "term", meaning: "学期", audio: "term.wav" },
                { word: "test", meaning: "测试", audio: "test.wav" },
                { word: "textbook", meaning: "教科书", audio: "textbook.wav" },
                { word: "theory", meaning: "理论", audio: "theory.wav" },
                { word: "tutor", meaning: "家教", audio: "tutor.wav" },
                { word: "undergraduate", meaning: "本科生", audio: "undergraduate.wav" },
                { word: "university", meaning: "大学", audio: "university.wav" },
                { word: "vocabulary", meaning: "词汇", audio: "vocabulary.wav" },
                { word: "write", meaning: "写", audio: "write.wav" },
                { word: "writing", meaning: "写作", audio: "writing.wav" }
            ]
        }
    }
});
