registerWordbook('scene_cooking', {
    name: "烹饪厨房",
    emoji: "🍳",
    group: 'scene',
    description: "烹饪方法、厨具、调料相关词汇",
    levels: {
        all: {
            name: "🍳 全部",
            words: [
                { word: "bake", meaning: "烤", audio: "bake.wav" },
                { word: "barbecue", meaning: "烧烤", audio: "barbecue.wav" },
                { word: "basin", meaning: "盆", audio: "basin.wav" },
                { word: "baste", meaning: "浇汁", audio: "baste.wav" },
                { word: "beat", meaning: "打", audio: "beat.wav" },
                { word: "blend", meaning: "混合", audio: "blend.wav" },
                { word: "blender", meaning: "搅拌机", audio: "blender.wav" },
                { word: "boil", meaning: "熬", audio: "boil.wav" },
                { word: "bone", meaning: "骨", audio: "bone.wav" },
                { word: "bottle", meaning: "瓶子", audio: "bottle.wav" },
                { word: "bowl", meaning: "碗", audio: "bowl.wav" },
                { word: "braise", meaning: "炖", audio: "braise.wav" },
                { word: "bread", meaning: "面包", audio: "bread.wav" },
                { word: "broil", meaning: "炒", audio: "broil.wav" },
                { word: "broth", meaning: "肉汤", audio: "broth.wav" },
                { word: "brown", meaning: "棕色的", audio: "brown.wav" },
                { word: "brush", meaning: "刷子", audio: "brush.wav" },
                { word: "burn", meaning: "烧伤", audio: "burn.wav" },
                { word: "butter", meaning: "黄油", audio: "butter.wav" },
                { word: "cabinet", meaning: "内阁", audio: "cabinet.wav" },
                { word: "carve", meaning: "雕刻", audio: "carve.wav" },
                { word: "chilli", meaning: "辣椒", audio: "chilli.wav" },
                { word: "chop", meaning: "劈", audio: "chop.wav" },
                { word: "cinnamon", meaning: "肉桂", audio: "cinnamon.wav" },
                { word: "clean", meaning: "干净的", audio: "clean.wav" },
                { word: "coat", meaning: "外套", audio: "coat.wav" },
                { word: "combine", meaning: "结合", audio: "combine.wav" },
                { word: "cook", meaning: "厨师", audio: "cook.wav" },
                { word: "counter", meaning: "柜台", audio: "counter.wav" },
                { word: "cream", meaning: "奶油", audio: "cream.wav" },
                { word: "crush", meaning: "压碎", audio: "crush.wav" },
                { word: "cube", meaning: "切成丁", audio: "cube.wav" },
                { word: "cup", meaning: "杯子", audio: "cup.wav" },
                { word: "cut", meaning: "切割", audio: "cut.wav" },
                { word: "deep", meaning: "深的", audio: "deep.wav" },
                { word: "defrost", meaning: "解冻", audio: "defrost.wav" },
                { word: "dice", meaning: "切粒", audio: "dice.wav" },
                { word: "dish", meaning: "盘子", audio: "dish.wav" },
                { word: "dissolve", meaning: "溶解", audio: "dissolve.wav" },
                { word: "drain", meaning: "流走", audio: "drain.wav" },
                { word: "dressing", meaning: "调料", audio: "dressing.wav" },
                { word: "dry", meaning: "干燥", audio: "dry.wav" },
                { word: "egg", meaning: "蛋", audio: "egg.wav" },
                { word: "extract", meaning: "提炼", audio: "extract.wav" },
                { word: "fat", meaning: "胖的", audio: "fat.wav" },
                { word: "fill", meaning: "充满", audio: "fill.wav" },
                { word: "filter", meaning: "筛选", audio: "filter.wav" },
                { word: "flame", meaning: "火焰", audio: "flame.wav" },
                { word: "flavour", meaning: "味道", audio: "flavour.wav" },
                { word: "flour", meaning: "面粉", audio: "flour.wav" },
                { word: "fold", meaning: "折叠", audio: "fold.wav" },
                { word: "food", meaning: "食物", audio: "food.wav" },
                { word: "fork", meaning: "叉", audio: "fork.wav" },
                { word: "freeze", meaning: "冻结", audio: "freeze.wav" },
                { word: "fresh", meaning: "新鲜的", audio: "fresh.wav" },
                { word: "fridge", meaning: "冰箱", audio: "fridge.wav" },
                { word: "fry", meaning: "炒", audio: "fry.wav" },
                { word: "ginger", meaning: "姜", audio: "ginger.wav" },
                { word: "glass", meaning: "玻璃", audio: "glass.wav" },
                { word: "grate", meaning: "擦磨", audio: "grate.wav" },
                { word: "gravy", meaning: "肉汁", audio: "gravy.wav" },
                { word: "grease", meaning: "油脂", audio: "grease.wav" },
                { word: "grill", meaning: "烧烤", audio: "grill.wav" },
                { word: "grind", meaning: "研磨", audio: "grind.wav" },
                { word: "heat", meaning: "热", audio: "heat.wav" },
                { word: "herb", meaning: "草本植物", audio: "herb.wav" },
                { word: "honey", meaning: "蜂蜜", audio: "honey.wav" },
                { word: "ingredient", meaning: "成分", audio: "ingredient.wav" },
                { word: "jar", meaning: "罐子", audio: "jar.wav" },
                { word: "juice", meaning: "汁", audio: "juice.wav" },
                { word: "kettle", meaning: "水壶", audio: "kettle.wav" },
                { word: "knife", meaning: "刀", audio: "knife.wav" },
                { word: "knead", meaning: "揉面", audio: "knead.wav" },
                { word: "ladle", meaning: "长柄勺", audio: "ladle.wav" },
                { word: "lid", meaning: "盖子", audio: "lid.wav" },
                { word: "liquid", meaning: "液体", audio: "liquid.wav" },
                { word: "marinade", meaning: "腌汁", audio: "marinade.wav" },
                { word: "marinate", meaning: "腌制", audio: "marinate.wav" },
                { word: "mash", meaning: "捣碎", audio: "mash.wav" },
                { word: "measure", meaning: "措施", audio: "measure.wav" },
                { word: "melt", meaning: "熔化", audio: "melt.wav" },
                { word: "microwave", meaning: "微波炉", audio: "microwave.wav" },
                { word: "mince", meaning: "切碎", audio: "mince.wav" },
                { word: "mix", meaning: "混合", audio: "mix.wav" },
                { word: "mustard", meaning: "芥末", audio: "mustard.wav" },
                { word: "oil", meaning: "油", audio: "oil.wav" },
                { word: "oven", meaning: "烤箱", audio: "oven.wav" },
                { word: "pan", meaning: "平底锅", audio: "pan.wav" },
                { word: "paste", meaning: "糊状物", audio: "paste.wav" },
                { word: "peel", meaning: "削皮", audio: "peel.wav" },
                { word: "pepper", meaning: "胡椒", audio: "pepper.wav" },
                { word: "pinch", meaning: "一撒", audio: "pinch.wav" },
                { word: "plate", meaning: "盘子", audio: "plate.wav" },
                { word: "poach", meaning: "水煮", audio: "poach.wav" },
                { word: "portion", meaning: "部分", audio: "portion.wav" },
                { word: "pot", meaning: "锅", audio: "pot.wav" },
                { word: "pour", meaning: "倒", audio: "pour.wav" },
                { word: "preserve", meaning: "保存", audio: "preserve.wav" },
                { word: "press", meaning: "按", audio: "press.wav" },
                { word: "raw", meaning: "生的", audio: "raw.wav" },
                { word: "recipe", meaning: "食谱", audio: "recipe.wav" },
                { word: "reduce", meaning: "减少", audio: "reduce.wav" },
                { word: "refrigerate", meaning: "冷藏", audio: "refrigerate.wav" },
                { word: "rinse", meaning: "冲洗", audio: "rinse.wav" },
                { word: "roast", meaning: "烤", audio: "roast.wav" },
                { word: "roll", meaning: "卷", audio: "roll.wav" },
                { word: "salt", meaning: "盐", audio: "salt.wav" },
                { word: "sauce", meaning: "酱", audio: "sauce.wav" },
                { word: "season", meaning: "季节", audio: "season.wav" },
                { word: "serve", meaning: "服务", audio: "serve.wav" },
                { word: "shallow", meaning: "浅的", audio: "shallow.wav" },
                { word: "simmer", meaning: "慢炖", audio: "simmer.wav" },
                { word: "sink", meaning: "下沉", audio: "sink.wav" },
                { word: "slice", meaning: "片", audio: "slice.wav" },
                { word: "smoke", meaning: "抽烟", audio: "smoke.wav" },
                { word: "soak", meaning: "浸泡", audio: "soak.wav" },
                { word: "soup", meaning: "汤", audio: "soup.wav" },
                { word: "spatula", meaning: "铲刀", audio: "spatula.wav" },
                { word: "spice", meaning: "香料", audio: "spice.wav" },
                { word: "spoon", meaning: "勺子", audio: "spoon.wav" },
                { word: "spray", meaning: "喷洒", audio: "spray.wav" },
                { word: "sprinkle", meaning: "撒", audio: "sprinkle.wav" },
                { word: "squeeze", meaning: "挤压", audio: "squeeze.wav" },
                { word: "steam", meaning: "蒸汽", audio: "steam.wav" },
                { word: "stew", meaning: "炖菜", audio: "stew.wav" },
                { word: "stir", meaning: "搅拌", audio: "stir.wav" },
                { word: "stock", meaning: "库存", audio: "stock.wav" },
                { word: "stove", meaning: "炉子", audio: "stove.wav" },
                { word: "strain", meaning: "压力", audio: "strain.wav" },
                { word: "sugar", meaning: "糖", audio: "sugar.wav" },
                { word: "tablespoon", meaning: "汤匙", audio: "tablespoon.wav" },
                { word: "taste", meaning: "品尝", audio: "taste.wav" },
                { word: "temperature", meaning: "温度", audio: "temperature.wav" },
                { word: "tender", meaning: "温柔的", audio: "tender.wav" },
                { word: "thaw", meaning: "解冻", audio: "thaw.wav" },
                { word: "thermometer", meaning: "温度计", audio: "thermometer.wav" },
                { word: "toast", meaning: "吐司", audio: "toast.wav" },
                { word: "toss", meaning: "投掷", audio: "toss.wav" },
                { word: "trim", meaning: "修剪", audio: "trim.wav" },
                { word: "vinegar", meaning: "醋", audio: "vinegar.wav" },
                { word: "warm", meaning: "温暖的", audio: "warm.wav" },
                { word: "wash", meaning: "洗", audio: "wash.wav" },
                { word: "water", meaning: "水", audio: "water.wav" },
                { word: "whip", meaning: "鞭子", audio: "whip.wav" },
                { word: "whisk", meaning: "打蛋器", audio: "whisk.wav" }
            ]
        }
    }
});
