registerWordbook('scene_law', {
    name: "法律法规",
    emoji: "⚖️",
    group: 'scene',
    description: "日常法律术语相关词汇",
    levels: {
        all: {
            name: "⚖️ 全部",
            words: [
                { word: "abolish", meaning: "取消", audio: "abolish.wav" },
                { word: "abuse", meaning: "虐待", audio: "abuse.wav" },
                { word: "accuse", meaning: "控", audio: "accuse.wav" },
                { word: "acquit", meaning: "宣判无罪", audio: "acquit.wav" },
                { word: "act", meaning: "法案; 法令", audio: "act.wav" },
                { word: "allege", meaning: "声称", audio: "allege.wav" },
                { word: "amend", meaning: "修正", audio: "amend.wav" },
                { word: "appeal", meaning: "上诉", audio: "appeal.wav" },
                { word: "appoint", meaning: "委", audio: "appoint.wav" },
                { word: "arbitrate", meaning: "仲裁", audio: "arbitrate.wav" },
                { word: "arrest", meaning: "逮捕", audio: "arrest.wav" },
                { word: "assault", meaning: "人身攻击; 侵犯", audio: "assault.wav" },
                { word: "attorney", meaning: "律师", audio: "attorney.wav" },
                { word: "authority", meaning: "权威", audio: "authority.wav" },
                { word: "bail", meaning: "保释", audio: "bail.wav" },
                { word: "ban", meaning: "禁止", audio: "ban.wav" },
                { word: "bankrupt", meaning: "破产的", audio: "bankrupt.wav" },
                { word: "bar", meaning: "律师协会; 法律界", audio: "bar.wav" },
                { word: "bind", meaning: "绑定", audio: "bind.wav" },
                { word: "blame", meaning: "责备", audio: "blame.wav" },
                { word: "breach", meaning: "违反", audio: "breach.wav" },
                { word: "bribe", meaning: "贿赂", audio: "bribe.wav" },
                { word: "burden", meaning: "负担", audio: "burden.wav" },
                { word: "case", meaning: "案件", audio: "case.wav" },
                { word: "charge", meaning: "指控; 控告", audio: "charge.wav" },
                { word: "civil", meaning: "民事", audio: "civil.wav" },
                { word: "claim", meaning: "索赔; 诉求", audio: "claim.wav" },
                { word: "clause", meaning: "条款", audio: "clause.wav" },
                { word: "client", meaning: "客户", audio: "client.wav" },
                { word: "code", meaning: "法典; 法规", audio: "code.wav" },
                { word: "commit", meaning: "犯罪", audio: "commit.wav" },
                { word: "compensation", meaning: "赔偿", audio: "compensation.wav" },
                { word: "complaint", meaning: "起诉书; 控告", audio: "complaint.wav" },
                { word: "comply", meaning: "遵守", audio: "comply.wav" },
                { word: "confess", meaning: "承认", audio: "confess.wav" },
                { word: "confiscate", meaning: "没收", audio: "confiscate.wav" },
                { word: "consent", meaning: "同意", audio: "consent.wav" },
                { word: "constitution", meaning: "宪法", audio: "constitution.wav" },
                { word: "contract", meaning: "合同", audio: "contract.wav" },
                { word: "convict", meaning: "定罪", audio: "convict.wav" },
                { word: "copyright", meaning: "版权", audio: "copyright.wav" },
                { word: "corrupt", meaning: "腐败", audio: "corrupt.wav" },
                { word: "counsel", meaning: "辩护律师", audio: "counsel.wav" },
                { word: "court", meaning: "法庭", audio: "court.wav" },
                { word: "crime", meaning: "犯罪", audio: "crime.wav" },
                { word: "criminal", meaning: "刑事", audio: "criminal.wav" },
                { word: "custody", meaning: "保管", audio: "custody.wav" },
                { word: "damage", meaning: "损害", audio: "damage.wav" },
                { word: "deceive", meaning: "欺骗", audio: "deceive.wav" },
                { word: "decree", meaning: "法令", audio: "decree.wav" },
                { word: "defence", meaning: "防御", audio: "defence.wav" },
                { word: "defendant", meaning: "被告", audio: "defendant.wav" },
                { word: "detain", meaning: "扣留", audio: "detain.wav" },
                { word: "discriminate", meaning: "歧视", audio: "discriminate.wav" },
                { word: "dispute", meaning: "争议", audio: "dispute.wav" },
                { word: "dissolve", meaning: "解散", audio: "dissolve.wav" },
                { word: "document", meaning: "文档", audio: "document.wav" },
                { word: "draft", meaning: "草稿", audio: "draft.wav" },
                { word: "duty", meaning: "责任", audio: "duty.wav" },
                { word: "enforce", meaning: "执行", audio: "enforce.wav" },
                { word: "entitle", meaning: "赋予", audio: "entitle.wav" },
                { word: "estate", meaning: "财产", audio: "estate.wav" },
                { word: "evidence", meaning: "证据", audio: "evidence.wav" },
                { word: "execute", meaning: "执行", audio: "execute.wav" },
                { word: "exempt", meaning: "豁免", audio: "exempt.wav" },
                { word: "extradite", meaning: "引渡", audio: "extradite.wav" },
                { word: "federal", meaning: "联邦", audio: "federal.wav" },
                { word: "felony", meaning: "重罪", audio: "felony.wav" },
                { word: "file", meaning: "提交(诉讼); 立案", audio: "file.wav" },
                { word: "fine", meaning: "罚款", audio: "fine.wav" },
                { word: "forge", meaning: "伪造", audio: "forge.wav" },
                { word: "fraud", meaning: "欺诈罪", audio: "fraud.wav" },
                { word: "freedom", meaning: "自由", audio: "freedom.wav" },
                { word: "guilty", meaning: "有罪的", audio: "guilty.wav" },
                { word: "hearing", meaning: "听证会", audio: "hearing.wav" },
                { word: "heir", meaning: "继承人", audio: "heir.wav" },
                { word: "illegal", meaning: "非法的", audio: "illegal.wav" },
                { word: "imprison", meaning: "监禁", audio: "imprison.wav" },
                { word: "indict", meaning: "起诉", audio: "indict.wav" },
                { word: "inherit", meaning: "继承", audio: "inherit.wav" },
                { word: "injustice", meaning: "不公正", audio: "injustice.wav" },
                { word: "innocent", meaning: "清白的", audio: "innocent.wav" },
                { word: "inspect", meaning: "检查", audio: "inspect.wav" },
                { word: "insurance", meaning: "保险", audio: "insurance.wav" },
                { word: "intellectual", meaning: "知识产权的", audio: "intellectual.wav" },
                { word: "investigate", meaning: "调查", audio: "investigate.wav" },
                { word: "jail", meaning: "监狱", audio: "jail.wav" },
                { word: "judge", meaning: "法官", audio: "judge.wav" },
                { word: "jury", meaning: "陪审团", audio: "jury.wav" },
                { word: "justice", meaning: "正义", audio: "justice.wav" },
                { word: "juvenile", meaning: "少年的", audio: "juvenile.wav" },
                { word: "kidnap", meaning: "绑架", audio: "kidnap.wav" },
                { word: "law", meaning: "法律", audio: "law.wav" },
                { word: "lawsuit", meaning: "诉讼", audio: "lawsuit.wav" },
                { word: "lawyer", meaning: "律师", audio: "lawyer.wav" },
                { word: "legal", meaning: "合法的", audio: "legal.wav" },
                { word: "legislate", meaning: "立法", audio: "legislate.wav" },
                { word: "legitimate", meaning: "合法的", audio: "legitimate.wav" },
                { word: "liability", meaning: "法律责任", audio: "liability.wav" },
                { word: "licence", meaning: "执照", audio: "licence.wav" },
                { word: "litigate", meaning: "诉讼", audio: "litigate.wav" },
                { word: "mandate", meaning: "授权", audio: "mandate.wav" },
                { word: "misconduct", meaning: "不当行为", audio: "misconduct.wav" },
                { word: "murder", meaning: "谋杀", audio: "murder.wav" },
                { word: "negotiate", meaning: "谈判", audio: "negotiate.wav" },
                { word: "oath", meaning: "宣誓", audio: "oath.wav" },
                { word: "offence", meaning: "罪行", audio: "offence.wav" },
                { word: "offend", meaning: "得罪", audio: "offend.wav" },
                { word: "pardon", meaning: "赦免", audio: "pardon.wav" },
                { word: "parole", meaning: "假释", audio: "parole.wav" },
                { word: "patent", meaning: "专利", audio: "patent.wav" },
                { word: "penalty", meaning: "惩罚", audio: "penalty.wav" },
                { word: "petition", meaning: "请愿", audio: "petition.wav" },
                { word: "plead", meaning: "辩护", audio: "plead.wav" },
                { word: "police", meaning: "警察", audio: "police.wav" },
                { word: "precedent", meaning: "先例", audio: "precedent.wav" },
                { word: "prison", meaning: "监狱", audio: "prison.wav" },
                { word: "prosecute", meaning: "起诉", audio: "prosecute.wav" },
                { word: "prove", meaning: "证明", audio: "prove.wav" },
                { word: "punish", meaning: "惩治", audio: "punish.wav" },
                { word: "regulate", meaning: "监管", audio: "regulate.wav" },
                { word: "release", meaning: "释放", audio: "release.wav" },
                { word: "remedy", meaning: "补救", audio: "remedy.wav" },
                { word: "repeal", meaning: "废除", audio: "repeal.wav" },
                { word: "right", meaning: "权利", audio: "right.wav" },
                { word: "rob", meaning: "抢", audio: "rob.wav" },
                { word: "rule", meaning: "规则", audio: "rule.wav" },
                { word: "sanction", meaning: "制裁", audio: "sanction.wav" },
                { word: "sentence", meaning: "判决; 量刑", audio: "sentence.wav" },
                { word: "settle", meaning: "和解", audio: "settle.wav" },
                { word: "smuggle", meaning: "走私", audio: "smuggle.wav" },
                { word: "statute", meaning: "法规", audio: "statute.wav" },
                { word: "steal", meaning: "偷", audio: "steal.wav" },
                { word: "sue", meaning: "起诉", audio: "sue.wav" },
                { word: "suspect", meaning: "怀疑", audio: "suspect.wav" },
                { word: "testify", meaning: "作证", audio: "testify.wav" },
                { word: "testimony", meaning: "证词", audio: "testimony.wav" },
                { word: "theft", meaning: "盗窃", audio: "theft.wav" },
                { word: "trial", meaning: "审判", audio: "trial.wav" },
                { word: "tribunal", meaning: "法庭", audio: "tribunal.wav" },
                { word: "verdict", meaning: "裁决", audio: "verdict.wav" },
                { word: "victim", meaning: "受害者", audio: "victim.wav" },
                { word: "violate", meaning: "违反", audio: "violate.wav" },
                { word: "warrant", meaning: "逮捕令", audio: "warrant.wav" },
                { word: "witness", meaning: "证人", audio: "witness.wav" }
            ]
        }
    }
});
