registerWordbook('scene_health', {
    name: "健康身体",
    emoji: "🏥",
    group: 'scene',
    description: "身体、疾病、医疗、健身相关词汇",
    levels: {
        all: {
            name: "🏥 全部",
            words: [
                { word: "ache", meaning: "疼痛", audio: "ache.wav" },
                { word: "allergy", meaning: "过敏", audio: "allergy.wav" },
                { word: "ambulance", meaning: "救护车", audio: "ambulance.wav" },
                { word: "ankle", meaning: "踝关节; 脚踝", audio: "ankle.wav" },
                { word: "appointment", meaning: "预约", audio: "appointment.wav" },
                { word: "arm", meaning: "手臂", audio: "arm.wav" },
                { word: "back", meaning: "背部", audio: "back.wav" },
                { word: "bandage", meaning: "绷带", audio: "bandage.wav" },
                { word: "blood", meaning: "血", audio: "blood.wav" },
                { word: "body", meaning: "身体", audio: "body.wav" },
                { word: "bone", meaning: "骨", audio: "bone.wav" },
                { word: "brain", meaning: "脑", audio: "brain.wav" },
                { word: "breath", meaning: "气息", audio: "breath.wav" },
                { word: "breathe", meaning: "呼吸", audio: "breathe.wav" },
                { word: "burn", meaning: "烧伤", audio: "burn.wav" },
                { word: "cancer", meaning: "癌症", audio: "cancer.wav" },
                { word: "chest", meaning: "胸部", audio: "chest.wav" },
                { word: "chin", meaning: "下巴", audio: "chin.wav" },
                { word: "clinic", meaning: "诊所", audio: "clinic.wav" },
                { word: "cold", meaning: "感冒", audio: "cold.wav" },
                { word: "cough", meaning: "咳嗽", audio: "cough.wav" },
                { word: "cure", meaning: "治愈", audio: "cure.wav" },
                { word: "deaf", meaning: "聋的", audio: "deaf.wav" },
                { word: "dentist", meaning: "牙医", audio: "dentist.wav" },
                { word: "depression", meaning: "抑郁症", audio: "depression.wav" },
                { word: "diabetes", meaning: "糖尿病", audio: "diabetes.wav" },
                { word: "diagnosis", meaning: "诊断", audio: "diagnosis.wav" },
                { word: "diet", meaning: "饮食", audio: "diet.wav" },
                { word: "disability", meaning: "残疾", audio: "disability.wav" },
                { word: "disease", meaning: "疾病", audio: "disease.wav" },
                { word: "dizzy", meaning: "头晕的", audio: "dizzy.wav" },
                { word: "doctor", meaning: "医生", audio: "doctor.wav" },
                { word: "dose", meaning: "剂量", audio: "dose.wav" },
                { word: "drug", meaning: "药品", audio: "drug.wav" },
                { word: "ear", meaning: "耳朵", audio: "ear.wav" },
                { word: "elbow", meaning: "肘部", audio: "elbow.wav" },
                { word: "emergency", meaning: "紧急情况", audio: "emergency.wav" },
                { word: "examine", meaning: "检查", audio: "examine.wav" },
                { word: "exercise", meaning: "锻炼", audio: "exercise.wav" },
                { word: "eye", meaning: "眼睛", audio: "eye.wav" },
                { word: "face", meaning: "脸", audio: "face.wav" },
                { word: "fat", meaning: "脂肪", audio: "fat.wav" },
                { word: "fever", meaning: "发烧", audio: "fever.wav" },
                { word: "finger", meaning: "手指", audio: "finger.wav" },
                { word: "fitness", meaning: "健身", audio: "fitness.wav" },
                { word: "flu", meaning: "流感", audio: "flu.wav" },
                { word: "foot", meaning: "脚", audio: "foot.wav" },
                { word: "forehead", meaning: "额头", audio: "forehead.wav" },
                { word: "gym", meaning: "健身房", audio: "gym.wav" },
                { word: "hair", meaning: "头发", audio: "hair.wav" },
                { word: "hand", meaning: "手", audio: "hand.wav" },
                { word: "head", meaning: "头", audio: "head.wav" },
                { word: "headache", meaning: "头痛", audio: "headache.wav" },
                { word: "heal", meaning: "愈合", audio: "heal.wav" },
                { word: "health", meaning: "健康", audio: "health.wav" },
                { word: "healthy", meaning: "健康的", audio: "healthy.wav" },
                { word: "hear", meaning: "听到", audio: "hear.wav" },
                { word: "heart", meaning: "心脏", audio: "heart.wav" },
                { word: "heel", meaning: "脚跟", audio: "heel.wav" },
                { word: "hip", meaning: "臀部", audio: "hip.wav" },
                { word: "hospital", meaning: "医院", audio: "hospital.wav" },
                { word: "hurt", meaning: "受伤; 疼痛", audio: "hurt.wav" },
                { word: "ill", meaning: "患病的", audio: "ill.wav" },
                { word: "illness", meaning: "疾病", audio: "illness.wav" },
                { word: "immune", meaning: "免疫", audio: "immune.wav" },
                { word: "infection", meaning: "感染", audio: "infection.wav" },
                { word: "injection", meaning: "注射", audio: "injection.wav" },
                { word: "injury", meaning: "受伤", audio: "injury.wav" },
                { word: "jaw", meaning: "颌; 下颌骨", audio: "jaw.wav" },
                { word: "joint", meaning: "关节", audio: "joint.wav" },
                { word: "kidney", meaning: "肾", audio: "kidney.wav" },
                { word: "knee", meaning: "膝盖", audio: "knee.wav" },
                { word: "leg", meaning: "腿", audio: "leg.wav" },
                { word: "lip", meaning: "唇", audio: "lip.wav" },
                { word: "liver", meaning: "肝", audio: "liver.wav" },
                { word: "lung", meaning: "肺", audio: "lung.wav" },
                { word: "medicine", meaning: "药品", audio: "medicine.wav" },
                { word: "mental", meaning: "精神的", audio: "mental.wav" },
                { word: "mouth", meaning: "嘴", audio: "mouth.wav" },
                { word: "muscle", meaning: "肌肉", audio: "muscle.wav" },
                { word: "nail", meaning: "指甲", audio: "nail.wav" },
                { word: "neck", meaning: "脖子", audio: "neck.wav" },
                { word: "nerve", meaning: "神经", audio: "nerve.wav" },
                { word: "nose", meaning: "鼻子", audio: "nose.wav" },
                { word: "nurse", meaning: "护士", audio: "nurse.wav" },
                { word: "operate", meaning: "动手术", audio: "operate.wav" },
                { word: "operation", meaning: "手术", audio: "operation.wav" },
                { word: "organ", meaning: "器官", audio: "organ.wav" },
                { word: "pain", meaning: "疼痛", audio: "pain.wav" },
                { word: "painful", meaning: "疼痛的", audio: "painful.wav" },
                { word: "patient", meaning: "病人", audio: "patient.wav" },
                { word: "pharmacy", meaning: "药房", audio: "pharmacy.wav" },
                { word: "physical", meaning: "身体的", audio: "physical.wav" },
                { word: "pill", meaning: "药丸; 药片", audio: "pill.wav" },
                { word: "poison", meaning: "毒药; 毒物", audio: "poison.wav" },
                { word: "pregnant", meaning: "怀孕的", audio: "pregnant.wav" },
                { word: "prescription", meaning: "处方", audio: "prescription.wav" },
                { word: "pulse", meaning: "脉搏", audio: "pulse.wav" },
                { word: "recover", meaning: "恢复", audio: "recover.wav" },
                { word: "recovery", meaning: "恢复", audio: "recovery.wav" },
                { word: "relax", meaning: "放松", audio: "relax.wav" },
                { word: "rib", meaning: "肋骨", audio: "rib.wav" },
                { word: "shoulder", meaning: "肩膀", audio: "shoulder.wav" },
                { word: "sick", meaning: "生病的", audio: "sick.wav" },
                { word: "skin", meaning: "皮肤", audio: "skin.wav" },
                { word: "sleep", meaning: "睡觉", audio: "sleep.wav" },
                { word: "spine", meaning: "脊柱", audio: "spine.wav" },
                { word: "stomach", meaning: "胃", audio: "stomach.wav" },
                { word: "stress", meaning: "压力", audio: "stress.wav" },
                { word: "stroke", meaning: "中风", audio: "stroke.wav" },
                { word: "surgeon", meaning: "外科医生", audio: "surgeon.wav" },
                { word: "surgery", meaning: "外科手术", audio: "surgery.wav" },
                { word: "swallow", meaning: "吞", audio: "swallow.wav" },
                { word: "symptom", meaning: "症状", audio: "symptom.wav" },
                { word: "teeth", meaning: "牙齿", audio: "teeth.wav" },
                { word: "therapy", meaning: "治疗", audio: "therapy.wav" },
                { word: "throat", meaning: "咽喉; 喉咙", audio: "throat.wav" },
                { word: "thumb", meaning: "拇指", audio: "thumb.wav" },
                { word: "toe", meaning: "脚趾", audio: "toe.wav" },
                { word: "tongue", meaning: "舌头", audio: "tongue.wav" },
                { word: "tooth", meaning: "牙齿", audio: "tooth.wav" },
                { word: "treatment", meaning: "治疗", audio: "treatment.wav" },
                { word: "vaccine", meaning: "疫苗", audio: "vaccine.wav" },
                { word: "virus", meaning: "病毒", audio: "virus.wav" },
                { word: "vitamin", meaning: "维生素", audio: "vitamin.wav" },
                { word: "waist", meaning: "腰", audio: "waist.wav" },
                { word: "ward", meaning: "病房", audio: "ward.wav" },
                { word: "weight", meaning: "体重", audio: "weight.wav" },
                { word: "wheelchair", meaning: "轮椅", audio: "wheelchair.wav" },
                { word: "wound", meaning: "伤口", audio: "wound.wav" },
                { word: "wrist", meaning: "手腕", audio: "wrist.wav" }
            ]
        }
    }
});
