registerWordbook('scene_entertainment', {
    name: "娱乐爱好",
    emoji: "🎭",
    group: 'scene',
    description: "音乐、体育、艺术、游戏相关词汇",
    levels: {
        all: {
            name: "🎭 全部",
            words: [
                { word: "act", meaning: "行为", audio: "act.wav" },
                { word: "action", meaning: "行动", audio: "action.wav" },
                { word: "actor", meaning: "演员", audio: "actor.wav" },
                { word: "actress", meaning: "演员", audio: "actress.wav" },
                { word: "adventure", meaning: "冒险", audio: "adventure.wav" },
                { word: "album", meaning: "专辑", audio: "album.wav" },
                { word: "art", meaning: "艺术", audio: "art.wav" },
                { word: "artist", meaning: "艺术家", audio: "artist.wav" },
                { word: "athletics", meaning: "田径", audio: null },
                { word: "audience", meaning: "观众", audio: "audience.wav" },
                { word: "ballet", meaning: "芭蕾舞", audio: "ballet.wav" },
                { word: "band", meaning: "乐队", audio: "band.wav" },
                { word: "baseball", meaning: "棒球", audio: "baseball.wav" },
                { word: "basketball", meaning: "篮球", audio: "basketball.wav" },
                { word: "beat", meaning: "打", audio: "beat.wav" },
                { word: "camera", meaning: "相机", audio: "camera.wav" },
                { word: "camp", meaning: "营", audio: "camp.wav" },
                { word: "captain", meaning: "队长", audio: "captain.wav" },
                { word: "celebrate", meaning: "庆祝", audio: "celebrate.wav" },
                { word: "champion", meaning: "冠军", audio: "champion.wav" },
                { word: "channel", meaning: "渠道", audio: "channel.wav" },
                { word: "chess", meaning: "国际象棋", audio: null },
                { word: "cinema", meaning: "电影", audio: "cinema.wav" },
                { word: "climb", meaning: "爬", audio: "climb.wav" },
                { word: "club", meaning: "俱乐部", audio: "club.wav" },
                { word: "coach", meaning: "教练", audio: "coach.wav" },
                { word: "comedy", meaning: "喜剧", audio: "comedy.wav" },
                { word: "compete", meaning: "竞争", audio: "compete.wav" },
                { word: "competition", meaning: "竞赛", audio: "competition.wav" },
                { word: "concert", meaning: "音乐会", audio: "concert.wav" },
                { word: "contest", meaning: "竞赛", audio: "contest.wav" },
                { word: "creative", meaning: "有创造力的", audio: "creative.wav" },
                { word: "dance", meaning: "舞蹈", audio: "dance.wav" },
                { word: "director", meaning: "导演", audio: "director.wav" },
                { word: "drama", meaning: "戏剧", audio: "drama.wav" },
                { word: "draw", meaning: "画", audio: "draw.wav" },
                { word: "drawing", meaning: "绘画", audio: "drawing.wav" },
                { word: "entertainment", meaning: "娱乐", audio: "entertainment.wav" },
                { word: "episode", meaning: "插曲", audio: "episode.wav" },
                { word: "exhibition", meaning: "展览", audio: "exhibition.wav" },
                { word: "fan", meaning: "扇子", audio: "fan.wav" },
                { word: "fiction", meaning: "小说", audio: "fiction.wav" },
                { word: "film", meaning: "电影", audio: "film.wav" },
                { word: "football", meaning: "足球", audio: "football.wav" },
                { word: "fun", meaning: "乐趣", audio: "fun.wav" },
                { word: "gallery", meaning: "画廊", audio: "gallery.wav" },
                { word: "game", meaning: "游戏", audio: "game.wav" },
                { word: "goal", meaning: "目标", audio: "goal.wav" },
                { word: "golf", meaning: "高尔夫球", audio: "golf.wav" },
                { word: "guitar", meaning: "吉他", audio: "guitar.wav" },
                { word: "hero", meaning: "英雄", audio: "hero.wav" },
                { word: "hobby", meaning: "爱好", audio: "hobby.wav" },
                { word: "holiday", meaning: "假期", audio: "holiday.wav" },
                { word: "instrument", meaning: "乐器", audio: "instrument.wav" },
                { word: "jazz", meaning: "爵士乐", audio: "jazz.wav" },
                { word: "joke", meaning: "开玩笑", audio: "joke.wav" },
                { word: "kick", meaning: "踢", audio: "kick.wav" },
                { word: "league", meaning: "联盟", audio: "league.wav" },
                { word: "leisure", meaning: "闲暇", audio: "leisure.wav" },
                { word: "match", meaning: "匹配", audio: "match.wav" },
                { word: "medal", meaning: "勋章", audio: "medal.wav" },
                { word: "media", meaning: "媒体", audio: "media.wav" },
                { word: "movie", meaning: "电影", audio: "movie.wav" },
                { word: "museum", meaning: "博物馆", audio: "museum.wav" },
                { word: "music", meaning: "音乐", audio: "music.wav" },
                { word: "musical", meaning: "音乐", audio: "musical.wav" },
                { word: "novel", meaning: "小说", audio: "novel.wav" },
                { word: "opera", meaning: "歌剧", audio: "opera.wav" },
                { word: "orchestra", meaning: "乐队", audio: "orchestra.wav" },
                { word: "outdoor", meaning: "户外的", audio: "outdoor.wav" },
                { word: "paint", meaning: "画", audio: "paint.wav" },
                { word: "painting", meaning: "绘画", audio: "painting.wav" },
                { word: "party", meaning: "派对", audio: "party.wav" },
                { word: "perform", meaning: "履行", audio: "perform.wav" },
                { word: "performance", meaning: "表现", audio: "performance.wav" },
                { word: "photo", meaning: "照片", audio: "photo.wav" },
                { word: "photograph", meaning: "照片", audio: "photograph.wav" },
                { word: "photography", meaning: "摄影", audio: "photography.wav" },
                { word: "piano", meaning: "钢琴", audio: "piano.wav" },
                { word: "play", meaning: "玩", audio: "play.wav" },
                { word: "player", meaning: "玩家", audio: "player.wav" },
                { word: "plot", meaning: "阴谋", audio: "plot.wav" },
                { word: "poem", meaning: "诗", audio: "poem.wav" },
                { word: "poet", meaning: "诗人", audio: "poet.wav" },
                { word: "poetry", meaning: "诗", audio: "poetry.wav" },
                { word: "pool", meaning: "水池", audio: "pool.wav" },
                { word: "race", meaning: "种族", audio: "race.wav" },
                { word: "recreation", meaning: "娱乐", audio: null },
                { word: "record", meaning: "记录", audio: "record.wav" },
                { word: "rehearsal", meaning: "排练", audio: null },
                { word: "relax", meaning: "放松", audio: "relax.wav" },
                { word: "rhythm", meaning: "韵律", audio: "rhythm.wav" },
                { word: "rock", meaning: "岩石", audio: "rock.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "run", meaning: "跑步", audio: "run.wav" },
                { word: "scene", meaning: "场景", audio: "scene.wav" },
                { word: "score", meaning: "分数", audio: "score.wav" },
                { word: "screen", meaning: "屏幕", audio: "screen.wav" },
                { word: "sculpture", meaning: "雕塑", audio: "sculpture.wav" },
                { word: "series", meaning: "系列", audio: "series.wav" },
                { word: "show", meaning: "展示", audio: "show.wav" },
                { word: "sing", meaning: "唱歌", audio: "sing.wav" },
                { word: "singer", meaning: "歌手", audio: "singer.wav" },
                { word: "ski", meaning: "滑雪", audio: "ski.wav" },
                { word: "soccer", meaning: "足球", audio: "soccer.wav" },
                { word: "song", meaning: "歌曲", audio: "song.wav" },
                { word: "sport", meaning: "运动", audio: "sport.wav" },
                { word: "stadium", meaning: "体育场", audio: "stadium.wav" },
                { word: "stage", meaning: "阶段", audio: "stage.wav" },
                { word: "star", meaning: "星星", audio: "star.wav" },
                { word: "studio", meaning: "工作室", audio: "studio.wav" },
                { word: "surf", meaning: "冲浪", audio: null },
                { word: "swim", meaning: "游泳", audio: "swim.wav" },
                { word: "team", meaning: "团队", audio: "team.wav" },
                { word: "tennis", meaning: "网球", audio: "tennis.wav" },
                { word: "theatre", meaning: "剧院", audio: "theatre.wav" },
                { word: "tour", meaning: "旅游", audio: "tour.wav" },
                { word: "tournament", meaning: "比赛", audio: "tournament.wav" },
                { word: "video", meaning: "视频", audio: "video.wav" },
                { word: "volleyball", meaning: "排球", audio: null },
                { word: "yoga", meaning: "瑜伽", audio: null }
            ]
        }
    }
});
