registerWordbook('scene_transport', {
    name: "交通出行",
    emoji: "🚗",
    group: 'scene',
    description: "交通工具、道路、出行相关词汇",
    levels: {
        all: {
            name: "🚗 全部",
            words: [
                { word: "accelerate", meaning: "加速", audio: "accelerate.wav" },
                { word: "accident", meaning: "事故", audio: "accident.wav" },
                { word: "airline", meaning: "航空公司", audio: "airline.wav" },
                { word: "airport", meaning: "飞机场", audio: "airport.wav" },
                { word: "bicycle", meaning: "自行车", audio: "bicycle.wav" },
                { word: "bike", meaning: "自行车", audio: "bike.wav" },
                { word: "board", meaning: "木板", audio: "board.wav" },
                { word: "brake", meaning: "刹车", audio: "brake.wav" },
                { word: "bridge", meaning: "桥", audio: "bridge.wav" },
                { word: "bus", meaning: "公共汽车", audio: "bus.wav" },
                { word: "cab", meaning: "出租车", audio: "cab.wav" },
                { word: "car", meaning: "车", audio: "car.wav" },
                { word: "cargo", meaning: "货物", audio: "cargo.wav" },
                { word: "carriage", meaning: "运输", audio: "carriage.wav" },
                { word: "coach", meaning: "教练", audio: "coach.wav" },
                { word: "commute", meaning: "通勤", audio: "commute.wav" },
                { word: "crash", meaning: "碰撞", audio: "crash.wav" },
                { word: "cross", meaning: "叉", audio: "cross.wav" },
                { word: "crossing", meaning: "人行横道", audio: "crossing.wav" },
                { word: "cruise", meaning: "巡航", audio: "cruise.wav" },
                { word: "cycle", meaning: "循环", audio: "cycle.wav" },
                { word: "delay", meaning: "延迟", audio: "delay.wav" },
                { word: "deliver", meaning: "递送", audio: "deliver.wav" },
                { word: "departure", meaning: "离开", audio: "departure.wav" },
                { word: "destination", meaning: "目的地", audio: "destination.wav" },
                { word: "diesel", meaning: "柴油", audio: "diesel.wav" },
                { word: "direction", meaning: "方向", audio: "direction.wav" },
                { word: "distance", meaning: "距离", audio: "distance.wav" },
                { word: "drive", meaning: "驾驶", audio: "drive.wav" },
                { word: "driver", meaning: "司机", audio: "driver.wav" },
                { word: "engine", meaning: "引擎", audio: "engine.wav" },
                { word: "exit", meaning: "出口", audio: "exit.wav" },
                { word: "fare", meaning: "票价", audio: "fare.wav" },
                { word: "ferry", meaning: "渡轮", audio: "ferry.wav" },
                { word: "flight", meaning: "航班", audio: "flight.wav" },
                { word: "fuel", meaning: "燃料", audio: "fuel.wav" },
                { word: "garage", meaning: "车库", audio: "garage.wav" },
                { word: "gear", meaning: "齿轮", audio: "gear.wav" },
                { word: "harbour", meaning: "港口", audio: "harbour.wav" },
                { word: "helicopter", meaning: "直升机", audio: "helicopter.wav" },
                { word: "highway", meaning: "公路", audio: "highway.wav" },
                { word: "jam", meaning: "果酱", audio: "jam.wav" },
                { word: "journey", meaning: "旅行", audio: "journey.wav" },
                { word: "junction", meaning: "交界处", audio: "junction.wav" },
                { word: "lane", meaning: "车道", audio: "lane.wav" },
                { word: "lorry", meaning: "货车", audio: "lorry.wav" },
                { word: "map", meaning: "地图", audio: "map.wav" },
                { word: "motorway", meaning: "高速公路", audio: "motorway.wav" },
                { word: "park", meaning: "公园", audio: "park.wav" },
                { word: "parking", meaning: "停車處", audio: "parking.wav" },
                { word: "passenger", meaning: "乘客", audio: "passenger.wav" },
                { word: "path", meaning: "小路", audio: "path.wav" },
                { word: "petrol", meaning: "汽油", audio: "petrol.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "port", meaning: "港口", audio: "port.wav" },
                { word: "rail", meaning: "轨", audio: "rail.wav" },
                { word: "railway", meaning: "铁路", audio: "railway.wav" },
                { word: "ride", meaning: "骑", audio: "ride.wav" },
                { word: "road", meaning: "路", audio: "road.wav" },
                { word: "route", meaning: "路线", audio: "route.wav" },
                { word: "runway", meaning: "跑道", audio: "runway.wav" },
                { word: "sail", meaning: "帆", audio: "sail.wav" },
                { word: "seat", meaning: "座位", audio: "seat.wav" },
                { word: "ship", meaning: "船", audio: "ship.wav" },
                { word: "signal", meaning: "信号", audio: "signal.wav" },
                { word: "speed", meaning: "速度", audio: "speed.wav" },
                { word: "station", meaning: "车站", audio: "station.wav" },
                { word: "steer", meaning: "引导", audio: "steer.wav" },
                { word: "stop", meaning: "停止", audio: "stop.wav" },
                { word: "street", meaning: "街道", audio: "street.wav" },
                { word: "subway", meaning: "地铁", audio: "subway.wav" },
                { word: "taxi", meaning: "出租车", audio: "taxi.wav" },
                { word: "terminal", meaning: "终端", audio: "terminal.wav" },
                { word: "ticket", meaning: "票", audio: "ticket.wav" },
                { word: "tire", meaning: "轮胎", audio: "tire.wav" },
                { word: "traffic", meaning: "交通", audio: "traffic.wav" },
                { word: "train", meaning: "火车", audio: "train.wav" },
                { word: "transport", meaning: "运输", audio: "transport.wav" },
                { word: "trip", meaning: "旅行", audio: "trip.wav" },
                { word: "truck", meaning: "卡车", audio: "truck.wav" },
                { word: "tunnel", meaning: "隧道", audio: "tunnel.wav" },
                { word: "turn", meaning: "转动", audio: "turn.wav" },
                { word: "van", meaning: "货车", audio: "van.wav" },
                { word: "vehicle", meaning: "车辆", audio: "vehicle.wav" },
                { word: "wheel", meaning: "车轮", audio: "wheel.wav" }
            ]
        }
    }
});
