registerWordbook('scene_work', {
    name: "工作职场",
    emoji: "💼",
    group: 'scene',
    description: "职业、办公、商务相关词汇",
    levels: {
        all: {
            name: "💼 全部",
            words: [
                { word: "accountant", meaning: "会计", audio: "accountant.wav" },
                { word: "agency", meaning: "机构", audio: "agency.wav" },
                { word: "agenda", meaning: "议程", audio: "agenda.wav" },
                { word: "ambition", meaning: "志向", audio: "ambition.wav" },
                { word: "applicant", meaning: "申请人", audio: "applicant.wav" },
                { word: "application", meaning: "申请; 求职申请", audio: "application.wav" },
                { word: "apply", meaning: "申请", audio: "apply.wav" },
                { word: "appoint", meaning: "委", audio: "appoint.wav" },
                { word: "appointment", meaning: "预约", audio: "appointment.wav" },
                { word: "assistant", meaning: "助手", audio: "assistant.wav" },
                { word: "authority", meaning: "权威", audio: "authority.wav" },
                { word: "boss", meaning: "老板", audio: "boss.wav" },
                { word: "brand", meaning: "品牌", audio: "brand.wav" },
                { word: "business", meaning: "商业", audio: "business.wav" },
                { word: "candidate", meaning: "候选人", audio: "candidate.wav" },
                { word: "career", meaning: "职业", audio: "career.wav" },
                { word: "chairman", meaning: "主席", audio: "chairman.wav" },
                { word: "client", meaning: "客户", audio: "client.wav" },
                { word: "colleague", meaning: "同事", audio: "colleague.wav" },
                { word: "commission", meaning: "佣金", audio: "commission.wav" },
                { word: "committee", meaning: "委员会", audio: "committee.wav" },
                { word: "company", meaning: "公司", audio: "company.wav" },
                { word: "conference", meaning: "会议", audio: "conference.wav" },
                { word: "consultant", meaning: "顾问", audio: "consultant.wav" },
                { word: "contract", meaning: "合同", audio: "contract.wav" },
                { word: "cooperate", meaning: "合作", audio: "cooperate.wav" },
                { word: "corporate", meaning: "公司的", audio: "corporate.wav" },
                { word: "corporation", meaning: "公司", audio: "corporation.wav" },
                { word: "deal", meaning: "交易", audio: "deal.wav" },
                { word: "deadline", meaning: "最后期限", audio: "deadline.wav" },
                { word: "demand", meaning: "要求", audio: "demand.wav" },
                { word: "department", meaning: "部门", audio: "department.wav" },
                { word: "deputy", meaning: "副", audio: "deputy.wav" },
                { word: "director", meaning: "总监; 董事", audio: "director.wav" },
                { word: "dismiss", meaning: "解雇", audio: "dismiss.wav" },
                { word: "document", meaning: "文档", audio: "document.wav" },
                { word: "duty", meaning: "责任", audio: "duty.wav" },
                { word: "earn", meaning: "赚", audio: "earn.wav" },
                { word: "economy", meaning: "经济", audio: "economy.wav" },
                { word: "efficiency", meaning: "效率", audio: "efficiency.wav" },
                { word: "employ", meaning: "雇佣", audio: "employ.wav" },
                { word: "employee", meaning: "员工", audio: "employee.wav" },
                { word: "employer", meaning: "雇主", audio: "employer.wav" },
                { word: "employment", meaning: "就业", audio: "employment.wav" },
                { word: "enterprise", meaning: "企业", audio: "enterprise.wav" },
                { word: "entrepreneur", meaning: "企业家", audio: "entrepreneur.wav" },
                { word: "executive", meaning: "管理人员", audio: "executive.wav" },
                { word: "experience", meaning: "经验", audio: "experience.wav" },
                { word: "export", meaning: "出口", audio: "export.wav" },
                { word: "factory", meaning: "工厂", audio: "factory.wav" },
                { word: "firm", meaning: "公司", audio: "firm.wav" },
                { word: "hire", meaning: "聘请", audio: "hire.wav" },
                { word: "human", meaning: "人类", audio: "human.wav" },
                { word: "import", meaning: "进口", audio: "import.wav" },
                { word: "income", meaning: "收入", audio: "income.wav" },
                { word: "industry", meaning: "行业", audio: "industry.wav" },
                { word: "intern", meaning: "实习生", audio: "intern.wav" },
                { word: "interview", meaning: "面试", audio: "interview.wav" },
                { word: "invest", meaning: "投资", audio: "invest.wav" },
                { word: "investment", meaning: "投资", audio: "investment.wav" },
                { word: "job", meaning: "工作", audio: "job.wav" },
                { word: "labour", meaning: "劳动", audio: "labour.wav" },
                { word: "lead", meaning: "领导; 带领", audio: "lead.wav" },
                { word: "leadership", meaning: "领导", audio: "leadership.wav" },
                { word: "manage", meaning: "管理", audio: "manage.wav" },
                { word: "management", meaning: "管理", audio: "management.wav" },
                { word: "manager", meaning: "经理", audio: "manager.wav" },
                { word: "manufacture", meaning: "生产", audio: "manufacture.wav" },
                { word: "marketing", meaning: "营销", audio: "marketing.wav" },
                { word: "meeting", meaning: "会议", audio: "meeting.wav" },
                { word: "negotiate", meaning: "谈判", audio: "negotiate.wav" },
                { word: "network", meaning: "网络", audio: "network.wav" },
                { word: "occupation", meaning: "职业", audio: "occupation.wav" },
                { word: "office", meaning: "办公室", audio: "office.wav" },
                { word: "operate", meaning: "操作", audio: "operate.wav" },
                { word: "organization", meaning: "组织", audio: "organization.wav" },
                { word: "overtime", meaning: "加班", audio: "overtime.wav" },
                { word: "partner", meaning: "伙伴", audio: "partner.wav" },
                { word: "partnership", meaning: "合伙", audio: "partnership.wav" },
                { word: "pension", meaning: "养老金", audio: "pension.wav" },
                { word: "position", meaning: "职位", audio: "position.wav" },
                { word: "profession", meaning: "职业", audio: "profession.wav" },
                { word: "professional", meaning: "专业的", audio: "professional.wav" },
                { word: "profit", meaning: "利润", audio: "profit.wav" },
                { word: "project", meaning: "项目", audio: "project.wav" },
                { word: "promote", meaning: "晋升; 提拔", audio: "promote.wav" },
                { word: "promotion", meaning: "晋升", audio: "promotion.wav" },
                { word: "proposal", meaning: "提议", audio: "proposal.wav" },
                { word: "qualify", meaning: "有资格", audio: "qualify.wav" },
                { word: "recruit", meaning: "招募", audio: "recruit.wav" },
                { word: "reference", meaning: "参考", audio: "reference.wav" },
                { word: "resign", meaning: "辞职", audio: "resign.wav" },
                { word: "responsibility", meaning: "责任", audio: "responsibility.wav" },
                { word: "resume", meaning: "简历", audio: "resume.wav" },
                { word: "retire", meaning: "退休", audio: "retire.wav" },
                { word: "retirement", meaning: "退休", audio: "retirement.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "salary", meaning: "薪水", audio: "salary.wav" },
                { word: "schedule", meaning: "日程", audio: "schedule.wav" },
                { word: "sector", meaning: "部门", audio: "sector.wav" },
                { word: "shift", meaning: "轮班; 班次", audio: "shift.wav" },
                { word: "skill", meaning: "技能", audio: "skill.wav" },
                { word: "staff", meaning: "职员", audio: "staff.wav" },
                { word: "strategy", meaning: "战略", audio: "strategy.wav" },
                { word: "succeed", meaning: "成功", audio: "succeed.wav" },
                { word: "success", meaning: "成功", audio: "success.wav" },
                { word: "supervisor", meaning: "主管", audio: "supervisor.wav" },
                { word: "task", meaning: "任务", audio: "task.wav" },
                { word: "team", meaning: "团队", audio: "team.wav" },
                { word: "trade", meaning: "贸易", audio: "trade.wav" },
                { word: "training", meaning: "训练", audio: "training.wav" },
                { word: "union", meaning: "工会", audio: "union.wav" },
                { word: "volunteer", meaning: "志愿者", audio: "volunteer.wav" },
                { word: "wage", meaning: "工资", audio: "wage.wav" },
                { word: "work", meaning: "工作", audio: "work.wav" },
                { word: "worker", meaning: "工人", audio: "worker.wav" },
                { word: "workplace", meaning: "工作场所", audio: "workplace.wav" }
            ]
        }
    }
});
