registerWordbook('scene_plants', {
    name: "植物花卉",
    emoji: "🌿",
    group: 'scene',
    description: "花、树、果蔬植物名相关词汇",
    levels: {
        all: {
            name: "🌿 全部",
            words: [
                { word: "agriculture", meaning: "农业", audio: "agriculture.wav" },
                { word: "apple", meaning: "苹果", audio: "apple.wav" },
                { word: "bamboo", meaning: "竹子", audio: "bamboo.wav" },
                { word: "bark", meaning: "树皮", audio: "bark.wav" },
                { word: "bean", meaning: "豆", audio: "bean.wav" },
                { word: "berry", meaning: "浆果", audio: "berry.wav" },
                { word: "bloom", meaning: "开花", audio: "bloom.wav" },
                { word: "blossom", meaning: "花朵", audio: "blossom.wav" },
                { word: "botanical", meaning: "植物学的", audio: "botanical.wav" },
                { word: "bouquet", meaning: "花束", audio: "bouquet.wav" },
                { word: "branch", meaning: "树枝", audio: "branch.wav" },
                { word: "bud", meaning: "芽", audio: "bud.wav" },
                { word: "bulb", meaning: "球茎", audio: "bulb.wav" },
                { word: "bush", meaning: "灌木", audio: "bush.wav" },
                { word: "cabbage", meaning: "卷心菜", audio: "cabbage.wav" },
                { word: "cactus", meaning: "仙人掌", audio: "cactus.wav" },
                { word: "carrot", meaning: "胡萝卜", audio: "carrot.wav" },
                { word: "cedar", meaning: "雪松", audio: "cedar.wav" },
                { word: "cherry", meaning: "樱桃", audio: "cherry.wav" },
                { word: "chestnut", meaning: "栗子", audio: "chestnut.wav" },
                { word: "climate", meaning: "气候", audio: "climate.wav" },
                { word: "clover", meaning: "三叶草", audio: "clover.wav" },
                { word: "coconut", meaning: "椰子", audio: "coconut.wav" },
                { word: "compost", meaning: "堆肥", audio: "compost.wav" },
                { word: "corn", meaning: "玉米", audio: "corn.wav" },
                { word: "cotton", meaning: "棉花", audio: "cotton.wav" },
                { word: "crop", meaning: "庄稼", audio: "crop.wav" },
                { word: "cultivate", meaning: "培育", audio: "cultivate.wav" },
                { word: "daisy", meaning: "雏菊", audio: "daisy.wav" },
                { word: "decay", meaning: "腐烂", audio: "decay.wav" },
                { word: "dig", meaning: "挖", audio: "dig.wav" },
                { word: "drain", meaning: "排水", audio: "drain.wav" },
                { word: "drought", meaning: "干旱", audio: "drought.wav" },
                { word: "ecology", meaning: "生态学", audio: "ecology.wav" },
                { word: "elm", meaning: "榆树", audio: "elm.wav" },
                { word: "exotic", meaning: "异国情调", audio: "exotic.wav" },
                { word: "farm", meaning: "农场", audio: "farm.wav" },
                { word: "fern", meaning: "蕨类", audio: "fern.wav" },
                { word: "fertile", meaning: "肥沃的", audio: "fertile.wav" },
                { word: "fertilizer", meaning: "肥料", audio: "fertilizer.wav" },
                { word: "fig", meaning: "无花果", audio: "fig.wav" },
                { word: "flora", meaning: "植物群", audio: "flora.wav" },
                { word: "flour", meaning: "面粉", audio: "flour.wav" },
                { word: "flower", meaning: "花", audio: "flower.wav" },
                { word: "forest", meaning: "森林", audio: "forest.wav" },
                { word: "fruit", meaning: "水果", audio: "fruit.wav" },
                { word: "fungus", meaning: "真菌", audio: "fungus.wav" },
                { word: "garden", meaning: "花园", audio: "garden.wav" },
                { word: "garlic", meaning: "大蒜", audio: "garlic.wav" },
                { word: "grain", meaning: "粮食", audio: "grain.wav" },
                { word: "grape", meaning: "葡萄", audio: "grape.wav" },
                { word: "grass", meaning: "草", audio: "grass.wav" },
                { word: "greenhouse", meaning: "温室", audio: "greenhouse.wav" },
                { word: "grow", meaning: "生长", audio: "grow.wav" },
                { word: "harvest", meaning: "收成", audio: "harvest.wav" },
                { word: "hay", meaning: "干草", audio: "hay.wav" },
                { word: "herb", meaning: "草本植物", audio: "herb.wav" },
                { word: "ivy", meaning: "常春藤", audio: "ivy.wav" },
                { word: "jungle", meaning: "丛林", audio: "jungle.wav" },
                { word: "lavender", meaning: "薰衣草", audio: "lavender.wav" },
                { word: "lawn", meaning: "草地", audio: "lawn.wav" },
                { word: "leaf", meaning: "叶子", audio: "leaf.wav" },
                { word: "lemon", meaning: "柠檬", audio: "lemon.wav" },
                { word: "lettuce", meaning: "生菜", audio: "lettuce.wav" },
                { word: "lily", meaning: "百合花", audio: "lily.wav" },
                { word: "maple", meaning: "枫树", audio: "maple.wav" },
                { word: "meadow", meaning: "草地", audio: "meadow.wav" },
                { word: "melon", meaning: "瓜", audio: "melon.wav" },
                { word: "moss", meaning: "苔藓", audio: "moss.wav" },
                { word: "mushroom", meaning: "蘑菇", audio: "mushroom.wav" },
                { word: "nature", meaning: "自然", audio: "nature.wav" },
                { word: "nut", meaning: "坚果", audio: "nut.wav" },
                { word: "oak", meaning: "橡树", audio: "oak.wav" },
                { word: "olive", meaning: "橄榄", audio: "olive.wav" },
                { word: "onion", meaning: "洋葱", audio: "onion.wav" },
                { word: "orange", meaning: "橙子", audio: "orange.wav" },
                { word: "orchid", meaning: "兰花", audio: "orchid.wav" },
                { word: "organic", meaning: "有机的", audio: "organic.wav" },
                { word: "palm", meaning: "棕榈", audio: "palm.wav" },
                { word: "peach", meaning: "桃子", audio: "peach.wav" },
                { word: "pear", meaning: "梨", audio: "pear.wav" },
                { word: "pea", meaning: "豌豆", audio: "pea.wav" },
                { word: "petal", meaning: "花瓣", audio: "petal.wav" },
                { word: "pine", meaning: "松树", audio: "pine.wav" },
                { word: "plant", meaning: "植物", audio: "plant.wav" },
                { word: "plum", meaning: "李子", audio: "plum.wav" },
                { word: "pollen", meaning: "花粉", audio: "pollen.wav" },
                { word: "potato", meaning: "土豆", audio: "potato.wav" },
                { word: "prune", meaning: "修剪", audio: "prune.wav" },
                { word: "pumpkin", meaning: "南瓜", audio: "pumpkin.wav" },
                { word: "rainforest", meaning: "雨林", audio: "rainforest.wav" },
                { word: "rice", meaning: "米", audio: "rice.wav" },
                { word: "root", meaning: "根", audio: "root.wav" },
                { word: "rose", meaning: "玫瑰", audio: "rose.wav" },
                { word: "rye", meaning: "黑麦", audio: "rye.wav" },
                { word: "seed", meaning: "种子", audio: "seed.wav" },
                { word: "shrub", meaning: "灌木", audio: "shrub.wav" },
                { word: "soil", meaning: "土壤", audio: "soil.wav" },
                { word: "species", meaning: "物种", audio: "species.wav" },
                { word: "stem", meaning: "茎", audio: "stem.wav" },
                { word: "strawberry", meaning: "草莓", audio: "strawberry.wav" },
                { word: "sunflower", meaning: "向日葵", audio: "sunflower.wav" },
                { word: "thorn", meaning: "刺", audio: "thorn.wav" },
                { word: "timber", meaning: "木材", audio: "timber.wav" },
                { word: "tobacco", meaning: "烟草", audio: "tobacco.wav" },
                { word: "tomato", meaning: "番茄", audio: "tomato.wav" },
                { word: "tree", meaning: "树", audio: "tree.wav" },
                { word: "tropical", meaning: "热带", audio: "tropical.wav" },
                { word: "tulip", meaning: "郁金香", audio: "tulip.wav" },
                { word: "vegetation", meaning: "植被", audio: "vegetation.wav" },
                { word: "vine", meaning: "藤蔓", audio: "vine.wav" },
                { word: "violet", meaning: "紫罗兰", audio: "violet.wav" },
                { word: "water", meaning: "水", audio: "water.wav" },
                { word: "weed", meaning: "杂草", audio: "weed.wav" },
                { word: "wheat", meaning: "小麦", audio: "wheat.wav" },
                { word: "willow", meaning: "柳树", audio: "willow.wav" },
                { word: "wood", meaning: "木头", audio: "wood.wav" }
            ]
        }
    }
});
