registerWordbook('scene_food', {
    name: "食物饮料",
    emoji: "🍔",
    group: 'scene',
    description: "食物、饮料、烹饪相关词汇",
    levels: {
        all: {
            name: "🍔 全部",
            words: [
                { word: "apple", meaning: "苹果", audio: "apple.wav" },
                { word: "banana", meaning: "香蕉", audio: "banana.wav" },
                { word: "bean", meaning: "豆", audio: "bean.wav" },
                { word: "beef", meaning: "牛肉", audio: "beef.wav" },
                { word: "beer", meaning: "啤酒", audio: "beer.wav" },
                { word: "berry", meaning: "浆果", audio: null },
                { word: "biscuit", meaning: "饼干", audio: "biscuit.wav" },
                { word: "bite", meaning: "咬", audio: null },
                { word: "boil", meaning: "熬", audio: "boil.wav" },
                { word: "bottle", meaning: "瓶子", audio: "bottle.wav" },
                { word: "bowl", meaning: "碗", audio: "bowl.wav" },
                { word: "bread", meaning: "面包", audio: "bread.wav" },
                { word: "breakfast", meaning: "早餐", audio: "breakfast.wav" },
                { word: "butter", meaning: "黄油", audio: "butter.wav" },
                { word: "cafe", meaning: "咖啡店", audio: "cafe.wav" },
                { word: "cake", meaning: "蛋糕", audio: "cake.wav" },
                { word: "candy", meaning: "糖果", audio: null },
                { word: "carrot", meaning: "胡萝卜", audio: "carrot.wav" },
                { word: "cereal", meaning: "谷物", audio: null },
                { word: "cheese", meaning: "奶酪", audio: "cheese.wav" },
                { word: "chef", meaning: "厨师", audio: "chef.wav" },
                { word: "cherry", meaning: "樱桃", audio: null },
                { word: "chicken", meaning: "鸡", audio: "chicken.wav" },
                { word: "chip", meaning: "芯片", audio: "chip.wav" },
                { word: "chocolate", meaning: "巧克力", audio: "chocolate.wav" },
                { word: "chop", meaning: "劈", audio: "chop.wav" },
                { word: "coffee", meaning: "咖啡", audio: "coffee.wav" },
                { word: "cook", meaning: "厨师", audio: "cook.wav" },
                { word: "cookie", meaning: "饼干", audio: null },
                { word: "corn", meaning: "玉米", audio: null },
                { word: "cream", meaning: "奶油", audio: "cream.wav" },
                { word: "cup", meaning: "杯子", audio: "cup.wav" },
                { word: "dairy", meaning: "奶制品", audio: "dairy.wav" },
                { word: "delicious", meaning: "可口的", audio: "delicious.wav" },
                { word: "dessert", meaning: "甜点", audio: null },
                { word: "diet", meaning: "饮食", audio: "diet.wav" },
                { word: "dine", meaning: "用餐", audio: null },
                { word: "dinner", meaning: "晚餐", audio: "dinner.wav" },
                { word: "dish", meaning: "盘子", audio: "dish.wav" },
                { word: "drink", meaning: "喝", audio: "drink.wav" },
                { word: "eat", meaning: "吃", audio: "eat.wav" },
                { word: "egg", meaning: "蛋", audio: "egg.wav" },
                { word: "fat", meaning: "胖的", audio: "fat.wav" },
                { word: "feed", meaning: "喂养", audio: "feed.wav" },
                { word: "fish", meaning: "鱼", audio: "fish.wav" },
                { word: "flavour", meaning: "味道", audio: "flavour.wav" },
                { word: "flour", meaning: "面粉", audio: "flour.wav" },
                { word: "food", meaning: "食物", audio: "food.wav" },
                { word: "fork", meaning: "叉", audio: "fork.wav" },
                { word: "fresh", meaning: "新鲜的", audio: "fresh.wav" },
                { word: "fridge", meaning: "冰箱", audio: "fridge.wav" },
                { word: "fruit", meaning: "水果", audio: "fruit.wav" },
                { word: "fry", meaning: "炒", audio: "fry.wav" },
                { word: "garlic", meaning: "大蒜", audio: null },
                { word: "glass", meaning: "玻璃", audio: "glass.wav" },
                { word: "grain", meaning: "粮食", audio: "grain.wav" },
                { word: "grape", meaning: "葡萄", audio: null },
                { word: "grill", meaning: "烧烤", audio: null },
                { word: "grocery", meaning: "杂货店", audio: "grocery.wav" },
                { word: "honey", meaning: "蜂蜜", audio: null },
                { word: "hungry", meaning: "饥饿的", audio: "hungry.wav" },
                { word: "ingredient", meaning: "成分", audio: "ingredient.wav" },
                { word: "jam", meaning: "果酱", audio: "jam.wav" },
                { word: "juice", meaning: "汁", audio: "juice.wav" },
                { word: "kettle", meaning: "水壶", audio: null },
                { word: "kitchen", meaning: "厨房", audio: "kitchen.wav" },
                { word: "knife", meaning: "刀", audio: "knife.wav" },
                { word: "lamb", meaning: "羊肉", audio: null },
                { word: "lemon", meaning: "柠檬", audio: "lemon.wav" },
                { word: "lettuce", meaning: "生菜", audio: null },
                { word: "lunch", meaning: "午餐", audio: "lunch.wav" },
                { word: "meal", meaning: "一顿饭", audio: "meal.wav" },
                { word: "meat", meaning: "肉", audio: "meat.wav" },
                { word: "menu", meaning: "菜单", audio: "menu.wav" },
                { word: "microwave", meaning: "微波炉", audio: null },
                { word: "milk", meaning: "牛奶", audio: "milk.wav" },
                { word: "mix", meaning: "混合", audio: "mix.wav" },
                { word: "mushroom", meaning: "蘑菇", audio: null },
                { word: "nut", meaning: "坚果", audio: "nut.wav" },
                { word: "oil", meaning: "油", audio: "oil.wav" },
                { word: "olive", meaning: "橄榄", audio: null },
                { word: "onion", meaning: "洋葱", audio: "onion.wav" },
                { word: "orange", meaning: "橙子", audio: "orange.wav" },
                { word: "organic", meaning: "有机的", audio: "organic.wav" },
                { word: "oven", meaning: "烤箱", audio: "oven.wav" },
                { word: "pan", meaning: "平底锅", audio: "pan.wav" },
                { word: "pasta", meaning: "意大利面", audio: null },
                { word: "pea", meaning: "豌豆", audio: null },
                { word: "peach", meaning: "桃子", audio: null },
                { word: "pepper", meaning: "胡椒", audio: "pepper.wav" },
                { word: "pie", meaning: "馅饼", audio: null },
                { word: "pizza", meaning: "比萨", audio: null },
                { word: "plate", meaning: "盘子", audio: "plate.wav" },
                { word: "pork", meaning: "猪肉", audio: null },
                { word: "pot", meaning: "锅", audio: "pot.wav" },
                { word: "potato", meaning: "土豆", audio: "potato.wav" },
                { word: "pour", meaning: "倒", audio: "pour.wav" },
                { word: "protein", meaning: "蛋白质", audio: "protein.wav" },
                { word: "raw", meaning: "生的", audio: "raw.wav" },
                { word: "recipe", meaning: "食谱", audio: "recipe.wav" },
                { word: "restaurant", meaning: "餐厅", audio: "restaurant.wav" },
                { word: "rice", meaning: "米", audio: "rice.wav" },
                { word: "roast", meaning: "烤", audio: null },
                { word: "salad", meaning: "沙拉", audio: "salad.wav" },
                { word: "salt", meaning: "盐", audio: "salt.wav" },
                { word: "sandwich", meaning: "三明治", audio: "sandwich.wav" },
                { word: "sauce", meaning: "酱", audio: "sauce.wav" },
                { word: "sausage", meaning: "香肠", audio: null },
                { word: "slice", meaning: "片", audio: "slice.wav" },
                { word: "snack", meaning: "零食", audio: null },
                { word: "soup", meaning: "汤", audio: "soup.wav" },
                { word: "spice", meaning: "香料", audio: "spice.wav" },
                { word: "spoon", meaning: "勺子", audio: "spoon.wav" },
                { word: "steak", meaning: "牛排", audio: null },
                { word: "stir", meaning: "搅拌", audio: null },
                { word: "stomach", meaning: "胃", audio: "stomach.wav" },
                { word: "strawberry", meaning: "草莓", audio: null },
                { word: "sugar", meaning: "糖", audio: "sugar.wav" },
                { word: "supper", meaning: "晚餐", audio: null },
                { word: "sweet", meaning: "甜的", audio: "sweet.wav" },
                { word: "taste", meaning: "品尝", audio: "taste.wav" },
                { word: "tea", meaning: "茶", audio: "tea.wav" },
                { word: "toast", meaning: "吐司", audio: null },
                { word: "tomato", meaning: "番茄", audio: null },
                { word: "vegetable", meaning: "蔬菜", audio: "vegetable.wav" },
                { word: "vinegar", meaning: "醋", audio: null },
                { word: "water", meaning: "水", audio: "water.wav" },
                { word: "wheat", meaning: "小麦", audio: "wheat.wav" },
                { word: "wine", meaning: "葡萄酒", audio: "wine.wav" }
            ]
        }
    }
});
