registerWordbook('scene_animals', {
    name: "宠物动物",
    emoji: "🐾",
    group: 'scene',
    description: "动物种类、宠物护理相关词汇",
    levels: {
        all: {
            name: "🐾 全部",
            words: [
                { word: "adopt", meaning: "采纳", audio: "adopt.wav" },
                { word: "alligator", meaning: "鳄鱼", audio: "alligator.wav" },
                { word: "ant", meaning: "蚂蚁", audio: "ant.wav" },
                { word: "ape", meaning: "猿猴", audio: "ape.wav" },
                { word: "aquarium", meaning: "水族馆", audio: "aquarium.wav" },
                { word: "bat", meaning: "球棒", audio: "bat.wav" },
                { word: "beak", meaning: "鸟嘴", audio: "beak.wav" },
                { word: "bear", meaning: "熊", audio: "bear.wav" },
                { word: "beast", meaning: "兽", audio: "beast.wav" },
                { word: "bee", meaning: "蜜蜂", audio: "bee.wav" },
                { word: "beetle", meaning: "甲虫", audio: "beetle.wav" },
                { word: "bird", meaning: "鸟", audio: "bird.wav" },
                { word: "bite", meaning: "咬", audio: "bite.wav" },
                { word: "breed", meaning: "品种", audio: "breed.wav" },
                { word: "buffalo", meaning: "水牛", audio: "buffalo.wav" },
                { word: "bug", meaning: "漏洞", audio: "bug.wav" },
                { word: "bull", meaning: "公牛", audio: "bull.wav" },
                { word: "butterfly", meaning: "蝴蝶", audio: "butterfly.wav" },
                { word: "cage", meaning: "笼子", audio: "cage.wav" },
                { word: "camel", meaning: "骆驼", audio: "camel.wav" },
                { word: "cat", meaning: "猫", audio: "cat.wav" },
                { word: "cattle", meaning: "牛", audio: "cattle.wav" },
                { word: "chick", meaning: "小鸡", audio: "chick.wav" },
                { word: "chicken", meaning: "鸡", audio: "chicken.wav" },
                { word: "claw", meaning: "爪子", audio: "claw.wav" },
                { word: "collar", meaning: "衣领", audio: "collar.wav" },
                { word: "cow", meaning: "奶牛", audio: "cow.wav" },
                { word: "creature", meaning: "生物", audio: "creature.wav" },
                { word: "crocodile", meaning: "鳄鱼", audio: "crocodile.wav" },
                { word: "crow", meaning: "乌鸦", audio: "crow.wav" },
                { word: "deer", meaning: "鹿", audio: "deer.wav" },
                { word: "dinosaur", meaning: "恐龙", audio: "dinosaur.wav" },
                { word: "dog", meaning: "狗", audio: "dog.wav" },
                { word: "dolphin", meaning: "海豚", audio: "dolphin.wav" },
                { word: "donkey", meaning: "驴", audio: "donkey.wav" },
                { word: "dove", meaning: "鸽子", audio: "dove.wav" },
                { word: "duck", meaning: "鸭子", audio: "duck.wav" },
                { word: "eagle", meaning: "鹰", audio: "eagle.wav" },
                { word: "elephant", meaning: "大象", audio: "elephant.wav" },
                { word: "endangered", meaning: "濒危的", audio: "endangered.wav" },
                { word: "evolve", meaning: "发展", audio: "evolve.wav" },
                { word: "exotic", meaning: "异国情调", audio: "exotic.wav" },
                { word: "extinction", meaning: "灭绝", audio: "extinction.wav" },
                { word: "falcon", meaning: "隼", audio: "falcon.wav" },
                { word: "farm", meaning: "农场", audio: "farm.wav" },
                { word: "feather", meaning: "羽毛", audio: "feather.wav" },
                { word: "feed", meaning: "喂养", audio: "feed.wav" },
                { word: "fin", meaning: "鱼鳍", audio: "fin.wav" },
                { word: "fish", meaning: "鱼", audio: "fish.wav" },
                { word: "flock", meaning: "群", audio: "flock.wav" },
                { word: "fly", meaning: "飞", audio: "fly.wav" },
                { word: "fox", meaning: "狐狸", audio: "fox.wav" },
                { word: "frog", meaning: "青蛙", audio: "frog.wav" },
                { word: "fur", meaning: "毛皮", audio: "fur.wav" },
                { word: "goat", meaning: "山羊", audio: "goat.wav" },
                { word: "goose", meaning: "鹅", audio: "goose.wav" },
                { word: "gorilla", meaning: "大猩猩", audio: "gorilla.wav" },
                { word: "habitat", meaning: "栖息地", audio: "habitat.wav" },
                { word: "hamster", meaning: "仓鼠", audio: "hamster.wav" },
                { word: "hare", meaning: "野兔", audio: "hare.wav" },
                { word: "hawk", meaning: "鹰", audio: "hawk.wav" },
                { word: "hen", meaning: "母鸡", audio: "hen.wav" },
                { word: "herd", meaning: "兽群", audio: "herd.wav" },
                { word: "horn", meaning: "喇叭", audio: "horn.wav" },
                { word: "horse", meaning: "马", audio: "horse.wav" },
                { word: "hound", meaning: "猎犬", audio: "hound.wav" },
                { word: "hunt", meaning: "打猎", audio: "hunt.wav" },
                { word: "insect", meaning: "昆虫", audio: "insect.wav" },
                { word: "ivory", meaning: "象牙", audio: "ivory.wav" },
                { word: "kangaroo", meaning: "袋鼠", audio: "kangaroo.wav" },
                { word: "kitten", meaning: "小猫", audio: "kitten.wav" },
                { word: "lamb", meaning: "羊肉", audio: "lamb.wav" },
                { word: "leash", meaning: "牵引绳", audio: "leash.wav" },
                { word: "leopard", meaning: "豹", audio: "leopard.wav" },
                { word: "lion", meaning: "狮子", audio: "lion.wav" },
                { word: "lizard", meaning: "蜥蜴", audio: "lizard.wav" },
                { word: "mammal", meaning: "哺乳动物", audio: "mammal.wav" },
                { word: "mare", meaning: "母马", audio: "mare.wav" },
                { word: "migrate", meaning: "迁徙", audio: "migrate.wav" },
                { word: "monkey", meaning: "猴", audio: "monkey.wav" },
                { word: "mosquito", meaning: "蚊子", audio: "mosquito.wav" },
                { word: "mouse", meaning: "老鼠", audio: "mouse.wav" },
                { word: "mule", meaning: "骡子", audio: "mule.wav" },
                { word: "nest", meaning: "巢", audio: "nest.wav" },
                { word: "ostrich", meaning: "鸵鸟", audio: "ostrich.wav" },
                { word: "otter", meaning: "水獭", audio: "otter.wav" },
                { word: "owl", meaning: "猫头鹰", audio: "owl.wav" },
                { word: "ox", meaning: "公牛", audio: "ox.wav" },
                { word: "panda", meaning: "熊猫", audio: "panda.wav" },
                { word: "parrot", meaning: "鹦鹉", audio: "parrot.wav" },
                { word: "paw", meaning: "爪子", audio: "paw.wav" },
                { word: "peacock", meaning: "孔雀", audio: "peacock.wav" },
                { word: "penguin", meaning: "企鹅", audio: "penguin.wav" },
                { word: "pet", meaning: "宠物", audio: "pet.wav" },
                { word: "pig", meaning: "猪", audio: "pig.wav" },
                { word: "pigeon", meaning: "鸽子", audio: "pigeon.wav" },
                { word: "polar", meaning: "极地的", audio: "polar.wav" },
                { word: "pony", meaning: "小马", audio: "pony.wav" },
                { word: "predator", meaning: "掠食者", audio: "predator.wav" },
                { word: "prey", meaning: "猎物", audio: "prey.wav" },
                { word: "puppy", meaning: "小狗", audio: "puppy.wav" },
                { word: "rabbit", meaning: "兔子", audio: "rabbit.wav" },
                { word: "rat", meaning: "鼠", audio: "rat.wav" },
                { word: "reptile", meaning: "爬行动物", audio: "reptile.wav" },
                { word: "rooster", meaning: "公鸡", audio: "rooster.wav" },
                { word: "salmon", meaning: "三文鱼", audio: "salmon.wav" },
                { word: "seal", meaning: "密封", audio: "seal.wav" },
                { word: "shark", meaning: "鲨鱼", audio: "shark.wav" },
                { word: "sheep", meaning: "羊", audio: "sheep.wav" },
                { word: "shell", meaning: "壳", audio: "shell.wav" },
                { word: "shelter", meaning: "庇护所", audio: "shelter.wav" },
                { word: "snake", meaning: "蛇", audio: "snake.wav" },
                { word: "sparrow", meaning: "麻雀", audio: "sparrow.wav" },
                { word: "species", meaning: "物种", audio: "species.wav" },
                { word: "spider", meaning: "蜘蛛", audio: "spider.wav" },
                { word: "squirrel", meaning: "松鼠", audio: "squirrel.wav" },
                { word: "stray", meaning: "流浪的", audio: "stray.wav" },
                { word: "swan", meaning: "天鹅", audio: "swan.wav" },
                { word: "tail", meaning: "尾巴", audio: "tail.wav" },
                { word: "tame", meaning: "驯养", audio: "tame.wav" },
                { word: "tiger", meaning: "老虎", audio: "tiger.wav" },
                { word: "tortoise", meaning: "陆龟", audio: "tortoise.wav" },
                { word: "trunk", meaning: "象鼻", audio: "trunk.wav" },
                { word: "turkey", meaning: "火鸡", audio: "turkey.wav" },
                { word: "turtle", meaning: "海龟", audio: "turtle.wav" },
                { word: "tusk", meaning: "象牙", audio: "tusk.wav" },
                { word: "vet", meaning: "兽医", audio: "vet.wav" },
                { word: "veterinarian", meaning: "兽医", audio: "veterinarian.wav" },
                { word: "vulture", meaning: "秃鹰", audio: "vulture.wav" },
                { word: "walrus", meaning: "海象", audio: "walrus.wav" },
                { word: "whale", meaning: "鲸鱼", audio: "whale.wav" },
                { word: "wild", meaning: "荒野", audio: "wild.wav" },
                { word: "wildlife", meaning: "野生动物", audio: "wildlife.wav" },
                { word: "wing", meaning: "翼", audio: "wing.wav" },
                { word: "wolf", meaning: "狼", audio: "wolf.wav" },
                { word: "worm", meaning: "蠕虫", audio: "worm.wav" },
                { word: "zebra", meaning: "斑马", audio: "zebra.wav" },
                { word: "zoo", meaning: "动物园", audio: "zoo.wav" }
            ]
        }
    }
});
