registerWordbook('topic_architecture', {
    name: "建筑工程",
    emoji: "🏗️",
    group: 'topic',
    description: "建筑材料、结构、施工相关词汇",
    levels: {
        all: {
            name: "🏗️ 全部",
            words: [
                { word: "anchor", meaning: "锚", audio: "anchor.wav" },
                { word: "angle", meaning: "角度", audio: "angle.wav" },
                { word: "arch", meaning: "拱门", audio: "arch.wav" },
                { word: "architect", meaning: "建筑师", audio: "architect.wav" },
                { word: "architecture", meaning: "建筑学", audio: "architecture.wav" },
                { word: "assemble", meaning: "集合", audio: "assemble.wav" },
                { word: "balance", meaning: "平衡", audio: "balance.wav" },
                { word: "base", meaning: "根据", audio: "base.wav" },
                { word: "beam", meaning: "光束", audio: "beam.wav" },
                { word: "block", meaning: "堵塞", audio: "block.wav" },
                { word: "blueprint", meaning: "蓝图", audio: "blueprint.wav" },
                { word: "bolt", meaning: "螺栓", audio: "bolt.wav" },
                { word: "boundary", meaning: "边界", audio: "boundary.wav" },
                { word: "brace", meaning: "支撑", audio: "brace.wav" },
                { word: "brick", meaning: "砖", audio: "brick.wav" },
                { word: "bridge", meaning: "桥", audio: "bridge.wav" },
                { word: "budget", meaning: "预算", audio: "budget.wav" },
                { word: "build", meaning: "建造", audio: "build.wav" },
                { word: "building", meaning: "建筑", audio: "building.wav" },
                { word: "cable", meaning: "电缆", audio: "cable.wav" },
                { word: "calculate", meaning: "计算", audio: "calculate.wav" },
                { word: "capacity", meaning: "容量", audio: "capacity.wav" },
                { word: "ceiling", meaning: "天花板", audio: "ceiling.wav" },
                { word: "cement", meaning: "水泥", audio: "cement.wav" },
                { word: "chamber", meaning: "室", audio: "chamber.wav" },
                { word: "chimney", meaning: "烟囱", audio: "chimney.wav" },
                { word: "civil", meaning: "民事", audio: "civil.wav" },
                { word: "clamp", meaning: "夹具", audio: "clamp.wav" },
                { word: "clay", meaning: "黏土", audio: "clay.wav" },
                { word: "client", meaning: "客户", audio: "client.wav" },
                { word: "code", meaning: "代码", audio: "code.wav" },
                { word: "column", meaning: "柱子", audio: "column.wav" },
                { word: "commercial", meaning: "商业的", audio: "commercial.wav" },
                { word: "concrete", meaning: "具体的", audio: "concrete.wav" },
                { word: "conduct", meaning: "执行", audio: "conduct.wav" },
                { word: "construct", meaning: "构造", audio: "construct.wav" },
                { word: "construction", meaning: "建造", audio: "construction.wav" },
                { word: "consultant", meaning: "顾问", audio: "consultant.wav" },
                { word: "contract", meaning: "合同", audio: "contract.wav" },
                { word: "core", meaning: "核", audio: "core.wav" },
                { word: "corridor", meaning: "走廊", audio: "corridor.wav" },
                { word: "crane", meaning: "起重机", audio: "crane.wav" },
                { word: "cross", meaning: "叉", audio: "cross.wav" },
                { word: "dam", meaning: "坝", audio: "dam.wav" },
                { word: "deck", meaning: "甲板", audio: "deck.wav" },
                { word: "demolish", meaning: "拆除", audio: "demolish.wav" },
                { word: "dense", meaning: "稠密", audio: "dense.wav" },
                { word: "depth", meaning: "深度", audio: "depth.wav" },
                { word: "design", meaning: "设计", audio: "design.wav" },
                { word: "dimension", meaning: "方面", audio: "dimension.wav" },
                { word: "dome", meaning: "圆顶", audio: "dome.wav" },
                { word: "door", meaning: "门", audio: "door.wav" },
                { word: "drain", meaning: "流走", audio: "drain.wav" },
                { word: "drill", meaning: "训练", audio: "drill.wav" },
                { word: "durable", meaning: "耐用的", audio: "durable.wav" },
                { word: "dwelling", meaning: "住宅", audio: "dwelling.wav" },
                { word: "edge", meaning: "边缘", audio: "edge.wav" },
                { word: "elevate", meaning: "提升", audio: "elevate.wav" },
                { word: "engineer", meaning: "工程师", audio: "engineer.wav" },
                { word: "environment", meaning: "环境", audio: "environment.wav" },
                { word: "erect", meaning: "直立", audio: "erect.wav" },
                { word: "estimate", meaning: "估计", audio: "estimate.wav" },
                { word: "excavate", meaning: "挖掘", audio: "excavate.wav" },
                { word: "exterior", meaning: "外部", audio: "exterior.wav" },
                { word: "facade", meaning: "外立面", audio: "facade.wav" },
                { word: "facility", meaning: "设施", audio: "facility.wav" },
                { word: "feature", meaning: "特征", audio: "feature.wav" },
                { word: "fence", meaning: "栅栏", audio: "fence.wav" },
                { word: "fibre", meaning: "纤维", audio: "fibre.wav" },
                { word: "fixture", meaning: "夹具", audio: "fixture.wav" },
                { word: "flat", meaning: "平坦的", audio: "flat.wav" },
                { word: "floor", meaning: "地面", audio: "floor.wav" },
                { word: "foundation", meaning: "基础", audio: "foundation.wav" },
                { word: "frame", meaning: "框架", audio: "frame.wav" },
                { word: "function", meaning: "功能", audio: "function.wav" },
                { word: "furnish", meaning: "装修", audio: "furnish.wav" },
                { word: "gallery", meaning: "画廊", audio: "gallery.wav" },
                { word: "girder", meaning: "大梁", audio: "girder.wav" },
                { word: "glass", meaning: "玻璃", audio: "glass.wav" },
                { word: "grade", meaning: "年级", audio: "grade.wav" },
                { word: "gravel", meaning: "砦石", audio: "gravel.wav" },
                { word: "ground", meaning: "地面", audio: "ground.wav" },
                { word: "gutter", meaning: "排水沟", audio: "gutter.wav" },
                { word: "height", meaning: "高度", audio: "height.wav" },
                { word: "heritage", meaning: "遗产", audio: "heritage.wav" },
                { word: "horizontal", meaning: "水平的", audio: "horizontal.wav" },
                { word: "infrastructure", meaning: "基础设施", audio: "infrastructure.wav" },
                { word: "inspect", meaning: "检查", audio: "inspect.wav" },
                { word: "install", meaning: "安装", audio: "install.wav" },
                { word: "insulate", meaning: "绝缘", audio: "insulate.wav" },
                { word: "interior", meaning: "内部的", audio: "interior.wav" },
                { word: "iron", meaning: "铁", audio: "iron.wav" },
                { word: "joint", meaning: "联合的", audio: "joint.wav" },
                { word: "landmark", meaning: "地标", audio: "landmark.wav" },
                { word: "landscape", meaning: "景观", audio: "landscape.wav" },
                { word: "layout", meaning: "布局", audio: "layout.wav" },
                { word: "level", meaning: "等级", audio: "level.wav" },
                { word: "lift", meaning: "举起", audio: "lift.wav" },
                { word: "load", meaning: "加载", audio: "load.wav" },
                { word: "maintain", meaning: "维持", audio: "maintain.wav" },
                { word: "marble", meaning: "大理石", audio: "marble.wav" },
                { word: "material", meaning: "材料", audio: "material.wav" },
                { word: "measure", meaning: "措施", audio: "measure.wav" },
                { word: "metal", meaning: "金属", audio: "metal.wav" },
                { word: "model", meaning: "模型", audio: "model.wav" },
                { word: "mortar", meaning: "砂浆", audio: "mortar.wav" },
                { word: "panel", meaning: "控制板", audio: "panel.wav" },
                { word: "pier", meaning: "墩", audio: "pier.wav" },
                { word: "pillar", meaning: "柱子", audio: "pillar.wav" },
                { word: "pipe", meaning: "管道", audio: "pipe.wav" },
                { word: "plan", meaning: "计划", audio: "plan.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "plaster", meaning: "灰泥", audio: "plaster.wav" },
                { word: "plot", meaning: "阴谋", audio: "plot.wav" },
                { word: "plumb", meaning: "铅垂的", audio: "plumb.wav" },
                { word: "pole", meaning: "极", audio: "pole.wav" },
                { word: "project", meaning: "项目", audio: "project.wav" },
                { word: "property", meaning: "财产", audio: "property.wav" },
                { word: "proportion", meaning: "部分", audio: "proportion.wav" },
                { word: "ramp", meaning: "坡道", audio: "ramp.wav" },
                { word: "reinforce", meaning: "加强", audio: "reinforce.wav" },
                { word: "render", meaning: "渲染", audio: "render.wav" },
                { word: "renovate", meaning: "翻新", audio: "renovate.wav" },
                { word: "residential", meaning: "住宅的", audio: "residential.wav" },
                { word: "restore", meaning: "恢复", audio: "restore.wav" },
                { word: "rigid", meaning: "坚硬的", audio: "rigid.wav" },
                { word: "roof", meaning: "屋顶", audio: "roof.wav" },
                { word: "scaffold", meaning: "脚手架", audio: "scaffold.wav" },
                { word: "scale", meaning: "规模", audio: "scale.wav" },
                { word: "secure", meaning: "安全的", audio: "secure.wav" },
                { word: "site", meaning: "地点", audio: "site.wav" },
                { word: "slab", meaning: "板", audio: "slab.wav" },
                { word: "slope", meaning: "坡", audio: "slope.wav" },
                { word: "span", meaning: "跨度", audio: "span.wav" },
                { word: "specification", meaning: "规格", audio: "specification.wav" },
                { word: "stable", meaning: "稳定的", audio: "stable.wav" },
                { word: "steel", meaning: "钢", audio: "steel.wav" },
                { word: "storey", meaning: "楼层", audio: "storey.wav" },
                { word: "structure", meaning: "结构", audio: "structure.wav" },
                { word: "studio", meaning: "工作室", audio: "studio.wav" },
                { word: "survey", meaning: "民意调查", audio: "survey.wav" },
                { word: "suspend", meaning: "暂停", audio: "suspend.wav" },
                { word: "sustain", meaning: "维持", audio: "sustain.wav" },
                { word: "terrace", meaning: "露台", audio: "terrace.wav" },
                { word: "tile", meaning: "瓷砖", audio: "tile.wav" },
                { word: "timber", meaning: "木材", audio: "timber.wav" },
                { word: "tower", meaning: "塔", audio: "tower.wav" },
                { word: "trench", meaning: "沟渠", audio: "trench.wav" },
                { word: "tunnel", meaning: "隧道", audio: "tunnel.wav" },
                { word: "vault", meaning: "拱顶", audio: "vault.wav" },
                { word: "ventilate", meaning: "通风", audio: "ventilate.wav" },
                { word: "vertical", meaning: "垂直的", audio: "vertical.wav" },
                { word: "wall", meaning: "墙", audio: "wall.wav" },
                { word: "weld", meaning: "焊接", audio: "weld.wav" },
                { word: "wire", meaning: "金属丝", audio: "wire.wav" },
                { word: "zone", meaning: "区", audio: "zone.wav" }
            ]
        }
    }
});
