registerWordbook('topic_social_media', {
    name: "社交媒体",
    emoji: "📱",
    group: 'topic',
    description: "社交网络、内容创作、网络交流相关词汇",
    levels: {
        all: {
            name: "📱 全部",
            words: [
                { word: "account", meaning: "账号", audio: "account.wav" },
                { word: "algorithm", meaning: "算法", audio: "algorithm.wav" },
                { word: "anonymous", meaning: "匿名的", audio: "anonymous.wav" },
                { word: "audience", meaning: "受众; 粉丝群体", audio: "audience.wav" },
                { word: "authentic", meaning: "真实的; 原创的", audio: "authentic.wav" },
                { word: "avatar", meaning: "头像", audio: "avatar.wav" },
                { word: "ban", meaning: "禁止", audio: "ban.wav" },
                { word: "bias", meaning: "偏见", audio: "bias.wav" },
                { word: "block", meaning: "拉黑; 屏蔽", audio: "block.wav" },
                { word: "blog", meaning: "博客", audio: "blog.wav" },
                { word: "bookmark", meaning: "收藏", audio: "bookmark.wav" },
                { word: "bot", meaning: "水军; 自动账号", audio: "bot.wav" },
                { word: "caption", meaning: "配文; 图片说明", audio: "caption.wav" },
                { word: "celebrity", meaning: "名人", audio: "celebrity.wav" },
                { word: "censor", meaning: "审查", audio: "censor.wav" },
                { word: "channel", meaning: "频道", audio: "channel.wav" },
                { word: "chat", meaning: "聊天", audio: "chat.wav" },
                { word: "click", meaning: "点击", audio: "click.wav" },
                { word: "collaborate", meaning: "合作", audio: "collaborate.wav" },
                { word: "comment", meaning: "评论", audio: "comment.wav" },
                { word: "community", meaning: "社区", audio: "community.wav" },
                { word: "connect", meaning: "建立联系; 加好友", audio: "connect.wav" },
                { word: "content", meaning: "内容", audio: "content.wav" },
                { word: "conversation", meaning: "对话", audio: "conversation.wav" },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "creator", meaning: "内容创作者; 博主", audio: "creator.wav" },
                { word: "crowd", meaning: "众筹; 群体", audio: "crowd.wav" },
                { word: "curate", meaning: "精选; 内容策展", audio: "curate.wav" },
                { word: "dashboard", meaning: "管理后台; 数据面板", audio: "dashboard.wav" },
                { word: "debate", meaning: "辩论", audio: "debate.wav" },
                { word: "delete", meaning: "删除", audio: "delete.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "discover", meaning: "发现", audio: "discover.wav" },
                { word: "dislike", meaning: "踩; 不喜欢", audio: "dislike.wav" },
                { word: "donate", meaning: "打赏; 捐赠", audio: "donate.wav" },
                { word: "edit", meaning: "编辑", audio: "edit.wav" },
                { word: "emoji", meaning: "表情符号", audio: "emoji.wav" },
                { word: "engage", meaning: "互动", audio: "engage.wav" },
                { word: "explore", meaning: "探索", audio: "explore.wav" },
                { word: "expose", meaning: "曝光", audio: "expose.wav" },
                { word: "fake", meaning: "伪造的", audio: "fake.wav" },
                { word: "fan", meaning: "粉丝", audio: "fan.wav" },
                { word: "feed", meaning: "信息流; 动态", audio: "feed.wav" },
                { word: "filter", meaning: "滤镜", audio: "filter.wav" },
                { word: "follow", meaning: "关注", audio: "follow.wav" },
                { word: "follower", meaning: "粉丝", audio: "follower.wav" },
                { word: "forum", meaning: "论坛", audio: "forum.wav" },
                { word: "friend", meaning: "好友; 加好友", audio: "friend.wav" },
                { word: "generate", meaning: "生成", audio: "generate.wav" },
                { word: "group", meaning: "群组", audio: "group.wav" },
                { word: "handle", meaning: "用户名; 账号名", audio: "handle.wav" },
                { word: "hashtag", meaning: "话题标签", audio: "hashtag.wav" },
                { word: "highlight", meaning: "精选; 高光", audio: "highlight.wav" },
                { word: "identity", meaning: "网络身份; 账号身份", audio: "identity.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "impact", meaning: "影响", audio: "impact.wav" },
                { word: "inbox", meaning: "收件箱", audio: "inbox.wav" },
                { word: "influence", meaning: "影响", audio: "influence.wav" },
                { word: "influencer", meaning: "网红", audio: "influencer.wav" },
                { word: "interact", meaning: "互动", audio: "interact.wav" },
                { word: "invite", meaning: "邀请", audio: "invite.wav" },
                { word: "like", meaning: "点赞", audio: "like.wav" },
                { word: "link", meaning: "链接", audio: "link.wav" },
                { word: "live", meaning: "直播", audio: "live.wav" },
                { word: "login", meaning: "登录", audio: "login.wav" },
                { word: "mention", meaning: "@提及; 艾特", audio: "mention.wav" },
                { word: "message", meaning: "私信; 消息", audio: "message.wav" },
                { word: "meme", meaning: "网络流行图", audio: "meme.wav" },
                { word: "moderate", meaning: "审核; 管理", audio: "moderate.wav" },
                { word: "network", meaning: "网络", audio: "network.wav" },
                { word: "news", meaning: "新闻; 资讯", audio: "news.wav" },
                { word: "notify", meaning: "通知", audio: "notify.wav" },
                { word: "offline", meaning: "离线", audio: "offline.wav" },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "opinion", meaning: "观点", audio: "opinion.wav" },
                { word: "outreach", meaning: "推广; 触达", audio: "outreach.wav" },
                { word: "pin", meaning: "置顶", audio: "pin.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "podcast", meaning: "播客", audio: "podcast.wav" },
                { word: "poll", meaning: "投票", audio: "poll.wav" },
                { word: "popular", meaning: "受欢迎的", audio: "popular.wav" },
                { word: "post", meaning: "帖子; 发帖", audio: "post.wav" },
                { word: "privacy", meaning: "隐私", audio: "privacy.wav" },
                { word: "profile", meaning: "个人主页", audio: "profile.wav" },
                { word: "promote", meaning: "推广", audio: "promote.wav" },
                { word: "public", meaning: "公开的", audio: "public.wav" },
                { word: "publish", meaning: "发布", audio: "publish.wav" },
                { word: "react", meaning: "表态; 添加表情回应", audio: "react.wav" },
                { word: "reach", meaning: "触达; 覆盖量", audio: "reach.wav" },
                { word: "recommend", meaning: "推荐", audio: "recommend.wav" },
                { word: "reply", meaning: "回复", audio: "reply.wav" },
                { word: "report", meaning: "举报", audio: "report.wav" },
                { word: "repost", meaning: "转发", audio: "repost.wav" },
                { word: "review", meaning: "评价; 用户评论", audio: "review.wav" },
                { word: "scroll", meaning: "滚动", audio: "scroll.wav" },
                { word: "search", meaning: "搜索", audio: "search.wav" },
                { word: "share", meaning: "分享", audio: "share.wav" },
                { word: "status", meaning: "状态; 动态", audio: "status.wav" },
                { word: "story", meaning: "快拍; 限时动态", audio: "story.wav" },
                { word: "stream", meaning: "直播", audio: "stream.wav" },
                { word: "subscribe", meaning: "订阅", audio: "subscribe.wav" },
                { word: "tag", meaning: "标签", audio: "tag.wav" },
                { word: "thread", meaning: "帖子串; 话题链", audio: "thread.wav" },
                { word: "timeline", meaning: "时间线", audio: "timeline.wav" },
                { word: "troll", meaning: "网络喷子", audio: "troll.wav" },
                { word: "trend", meaning: "热门话题; 趋势", audio: "trend.wav" },
                { word: "trending", meaning: "热门的", audio: "trending.wav" },
                { word: "unfollow", meaning: "取消关注", audio: "unfollow.wav" },
                { word: "update", meaning: "更新", audio: "update.wav" },
                { word: "upload", meaning: "上传", audio: "upload.wav" },
                { word: "user", meaning: "用户", audio: "user.wav" },
                { word: "verify", meaning: "验证", audio: "verify.wav" },
                { word: "video", meaning: "视频", audio: "video.wav" },
                { word: "view", meaning: "浏览量", audio: "view.wav" },
                { word: "viral", meaning: "病毒式传播的", audio: "viral.wav" },
                { word: "voice", meaning: "语音", audio: "voice.wav" },
                { word: "vlog", meaning: "视频博客", audio: "vlog.wav" }
            ]
        }
    }
});
