registerWordbook('topic_ai', {
    name: "人工智能",
    emoji: "🤖",
    group: 'topic',
    description: "AI、机器学习、深度学习相关词汇",
    levels: {
        all: {
            name: "🤖 全部",
            words: [
                { word: "accuracy", meaning: "准确性", audio: "accuracy.wav" },
                { word: "adapt", meaning: "适应", audio: "adapt.wav" },
                { word: "agent", meaning: "智能体", audio: "agent.wav" },
                { word: "algorithm", meaning: "算法", audio: "algorithm.wav" },
                { word: "analyse", meaning: "分析", audio: "analyse.wav" },
                { word: "annotate", meaning: "标注", audio: "annotate.wav" },
                { word: "application", meaning: "应用", audio: "application.wav" },
                { word: "architecture", meaning: "架构; 模型架构", audio: "architecture.wav" },
                { word: "artificial", meaning: "人工的", audio: "artificial.wav" },
                { word: "assistant", meaning: "助手", audio: "assistant.wav" },
                { word: "attention", meaning: "注意力机制", audio: "attention.wav" },
                { word: "augment", meaning: "增强", audio: "augment.wav" },
                { word: "automate", meaning: "自动化", audio: "automate.wav" },
                { word: "autonomous", meaning: "自主的", audio: "autonomous.wav" },
                { word: "batch", meaning: "批次", audio: "batch.wav" },
                { word: "benchmark", meaning: "基准", audio: "benchmark.wav" },
                { word: "bias", meaning: "偏置; 偏差", audio: "bias.wav" },
                { word: "binary", meaning: "二进制", audio: "binary.wav" },
                { word: "bot", meaning: "机器人", audio: "bot.wav" },
                { word: "calculate", meaning: "计算", audio: "calculate.wav" },
                { word: "caption", meaning: "描述文字", audio: "caption.wav" },
                { word: "classify", meaning: "分类", audio: "classify.wav" },
                { word: "cloud", meaning: "云计算; 云端", audio: "cloud.wav" },
                { word: "cluster", meaning: "聚类", audio: "cluster.wav" },
                { word: "code", meaning: "代码", audio: "code.wav" },
                { word: "cognitive", meaning: "认知的", audio: "cognitive.wav" },
                { word: "compute", meaning: "计算", audio: "compute.wav" },
                { word: "converge", meaning: "收敛", audio: "converge.wav" },
                { word: "converse", meaning: "对话", audio: "converse.wav" },
                { word: "corpus", meaning: "语料库", audio: "corpus.wav" },
                { word: "correlate", meaning: "关联", audio: "correlate.wav" },
                { word: "data", meaning: "数据", audio: "data.wav" },
                { word: "dataset", meaning: "数据集", audio: "dataset.wav" },
                { word: "debug", meaning: "调试", audio: "debug.wav" },
                { word: "decision", meaning: "决定", audio: "decision.wav" },
                { word: "decode", meaning: "解码", audio: "decode.wav" },
                { word: "deep", meaning: "深度的", audio: "deep.wav" },
                { word: "deploy", meaning: "部署", audio: "deploy.wav" },
                { word: "detect", meaning: "探测", audio: "detect.wav" },
                { word: "device", meaning: "设备", audio: "device.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "dimension", meaning: "维度", audio: "dimension.wav" },
                { word: "discriminate", meaning: "判别", audio: "discriminate.wav" },
                { word: "distribute", meaning: "分布式", audio: "distribute.wav" },
                { word: "domain", meaning: "领域", audio: "domain.wav" },
                { word: "drone", meaning: "无人机", audio: "drone.wav" },
                { word: "dynamic", meaning: "动态的", audio: "dynamic.wav" },
                { word: "efficient", meaning: "高效的", audio: "efficient.wav" },
                { word: "embed", meaning: "嵌入", audio: "embed.wav" },
                { word: "encode", meaning: "编码", audio: "encode.wav" },
                { word: "engine", meaning: "引擎", audio: "engine.wav" },
                { word: "entity", meaning: "实体", audio: "entity.wav" },
                { word: "epoch", meaning: "训练轮次", audio: "epoch.wav" },
                { word: "error", meaning: "错误", audio: "error.wav" },
                { word: "estimate", meaning: "估计", audio: "estimate.wav" },
                { word: "evaluate", meaning: "评价", audio: "evaluate.wav" },
                { word: "evolve", meaning: "演化; 进化", audio: "evolve.wav" },
                { word: "experiment", meaning: "实验", audio: "experiment.wav" },
                { word: "exploit", meaning: "利用; 探索利用", audio: "exploit.wav" },
                { word: "extract", meaning: "提取", audio: "extract.wav" },
                { word: "feature", meaning: "特征", audio: "feature.wav" },
                { word: "feedback", meaning: "反馈", audio: "feedback.wav" },
                { word: "filter", meaning: "筛选", audio: "filter.wav" },
                { word: "fine", meaning: "微调(fine-tune)", audio: "fine.wav" },
                { word: "forecast", meaning: "预测", audio: "forecast.wav" },
                { word: "foundation", meaning: "基础", audio: "foundation.wav" },
                { word: "framework", meaning: "框架", audio: "framework.wav" },
                { word: "function", meaning: "函数", audio: "function.wav" },
                { word: "generate", meaning: "生成", audio: "generate.wav" },
                { word: "gradient", meaning: "梯度", audio: "gradient.wav" },
                { word: "graph", meaning: "图", audio: "graph.wav" },
                { word: "hardware", meaning: "硬件", audio: "hardware.wav" },
                { word: "hypothesis", meaning: "假设", audio: "hypothesis.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "implement", meaning: "实施", audio: "implement.wav" },
                { word: "inference", meaning: "推理", audio: "inference.wav" },
                { word: "input", meaning: "输入", audio: "input.wav" },
                { word: "instance", meaning: "实例", audio: "instance.wav" },
                { word: "integrate", meaning: "整合", audio: "integrate.wav" },
                { word: "intelligence", meaning: "智能", audio: "intelligence.wav" },
                { word: "interact", meaning: "交互", audio: "interact.wav" },
                { word: "interface", meaning: "界面", audio: "interface.wav" },
                { word: "iterate", meaning: "迭代", audio: "iterate.wav" },
                { word: "kernel", meaning: "核函数; 卷积核", audio: "kernel.wav" },
                { word: "label", meaning: "标签", audio: "label.wav" },
                { word: "language", meaning: "语言", audio: "language.wav" },
                { word: "latent", meaning: "潜在的", audio: "latent.wav" },
                { word: "layer", meaning: "层", audio: "layer.wav" },
                { word: "learn", meaning: "学习", audio: "learn.wav" },
                { word: "linear", meaning: "线性", audio: "linear.wav" },
                { word: "logic", meaning: "逻辑", audio: "logic.wav" },
                { word: "loss", meaning: "损失函数", audio: "loss.wav" },
                { word: "machine", meaning: "机器", audio: "machine.wav" },
                { word: "matrix", meaning: "矩阵", audio: "matrix.wav" },
                { word: "memory", meaning: "内存; 记忆体", audio: "memory.wav" },
                { word: "metric", meaning: "评价指标", audio: "metric.wav" },
                { word: "model", meaning: "模型", audio: "model.wav" },
                { word: "module", meaning: "模块", audio: "module.wav" },
                { word: "monitor", meaning: "监控", audio: "monitor.wav" },
                { word: "network", meaning: "网络", audio: "network.wav" },
                { word: "neural", meaning: "神经的", audio: "neural.wav" },
                { word: "node", meaning: "节点", audio: "node.wav" },
                { word: "noise", meaning: "噪音", audio: "noise.wav" },
                { word: "norm", meaning: "范数; 归一化", audio: "norm.wav" },
                { word: "objective", meaning: "目标; 目标函数", audio: "objective.wav" },
                { word: "observe", meaning: "观察", audio: "observe.wav" },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "operate", meaning: "操作", audio: "operate.wav" },
                { word: "optimize", meaning: "优化", audio: "optimize.wav" },
                { word: "output", meaning: "输出", audio: "output.wav" },
                { word: "overfit", meaning: "过拟合", audio: "overfit.wav" },
                { word: "parallel", meaning: "并行的", audio: "parallel.wav" },
                { word: "parameter", meaning: "参数", audio: "parameter.wav" },
                { word: "pattern", meaning: "模式", audio: "pattern.wav" },
                { word: "perceive", meaning: "感知", audio: "perceive.wav" },
                { word: "pipeline", meaning: "流水线; 处理管道", audio: "pipeline.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "predict", meaning: "预测", audio: "predict.wav" },
                { word: "pretrain", meaning: "预训练", audio: "pretrain.wav" },
                { word: "probability", meaning: "概率", audio: "probability.wav" },
                { word: "process", meaning: "处理", audio: "process.wav" },
                { word: "prompt", meaning: "提示词", audio: "prompt.wav" },
                { word: "random", meaning: "随机的", audio: "random.wav" },
                { word: "rank", meaning: "秩; 排名", audio: "rank.wav" },
                { word: "recall", meaning: "召回率", audio: "recall.wav" },
                { word: "recognition", meaning: "识别", audio: "recognition.wav" },
                { word: "recommend", meaning: "推荐", audio: "recommend.wav" },
                { word: "reinforce", meaning: "强化", audio: "reinforce.wav" },
                { word: "represent", meaning: "表示; 表征", audio: "represent.wav" },
                { word: "research", meaning: "研究", audio: "research.wav" },
                { word: "robot", meaning: "机器人", audio: "robot.wav" },
                { word: "sample", meaning: "样本", audio: "sample.wav" },
                { word: "scale", meaning: "规模", audio: "scale.wav" },
                { word: "score", meaning: "分数", audio: "score.wav" },
                { word: "segment", meaning: "分割", audio: "segment.wav" },
                { word: "semantic", meaning: "语义的", audio: "semantic.wav" },
                { word: "sensor", meaning: "传感器", audio: "sensor.wav" },
                { word: "sequence", meaning: "序列", audio: "sequence.wav" },
                { word: "server", meaning: "服务器", audio: "server.wav" },
                { word: "signal", meaning: "信号", audio: "signal.wav" },
                { word: "simulate", meaning: "模拟", audio: "simulate.wav" },
                { word: "software", meaning: "软件", audio: "software.wav" },
                { word: "speech", meaning: "语音", audio: "speech.wav" },
                { word: "statistic", meaning: "统计", audio: "statistic.wav" },
                { word: "structure", meaning: "结构", audio: "structure.wav" },
                { word: "supervise", meaning: "监督", audio: "supervise.wav" },
                { word: "synthetic", meaning: "合成的", audio: "synthetic.wav" },
                { word: "system", meaning: "系统", audio: "system.wav" },
                { word: "task", meaning: "任务", audio: "task.wav" },
                { word: "tensor", meaning: "张量", audio: "tensor.wav" },
                { word: "test", meaning: "测试", audio: "test.wav" },
                { word: "token", meaning: "词元; 标记", audio: "token.wav" },
                { word: "train", meaning: "训练", audio: "train.wav" },
                { word: "transfer", meaning: "迁移", audio: "transfer.wav" },
                { word: "transform", meaning: "转换", audio: "transform.wav" },
                { word: "tune", meaning: "调参; 微调", audio: "tune.wav" },
                { word: "validate", meaning: "验证", audio: "validate.wav" },
                { word: "vector", meaning: "向量", audio: "vector.wav" },
                { word: "virtual", meaning: "虚拟的", audio: "virtual.wav" },
                { word: "vision", meaning: "视觉; 计算机视觉", audio: "vision.wav" },
                { word: "weight", meaning: "权重", audio: "weight.wav" }
            ]
        }
    }
});
