registerWordbook('topic_social_media', {
    name: "社交媒体",
    emoji: "📱",
    group: 'topic',
    description: "社交网络、内容创作、网络交流相关词汇",
    levels: {
        all: {
            name: "📱 全部",
            words: [
                { word: "account", meaning: "帐户", audio: "account.wav" },
                { word: "algorithm", meaning: "算法", audio: null },
                { word: "anonymous", meaning: "匿名的", audio: "anonymous.wav" },
                { word: "audience", meaning: "观众", audio: "audience.wav" },
                { word: "authentic", meaning: "真正的", audio: "authentic.wav" },
                { word: "avatar", meaning: "头像", audio: null },
                { word: "ban", meaning: "禁止", audio: "ban.wav" },
                { word: "bias", meaning: "偏见", audio: "bias.wav" },
                { word: "block", meaning: "堵塞", audio: "block.wav" },
                { word: "blog", meaning: "博客", audio: "blog.wav" },
                { word: "bookmark", meaning: "书签", audio: null },
                { word: "bot", meaning: "机器人", audio: null },
                { word: "caption", meaning: "字幕", audio: null },
                { word: "celebrity", meaning: "名人", audio: "celebrity.wav" },
                { word: "censor", meaning: "审查", audio: null },
                { word: "channel", meaning: "渠道", audio: "channel.wav" },
                { word: "chat", meaning: "聊天", audio: "chat.wav" },
                { word: "click", meaning: "点击", audio: "click.wav" },
                { word: "collaborate", meaning: "合作", audio: "collaborate.wav" },
                { word: "comment", meaning: "评论", audio: "comment.wav" },
                { word: "community", meaning: "社区", audio: "community.wav" },
                { word: "connect", meaning: "连接", audio: "connect.wav" },
                { word: "content", meaning: "内容", audio: "content.wav" },
                { word: "conversation", meaning: "对话", audio: "conversation.wav" },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "creator", meaning: "创造者", audio: "creator.wav" },
                { word: "crowd", meaning: "人群", audio: "crowd.wav" },
                { word: "curate", meaning: "策展", audio: null },
                { word: "dashboard", meaning: "仪表盘", audio: null },
                { word: "debate", meaning: "辩论", audio: "debate.wav" },
                { word: "delete", meaning: "删除", audio: "delete.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "discover", meaning: "发现", audio: "discover.wav" },
                { word: "dislike", meaning: "不喜欢", audio: "dislike.wav" },
                { word: "donate", meaning: "捐", audio: "donate.wav" },
                { word: "edit", meaning: "编辑", audio: "edit.wav" },
                { word: "emoji", meaning: "表情符号", audio: null },
                { word: "engage", meaning: "从事", audio: "engage.wav" },
                { word: "explore", meaning: "探索", audio: "explore.wav" },
                { word: "expose", meaning: "暴露", audio: "expose.wav" },
                { word: "fake", meaning: "伪造的", audio: "fake.wav" },
                { word: "fan", meaning: "扇子", audio: "fan.wav" },
                { word: "feed", meaning: "喂养", audio: "feed.wav" },
                { word: "filter", meaning: "筛选", audio: "filter.wav" },
                { word: "follow", meaning: "跟随", audio: "follow.wav" },
                { word: "follower", meaning: "粉丝", audio: null },
                { word: "forum", meaning: "论坛", audio: "forum.wav" },
                { word: "friend", meaning: "朋友", audio: "friend.wav" },
                { word: "generate", meaning: "产生", audio: "generate.wav" },
                { word: "group", meaning: "团体", audio: "group.wav" },
                { word: "handle", meaning: "处理", audio: "handle.wav" },
                { word: "hashtag", meaning: "话题标签", audio: null },
                { word: "highlight", meaning: "强调", audio: "highlight.wav" },
                { word: "identity", meaning: "身份", audio: "identity.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "impact", meaning: "影响", audio: "impact.wav" },
                { word: "inbox", meaning: "收件箱", audio: null },
                { word: "influence", meaning: "影响", audio: "influence.wav" },
                { word: "influencer", meaning: "网红", audio: null },
                { word: "interact", meaning: "相互影响", audio: "interact.wav" },
                { word: "invite", meaning: "邀请", audio: "invite.wav" },
                { word: "like", meaning: "喜欢", audio: "like.wav" },
                { word: "link", meaning: "关联", audio: "link.wav" },
                { word: "live", meaning: "直播", audio: "live.wav" },
                { word: "login", meaning: "登录", audio: null },
                { word: "mention", meaning: "提到", audio: "mention.wav" },
                { word: "message", meaning: "信息", audio: "message.wav" },
                { word: "meme", meaning: "网络流行图", audio: null },
                { word: "moderate", meaning: "缓和", audio: "moderate.wav" },
                { word: "network", meaning: "网络", audio: "network.wav" },
                { word: "news", meaning: "消息", audio: "news.wav" },
                { word: "notify", meaning: "通知", audio: "notify.wav" },
                { word: "offline", meaning: "离线", audio: null },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "opinion", meaning: "观点", audio: "opinion.wav" },
                { word: "outreach", meaning: "外展", audio: null },
                { word: "pin", meaning: "别针", audio: "pin.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "podcast", meaning: "播客", audio: null },
                { word: "poll", meaning: "投票", audio: "poll.wav" },
                { word: "popular", meaning: "受欢迎的", audio: "popular.wav" },
                { word: "post", meaning: "邮政", audio: "post.wav" },
                { word: "privacy", meaning: "隐私", audio: "privacy.wav" },
                { word: "profile", meaning: "轮廓", audio: "profile.wav" },
                { word: "promote", meaning: "推动", audio: "promote.wav" },
                { word: "public", meaning: "民众", audio: "public.wav" },
                { word: "publish", meaning: "发布", audio: "publish.wav" },
                { word: "react", meaning: "反应", audio: "react.wav" },
                { word: "reach", meaning: "抵达", audio: "reach.wav" },
                { word: "recommend", meaning: "推荐", audio: "recommend.wav" },
                { word: "reply", meaning: "回复", audio: "reply.wav" },
                { word: "report", meaning: "报告", audio: "report.wav" },
                { word: "repost", meaning: "转发", audio: null },
                { word: "review", meaning: "审查", audio: "review.wav" },
                { word: "scroll", meaning: "滚动", audio: null },
                { word: "search", meaning: "搜索", audio: "search.wav" },
                { word: "share", meaning: "分享", audio: "share.wav" },
                { word: "status", meaning: "地位", audio: "status.wav" },
                { word: "story", meaning: "故事", audio: "story.wav" },
                { word: "stream", meaning: "溪流", audio: "stream.wav" },
                { word: "subscribe", meaning: "订阅", audio: null },
                { word: "tag", meaning: "标签", audio: "tag.wav" },
                { word: "thread", meaning: "线程", audio: null },
                { word: "timeline", meaning: "时间线", audio: null },
                { word: "troll", meaning: "网络喇叭", audio: null },
                { word: "trend", meaning: "趋势", audio: "trend.wav" },
                { word: "trending", meaning: "热门的", audio: null },
                { word: "unfollow", meaning: "取消关注", audio: null },
                { word: "update", meaning: "更新", audio: "update.wav" },
                { word: "upload", meaning: "上传", audio: null },
                { word: "user", meaning: "用户", audio: "user.wav" },
                { word: "verify", meaning: "验证", audio: "verify.wav" },
                { word: "video", meaning: "视频", audio: "video.wav" },
                { word: "view", meaning: "看法", audio: "view.wav" },
                { word: "viral", meaning: "病毒式传播的", audio: null },
                { word: "voice", meaning: "嗓音", audio: "voice.wav" },
                { word: "vlog", meaning: "视频博客", audio: null }
            ]
        }
    }
});
