registerWordbook('topic_politics', {
    name: "政治外交",
    emoji: "🏛️",
    group: 'topic',
    description: "政治制度、国际关系相关词汇",
    levels: {
        all: {
            name: "🏛️ 全部",
            words: [
                { word: "administration", meaning: "行政", audio: "administration.wav" },
                { word: "advocate", meaning: "提倡", audio: "advocate.wav" },
                { word: "agenda", meaning: "议程", audio: "agenda.wav" },
                { word: "agreement", meaning: "协议", audio: "agreement.wav" },
                { word: "alliance", meaning: "联盟", audio: "alliance.wav" },
                { word: "ambassador", meaning: "大使", audio: "ambassador.wav" },
                { word: "amend", meaning: "修正", audio: "amend.wav" },
                { word: "authority", meaning: "权威", audio: "authority.wav" },
                { word: "ballot", meaning: "选票", audio: "ballot.wav" },
                { word: "ban", meaning: "禁止", audio: "ban.wav" },
                { word: "bilateral", meaning: "双边的", audio: "bilateral.wav" },
                { word: "border", meaning: "边界", audio: "border.wav" },
                { word: "budget", meaning: "预算", audio: "budget.wav" },
                { word: "bureaucracy", meaning: "官僚", audio: "bureaucracy.wav" },
                { word: "cabinet", meaning: "内阁", audio: "cabinet.wav" },
                { word: "campaign", meaning: "竞选活动", audio: "campaign.wav" },
                { word: "candidate", meaning: "候选人", audio: "candidate.wav" },
                { word: "capitalism", meaning: "资本主义", audio: "capitalism.wav" },
                { word: "censor", meaning: "审查", audio: "censor.wav" },
                { word: "chancellor", meaning: "总理", audio: "chancellor.wav" },
                { word: "citizen", meaning: "公民", audio: "citizen.wav" },
                { word: "civil", meaning: "公民的; 民间的", audio: "civil.wav" },
                { word: "coalition", meaning: "联盟", audio: "coalition.wav" },
                { word: "colony", meaning: "殖民地", audio: "colony.wav" },
                { word: "committee", meaning: "委员会", audio: "committee.wav" },
                { word: "communism", meaning: "共产主义", audio: "communism.wav" },
                { word: "compromise", meaning: "妥协", audio: "compromise.wav" },
                { word: "conflict", meaning: "冲突", audio: "conflict.wav" },
                { word: "congress", meaning: "国会", audio: "congress.wav" },
                { word: "consensus", meaning: "共识", audio: "consensus.wav" },
                { word: "conservative", meaning: "保守的", audio: "conservative.wav" },
                { word: "constitution", meaning: "宪法", audio: "constitution.wav" },
                { word: "consul", meaning: "领事", audio: "consul.wav" },
                { word: "convention", meaning: "大会; 公约", audio: "convention.wav" },
                { word: "corrupt", meaning: "腐败", audio: "corrupt.wav" },
                { word: "council", meaning: "理事会", audio: "council.wav" },
                { word: "coup", meaning: "政变", audio: "coup.wav" },
                { word: "court", meaning: "法庭", audio: "court.wav" },
                { word: "crisis", meaning: "危机", audio: "crisis.wav" },
                { word: "debate", meaning: "辩论", audio: "debate.wav" },
                { word: "decree", meaning: "法令", audio: "decree.wav" },
                { word: "delegate", meaning: "代表", audio: "delegate.wav" },
                { word: "democracy", meaning: "民主", audio: "democracy.wav" },
                { word: "demonstrate", meaning: "示威; 游行", audio: "demonstrate.wav" },
                { word: "department", meaning: "部门", audio: "department.wav" },
                { word: "dictator", meaning: "独裁者", audio: "dictator.wav" },
                { word: "diplomacy", meaning: "外交", audio: "diplomacy.wav" },
                { word: "diplomat", meaning: "外交官", audio: "diplomat.wav" },
                { word: "domestic", meaning: "国内的", audio: "domestic.wav" },
                { word: "elect", meaning: "选举", audio: "elect.wav" },
                { word: "election", meaning: "选举", audio: "election.wav" },
                { word: "embassy", meaning: "大使馆", audio: "embassy.wav" },
                { word: "empire", meaning: "帝国", audio: "empire.wav" },
                { word: "enforce", meaning: "执行", audio: "enforce.wav" },
                { word: "executive", meaning: "行政的; 行政长官", audio: "executive.wav" },
                { word: "exile", meaning: "流亡", audio: "exile.wav" },
                { word: "federal", meaning: "联邦", audio: "federal.wav" },
                { word: "foreign", meaning: "外国的", audio: "foreign.wav" },
                { word: "freedom", meaning: "自由", audio: "freedom.wav" },
                { word: "govern", meaning: "治理", audio: "govern.wav" },
                { word: "government", meaning: "政府", audio: "government.wav" },
                { word: "ideology", meaning: "意识形态", audio: "ideology.wav" },
                { word: "immigrate", meaning: "移民", audio: "immigrate.wav" },
                { word: "imperial", meaning: "帝国的", audio: "imperial.wav" },
                { word: "impose", meaning: "强加", audio: "impose.wav" },
                { word: "independence", meaning: "独立", audio: "independence.wav" },
                { word: "influence", meaning: "影响", audio: "influence.wav" },
                { word: "institution", meaning: "机构", audio: "institution.wav" },
                { word: "interfere", meaning: "干涉; 干预", audio: "interfere.wav" },
                { word: "justice", meaning: "正义", audio: "justice.wav" },
                { word: "kingdom", meaning: "王国", audio: "kingdom.wav" },
                { word: "law", meaning: "法律", audio: "law.wav" },
                { word: "legislate", meaning: "立法", audio: "legislate.wav" },
                { word: "liberal", meaning: "自由主义", audio: "liberal.wav" },
                { word: "liberty", meaning: "自由", audio: "liberty.wav" },
                { word: "lobby", meaning: "游说", audio: "lobby.wav" },
                { word: "majority", meaning: "多数", audio: "majority.wav" },
                { word: "mandate", meaning: "授权", audio: "mandate.wav" },
                { word: "mayor", meaning: "市长", audio: "mayor.wav" },
                { word: "mediate", meaning: "调解", audio: "mediate.wav" },
                { word: "military", meaning: "军队", audio: "military.wav" },
                { word: "minister", meaning: "部长", audio: "minister.wav" },
                { word: "minority", meaning: "少数派; 少数群体", audio: "minority.wav" },
                { word: "monarchy", meaning: "君主制", audio: "monarchy.wav" },
                { word: "nation", meaning: "国家", audio: "nation.wav" },
                { word: "negotiate", meaning: "谈判", audio: "negotiate.wav" },
                { word: "neutral", meaning: "中立的", audio: "neutral.wav" },
                { word: "nominate", meaning: "提名", audio: "nominate.wav" },
                { word: "opposition", meaning: "反对党; 反对派", audio: "opposition.wav" },
                { word: "parliament", meaning: "议会", audio: "parliament.wav" },
                { word: "patriot", meaning: "爱国者", audio: "patriot.wav" },
                { word: "peace", meaning: "和平", audio: "peace.wav" },
                { word: "petition", meaning: "请愿", audio: "petition.wav" },
                { word: "policy", meaning: "政策", audio: "policy.wav" },
                { word: "poll", meaning: "投票", audio: "poll.wav" },
                { word: "power", meaning: "权力", audio: "power.wav" },
                { word: "president", meaning: "总统", audio: "president.wav" },
                { word: "prime", meaning: "首相的; 总理的", audio: "prime.wav" },
                { word: "privilege", meaning: "特权", audio: "privilege.wav" },
                { word: "propaganda", meaning: "宣传", audio: "propaganda.wav" },
                { word: "protest", meaning: "抗议", audio: "protest.wav" },
                { word: "province", meaning: "省", audio: "province.wav" },
                { word: "radical", meaning: "激进的", audio: "radical.wav" },
                { word: "rebel", meaning: "反叛者", audio: "rebel.wav" },
                { word: "reform", meaning: "改革", audio: "reform.wav" },
                { word: "refugee", meaning: "难民", audio: "refugee.wav" },
                { word: "regime", meaning: "政权", audio: "regime.wav" },
                { word: "regulate", meaning: "监管", audio: "regulate.wav" },
                { word: "republic", meaning: "共和国", audio: "republic.wav" },
                { word: "resign", meaning: "辞职", audio: "resign.wav" },
                { word: "revolution", meaning: "革命", audio: "revolution.wav" },
                { word: "right", meaning: "权利", audio: "right.wav" },
                { word: "rule", meaning: "统治; 执政", audio: "rule.wav" },
                { word: "sanction", meaning: "制裁", audio: "sanction.wav" },
                { word: "senate", meaning: "参议院", audio: "senate.wav" },
                { word: "socialist", meaning: "社会主义者", audio: "socialist.wav" },
                { word: "sovereign", meaning: "主权的", audio: "sovereign.wav" },
                { word: "state", meaning: "国家; 政权", audio: "state.wav" },
                { word: "strategy", meaning: "战略", audio: "strategy.wav" },
                { word: "summit", meaning: "峰会", audio: "summit.wav" },
                { word: "supreme", meaning: "最高的", audio: "supreme.wav" },
                { word: "territory", meaning: "领土", audio: "territory.wav" },
                { word: "treaty", meaning: "条约", audio: "treaty.wav" },
                { word: "unite", meaning: "团结", audio: "unite.wav" },
                { word: "veto", meaning: "否决", audio: "veto.wav" },
                { word: "vote", meaning: "投票", audio: "vote.wav" },
                { word: "welfare", meaning: "福利", audio: "welfare.wav" }
            ]
        }
    }
});
