registerWordbook('topic_film', {
    name: "电影影视",
    emoji: "🎬",
    group: 'topic',
    description: "电影、电视、表演、拍摄相关词汇",
    levels: {
        all: {
            name: "🎬 全部",
            words: [
                { word: "act", meaning: "行为", audio: "act.wav" },
                { word: "action", meaning: "行动", audio: "action.wav" },
                { word: "actor", meaning: "演员", audio: "actor.wav" },
                { word: "actress", meaning: "演员", audio: "actress.wav" },
                { word: "adapt", meaning: "适应", audio: "adapt.wav" },
                { word: "adventure", meaning: "冒险", audio: "adventure.wav" },
                { word: "alien", meaning: "外星人", audio: "alien.wav" },
                { word: "angle", meaning: "角度", audio: "angle.wav" },
                { word: "animate", meaning: "制作动画", audio: "animate.wav" },
                { word: "animation", meaning: "动画片", audio: "animation.wav" },
                { word: "applause", meaning: "掌声", audio: "applause.wav" },
                { word: "audience", meaning: "观众", audio: "audience.wav" },
                { word: "audition", meaning: "试镜", audio: "audition.wav" },
                { word: "award", meaning: "奖", audio: "award.wav" },
                { word: "background", meaning: "背景", audio: "background.wav" },
                { word: "blockbuster", meaning: "大片", audio: "blockbuster.wav" },
                { word: "broadcast", meaning: "播送", audio: "broadcast.wav" },
                { word: "camera", meaning: "相机", audio: "camera.wav" },
                { word: "caption", meaning: "字幕", audio: "caption.wav" },
                { word: "cast", meaning: "投掷", audio: "cast.wav" },
                { word: "celebrity", meaning: "名人", audio: "celebrity.wav" },
                { word: "chapter", meaning: "章", audio: "chapter.wav" },
                { word: "character", meaning: "特点", audio: "character.wav" },
                { word: "cinema", meaning: "电影", audio: "cinema.wav" },
                { word: "classic", meaning: "经典的", audio: "classic.wav" },
                { word: "clip", meaning: "夹子", audio: "clip.wav" },
                { word: "comedy", meaning: "喜剧", audio: "comedy.wav" },
                { word: "commercial", meaning: "商业的", audio: "commercial.wav" },
                { word: "compose", meaning: "撰写", audio: "compose.wav" },
                { word: "conclude", meaning: "得出结论", audio: "conclude.wav" },
                { word: "conflict", meaning: "冲突", audio: "conflict.wav" },
                { word: "contrast", meaning: "对比", audio: "contrast.wav" },
                { word: "costume", meaning: "戏服", audio: "costume.wav" },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "creative", meaning: "有创造力的", audio: "creative.wav" },
                { word: "credit", meaning: "信用", audio: "credit.wav" },
                { word: "crew", meaning: "全体人员", audio: "crew.wav" },
                { word: "critic", meaning: "评论家", audio: "critic.wav" },
                { word: "cut", meaning: "切割", audio: "cut.wav" },
                { word: "dark", meaning: "黑暗的", audio: "dark.wav" },
                { word: "dialogue", meaning: "对话", audio: "dialogue.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "direct", meaning: "直接的", audio: "direct.wav" },
                { word: "director", meaning: "导演", audio: "director.wav" },
                { word: "display", meaning: "展示", audio: "display.wav" },
                { word: "documentary", meaning: "记录", audio: "documentary.wav" },
                { word: "draft", meaning: "草稿", audio: "draft.wav" },
                { word: "drama", meaning: "戏剧", audio: "drama.wav" },
                { word: "dramatic", meaning: "戏剧性", audio: "dramatic.wav" },
                { word: "dub", meaning: "配音", audio: "dub.wav" },
                { word: "edit", meaning: "编辑", audio: "edit.wav" },
                { word: "edition", meaning: "版", audio: "edition.wav" },
                { word: "editor", meaning: "编辑", audio: "editor.wav" },
                { word: "effect", meaning: "影响", audio: "effect.wav" },
                { word: "emotion", meaning: "情感", audio: "emotion.wav" },
                { word: "ending", meaning: "结束", audio: "ending.wav" },
                { word: "entertain", meaning: "招待", audio: "entertain.wav" },
                { word: "entertainment", meaning: "娱乐", audio: "entertainment.wav" },
                { word: "epic", meaning: "史诗大片", audio: "epic.wav" },
                { word: "episode", meaning: "插曲", audio: "episode.wav" },
                { word: "event", meaning: "事件", audio: "event.wav" },
                { word: "exhibit", meaning: "展览", audio: "exhibit.wav" },
                { word: "express", meaning: "表达", audio: "express.wav" },
                { word: "extra", meaning: "额外的", audio: "extra.wav" },
                { word: "fade", meaning: "褪色", audio: "fade.wav" },
                { word: "fan", meaning: "扇子", audio: "fan.wav" },
                { word: "fantasy", meaning: "幻想", audio: "fantasy.wav" },
                { word: "feature", meaning: "特征", audio: "feature.wav" },
                { word: "fiction", meaning: "小说", audio: "fiction.wav" },
                { word: "film", meaning: "电影", audio: "film.wav" },
                { word: "filter", meaning: "筛选", audio: "filter.wav" },
                { word: "final", meaning: "最终的", audio: "final.wav" },
                { word: "flash", meaning: "闪光", audio: "flash.wav" },
                { word: "focus", meaning: "重点", audio: "focus.wav" },
                { word: "footage", meaning: "镜头", audio: "footage.wav" },
                { word: "format", meaning: "格式", audio: "format.wav" },
                { word: "frame", meaning: "框架", audio: "frame.wav" },
                { word: "genre", meaning: "类型", audio: "genre.wav" },
                { word: "hero", meaning: "英雄", audio: "hero.wav" },
                { word: "horror", meaning: "恐怖", audio: "horror.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "imagine", meaning: "想象", audio: "imagine.wav" },
                { word: "independent", meaning: "独立的", audio: "independent.wav" },
                { word: "inspire", meaning: "启发", audio: "inspire.wav" },
                { word: "install", meaning: "安装", audio: "install.wav" },
                { word: "interpret", meaning: "解释", audio: "interpret.wav" },
                { word: "interview", meaning: "面试", audio: "interview.wav" },
                { word: "joke", meaning: "开玩笑", audio: "joke.wav" },
                { word: "jump", meaning: "跳", audio: "jump.wav" },
                { word: "launch", meaning: "发射", audio: "launch.wav" },
                { word: "legend", meaning: "传奇", audio: "legend.wav" },
                { word: "lens", meaning: "镜片", audio: "lens.wav" },
                { word: "light", meaning: "光", audio: "light.wav" },
                { word: "location", meaning: "地点", audio: "location.wav" },
                { word: "makeup", meaning: "化妆", audio: "makeup.wav" },
                { word: "master", meaning: "掌握", audio: "master.wav" },
                { word: "media", meaning: "媒体", audio: "media.wav" },
                { word: "motion", meaning: "运动", audio: "motion.wav" },
                { word: "musical", meaning: "音乐", audio: "musical.wav" },
                { word: "mystery", meaning: "神秘", audio: "mystery.wav" },
                { word: "narrative", meaning: "叙述", audio: "narrative.wav" },
                { word: "nominate", meaning: "提名", audio: "nominate.wav" },
                { word: "novel", meaning: "小说", audio: "novel.wav" },
                { word: "original", meaning: "原来的", audio: "original.wav" },
                { word: "oscar", meaning: "奥斯卡", audio: "oscar.wav" },
                { word: "perform", meaning: "履行", audio: "perform.wav" },
                { word: "performance", meaning: "表现", audio: "performance.wav" },
                { word: "performer", meaning: "表演者", audio: "performer.wav" },
                { word: "photograph", meaning: "照片", audio: "photograph.wav" },
                { word: "pilot", meaning: "飞行员", audio: "pilot.wav" },
                { word: "plot", meaning: "阴谋", audio: "plot.wav" },
                { word: "point", meaning: "观点", audio: "point.wav" },
                { word: "premiere", meaning: "首映", audio: "premiere.wav" },
                { word: "present", meaning: "展示", audio: "present.wav" },
                { word: "preview", meaning: "预告", audio: "preview.wav" },
                { word: "produce", meaning: "生产", audio: "produce.wav" },
                { word: "producer", meaning: "制片人", audio: "producer.wav" },
                { word: "production", meaning: "生产", audio: "production.wav" },
                { word: "project", meaning: "项目", audio: "project.wav" },
                { word: "promote", meaning: "推动", audio: "promote.wav" },
                { word: "publish", meaning: "发布", audio: "publish.wav" },
                { word: "rate", meaning: "速度", audio: "rate.wav" },
                { word: "reality", meaning: "现实", audio: "reality.wav" },
                { word: "record", meaning: "记录", audio: "record.wav" },
                { word: "release", meaning: "发布", audio: "release.wav" },
                { word: "remake", meaning: "翻拍", audio: "remake.wav" },
                { word: "render", meaning: "渲染", audio: "render.wav" },
                { word: "replay", meaning: "回放", audio: "replay.wav" },
                { word: "represent", meaning: "代表", audio: "represent.wav" },
                { word: "review", meaning: "审查", audio: "review.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "romance", meaning: "浪漫", audio: "romance.wav" },
                { word: "scene", meaning: "场景", audio: "scene.wav" },
                { word: "score", meaning: "分数", audio: "score.wav" },
                { word: "screen", meaning: "屏幕", audio: "screen.wav" },
                { word: "screenplay", meaning: "剧本", audio: "screenplay.wav" },
                { word: "script", meaning: "脚本", audio: "script.wav" },
                { word: "sequel", meaning: "续集", audio: "sequel.wav" },
                { word: "series", meaning: "系列", audio: "series.wav" },
                { word: "set", meaning: "放", audio: "set.wav" },
                { word: "shoot", meaning: "射击", audio: "shoot.wav" },
                { word: "shot", meaning: "射击", audio: "shot.wav" },
                { word: "silent", meaning: "沉默的", audio: "silent.wav" },
                { word: "sound", meaning: "声音", audio: "sound.wav" },
                { word: "soundtrack", meaning: "原声带", audio: "soundtrack.wav" },
                { word: "special", meaning: "特别的", audio: "special.wav" },
                { word: "sponsor", meaning: "赞助", audio: "sponsor.wav" },
                { word: "stage", meaning: "阶段", audio: "stage.wav" },
                { word: "star", meaning: "星星", audio: "star.wav" },
                { word: "story", meaning: "故事", audio: "story.wav" },
                { word: "stream", meaning: "溪流", audio: "stream.wav" },
                { word: "studio", meaning: "工作室", audio: "studio.wav" },
                { word: "style", meaning: "风格", audio: "style.wav" },
                { word: "subtitle", meaning: "字幕", audio: "subtitle.wav" },
                { word: "talent", meaning: "天赋", audio: "talent.wav" },
                { word: "theme", meaning: "主题", audio: "theme.wav" },
                { word: "thriller", meaning: "惊悚片", audio: "thriller.wav" },
                { word: "ticket", meaning: "票", audio: "ticket.wav" },
                { word: "title", meaning: "标题", audio: "title.wav" },
                { word: "tone", meaning: "语气", audio: "tone.wav" },
                { word: "track", meaning: "追踪", audio: "track.wav" },
                { word: "trailer", meaning: "拖车", audio: "trailer.wav" },
                { word: "twist", meaning: "扭曲", audio: "twist.wav" },
                { word: "version", meaning: "版本", audio: "version.wav" },
                { word: "video", meaning: "视频", audio: "video.wav" },
                { word: "view", meaning: "看法", audio: "view.wav" },
                { word: "villain", meaning: "反派", audio: "villain.wav" },
                { word: "visual", meaning: "视觉的", audio: "visual.wav" },
                { word: "voice", meaning: "嗓音", audio: "voice.wav" },
                { word: "volume", meaning: "体积", audio: "volume.wav" }
            ]
        }
    }
});
