registerWordbook('topic_science', {
    name: "科学实验",
    emoji: "🔬",
    group: 'topic',
    description: "科学研究、实验、物理化学生物相关词汇",
    levels: {
        all: {
            name: "🔬 全部",
            words: [
                { word: "absorb", meaning: "吸收", audio: "absorb.wav" },
                { word: "abstract", meaning: "抽象的", audio: "abstract.wav" },
                { word: "accelerate", meaning: "加速", audio: "accelerate.wav" },
                { word: "acid", meaning: "酸", audio: "acid.wav" },
                { word: "analyse", meaning: "分析", audio: "analyse.wav" },
                { word: "analysis", meaning: "分析", audio: "analysis.wav" },
                { word: "apparatus", meaning: "设备", audio: "apparatus.wav" },
                { word: "apply", meaning: "应用", audio: "apply.wav" },
                { word: "approximate", meaning: "近似的", audio: "approximate.wav" },
                { word: "atom", meaning: "原子", audio: "atom.wav" },
                { word: "bacteria", meaning: "细菌", audio: "bacteria.wav" },
                { word: "beam", meaning: "光束", audio: "beam.wav" },
                { word: "biology", meaning: "生物学", audio: "biology.wav" },
                { word: "bond", meaning: "化学键", audio: "bond.wav" },
                { word: "breed", meaning: "繁殖; 培育", audio: "breed.wav" },
                { word: "carbon", meaning: "碳", audio: "carbon.wav" },
                { word: "catalyst", meaning: "催化剂", audio: "catalyst.wav" },
                { word: "cell", meaning: "细胞", audio: "cell.wav" },
                { word: "chain", meaning: "链", audio: "chain.wav" },
                { word: "chamber", meaning: "实验室; 反应室", audio: "chamber.wav" },
                { word: "chemical", meaning: "化学", audio: "chemical.wav" },
                { word: "chemistry", meaning: "化学", audio: "chemistry.wav" },
                { word: "circuit", meaning: "电路", audio: "circuit.wav" },
                { word: "classify", meaning: "分类", audio: "classify.wav" },
                { word: "climate", meaning: "气候", audio: "climate.wav" },
                { word: "clone", meaning: "克隆", audio: "clone.wav" },
                { word: "coal", meaning: "煤炭", audio: "coal.wav" },
                { word: "compound", meaning: "化合物", audio: "compound.wav" },
                { word: "compute", meaning: "计算", audio: "compute.wav" },
                { word: "concentrate", meaning: "集中", audio: "concentrate.wav" },
                { word: "concept", meaning: "概念", audio: "concept.wav" },
                { word: "conclusion", meaning: "结论", audio: "conclusion.wav" },
                { word: "conduct", meaning: "传导; 进行(实验)", audio: "conduct.wav" },
                { word: "confirm", meaning: "确认", audio: "confirm.wav" },
                { word: "conserve", meaning: "守恒; 保存", audio: "conserve.wav" },
                { word: "constant", meaning: "常数; 恒定的", audio: "constant.wav" },
                { word: "construct", meaning: "构造", audio: "construct.wav" },
                { word: "consume", meaning: "消耗", audio: "consume.wav" },
                { word: "contaminate", meaning: "污染", audio: "contaminate.wav" },
                { word: "control", meaning: "控制", audio: "control.wav" },
                { word: "convert", meaning: "转变", audio: "convert.wav" },
                { word: "core", meaning: "核", audio: "core.wav" },
                { word: "correlate", meaning: "关联", audio: "correlate.wav" },
                { word: "crystal", meaning: "晶体", audio: "crystal.wav" },
                { word: "current", meaning: "电流", audio: "current.wav" },
                { word: "curve", meaning: "曲线", audio: "curve.wav" },
                { word: "cycle", meaning: "循环", audio: "cycle.wav" },
                { word: "data", meaning: "数据", audio: "data.wav" },
                { word: "decay", meaning: "衰变", audio: "decay.wav" },
                { word: "demonstrate", meaning: "证明", audio: "demonstrate.wav" },
                { word: "density", meaning: "密度", audio: "density.wav" },
                { word: "derive", meaning: "派生", audio: "derive.wav" },
                { word: "detect", meaning: "探测", audio: "detect.wav" },
                { word: "device", meaning: "设备", audio: "device.wav" },
                { word: "diagram", meaning: "图表", audio: "diagram.wav" },
                { word: "dimension", meaning: "维度", audio: "dimension.wav" },
                { word: "discover", meaning: "发现", audio: "discover.wav" },
                { word: "discovery", meaning: "发现", audio: "discovery.wav" },
                { word: "dissolve", meaning: "溶解", audio: "dissolve.wav" },
                { word: "distinct", meaning: "独特的", audio: "distinct.wav" },
                { word: "dna", meaning: "脱氧核糖核酸", audio: "dna.wav" },
                { word: "document", meaning: "记录; 文献", audio: "document.wav" },
                { word: "element", meaning: "元素", audio: "element.wav" },
                { word: "emit", meaning: "发射", audio: "emit.wav" },
                { word: "empirical", meaning: "实证的; 经验主义的", audio: "empirical.wav" },
                { word: "energy", meaning: "能量", audio: "energy.wav" },
                { word: "engineer", meaning: "工程师", audio: "engineer.wav" },
                { word: "environment", meaning: "环境", audio: "environment.wav" },
                { word: "enzyme", meaning: "酶", audio: "enzyme.wav" },
                { word: "equation", meaning: "方程", audio: "equation.wav" },
                { word: "equilibrium", meaning: "平衡", audio: "equilibrium.wav" },
                { word: "evaluate", meaning: "评估; 求值", audio: "evaluate.wav" },
                { word: "evidence", meaning: "证据", audio: "evidence.wav" },
                { word: "evolve", meaning: "进化", audio: "evolve.wav" },
                { word: "examine", meaning: "检查", audio: "examine.wav" },
                { word: "experiment", meaning: "实验", audio: "experiment.wav" },
                { word: "exploit", meaning: "利用; 开发利用", audio: "exploit.wav" },
                { word: "explode", meaning: "爆炸", audio: "explode.wav" },
                { word: "expose", meaning: "暴露", audio: "expose.wav" },
                { word: "extract", meaning: "提炼", audio: "extract.wav" },
                { word: "factor", meaning: "因素", audio: "factor.wav" },
                { word: "filter", meaning: "过滤", audio: "filter.wav" },
                { word: "finding", meaning: "发现", audio: "finding.wav" },
                { word: "fluid", meaning: "流体", audio: "fluid.wav" },
                { word: "force", meaning: "力", audio: "force.wav" },
                { word: "formula", meaning: "公式", audio: "formula.wav" },
                { word: "fossil", meaning: "化石", audio: "fossil.wav" },
                { word: "fraction", meaning: "部分; 馏分", audio: "fraction.wav" },
                { word: "frequency", meaning: "频率", audio: "frequency.wav" },
                { word: "friction", meaning: "摩擦", audio: "friction.wav" },
                { word: "fuel", meaning: "燃料", audio: "fuel.wav" },
                { word: "function", meaning: "功能", audio: "function.wav" },
                { word: "fundamental", meaning: "基本的", audio: "fundamental.wav" },
                { word: "fusion", meaning: "融合", audio: "fusion.wav" },
                { word: "gas", meaning: "气体", audio: "gas.wav" },
                { word: "gene", meaning: "基因", audio: "gene.wav" },
                { word: "generate", meaning: "产生", audio: "generate.wav" },
                { word: "genetic", meaning: "遗传的", audio: "genetic.wav" },
                { word: "geology", meaning: "地质学", audio: "geology.wav" },
                { word: "gravity", meaning: "重力", audio: "gravity.wav" },
                { word: "habitat", meaning: "栖息地", audio: "habitat.wav" },
                { word: "heat", meaning: "热", audio: "heat.wav" },
                { word: "humidity", meaning: "湿度", audio: "humidity.wav" },
                { word: "hydrogen", meaning: "氢", audio: "hydrogen.wav" },
                { word: "hypothesis", meaning: "假设", audio: "hypothesis.wav" },
                { word: "illustrate", meaning: "阐明", audio: "illustrate.wav" },
                { word: "immune", meaning: "免疫", audio: "immune.wav" },
                { word: "impact", meaning: "影响", audio: "impact.wav" },
                { word: "infer", meaning: "推断", audio: "infer.wav" },
                { word: "infrared", meaning: "红外线", audio: "infrared.wav" },
                { word: "ingredient", meaning: "成分", audio: "ingredient.wav" },
                { word: "inspect", meaning: "检查", audio: "inspect.wav" },
                { word: "instrument", meaning: "仪器", audio: "instrument.wav" },
                { word: "insulate", meaning: "绝缘", audio: "insulate.wav" },
                { word: "interact", meaning: "相互影响", audio: "interact.wav" },
                { word: "interval", meaning: "间隔", audio: "interval.wav" },
                { word: "investigate", meaning: "研究; 探究", audio: "investigate.wav" },
                { word: "isolate", meaning: "隔离", audio: "isolate.wav" },
                { word: "journal", meaning: "学术期刊", audio: "journal.wav" },
                { word: "laboratory", meaning: "实验室", audio: "laboratory.wav" },
                { word: "laser", meaning: "激光", audio: "laser.wav" },
                { word: "layer", meaning: "层", audio: "layer.wav" },
                { word: "lens", meaning: "镜片", audio: "lens.wav" },
                { word: "liquid", meaning: "液体", audio: "liquid.wav" },
                { word: "magnet", meaning: "磁铁", audio: "magnet.wav" },
                { word: "magnitude", meaning: "量级; 数量级", audio: "magnitude.wav" },
                { word: "mass", meaning: "质量", audio: "mass.wav" },
                { word: "material", meaning: "材料", audio: "material.wav" },
                { word: "matter", meaning: "物质", audio: "matter.wav" },
                { word: "measure", meaning: "测量", audio: "measure.wav" },
                { word: "mechanism", meaning: "机制", audio: "mechanism.wav" },
                { word: "method", meaning: "方法", audio: "method.wav" },
                { word: "microscope", meaning: "显微镜", audio: "microscope.wav" },
                { word: "mineral", meaning: "矿物", audio: "mineral.wav" },
                { word: "mixture", meaning: "混合物", audio: "mixture.wav" },
                { word: "model", meaning: "模型", audio: "model.wav" },
                { word: "molecule", meaning: "分子", audio: "molecule.wav" },
                { word: "momentum", meaning: "动量", audio: "momentum.wav" },
                { word: "monitor", meaning: "监测", audio: "monitor.wav" },
                { word: "motion", meaning: "运动", audio: "motion.wav" },
                { word: "neutral", meaning: "中性的", audio: "neutral.wav" },
                { word: "neutron", meaning: "中子", audio: "neutron.wav" },
                { word: "nitrogen", meaning: "氮", audio: "nitrogen.wav" },
                { word: "nuclear", meaning: "核", audio: "nuclear.wav" },
                { word: "nucleus", meaning: "原子核", audio: "nucleus.wav" },
                { word: "observe", meaning: "观察", audio: "observe.wav" },
                { word: "orbit", meaning: "轨道", audio: "orbit.wav" },
                { word: "organic", meaning: "有机的", audio: "organic.wav" },
                { word: "organism", meaning: "有机体", audio: "organism.wav" },
                { word: "origin", meaning: "起源", audio: "origin.wav" },
                { word: "output", meaning: "输出", audio: "output.wav" },
                { word: "oxide", meaning: "氧化物", audio: "oxide.wav" },
                { word: "oxygen", meaning: "氧", audio: "oxygen.wav" },
                { word: "particle", meaning: "粒子", audio: "particle.wav" },
                { word: "patent", meaning: "专利", audio: "patent.wav" },
                { word: "phase", meaning: "阶段", audio: "phase.wav" },
                { word: "phenomenon", meaning: "现象", audio: "phenomenon.wav" },
                { word: "physics", meaning: "物理", audio: "physics.wav" },
                { word: "plasma", meaning: "等离子体", audio: "plasma.wav" },
                { word: "polar", meaning: "极性的", audio: "polar.wav" },
                { word: "predict", meaning: "预测", audio: "predict.wav" },
                { word: "pressure", meaning: "压力", audio: "pressure.wav" },
                { word: "principle", meaning: "原理", audio: "principle.wav" },
                { word: "probe", meaning: "探测", audio: "probe.wav" },
                { word: "procedure", meaning: "程序", audio: "procedure.wav" },
                { word: "process", meaning: "过程", audio: "process.wav" },
                { word: "property", meaning: "性质; 特性", audio: "property.wav" },
                { word: "proportion", meaning: "比例", audio: "proportion.wav" },
                { word: "protein", meaning: "蛋白质", audio: "protein.wav" },
                { word: "proton", meaning: "质子", audio: "proton.wav" },
                { word: "publish", meaning: "发表(论文)", audio: "publish.wav" },
                { word: "quantum", meaning: "量子", audio: "quantum.wav" },
                { word: "radiation", meaning: "辐射", audio: "radiation.wav" },
                { word: "reaction", meaning: "反应", audio: "reaction.wav" },
                { word: "reagent", meaning: "试剂", audio: "reagent.wav" },
                { word: "research", meaning: "研究", audio: "research.wav" },
                { word: "resist", meaning: "抵抗", audio: "resist.wav" },
                { word: "result", meaning: "结果", audio: "result.wav" },
                { word: "reveal", meaning: "揭示", audio: "reveal.wav" },
                { word: "sample", meaning: "样本", audio: "sample.wav" },
                { word: "satellite", meaning: "卫星", audio: "satellite.wav" },
                { word: "scale", meaning: "尺度; 刻度", audio: "scale.wav" },
                { word: "scan", meaning: "扫描", audio: "scan.wav" },
                { word: "sequence", meaning: "序列", audio: "sequence.wav" },
                { word: "simulate", meaning: "模拟", audio: "simulate.wav" },
                { word: "solar", meaning: "太阳的", audio: "solar.wav" },
                { word: "solution", meaning: "溶液", audio: "solution.wav" },
                { word: "solve", meaning: "解决", audio: "solve.wav" },
                { word: "species", meaning: "物种", audio: "species.wav" },
                { word: "specimen", meaning: "标本", audio: "specimen.wav" },
                { word: "spectrum", meaning: "光谱", audio: "spectrum.wav" },
                { word: "stable", meaning: "稳定的", audio: "stable.wav" },
                { word: "static", meaning: "静态的", audio: "static.wav" },
                { word: "stem", meaning: "茎", audio: "stem.wav" },
                { word: "structure", meaning: "结构", audio: "structure.wav" },
                { word: "substance", meaning: "物质", audio: "substance.wav" },
                { word: "survey", meaning: "调查; 勘测", audio: "survey.wav" },
                { word: "sustain", meaning: "维持", audio: "sustain.wav" },
                { word: "synthesis", meaning: "合成", audio: "synthesis.wav" },
                { word: "temperature", meaning: "温度", audio: "temperature.wav" },
                { word: "theorem", meaning: "定理", audio: "theorem.wav" },
                { word: "theory", meaning: "理论", audio: "theory.wav" },
                { word: "thermal", meaning: "热的", audio: "thermal.wav" },
                { word: "tissue", meaning: "组织", audio: "tissue.wav" },
                { word: "toxic", meaning: "有毒的", audio: "toxic.wav" },
                { word: "transform", meaning: "转换", audio: "transform.wav" },
                { word: "trial", meaning: "试验; 实验", audio: "trial.wav" },
                { word: "universe", meaning: "宇宙", audio: "universe.wav" },
                { word: "vacuum", meaning: "真空", audio: "vacuum.wav" },
                { word: "valid", meaning: "有效的", audio: "valid.wav" },
                { word: "variable", meaning: "变量", audio: "variable.wav" },
                { word: "velocity", meaning: "速度", audio: "velocity.wav" },
                { word: "verify", meaning: "验证", audio: "verify.wav" },
                { word: "volume", meaning: "体积", audio: "volume.wav" },
                { word: "wave", meaning: "波", audio: "wave.wav" },
                { word: "wavelength", meaning: "波长", audio: "wavelength.wav" }
            ]
        }
    }
});
