registerWordbook('topic_film', {
    name: "电影影视",
    emoji: "🎬",
    group: 'topic',
    description: "电影、电视、表演、拍摄相关词汇",
    levels: {
        all: {
            name: "🎬 全部",
            words: [
                { word: "act", meaning: "表演; 幕", audio: "act.wav" },
                { word: "action", meaning: "动作片; 开拍", audio: "action.wav" },
                { word: "actor", meaning: "演员", audio: "actor.wav" },
                { word: "actress", meaning: "女演员", audio: "actress.wav" },
                { word: "adapt", meaning: "改编", audio: "adapt.wav" },
                { word: "adventure", meaning: "冒险", audio: "adventure.wav" },
                { word: "alien", meaning: "外星人", audio: "alien.wav" },
                { word: "angle", meaning: "拍摄角度; 机位", audio: "angle.wav" },
                { word: "animate", meaning: "制作动画", audio: "animate.wav" },
                { word: "animation", meaning: "动画片", audio: "animation.wav" },
                { word: "applause", meaning: "掌声", audio: "applause.wav" },
                { word: "audience", meaning: "观众", audio: "audience.wav" },
                { word: "audition", meaning: "试镜", audio: "audition.wav" },
                { word: "award", meaning: "奖项; 颁奖", audio: "award.wav" },
                { word: "background", meaning: "背景", audio: "background.wav" },
                { word: "blockbuster", meaning: "大片", audio: "blockbuster.wav" },
                { word: "broadcast", meaning: "播送", audio: "broadcast.wav" },
                { word: "camera", meaning: "摄影机; 摄像机", audio: "camera.wav" },
                { word: "caption", meaning: "字幕; 说明文字", audio: "caption.wav" },
                { word: "cast", meaning: "演员阵容; 选角", audio: "cast.wav" },
                { word: "celebrity", meaning: "名人", audio: "celebrity.wav" },
                { word: "chapter", meaning: "章节; 段落", audio: "chapter.wav" },
                { word: "character", meaning: "角色; 人物", audio: "character.wav" },
                { word: "cinema", meaning: "电影院; 电影艺术", audio: "cinema.wav" },
                { word: "classic", meaning: "经典的", audio: "classic.wav" },
                { word: "clip", meaning: "片段", audio: "clip.wav" },
                { word: "comedy", meaning: "喜剧", audio: "comedy.wav" },
                { word: "commercial", meaning: "广告片", audio: "commercial.wav" },
                { word: "compose", meaning: "作曲; 配乐创作", audio: "compose.wav" },
                { word: "conclude", meaning: "结尾; 收官", audio: "conclude.wav" },
                { word: "conflict", meaning: "冲突", audio: "conflict.wav" },
                { word: "contrast", meaning: "对比度; 反差", audio: "contrast.wav" },
                { word: "costume", meaning: "戏服", audio: "costume.wav" },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "creative", meaning: "有创造力的", audio: "creative.wav" },
                { word: "credit", meaning: "片尾字幕; 演职员表", audio: "credit.wav" },
                { word: "crew", meaning: "剧组; 摄制组", audio: "crew.wav" },
                { word: "critic", meaning: "评论家", audio: "critic.wav" },
                { word: "cut", meaning: "剪辑; 剪切", audio: "cut.wav" },
                { word: "dark", meaning: "暗色调; 黑暗风格", audio: "dark.wav" },
                { word: "dialogue", meaning: "对话", audio: "dialogue.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "direct", meaning: "导演; 执导", audio: "direct.wav" },
                { word: "director", meaning: "导演", audio: "director.wav" },
                { word: "display", meaning: "展示", audio: "display.wav" },
                { word: "documentary", meaning: "纪录片", audio: "documentary.wav" },
                { word: "draft", meaning: "草稿", audio: "draft.wav" },
                { word: "drama", meaning: "戏剧", audio: "drama.wav" },
                { word: "dramatic", meaning: "戏剧性的", audio: "dramatic.wav" },
                { word: "dub", meaning: "配音", audio: "dub.wav" },
                { word: "edit", meaning: "剪辑", audio: "edit.wav" },
                { word: "edition", meaning: "版", audio: "edition.wav" },
                { word: "editor", meaning: "剪辑师", audio: "editor.wav" },
                { word: "effect", meaning: "特效", audio: "effect.wav" },
                { word: "emotion", meaning: "情感", audio: "emotion.wav" },
                { word: "ending", meaning: "结局", audio: "ending.wav" },
                { word: "entertain", meaning: "娱乐", audio: "entertain.wav" },
                { word: "entertainment", meaning: "娱乐", audio: "entertainment.wav" },
                { word: "epic", meaning: "史诗大片", audio: "epic.wav" },
                { word: "episode", meaning: "集; 单集", audio: "episode.wav" },
                { word: "event", meaning: "盛事; 首映活动", audio: "event.wav" },
                { word: "exhibit", meaning: "展览", audio: "exhibit.wav" },
                { word: "express", meaning: "表达", audio: "express.wav" },
                { word: "extra", meaning: "群众演员; 临时演员", audio: "extra.wav" },
                { word: "fade", meaning: "淡入淡出", audio: "fade.wav" },
                { word: "fan", meaning: "粉丝", audio: "fan.wav" },
                { word: "fantasy", meaning: "奇幻片", audio: "fantasy.wav" },
                { word: "feature", meaning: "故事片; 专题片", audio: "feature.wav" },
                { word: "fiction", meaning: "虚构; 虚构作品", audio: "fiction.wav" },
                { word: "film", meaning: "电影", audio: "film.wav" },
                { word: "filter", meaning: "滤镜; 滤光片", audio: "filter.wav" },
                { word: "final", meaning: "最终的", audio: "final.wav" },
                { word: "flash", meaning: "闪回; 闪光灯", audio: "flash.wav" },
                { word: "focus", meaning: "对焦; 焦点", audio: "focus.wav" },
                { word: "footage", meaning: "素材; 影像片段", audio: "footage.wav" },
                { word: "format", meaning: "格式", audio: "format.wav" },
                { word: "frame", meaning: "帧; 画面", audio: "frame.wav" },
                { word: "genre", meaning: "类型", audio: "genre.wav" },
                { word: "hero", meaning: "英雄", audio: "hero.wav" },
                { word: "horror", meaning: "恐怖片", audio: "horror.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "imagine", meaning: "想象", audio: "imagine.wav" },
                { word: "independent", meaning: "独立电影的", audio: "independent.wav" },
                { word: "inspire", meaning: "启发", audio: "inspire.wav" },
                { word: "install", meaning: "布置; 装置艺术", audio: "install.wav" },
                { word: "interpret", meaning: "诠释; 演绎", audio: "interpret.wav" },
                { word: "interview", meaning: "采访", audio: "interview.wav" },
                { word: "joke", meaning: "开玩笑", audio: "joke.wav" },
                { word: "jump", meaning: "跳切", audio: "jump.wav" },
                { word: "launch", meaning: "上映; 发布", audio: "launch.wav" },
                { word: "legend", meaning: "传奇", audio: "legend.wav" },
                { word: "lens", meaning: "镜头", audio: "lens.wav" },
                { word: "light", meaning: "灯光; 打光", audio: "light.wav" },
                { word: "location", meaning: "外景地; 拍摄地", audio: "location.wav" },
                { word: "makeup", meaning: "化妆", audio: "makeup.wav" },
                { word: "master", meaning: "母带; 原版", audio: "master.wav" },
                { word: "media", meaning: "媒体", audio: "media.wav" },
                { word: "motion", meaning: "动态; 运镜", audio: "motion.wav" },
                { word: "musical", meaning: "歌舞片; 音乐剧", audio: "musical.wav" },
                { word: "mystery", meaning: "悬疑片", audio: "mystery.wav" },
                { word: "narrative", meaning: "叙事; 叙事手法", audio: "narrative.wav" },
                { word: "nominate", meaning: "提名", audio: "nominate.wav" },
                { word: "novel", meaning: "小说", audio: "novel.wav" },
                { word: "original", meaning: "原创的; 原版的", audio: "original.wav" },
                { word: "oscar", meaning: "奥斯卡", audio: "oscar.wav" },
                { word: "perform", meaning: "表演", audio: "perform.wav" },
                { word: "performance", meaning: "表演; 演出", audio: "performance.wav" },
                { word: "performer", meaning: "表演者", audio: "performer.wav" },
                { word: "photograph", meaning: "照片", audio: "photograph.wav" },
                { word: "pilot", meaning: "试播集", audio: "pilot.wav" },
                { word: "plot", meaning: "剧情; 情节", audio: "plot.wav" },
                { word: "point", meaning: "要点", audio: "point.wav" },
                { word: "premiere", meaning: "首映", audio: "premiere.wav" },
                { word: "present", meaning: "展示", audio: "present.wav" },
                { word: "preview", meaning: "预告", audio: "preview.wav" },
                { word: "produce", meaning: "制作", audio: "produce.wav" },
                { word: "producer", meaning: "制片人", audio: "producer.wav" },
                { word: "production", meaning: "制作; 制片", audio: "production.wav" },
                { word: "project", meaning: "项目", audio: "project.wav" },
                { word: "promote", meaning: "宣传; 推广", audio: "promote.wav" },
                { word: "publish", meaning: "发布", audio: "publish.wav" },
                { word: "rate", meaning: "评分; 分级", audio: "rate.wav" },
                { word: "reality", meaning: "真人秀; 现实题材", audio: "reality.wav" },
                { word: "record", meaning: "记录", audio: "record.wav" },
                { word: "release", meaning: "上映; 发行", audio: "release.wav" },
                { word: "remake", meaning: "翻拍", audio: "remake.wav" },
                { word: "render", meaning: "渲染", audio: "render.wav" },
                { word: "replay", meaning: "回放", audio: "replay.wav" },
                { word: "represent", meaning: "代表", audio: "represent.wav" },
                { word: "review", meaning: "影评", audio: "review.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "romance", meaning: "爱情片", audio: "romance.wav" },
                { word: "scene", meaning: "场景", audio: "scene.wav" },
                { word: "score", meaning: "配乐", audio: "score.wav" },
                { word: "screen", meaning: "银幕", audio: "screen.wav" },
                { word: "screenplay", meaning: "剧本", audio: "screenplay.wav" },
                { word: "script", meaning: "剧本", audio: "script.wav" },
                { word: "sequel", meaning: "续集", audio: "sequel.wav" },
                { word: "series", meaning: "剧集; 系列片", audio: "series.wav" },
                { word: "set", meaning: "布景; 片场", audio: "set.wav" },
                { word: "shoot", meaning: "拍摄", audio: "shoot.wav" },
                { word: "shot", meaning: "镜头", audio: "shot.wav" },
                { word: "silent", meaning: "默片的; 无声的", audio: "silent.wav" },
                { word: "sound", meaning: "声音", audio: "sound.wav" },
                { word: "soundtrack", meaning: "原声带", audio: "soundtrack.wav" },
                { word: "special", meaning: "特效的; 特辑", audio: "special.wav" },
                { word: "sponsor", meaning: "赞助", audio: "sponsor.wav" },
                { word: "stage", meaning: "舞台", audio: "stage.wav" },
                { word: "star", meaning: "明星; 主演", audio: "star.wav" },
                { word: "story", meaning: "故事", audio: "story.wav" },
                { word: "stream", meaning: "流媒体", audio: "stream.wav" },
                { word: "studio", meaning: "工作室", audio: "studio.wav" },
                { word: "style", meaning: "风格", audio: "style.wav" },
                { word: "subtitle", meaning: "字幕", audio: "subtitle.wav" },
                { word: "talent", meaning: "演艺人才", audio: "talent.wav" },
                { word: "theme", meaning: "主题", audio: "theme.wav" },
                { word: "thriller", meaning: "惊悚片", audio: "thriller.wav" },
                { word: "ticket", meaning: "票", audio: "ticket.wav" },
                { word: "title", meaning: "片名; 字幕", audio: "title.wav" },
                { word: "tone", meaning: "影调; 基调", audio: "tone.wav" },
                { word: "track", meaning: "音轨; 配乐曲目", audio: "track.wav" },
                { word: "trailer", meaning: "预告片", audio: "trailer.wav" },
                { word: "twist", meaning: "反转; 转折", audio: "twist.wav" },
                { word: "version", meaning: "版本", audio: "version.wav" },
                { word: "video", meaning: "视频", audio: "video.wav" },
                { word: "view", meaning: "观看; 观影", audio: "view.wav" },
                { word: "villain", meaning: "反派", audio: "villain.wav" },
                { word: "visual", meaning: "视觉的", audio: "visual.wav" },
                { word: "voice", meaning: "配音", audio: "voice.wav" },
                { word: "volume", meaning: "音量; 卷", audio: "volume.wav" }
            ]
        }
    }
});
