registerWordbook('topic_marketing', {
    name: "营销广告",
    emoji: "📊",
    group: 'topic',
    description: "市场营销、广告、品牌推广相关词汇",
    levels: {
        all: {
            name: "📊 全部",
            words: [
                { word: "advertise", meaning: "广告", audio: "advertise.wav" },
                { word: "advertisement", meaning: "广告", audio: "advertisement.wav" },
                { word: "affiliate", meaning: "联盟", audio: null },
                { word: "agency", meaning: "机构", audio: "agency.wav" },
                { word: "analyse", meaning: "分析", audio: "analyse.wav" },
                { word: "appeal", meaning: "上诉", audio: "appeal.wav" },
                { word: "audience", meaning: "观众", audio: "audience.wav" },
                { word: "awareness", meaning: "意识", audio: "awareness.wav" },
                { word: "benchmark", meaning: "基准", audio: "benchmark.wav" },
                { word: "billboard", meaning: "广告牌", audio: null },
                { word: "boost", meaning: "促进", audio: "boost.wav" },
                { word: "brand", meaning: "品牌", audio: "brand.wav" },
                { word: "broadcast", meaning: "播送", audio: "broadcast.wav" },
                { word: "brochure", meaning: "手册", audio: null },
                { word: "budget", meaning: "预算", audio: "budget.wav" },
                { word: "bundle", meaning: "捆绑销售", audio: null },
                { word: "buyer", meaning: "买家", audio: null },
                { word: "campaign", meaning: "活动", audio: "campaign.wav" },
                { word: "catalogue", meaning: "目录", audio: "catalogue.wav" },
                { word: "channel", meaning: "渠道", audio: "channel.wav" },
                { word: "client", meaning: "客户", audio: "client.wav" },
                { word: "collaborate", meaning: "合作", audio: "collaborate.wav" },
                { word: "commercial", meaning: "商业的", audio: "commercial.wav" },
                { word: "commission", meaning: "委员会", audio: "commission.wav" },
                { word: "communicate", meaning: "交流", audio: "communicate.wav" },
                { word: "compete", meaning: "竞争", audio: "compete.wav" },
                { word: "consumer", meaning: "消费者", audio: "consumer.wav" },
                { word: "content", meaning: "内容", audio: "content.wav" },
                { word: "conversion", meaning: "转换", audio: "conversion.wav" },
                { word: "convince", meaning: "说服", audio: "convince.wav" },
                { word: "coupon", meaning: "优惠券", audio: null },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "creative", meaning: "有创造力的", audio: "creative.wav" },
                { word: "customer", meaning: "顾客", audio: "customer.wav" },
                { word: "data", meaning: "数据", audio: "data.wav" },
                { word: "deadline", meaning: "最后期限", audio: "deadline.wav" },
                { word: "deal", meaning: "交易", audio: "deal.wav" },
                { word: "deliver", meaning: "递送", audio: "deliver.wav" },
                { word: "demand", meaning: "要求", audio: "demand.wav" },
                { word: "demographic", meaning: "人口统计的", audio: null },
                { word: "design", meaning: "设计", audio: "design.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "direct", meaning: "直接的", audio: "direct.wav" },
                { word: "discount", meaning: "折扣", audio: "discount.wav" },
                { word: "display", meaning: "展示", audio: "display.wav" },
                { word: "distribute", meaning: "分发", audio: "distribute.wav" },
                { word: "domain", meaning: "领域", audio: "domain.wav" },
                { word: "email", meaning: "电子邮件", audio: "email.wav" },
                { word: "endorse", meaning: "赞同", audio: "endorse.wav" },
                { word: "engage", meaning: "从事", audio: "engage.wav" },
                { word: "estimate", meaning: "估计", audio: "estimate.wav" },
                { word: "event", meaning: "事件", audio: "event.wav" },
                { word: "execute", meaning: "执行", audio: "execute.wav" },
                { word: "expand", meaning: "扩张", audio: "expand.wav" },
                { word: "exposure", meaning: "接触", audio: "exposure.wav" },
                { word: "feature", meaning: "特征", audio: "feature.wav" },
                { word: "feedback", meaning: "反馈", audio: "feedback.wav" },
                { word: "filter", meaning: "筛选", audio: "filter.wav" },
                { word: "focus", meaning: "重点", audio: "focus.wav" },
                { word: "forecast", meaning: "预报", audio: "forecast.wav" },
                { word: "franchise", meaning: "特许经营权", audio: "franchise.wav" },
                { word: "frequency", meaning: "频率", audio: "frequency.wav" },
                { word: "fund", meaning: "基金", audio: "fund.wav" },
                { word: "generate", meaning: "产生", audio: "generate.wav" },
                { word: "graphic", meaning: "形象的", audio: "graphic.wav" },
                { word: "growth", meaning: "生长", audio: "growth.wav" },
                { word: "guarantee", meaning: "保证", audio: "guarantee.wav" },
                { word: "headline", meaning: "标题", audio: "headline.wav" },
                { word: "highlight", meaning: "强调", audio: "highlight.wav" },
                { word: "identity", meaning: "身份", audio: "identity.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "impact", meaning: "影响", audio: "impact.wav" },
                { word: "impression", meaning: "印象", audio: "impression.wav" },
                { word: "incentive", meaning: "激励", audio: "incentive.wav" },
                { word: "influence", meaning: "影响", audio: "influence.wav" },
                { word: "innovation", meaning: "创新", audio: "innovation.wav" },
                { word: "insight", meaning: "洞察力", audio: "insight.wav" },
                { word: "interview", meaning: "面试", audio: "interview.wav" },
                { word: "invest", meaning: "投资", audio: "invest.wav" },
                { word: "launch", meaning: "发射", audio: "launch.wav" },
                { word: "layout", meaning: "布局", audio: "layout.wav" },
                { word: "lead", meaning: "导联", audio: "lead.wav" },
                { word: "logo", meaning: "标识", audio: "logo.wav" },
                { word: "loyalty", meaning: "忠诚", audio: "loyalty.wav" },
                { word: "margin", meaning: "利润", audio: "margin.wav" },
                { word: "market", meaning: "市场", audio: "market.wav" },
                { word: "media", meaning: "媒体", audio: "media.wav" },
                { word: "merchandise", meaning: "商品", audio: null },
                { word: "metric", meaning: "指标", audio: null },
                { word: "motto", meaning: "广告语", audio: null },
                { word: "negotiate", meaning: "谈判", audio: "negotiate.wav" },
                { word: "network", meaning: "网络", audio: "network.wav" },
                { word: "niche", meaning: "利基", audio: "niche.wav" },
                { word: "objective", meaning: "客观的", audio: "objective.wav" },
                { word: "offer", meaning: "提供", audio: "offer.wav" },
                { word: "optimize", meaning: "优化", audio: null },
                { word: "organic", meaning: "有机的", audio: "organic.wav" },
                { word: "outreach", meaning: "外展", audio: null },
                { word: "partner", meaning: "伙伴", audio: "partner.wav" },
                { word: "perception", meaning: "洞察力", audio: "perception.wav" },
                { word: "persuade", meaning: "说服", audio: "persuade.wav" },
                { word: "pitch", meaning: "沥青", audio: "pitch.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "poll", meaning: "投票", audio: "poll.wav" },
                { word: "position", meaning: "位置", audio: "position.wav" },
                { word: "premium", meaning: "溢价", audio: "premium.wav" },
                { word: "press", meaning: "按", audio: "press.wav" },
                { word: "price", meaning: "价格", audio: "price.wav" },
                { word: "print", meaning: "打印", audio: "print.wav" },
                { word: "product", meaning: "产品", audio: "product.wav" },
                { word: "profile", meaning: "轮廓", audio: "profile.wav" },
                { word: "profit", meaning: "利润", audio: "profit.wav" },
                { word: "promote", meaning: "推动", audio: "promote.wav" },
                { word: "promotion", meaning: "晋升", audio: "promotion.wav" },
                { word: "prospect", meaning: "前景", audio: "prospect.wav" },
                { word: "public", meaning: "民众", audio: "public.wav" },
                { word: "publish", meaning: "发布", audio: "publish.wav" },
                { word: "purchase", meaning: "购买", audio: "purchase.wav" },
                { word: "rate", meaning: "速度", audio: "rate.wav" },
                { word: "reach", meaning: "抵达", audio: "reach.wav" },
                { word: "recommend", meaning: "推荐", audio: "recommend.wav" },
                { word: "referral", meaning: "推荐", audio: null },
                { word: "reputation", meaning: "名声", audio: "reputation.wav" },
                { word: "retail", meaning: "零售", audio: "retail.wav" },
                { word: "return", meaning: "返回", audio: "return.wav" },
                { word: "revenue", meaning: "收入", audio: "revenue.wav" },
                { word: "review", meaning: "审查", audio: "review.wav" },
                { word: "sample", meaning: "样本", audio: "sample.wav" },
                { word: "segment", meaning: "段", audio: "segment.wav" },
                { word: "slogan", meaning: "口号", audio: "slogan.wav" },
                { word: "sponsor", meaning: "赞助", audio: "sponsor.wav" },
                { word: "strategy", meaning: "战略", audio: "strategy.wav" },
                { word: "subscribe", meaning: "订阅", audio: null },
                { word: "survey", meaning: "民意调查", audio: "survey.wav" },
                { word: "tag", meaning: "标签", audio: "tag.wav" },
                { word: "target", meaning: "目标", audio: "target.wav" },
                { word: "testimonial", meaning: "推荐信", audio: null },
                { word: "track", meaning: "追踪", audio: "track.wav" },
                { word: "trade", meaning: "贸易", audio: "trade.wav" },
                { word: "traffic", meaning: "交通", audio: "traffic.wav" },
                { word: "trend", meaning: "趋势", audio: "trend.wav" },
                { word: "value", meaning: "价值", audio: "value.wav" },
                { word: "viral", meaning: "病毒式传播的", audio: null },
                { word: "visual", meaning: "视觉的", audio: "visual.wav" },
                { word: "wholesale", meaning: "批发", audio: null }
            ]
        }
    }
});
