registerWordbook('topic_psychology', {
    name: "心理学",
    emoji: "🧠",
    group: 'topic',
    description: "心理学概念、情绪认知相关词汇",
    levels: {
        all: {
            name: "🧠 全部",
            words: [
                { word: "absorb", meaning: "吸收", audio: "absorb.wav" },
                { word: "abuse", meaning: "虐待", audio: "abuse.wav" },
                { word: "adapt", meaning: "适应", audio: "adapt.wav" },
                { word: "addict", meaning: "上瘾者", audio: "addict.wav" },
                { word: "adolescent", meaning: "青少年", audio: "adolescent.wav" },
                { word: "aggressive", meaning: "挑衅的", audio: "aggressive.wav" },
                { word: "anger", meaning: "愤怒", audio: "anger.wav" },
                { word: "anxiety", meaning: "焦虑", audio: "anxiety.wav" },
                { word: "appetite", meaning: "食欲", audio: "appetite.wav" },
                { word: "arouse", meaning: "唤起", audio: "arouse.wav" },
                { word: "associate", meaning: "联系", audio: "associate.wav" },
                { word: "attach", meaning: "附", audio: "attach.wav" },
                { word: "attention", meaning: "注意力", audio: "attention.wav" },
                { word: "attitude", meaning: "态度", audio: "attitude.wav" },
                { word: "aware", meaning: "意识到的", audio: "aware.wav" },
                { word: "behaviour", meaning: "行为", audio: "behaviour.wav" },
                { word: "believe", meaning: "相信", audio: "believe.wav" },
                { word: "bias", meaning: "偏见", audio: "bias.wav" },
                { word: "bond", meaning: "纽带", audio: "bond.wav" },
                { word: "bore", meaning: "使厌烦", audio: "bore.wav" },
                { word: "brain", meaning: "脑", audio: "brain.wav" },
                { word: "bully", meaning: "欺凌", audio: "bully.wav" },
                { word: "calm", meaning: "冷静的", audio: "calm.wav" },
                { word: "capacity", meaning: "容量", audio: "capacity.wav" },
                { word: "character", meaning: "特点", audio: "character.wav" },
                { word: "clinical", meaning: "临床", audio: "clinical.wav" },
                { word: "cognitive", meaning: "认知的", audio: "cognitive.wav" },
                { word: "comfort", meaning: "舒适", audio: "comfort.wav" },
                { word: "communicate", meaning: "交流", audio: "communicate.wav" },
                { word: "compel", meaning: "迫使", audio: "compel.wav" },
                { word: "complex", meaning: "复杂的", audio: "complex.wav" },
                { word: "concentrate", meaning: "集中", audio: "concentrate.wav" },
                { word: "concept", meaning: "概念", audio: "concept.wav" },
                { word: "condition", meaning: "状况", audio: "condition.wav" },
                { word: "confidence", meaning: "信心", audio: "confidence.wav" },
                { word: "conflict", meaning: "冲突", audio: "conflict.wav" },
                { word: "conform", meaning: "顺从", audio: "conform.wav" },
                { word: "conscious", meaning: "有意识的", audio: "conscious.wav" },
                { word: "consent", meaning: "同意", audio: "consent.wav" },
                { word: "convince", meaning: "说服", audio: "convince.wav" },
                { word: "cope", meaning: "应付", audio: "cope.wav" },
                { word: "counsel", meaning: "心理咨询", audio: "counsel.wav" },
                { word: "creative", meaning: "有创造力的", audio: "creative.wav" },
                { word: "critical", meaning: "批判的", audio: "critical.wav" },
                { word: "cruel", meaning: "残忍的", audio: "cruel.wav" },
                { word: "curiosity", meaning: "好奇心", audio: "curiosity.wav" },
                { word: "depress", meaning: "使氮丧", audio: "depress.wav" },
                { word: "desire", meaning: "欲望", audio: "desire.wav" },
                { word: "develop", meaning: "发展", audio: "develop.wav" },
                { word: "diagnose", meaning: "诊断", audio: "diagnose.wav" },
                { word: "discipline", meaning: "纪律", audio: "discipline.wav" },
                { word: "disorder", meaning: "紊乱", audio: "disorder.wav" },
                { word: "distort", meaning: "歪曲", audio: "distort.wav" },
                { word: "distract", meaning: "转移", audio: "distract.wav" },
                { word: "disturb", meaning: "打扰", audio: "disturb.wav" },
                { word: "dominate", meaning: "支配", audio: "dominate.wav" },
                { word: "dream", meaning: "梦", audio: "dream.wav" },
                { word: "drive", meaning: "驾驶", audio: "drive.wav" },
                { word: "ego", meaning: "自我", audio: "ego.wav" },
                { word: "emotion", meaning: "情感", audio: "emotion.wav" },
                { word: "empathy", meaning: "共情; 同理心", audio: "empathy.wav" },
                { word: "environment", meaning: "环境", audio: "environment.wav" },
                { word: "evaluate", meaning: "评价", audio: "evaluate.wav" },
                { word: "experience", meaning: "经验", audio: "experience.wav" },
                { word: "express", meaning: "表达", audio: "express.wav" },
                { word: "fantasy", meaning: "幻想", audio: "fantasy.wav" },
                { word: "fear", meaning: "害怕", audio: "fear.wav" },
                { word: "feedback", meaning: "反馈", audio: "feedback.wav" },
                { word: "focus", meaning: "重点", audio: "focus.wav" },
                { word: "frustrate", meaning: "挫败", audio: "frustrate.wav" },
                { word: "function", meaning: "功能", audio: "function.wav" },
                { word: "genetic", meaning: "遗传的", audio: "genetic.wav" },
                { word: "grief", meaning: "悲伤", audio: "grief.wav" },
                { word: "guilt", meaning: "有罪", audio: "guilt.wav" },
                { word: "habit", meaning: "习惯", audio: "habit.wav" },
                { word: "hallucinate", meaning: "产生幻觉", audio: "hallucinate.wav" },
                { word: "heal", meaning: "愈合", audio: "heal.wav" },
                { word: "identity", meaning: "身份", audio: "identity.wav" },
                { word: "illusion", meaning: "错觉", audio: "illusion.wav" },
                { word: "imagine", meaning: "想象", audio: "imagine.wav" },
                { word: "impulse", meaning: "冲动", audio: "impulse.wav" },
                { word: "influence", meaning: "影响", audio: "influence.wav" },
                { word: "inherit", meaning: "继承", audio: "inherit.wav" },
                { word: "inhibit", meaning: "抑制", audio: "inhibit.wav" },
                { word: "insight", meaning: "洞察力", audio: "insight.wav" },
                { word: "instinct", meaning: "本能", audio: "instinct.wav" },
                { word: "intelligence", meaning: "智力", audio: "intelligence.wav" },
                { word: "interact", meaning: "相互影响", audio: "interact.wav" },
                { word: "interpret", meaning: "解释", audio: "interpret.wav" },
                { word: "intimate", meaning: "亲密的", audio: "intimate.wav" },
                { word: "introvert", meaning: "内向者", audio: "introvert.wav" },
                { word: "intuition", meaning: "直觉", audio: "intuition.wav" },
                { word: "isolate", meaning: "隔离", audio: "isolate.wav" },
                { word: "judge", meaning: "法官", audio: "judge.wav" },
                { word: "learn", meaning: "学习", audio: "learn.wav" },
                { word: "mature", meaning: "成熟", audio: "mature.wav" },
                { word: "meditate", meaning: "冒想", audio: "meditate.wav" },
                { word: "memory", meaning: "记忆", audio: "memory.wav" },
                { word: "mental", meaning: "精神的", audio: "mental.wav" },
                { word: "mood", meaning: "情绪", audio: "mood.wav" },
                { word: "motivate", meaning: "激励", audio: "motivate.wav" },
                { word: "neglect", meaning: "忽视", audio: "neglect.wav" },
                { word: "nerve", meaning: "神经", audio: "nerve.wav" },
                { word: "neurotic", meaning: "神经质的", audio: "neurotic.wav" },
                { word: "norm", meaning: "规范", audio: "norm.wav" },
                { word: "nurture", meaning: "培养", audio: "nurture.wav" },
                { word: "observe", meaning: "观察", audio: "observe.wav" },
                { word: "obsess", meaning: "缠住", audio: "obsess.wav" },
                { word: "perceive", meaning: "感知", audio: "perceive.wav" },
                { word: "personality", meaning: "性格", audio: "personality.wav" },
                { word: "persuade", meaning: "说服", audio: "persuade.wav" },
                { word: "phobia", meaning: "恐惧症", audio: "phobia.wav" },
                { word: "pleasure", meaning: "乐趣", audio: "pleasure.wav" },
                { word: "prejudice", meaning: "偏见", audio: "prejudice.wav" },
                { word: "pressure", meaning: "压力", audio: "pressure.wav" },
                { word: "punish", meaning: "惩治", audio: "punish.wav" },
                { word: "rational", meaning: "理性的", audio: "rational.wav" },
                { word: "recall", meaning: "记起", audio: "recall.wav" },
                { word: "recognize", meaning: "认出", audio: "recognize.wav" },
                { word: "recover", meaning: "恢复", audio: "recover.wav" },
                { word: "reinforce", meaning: "加强", audio: "reinforce.wav" },
                { word: "reject", meaning: "拒绝", audio: "reject.wav" },
                { word: "relate", meaning: "涉及", audio: "relate.wav" },
                { word: "relax", meaning: "放松", audio: "relax.wav" },
                { word: "repress", meaning: "压抑", audio: "repress.wav" },
                { word: "resist", meaning: "抵抗", audio: "resist.wav" },
                { word: "respond", meaning: "回应", audio: "respond.wav" },
                { word: "reward", meaning: "报酬", audio: "reward.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "satisfy", meaning: "满足", audio: "satisfy.wav" },
                { word: "self", meaning: "自己", audio: "self.wav" },
                { word: "sensation", meaning: "感觉", audio: "sensation.wav" },
                { word: "shame", meaning: "耻辱", audio: "shame.wav" },
                { word: "sleep", meaning: "睡觉", audio: "sleep.wav" },
                { word: "social", meaning: "社会的", audio: "social.wav" },
                { word: "stimulate", meaning: "刺激", audio: "stimulate.wav" },
                { word: "stress", meaning: "压力", audio: "stress.wav" },
                { word: "subconscious", meaning: "潜意识的", audio: "subconscious.wav" },
                { word: "suffer", meaning: "遭受", audio: "suffer.wav" },
                { word: "suppress", meaning: "压制", audio: "suppress.wav" },
                { word: "sympathy", meaning: "同情", audio: "sympathy.wav" },
                { word: "syndrome", meaning: "综合症", audio: "syndrome.wav" },
                { word: "temperament", meaning: "气质", audio: "temperament.wav" },
                { word: "tension", meaning: "紧张", audio: "tension.wav" },
                { word: "therapy", meaning: "治疗", audio: "therapy.wav" },
                { word: "thought", meaning: "想法", audio: "thought.wav" },
                { word: "trait", meaning: "特征", audio: "trait.wav" },
                { word: "trauma", meaning: "创伤", audio: "trauma.wav" },
                { word: "trigger", meaning: "扳机", audio: "trigger.wav" },
                { word: "trust", meaning: "相信", audio: "trust.wav" },
                { word: "unconscious", meaning: "无意识", audio: "unconscious.wav" },
                { word: "urge", meaning: "敦促", audio: "urge.wav" },
                { word: "vulnerable", meaning: "脆弱的", audio: "vulnerable.wav" },
                { word: "welfare", meaning: "福利", audio: "welfare.wav" },
                { word: "withdraw", meaning: "提取", audio: "withdraw.wav" }
            ]
        }
    }
});
