registerWordbook('topic_environment', {
    name: "环保生态",
    emoji: "🌍",
    group: 'topic',
    description: "环保、气候变化、可持续发展相关词汇",
    levels: {
        all: {
            name: "🌍 全部",
            words: [
                { word: "absorb", meaning: "吸收", audio: "absorb.wav" },
                { word: "acid", meaning: "酸", audio: "acid.wav" },
                { word: "adapt", meaning: "适应", audio: "adapt.wav" },
                { word: "agriculture", meaning: "农业", audio: "agriculture.wav" },
                { word: "atmosphere", meaning: "大气层", audio: "atmosphere.wav" },
                { word: "biodiversity", meaning: "生物多样性", audio: "biodiversity.wav" },
                { word: "biofuel", meaning: "生物燃料", audio: "biofuel.wav" },
                { word: "biology", meaning: "生物学", audio: "biology.wav" },
                { word: "breed", meaning: "品种", audio: "breed.wav" },
                { word: "bush", meaning: "灌木丛", audio: "bush.wav" },
                { word: "carbon", meaning: "碳", audio: "carbon.wav" },
                { word: "catastrophe", meaning: "灾难", audio: "catastrophe.wav" },
                { word: "chemical", meaning: "化学", audio: "chemical.wav" },
                { word: "clean", meaning: "干净的", audio: "clean.wav" },
                { word: "climate", meaning: "气候", audio: "climate.wav" },
                { word: "coal", meaning: "煤炭", audio: "coal.wav" },
                { word: "conserve", meaning: "养护", audio: "conserve.wav" },
                { word: "consume", meaning: "消耗", audio: "consume.wav" },
                { word: "contaminate", meaning: "污染", audio: "contaminate.wav" },
                { word: "coral", meaning: "珊瑚", audio: "coral.wav" },
                { word: "crop", meaning: "庄稼", audio: "crop.wav" },
                { word: "cultivate", meaning: "培育", audio: "cultivate.wav" },
                { word: "cycle", meaning: "循环", audio: "cycle.wav" },
                { word: "damage", meaning: "损害", audio: "damage.wav" },
                { word: "decay", meaning: "腐烂; 分解", audio: "decay.wav" },
                { word: "deforest", meaning: "砍伐森林", audio: "deforest.wav" },
                { word: "deplete", meaning: "耗尽", audio: "deplete.wav" },
                { word: "desert", meaning: "沙漠", audio: "desert.wav" },
                { word: "disaster", meaning: "灾难", audio: "disaster.wav" },
                { word: "dispose", meaning: "处置", audio: "dispose.wav" },
                { word: "drought", meaning: "干旱", audio: "drought.wav" },
                { word: "dump", meaning: "倾倒", audio: "dump.wav" },
                { word: "dust", meaning: "灰尘", audio: "dust.wav" },
                { word: "earth", meaning: "地球", audio: "earth.wav" },
                { word: "ecology", meaning: "生态学", audio: "ecology.wav" },
                { word: "ecosystem", meaning: "生态系统", audio: "ecosystem.wav" },
                { word: "electric", meaning: "电的", audio: "electric.wav" },
                { word: "emission", meaning: "排放", audio: "emission.wav" },
                { word: "endanger", meaning: "危及", audio: "endanger.wav" },
                { word: "energy", meaning: "能源", audio: "energy.wav" },
                { word: "environment", meaning: "环境", audio: "environment.wav" },
                { word: "erode", meaning: "侵蚀", audio: "erode.wav" },
                { word: "evolve", meaning: "进化", audio: "evolve.wav" },
                { word: "exhaust", meaning: "耗尽", audio: "exhaust.wav" },
                { word: "exploit", meaning: "开发", audio: "exploit.wav" },
                { word: "expose", meaning: "暴露", audio: "expose.wav" },
                { word: "extinct", meaning: "灭绝的", audio: "extinct.wav" },
                { word: "farm", meaning: "农场", audio: "farm.wav" },
                { word: "fertile", meaning: "肥沃的", audio: "fertile.wav" },
                { word: "flood", meaning: "洪水", audio: "flood.wav" },
                { word: "forest", meaning: "森林", audio: "forest.wav" },
                { word: "fossil", meaning: "化石", audio: "fossil.wav" },
                { word: "fuel", meaning: "燃料", audio: "fuel.wav" },
                { word: "glacier", meaning: "冰川", audio: "glacier.wav" },
                { word: "global", meaning: "全球的", audio: "global.wav" },
                { word: "greenhouse", meaning: "温室", audio: "greenhouse.wav" },
                { word: "habitat", meaning: "栖息地", audio: "habitat.wav" },
                { word: "harvest", meaning: "收成", audio: "harvest.wav" },
                { word: "hazard", meaning: "危害; 有害物", audio: "hazard.wav" },
                { word: "heat", meaning: "热", audio: "heat.wav" },
                { word: "hurricane", meaning: "飓风", audio: "hurricane.wav" },
                { word: "hydrogen", meaning: "氢", audio: "hydrogen.wav" },
                { word: "impact", meaning: "影响", audio: "impact.wav" },
                { word: "industrial", meaning: "工业的", audio: "industrial.wav" },
                { word: "insect", meaning: "昆虫", audio: "insect.wav" },
                { word: "irrigate", meaning: "灌溉", audio: "irrigate.wav" },
                { word: "landscape", meaning: "景观", audio: "landscape.wav" },
                { word: "layer", meaning: "层", audio: "layer.wav" },
                { word: "marine", meaning: "海洋", audio: "marine.wav" },
                { word: "meadow", meaning: "草地", audio: "meadow.wav" },
                { word: "mineral", meaning: "矿物", audio: "mineral.wav" },
                { word: "nature", meaning: "自然", audio: "nature.wav" },
                { word: "nuclear", meaning: "核", audio: "nuclear.wav" },
                { word: "ocean", meaning: "海洋", audio: "ocean.wav" },
                { word: "organic", meaning: "有机的", audio: "organic.wav" },
                { word: "ozone", meaning: "臭氧", audio: "ozone.wav" },
                { word: "pesticide", meaning: "杀虫剂", audio: "pesticide.wav" },
                { word: "planet", meaning: "行星", audio: "planet.wav" },
                { word: "plant", meaning: "植物", audio: "plant.wav" },
                { word: "polar", meaning: "极地的", audio: "polar.wav" },
                { word: "pollute", meaning: "污染", audio: "pollute.wav" },
                { word: "population", meaning: "人口", audio: "population.wav" },
                { word: "preserve", meaning: "保存", audio: "preserve.wav" },
                { word: "protect", meaning: "保护", audio: "protect.wav" },
                { word: "purify", meaning: "净化", audio: "purify.wav" },
                { word: "radiation", meaning: "辐射", audio: "radiation.wav" },
                { word: "rainforest", meaning: "雨林", audio: "rainforest.wav" },
                { word: "recycle", meaning: "回收", audio: "recycle.wav" },
                { word: "reduce", meaning: "减少", audio: "reduce.wav" },
                { word: "regulate", meaning: "调节", audio: "regulate.wav" },
                { word: "release", meaning: "释放; 排放", audio: "release.wav" },
                { word: "renewable", meaning: "可再生的", audio: "renewable.wav" },
                { word: "resource", meaning: "资源", audio: "resource.wav" },
                { word: "restore", meaning: "恢复", audio: "restore.wav" },
                { word: "reuse", meaning: "再利用", audio: "reuse.wav" },
                { word: "river", meaning: "河", audio: "river.wav" },
                { word: "rural", meaning: "乡村的", audio: "rural.wav" },
                { word: "sand", meaning: "沙", audio: "sand.wav" },
                { word: "sewage", meaning: "污水", audio: "sewage.wav" },
                { word: "solar", meaning: "太阳的", audio: "solar.wav" },
                { word: "soil", meaning: "土壤", audio: "soil.wav" },
                { word: "species", meaning: "物种", audio: "species.wav" },
                { word: "storm", meaning: "风暴", audio: "storm.wav" },
                { word: "substance", meaning: "物质", audio: "substance.wav" },
                { word: "sustain", meaning: "维持", audio: "sustain.wav" },
                { word: "sustainable", meaning: "可持续的", audio: "sustainable.wav" },
                { word: "temperature", meaning: "温度", audio: "temperature.wav" },
                { word: "threat", meaning: "威胁", audio: "threat.wav" },
                { word: "timber", meaning: "木材", audio: "timber.wav" },
                { word: "tornado", meaning: "龙卷风", audio: "tornado.wav" },
                { word: "toxic", meaning: "有毒的", audio: "toxic.wav" },
                { word: "trap", meaning: "陷阱", audio: "trap.wav" },
                { word: "tree", meaning: "树", audio: "tree.wav" },
                { word: "tropical", meaning: "热带", audio: "tropical.wav" },
                { word: "urban", meaning: "城市的", audio: "urban.wav" },
                { word: "vegetation", meaning: "植被", audio: "vegetation.wav" },
                { word: "volcano", meaning: "火山", audio: "volcano.wav" },
                { word: "warm", meaning: "温暖的", audio: "warm.wav" },
                { word: "waste", meaning: "废物; 废弃物", audio: "waste.wav" },
                { word: "water", meaning: "水", audio: "water.wav" },
                { word: "weather", meaning: "天气", audio: "weather.wav" },
                { word: "wetland", meaning: "湿地", audio: "wetland.wav" },
                { word: "wildlife", meaning: "野生动物", audio: "wildlife.wav" },
                { word: "wind", meaning: "风", audio: "wind.wav" }
            ]
        }
    }
});
