registerWordbook('topic_gaming', {
    name: "游戏电竞",
    emoji: "🎮",
    group: 'topic',
    description: "电子游戏、电竞、游戏机制相关词汇",
    levels: {
        all: {
            name: "🎮 全部",
            words: [
                { word: "achievement", meaning: "成就", audio: "achievement.wav" },
                { word: "action", meaning: "行动", audio: "action.wav" },
                { word: "adventure", meaning: "冒险", audio: "adventure.wav" },
                { word: "aim", meaning: "目的", audio: "aim.wav" },
                { word: "alliance", meaning: "联盟", audio: "alliance.wav" },
                { word: "animation", meaning: "动画片", audio: "animation.wav" },
                { word: "arcade", meaning: "街机", audio: null },
                { word: "arena", meaning: "竞技场", audio: "arena.wav" },
                { word: "armour", meaning: "盔甲", audio: null },
                { word: "assist", meaning: "协助", audio: "assist.wav" },
                { word: "attack", meaning: "攻击", audio: "attack.wav" },
                { word: "avatar", meaning: "头像", audio: null },
                { word: "badge", meaning: "徽章", audio: "badge.wav" },
                { word: "balance", meaning: "平衡", audio: "balance.wav" },
                { word: "ban", meaning: "禁止", audio: "ban.wav" },
                { word: "battle", meaning: "战斗", audio: "battle.wav" },
                { word: "beta", meaning: "测试版", audio: null },
                { word: "bonus", meaning: "奖金", audio: "bonus.wav" },
                { word: "boss", meaning: "老板", audio: "boss.wav" },
                { word: "bot", meaning: "机器人", audio: null },
                { word: "buff", meaning: "增益", audio: null },
                { word: "build", meaning: "建造", audio: "build.wav" },
                { word: "campaign", meaning: "活动", audio: "campaign.wav" },
                { word: "capture", meaning: "捕获", audio: "capture.wav" },
                { word: "casual", meaning: "随意的", audio: "casual.wav" },
                { word: "champion", meaning: "冠军", audio: "champion.wav" },
                { word: "character", meaning: "特点", audio: "character.wav" },
                { word: "cheat", meaning: "欺骗", audio: "cheat.wav" },
                { word: "checkpoint", meaning: "存档点", audio: null },
                { word: "clan", meaning: "战队", audio: null },
                { word: "clash", meaning: "冲突", audio: "clash.wav" },
                { word: "class", meaning: "班级", audio: "class.wav" },
                { word: "classic", meaning: "经典的", audio: "classic.wav" },
                { word: "combat", meaning: "战斗", audio: "combat.wav" },
                { word: "combo", meaning: "连招", audio: null },
                { word: "command", meaning: "命令", audio: "command.wav" },
                { word: "competitive", meaning: "竞争的", audio: "competitive.wav" },
                { word: "console", meaning: "游戏机", audio: null },
                { word: "controller", meaning: "手柄", audio: null },
                { word: "craft", meaning: "工艺", audio: "craft.wav" },
                { word: "crash", meaning: "碰撞", audio: "crash.wav" },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "crew", meaning: "全体人员", audio: "crew.wav" },
                { word: "critical", meaning: "批判的", audio: "critical.wav" },
                { word: "custom", meaning: "风俗", audio: "custom.wav" },
                { word: "damage", meaning: "损害", audio: "damage.wav" },
                { word: "debug", meaning: "调试", audio: null },
                { word: "deck", meaning: "甲板", audio: "deck.wav" },
                { word: "defend", meaning: "保卫", audio: "defend.wav" },
                { word: "demo", meaning: "试玩版", audio: null },
                { word: "deploy", meaning: "部署", audio: "deploy.wav" },
                { word: "dodge", meaning: "闪避", audio: null },
                { word: "download", meaning: "下载", audio: "download.wav" },
                { word: "dragon", meaning: "龙", audio: null },
                { word: "dungeon", meaning: "地牢", audio: null },
                { word: "elite", meaning: "精英", audio: "elite.wav" },
                { word: "emote", meaning: "表情动作", audio: null },
                { word: "enemy", meaning: "敌人", audio: "enemy.wav" },
                { word: "engine", meaning: "引擎", audio: "engine.wav" },
                { word: "epic", meaning: "史诗大片", audio: null },
                { word: "equip", meaning: "装备", audio: "equip.wav" },
                { word: "escape", meaning: "逃脱", audio: "escape.wav" },
                { word: "event", meaning: "事件", audio: "event.wav" },
                { word: "execute", meaning: "执行", audio: "execute.wav" },
                { word: "expand", meaning: "扩张", audio: "expand.wav" },
                { word: "experience", meaning: "经验", audio: "experience.wav" },
                { word: "exploit", meaning: "开发", audio: "exploit.wav" },
                { word: "explore", meaning: "探索", audio: "explore.wav" },
                { word: "fantasy", meaning: "幻想", audio: "fantasy.wav" },
                { word: "fight", meaning: "斗争", audio: "fight.wav" },
                { word: "final", meaning: "最终的", audio: "final.wav" },
                { word: "fire", meaning: "火", audio: "fire.wav" },
                { word: "forge", meaning: "锻造", audio: "forge.wav" },
                { word: "frame", meaning: "框架", audio: "frame.wav" },
                { word: "fury", meaning: "狂怒", audio: null },
                { word: "gear", meaning: "齿轮", audio: "gear.wav" },
                { word: "glitch", meaning: "漏洞", audio: null },
                { word: "grind", meaning: "研磨", audio: "grind.wav" },
                { word: "guild", meaning: "公会", audio: null },
                { word: "health", meaning: "健康", audio: "health.wav" },
                { word: "hero", meaning: "英雄", audio: "hero.wav" },
                { word: "hunt", meaning: "打猎", audio: "hunt.wav" },
                { word: "inventory", meaning: "背包", audio: null },
                { word: "item", meaning: "物品", audio: "item.wav" },
                { word: "jump", meaning: "跳", audio: "jump.wav" },
                { word: "kill", meaning: "杀", audio: "kill.wav" },
                { word: "kingdom", meaning: "王国", audio: "kingdom.wav" },
                { word: "launch", meaning: "发射", audio: "launch.wav" },
                { word: "league", meaning: "联盟", audio: "league.wav" },
                { word: "legend", meaning: "传奇", audio: "legend.wav" },
                { word: "level", meaning: "等级", audio: "level.wav" },
                { word: "lobby", meaning: "大堂", audio: "lobby.wav" },
                { word: "loot", meaning: "战利品", audio: null },
                { word: "magic", meaning: "魔法", audio: "magic.wav" },
                { word: "map", meaning: "地图", audio: "map.wav" },
                { word: "master", meaning: "掌握", audio: "master.wav" },
                { word: "match", meaning: "匹配", audio: "match.wav" },
                { word: "mission", meaning: "使命", audio: "mission.wav" },
                { word: "mode", meaning: "模式", audio: "mode.wav" },
                { word: "monster", meaning: "怪物", audio: "monster.wav" },
                { word: "mount", meaning: "山", audio: "mount.wav" },
                { word: "multiplayer", meaning: "多人游戏", audio: null },
                { word: "nerf", meaning: "削弱", audio: null },
                { word: "objective", meaning: "客观的", audio: "objective.wav" },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "opponent", meaning: "对手", audio: "opponent.wav" },
                { word: "patch", meaning: "修补", audio: "patch.wav" },
                { word: "penalty", meaning: "惩罚", audio: "penalty.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "play", meaning: "玩", audio: "play.wav" },
                { word: "player", meaning: "玩家", audio: "player.wav" },
                { word: "point", meaning: "观点", audio: "point.wav" },
                { word: "portal", meaning: "门户网站", audio: null },
                { word: "power", meaning: "力量", audio: "power.wav" },
                { word: "quest", meaning: "探索", audio: null },
                { word: "rage", meaning: "愤怒", audio: null },
                { word: "raid", meaning: "突袭", audio: null },
                { word: "rank", meaning: "秩", audio: "rank.wav" },
                { word: "realm", meaning: "领域", audio: null },
                { word: "release", meaning: "发布", audio: "release.wav" },
                { word: "replay", meaning: "回放", audio: null },
                { word: "respawn", meaning: "复活", audio: null },
                { word: "reward", meaning: "报酬", audio: "reward.wav" },
                { word: "rival", meaning: "竞争对手", audio: "rival.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "round", meaning: "圆形的", audio: "round.wav" },
                { word: "rush", meaning: "匆忙", audio: "rush.wav" },
                { word: "score", meaning: "分数", audio: "score.wav" },
                { word: "server", meaning: "服务器", audio: null },
                { word: "shield", meaning: "盾牌", audio: null },
                { word: "shoot", meaning: "射击", audio: "shoot.wav" },
                { word: "siege", meaning: "围攻", audio: null },
                { word: "skill", meaning: "技能", audio: "skill.wav" },
                { word: "snipe", meaning: "狙击", audio: null },
                { word: "solo", meaning: "独奏", audio: null },
                { word: "spawn", meaning: "生成", audio: null },
                { word: "speed", meaning: "速度", audio: "speed.wav" },
                { word: "spell", meaning: "拼写", audio: "spell.wav" },
                { word: "sprint", meaning: "冲刺", audio: null },
                { word: "stage", meaning: "阶段", audio: "stage.wav" },
                { word: "stamina", meaning: "耐力", audio: null },
                { word: "strategy", meaning: "战略", audio: "strategy.wav" },
                { word: "stream", meaning: "溪流", audio: "stream.wav" },
                { word: "strike", meaning: "罢工", audio: "strike.wav" },
                { word: "summon", meaning: "召唤", audio: null },
                { word: "survival", meaning: "生存", audio: "survival.wav" },
                { word: "sword", meaning: "剑", audio: null },
                { word: "talent", meaning: "天赋", audio: "talent.wav" },
                { word: "target", meaning: "目标", audio: "target.wav" },
                { word: "team", meaning: "团队", audio: "team.wav" },
                { word: "token", meaning: "令牌", audio: null },
                { word: "tower", meaning: "塔", audio: "tower.wav" },
                { word: "trade", meaning: "贸易", audio: "trade.wav" },
                { word: "trap", meaning: "陷阱", audio: "trap.wav" },
                { word: "treasure", meaning: "宝藏", audio: null },
                { word: "trigger", meaning: "扳机", audio: "trigger.wav" },
                { word: "trophy", meaning: "奖杯", audio: "trophy.wav" },
                { word: "tutorial", meaning: "新手教程", audio: null },
                { word: "ultimate", meaning: "最终的", audio: "ultimate.wav" },
                { word: "unlock", meaning: "解锁", audio: null },
                { word: "update", meaning: "更新", audio: "update.wav" },
                { word: "upgrade", meaning: "升级", audio: "upgrade.wav" },
                { word: "versus", meaning: "对", audio: "versus.wav" },
                { word: "victory", meaning: "胜利", audio: "victory.wav" },
                { word: "virtual", meaning: "虚拟的", audio: "virtual.wav" },
                { word: "warrior", meaning: "战士", audio: "warrior.wav" },
                { word: "weapon", meaning: "武器", audio: "weapon.wav" },
                { word: "wizard", meaning: "巫师", audio: null },
                { word: "zone", meaning: "区", audio: "zone.wav" }
            ]
        }
    }
});
