registerWordbook('topic_space', {
    name: "太空航天",
    emoji: "🚀",
    group: 'topic',
    description: "天文、航天器、宇宙现象相关词汇",
    levels: {
        all: {
            name: "🚀 全部",
            words: [
                { word: "altitude", meaning: "海拔", audio: "altitude.wav" },
                { word: "antenna", meaning: "天线", audio: "antenna.wav" },
                { word: "asteroid", meaning: "小行星", audio: "asteroid.wav" },
                { word: "astronaut", meaning: "宇航员", audio: "astronaut.wav" },
                { word: "astronomer", meaning: "天文学家", audio: "astronomer.wav" },
                { word: "astronomy", meaning: "天文学", audio: "astronomy.wav" },
                { word: "atmosphere", meaning: "大气层", audio: "atmosphere.wav" },
                { word: "axis", meaning: "轴", audio: "axis.wav" },
                { word: "beacon", meaning: "信标", audio: "beacon.wav" },
                { word: "blast", meaning: "爆炸", audio: "blast.wav" },
                { word: "booster", meaning: "助推器", audio: "booster.wav" },
                { word: "capsule", meaning: "太空舱", audio: "capsule.wav" },
                { word: "cargo", meaning: "货物", audio: "cargo.wav" },
                { word: "celestial", meaning: "天体的", audio: "celestial.wav" },
                { word: "cluster", meaning: "簇", audio: "cluster.wav" },
                { word: "comet", meaning: "彗星", audio: "comet.wav" },
                { word: "commander", meaning: "指挥官", audio: "commander.wav" },
                { word: "communication", meaning: "沟通", audio: "communication.wav" },
                { word: "constellation", meaning: "星座", audio: "constellation.wav" },
                { word: "core", meaning: "核", audio: "core.wav" },
                { word: "cosmic", meaning: "宇宙的", audio: "cosmic.wav" },
                { word: "cosmos", meaning: "宇宙", audio: "cosmos.wav" },
                { word: "crater", meaning: "降石坑", audio: "crater.wav" },
                { word: "crew", meaning: "机组; 宇航员团队", audio: "crew.wav" },
                { word: "debris", meaning: "碎片", audio: "debris.wav" },
                { word: "deploy", meaning: "部署", audio: "deploy.wav" },
                { word: "descent", meaning: "下降; 降落", audio: "descent.wav" },
                { word: "detect", meaning: "探测", audio: "detect.wav" },
                { word: "dimension", meaning: "维度", audio: "dimension.wav" },
                { word: "discovery", meaning: "发现", audio: "discovery.wav" },
                { word: "dock", meaning: "对接", audio: "dock.wav" },
                { word: "drift", meaning: "漂移", audio: "drift.wav" },
                { word: "dust", meaning: "灰尘", audio: "dust.wav" },
                { word: "dwarf", meaning: "矮星", audio: "dwarf.wav" },
                { word: "eclipse", meaning: "日食; 月食", audio: "eclipse.wav" },
                { word: "emission", meaning: "排放", audio: "emission.wav" },
                { word: "energy", meaning: "能量", audio: "energy.wav" },
                { word: "engineer", meaning: "工程师", audio: "engineer.wav" },
                { word: "equator", meaning: "赤道", audio: "equator.wav" },
                { word: "expand", meaning: "扩张", audio: "expand.wav" },
                { word: "experiment", meaning: "实验", audio: "experiment.wav" },
                { word: "exploration", meaning: "勘探", audio: "exploration.wav" },
                { word: "explorer", meaning: "探索者", audio: "explorer.wav" },
                { word: "explosion", meaning: "爆炸", audio: "explosion.wav" },
                { word: "frequency", meaning: "频率", audio: "frequency.wav" },
                { word: "fuel", meaning: "燃料", audio: "fuel.wav" },
                { word: "galaxy", meaning: "银河系", audio: "galaxy.wav" },
                { word: "gas", meaning: "气体", audio: "gas.wav" },
                { word: "gravity", meaning: "重力", audio: "gravity.wav" },
                { word: "habitat", meaning: "栖息地", audio: "habitat.wav" },
                { word: "heat", meaning: "热", audio: "heat.wav" },
                { word: "horizon", meaning: "地平线", audio: "horizon.wav" },
                { word: "hydrogen", meaning: "氢", audio: "hydrogen.wav" },
                { word: "impact", meaning: "影响", audio: "impact.wav" },
                { word: "infrared", meaning: "红外线", audio: "infrared.wav" },
                { word: "instrument", meaning: "仪器", audio: "instrument.wav" },
                { word: "interstellar", meaning: "星际的", audio: "interstellar.wav" },
                { word: "ion", meaning: "离子", audio: "ion.wav" },
                { word: "isolate", meaning: "隔离", audio: "isolate.wav" },
                { word: "launch", meaning: "发射", audio: "launch.wav" },
                { word: "layer", meaning: "层", audio: "layer.wav" },
                { word: "light", meaning: "光", audio: "light.wav" },
                { word: "lunar", meaning: "月球的", audio: "lunar.wav" },
                { word: "magnitude", meaning: "星等; 量级", audio: "magnitude.wav" },
                { word: "manoeuvre", meaning: "操纵", audio: "manoeuvre.wav" },
                { word: "mars", meaning: "火星", audio: "mars.wav" },
                { word: "mass", meaning: "质量", audio: "mass.wav" },
                { word: "mercury", meaning: "水星", audio: "mercury.wav" },
                { word: "meteor", meaning: "流星", audio: "meteor.wav" },
                { word: "meteorite", meaning: "降石", audio: "meteorite.wav" },
                { word: "mission", meaning: "任务; 飞行任务", audio: "mission.wav" },
                { word: "module", meaning: "舱; 太空舱模块", audio: "module.wav" },
                { word: "momentum", meaning: "动量", audio: "momentum.wav" },
                { word: "monitor", meaning: "监控", audio: "monitor.wav" },
                { word: "moon", meaning: "月亮", audio: "moon.wav" },
                { word: "navigate", meaning: "导航", audio: "navigate.wav" },
                { word: "nebula", meaning: "星云", audio: "nebula.wav" },
                { word: "neptune", meaning: "海王星", audio: "neptune.wav" },
                { word: "nuclear", meaning: "核", audio: "nuclear.wav" },
                { word: "observe", meaning: "观察", audio: "observe.wav" },
                { word: "orbit", meaning: "轨道", audio: "orbit.wav" },
                { word: "oxygen", meaning: "氧", audio: "oxygen.wav" },
                { word: "particle", meaning: "粒子", audio: "particle.wav" },
                { word: "payload", meaning: "有效载荷", audio: "payload.wav" },
                { word: "phase", meaning: "阶段", audio: "phase.wav" },
                { word: "planet", meaning: "行星", audio: "planet.wav" },
                { word: "plasma", meaning: "等离子体", audio: "plasma.wav" },
                { word: "polar", meaning: "极地的; 极轨的", audio: "polar.wav" },
                { word: "probe", meaning: "探测", audio: "probe.wav" },
                { word: "propel", meaning: "推进", audio: "propel.wav" },
                { word: "pulse", meaning: "脉冲", audio: "pulse.wav" },
                { word: "quantum", meaning: "量子", audio: "quantum.wav" },
                { word: "radar", meaning: "雷达", audio: "radar.wav" },
                { word: "radiation", meaning: "辐射", audio: "radiation.wav" },
                { word: "radio", meaning: "无线电", audio: "radio.wav" },
                { word: "reentry", meaning: "重返大气层", audio: "reentry.wav" },
                { word: "reflect", meaning: "反射", audio: "reflect.wav" },
                { word: "remote", meaning: "遥远的; 远程的", audio: "remote.wav" },
                { word: "research", meaning: "研究", audio: "research.wav" },
                { word: "revolve", meaning: "旋转", audio: "revolve.wav" },
                { word: "rocket", meaning: "火箭", audio: "rocket.wav" },
                { word: "rotate", meaning: "旋转", audio: "rotate.wav" },
                { word: "rover", meaning: "漫游车", audio: "rover.wav" },
                { word: "satellite", meaning: "卫星", audio: "satellite.wav" },
                { word: "saturn", meaning: "土星", audio: "saturn.wav" },
                { word: "shuttle", meaning: "航天飞机", audio: "shuttle.wav" },
                { word: "signal", meaning: "信号", audio: "signal.wav" },
                { word: "simulate", meaning: "模拟", audio: "simulate.wav" },
                { word: "solar", meaning: "太阳的", audio: "solar.wav" },
                { word: "spacecraft", meaning: "航天器", audio: "spacecraft.wav" },
                { word: "spectrum", meaning: "光谱", audio: "spectrum.wav" },
                { word: "sphere", meaning: "球体", audio: "sphere.wav" },
                { word: "star", meaning: "星星", audio: "star.wav" },
                { word: "station", meaning: "空间站", audio: "station.wav" },
                { word: "stellar", meaning: "恒星的", audio: "stellar.wav" },
                { word: "sun", meaning: "太阳", audio: "sun.wav" },
                { word: "surface", meaning: "表面", audio: "surface.wav" },
                { word: "survey", meaning: "探测; 勘测", audio: "survey.wav" },
                { word: "telescope", meaning: "望远镜", audio: "telescope.wav" },
                { word: "temperature", meaning: "温度", audio: "temperature.wav" },
                { word: "thrust", meaning: "推力", audio: "thrust.wav" },
                { word: "trajectory", meaning: "轨迹", audio: "trajectory.wav" },
                { word: "transmit", meaning: "发送", audio: "transmit.wav" },
                { word: "universe", meaning: "宇宙", audio: "universe.wav" },
                { word: "vacuum", meaning: "真空", audio: "vacuum.wav" },
                { word: "velocity", meaning: "速度", audio: "velocity.wav" },
                { word: "venus", meaning: "金星", audio: "venus.wav" },
                { word: "void", meaning: "虚空", audio: "void.wav" },
                { word: "volcano", meaning: "火山", audio: "volcano.wav" },
                { word: "wave", meaning: "波", audio: "wave.wav" },
                { word: "weightless", meaning: "失重的", audio: "weightless.wav" },
                { word: "zero", meaning: "零数", audio: "zero.wav" }
            ]
        }
    }
});
