registerWordbook('topic_math', {
    name: "数学逻辑",
    emoji: "📐",
    group: 'topic',
    description: "数学术语、几何、统计相关词汇",
    levels: {
        all: {
            name: "📐 全部",
            words: [
                { word: "absolute", meaning: "绝对", audio: "absolute.wav" },
                { word: "abstract", meaning: "抽象的", audio: "abstract.wav" },
                { word: "add", meaning: "添加", audio: "add.wav" },
                { word: "algebra", meaning: "代数", audio: "algebra.wav" },
                { word: "angle", meaning: "角度", audio: "angle.wav" },
                { word: "approximate", meaning: "近似的", audio: "approximate.wav" },
                { word: "area", meaning: "区域", audio: "area.wav" },
                { word: "average", meaning: "平均的", audio: "average.wav" },
                { word: "axis", meaning: "轴", audio: "axis.wav" },
                { word: "base", meaning: "根据", audio: "base.wav" },
                { word: "binary", meaning: "二进制", audio: "binary.wav" },
                { word: "calculate", meaning: "计算", audio: "calculate.wav" },
                { word: "calculus", meaning: "微积分", audio: "calculus.wav" },
                { word: "capacity", meaning: "容量", audio: "capacity.wav" },
                { word: "circle", meaning: "圆圈", audio: "circle.wav" },
                { word: "coefficient", meaning: "系数", audio: "coefficient.wav" },
                { word: "complex", meaning: "复杂的", audio: "complex.wav" },
                { word: "compute", meaning: "计算", audio: "compute.wav" },
                { word: "cone", meaning: "圆锥", audio: "cone.wav" },
                { word: "constant", meaning: "持续的", audio: "constant.wav" },
                { word: "converge", meaning: "收敛", audio: "converge.wav" },
                { word: "coordinate", meaning: "协调", audio: "coordinate.wav" },
                { word: "correlation", meaning: "相关性", audio: "correlation.wav" },
                { word: "cosine", meaning: "余弦", audio: "cosine.wav" },
                { word: "cube", meaning: "立方体", audio: "cube.wav" },
                { word: "curve", meaning: "曲线", audio: "curve.wav" },
                { word: "cylinder", meaning: "圆柱体", audio: "cylinder.wav" },
                { word: "data", meaning: "数据", audio: "data.wav" },
                { word: "decimal", meaning: "小数", audio: "decimal.wav" },
                { word: "deduce", meaning: "推导", audio: "deduce.wav" },
                { word: "define", meaning: "定义", audio: "define.wav" },
                { word: "degree", meaning: "程度", audio: "degree.wav" },
                { word: "denominator", meaning: "分母", audio: "denominator.wav" },
                { word: "derive", meaning: "派生", audio: "derive.wav" },
                { word: "diagonal", meaning: "对角线", audio: "diagonal.wav" },
                { word: "diameter", meaning: "直径", audio: "diameter.wav" },
                { word: "digit", meaning: "数字", audio: "digit.wav" },
                { word: "dimension", meaning: "方面", audio: "dimension.wav" },
                { word: "distribute", meaning: "分发", audio: "distribute.wav" },
                { word: "divide", meaning: "划分", audio: "divide.wav" },
                { word: "domain", meaning: "领域", audio: "domain.wav" },
                { word: "element", meaning: "元素", audio: "element.wav" },
                { word: "equal", meaning: "平等的", audio: "equal.wav" },
                { word: "equation", meaning: "方程", audio: "equation.wav" },
                { word: "estimate", meaning: "估计", audio: "estimate.wav" },
                { word: "evaluate", meaning: "评价", audio: "evaluate.wav" },
                { word: "even", meaning: "甚至", audio: "even.wav" },
                { word: "exponent", meaning: "指数", audio: "exponent.wav" },
                { word: "expression", meaning: "表达", audio: "expression.wav" },
                { word: "factor", meaning: "因素", audio: "factor.wav" },
                { word: "figure", meaning: "数字", audio: "figure.wav" },
                { word: "formula", meaning: "公式", audio: "formula.wav" },
                { word: "fraction", meaning: "分数", audio: "fraction.wav" },
                { word: "function", meaning: "功能", audio: "function.wav" },
                { word: "geometry", meaning: "几何学", audio: "geometry.wav" },
                { word: "gradient", meaning: "渐变", audio: "gradient.wav" },
                { word: "graph", meaning: "图", audio: "graph.wav" },
                { word: "hypotenuse", meaning: "斜边", audio: "hypotenuse.wav" },
                { word: "hypothesis", meaning: "假设", audio: "hypothesis.wav" },
                { word: "index", meaning: "指数", audio: "index.wav" },
                { word: "inequality", meaning: "不等式", audio: "inequality.wav" },
                { word: "infinite", meaning: "无穷的", audio: "infinite.wav" },
                { word: "integer", meaning: "整数", audio: "integer.wav" },
                { word: "integrate", meaning: "整合", audio: "integrate.wav" },
                { word: "intercept", meaning: "截距", audio: "intercept.wav" },
                { word: "intersect", meaning: "相交", audio: "intersect.wav" },
                { word: "interval", meaning: "间隔", audio: "interval.wav" },
                { word: "inverse", meaning: "逆", audio: "inverse.wav" },
                { word: "irrational", meaning: "无理数的", audio: "irrational.wav" },
                { word: "linear", meaning: "线性", audio: "linear.wav" },
                { word: "logarithm", meaning: "对数", audio: "logarithm.wav" },
                { word: "logic", meaning: "逻辑", audio: "logic.wav" },
                { word: "magnitude", meaning: "震级", audio: "magnitude.wav" },
                { word: "matrix", meaning: "矩阵", audio: "matrix.wav" },
                { word: "maximum", meaning: "最大限度", audio: "maximum.wav" },
                { word: "mean", meaning: "意思是", audio: "mean.wav" },
                { word: "measure", meaning: "措施", audio: "measure.wav" },
                { word: "median", meaning: "中位数", audio: "median.wav" },
                { word: "method", meaning: "方法", audio: "method.wav" },
                { word: "minimum", meaning: "最低限度", audio: "minimum.wav" },
                { word: "minus", meaning: "减", audio: "minus.wav" },
                { word: "mode", meaning: "模式", audio: "mode.wav" },
                { word: "model", meaning: "模型", audio: "model.wav" },
                { word: "multiple", meaning: "多种的", audio: "multiple.wav" },
                { word: "multiply", meaning: "乘", audio: "multiply.wav" },
                { word: "negative", meaning: "消极的", audio: "negative.wav" },
                { word: "odd", meaning: "奇怪的", audio: "odd.wav" },
                { word: "operation", meaning: "手术", audio: "operation.wav" },
                { word: "parallel", meaning: "平行线", audio: "parallel.wav" },
                { word: "pattern", meaning: "图案", audio: "pattern.wav" },
                { word: "percent", meaning: "百分比", audio: "percent.wav" },
                { word: "perimeter", meaning: "周长", audio: "perimeter.wav" },
                { word: "perpendicular", meaning: "垂直的", audio: "perpendicular.wav" },
                { word: "plane", meaning: "飞机", audio: "plane.wav" },
                { word: "plot", meaning: "阴谋", audio: "plot.wav" },
                { word: "plus", meaning: "加", audio: "plus.wav" },
                { word: "polygon", meaning: "多边形", audio: "polygon.wav" },
                { word: "positive", meaning: "积极的", audio: "positive.wav" },
                { word: "power", meaning: "力量", audio: "power.wav" },
                { word: "prime", meaning: "主要的", audio: "prime.wav" },
                { word: "probability", meaning: "可能性", audio: "probability.wav" },
                { word: "product", meaning: "产品", audio: "product.wav" },
                { word: "proof", meaning: "证明", audio: "proof.wav" },
                { word: "proportion", meaning: "部分", audio: "proportion.wav" },
                { word: "radius", meaning: "半径", audio: "radius.wav" },
                { word: "random", meaning: "随机的", audio: "random.wav" },
                { word: "range", meaning: "范围", audio: "range.wav" },
                { word: "ratio", meaning: "比率", audio: "ratio.wav" },
                { word: "rational", meaning: "理性的", audio: "rational.wav" },
                { word: "rectangle", meaning: "矩形", audio: "rectangle.wav" },
                { word: "remainder", meaning: "剩余", audio: "remainder.wav" },
                { word: "root", meaning: "根", audio: "root.wav" },
                { word: "rotate", meaning: "旋转", audio: "rotate.wav" },
                { word: "round", meaning: "圆形的", audio: "round.wav" },
                { word: "sample", meaning: "样本", audio: "sample.wav" },
                { word: "sequence", meaning: "顺序", audio: "sequence.wav" },
                { word: "set", meaning: "放", audio: "set.wav" },
                { word: "solve", meaning: "解决", audio: "solve.wav" },
                { word: "sphere", meaning: "球体", audio: "sphere.wav" },
                { word: "square", meaning: "正方形", audio: "square.wav" },
                { word: "statistic", meaning: "统计", audio: "statistic.wav" },
                { word: "subtract", meaning: "减去", audio: "subtract.wav" },
                { word: "sum", meaning: "和", audio: "sum.wav" },
                { word: "surface", meaning: "表面", audio: "surface.wav" },
                { word: "symbol", meaning: "象征", audio: "symbol.wav" },
                { word: "symmetry", meaning: "对称", audio: "symmetry.wav" },
                { word: "tangent", meaning: "正切", audio: "tangent.wav" },
                { word: "theorem", meaning: "定理", audio: "theorem.wav" },
                { word: "theory", meaning: "理论", audio: "theory.wav" },
                { word: "total", meaning: "全部的", audio: "total.wav" },
                { word: "triangle", meaning: "三角形", audio: "triangle.wav" },
                { word: "value", meaning: "价值", audio: "value.wav" },
                { word: "variable", meaning: "变量", audio: "variable.wav" },
                { word: "vector", meaning: "向量", audio: "vector.wav" },
                { word: "volume", meaning: "体积", audio: "volume.wav" }
            ]
        }
    }
});
