registerWordbook('topic_art', {
    name: "艺术设计",
    emoji: "🎨",
    group: 'topic',
    description: "绘画、设计、美学相关词汇",
    levels: {
        all: {
            name: "🎨 全部",
            words: [
                { word: "abstract", meaning: "抽象的", audio: "abstract.wav" },
                { word: "acrylic", meaning: "丙烯颜料", audio: "acrylic.wav" },
                { word: "aesthetic", meaning: "审美的", audio: "aesthetic.wav" },
                { word: "angle", meaning: "角度", audio: "angle.wav" },
                { word: "architect", meaning: "建筑师", audio: "architect.wav" },
                { word: "artistic", meaning: "艺术的", audio: "artistic.wav" },
                { word: "assemble", meaning: "集合", audio: "assemble.wav" },
                { word: "balance", meaning: "平衡", audio: "balance.wav" },
                { word: "bold", meaning: "大胆的", audio: "bold.wav" },
                { word: "border", meaning: "边界", audio: "border.wav" },
                { word: "brush", meaning: "刷子", audio: "brush.wav" },
                { word: "canvas", meaning: "帆布", audio: "canvas.wav" },
                { word: "carve", meaning: "雕刻", audio: "carve.wav" },
                { word: "ceramic", meaning: "陶瓷", audio: "ceramic.wav" },
                { word: "charcoal", meaning: "木炭", audio: "charcoal.wav" },
                { word: "clay", meaning: "黏土", audio: "clay.wav" },
                { word: "collage", meaning: "拼贴画", audio: "collage.wav" },
                { word: "colour", meaning: "颜色", audio: "colour.wav" },
                { word: "commission", meaning: "委员会", audio: "commission.wav" },
                { word: "compose", meaning: "撰写", audio: "compose.wav" },
                { word: "composition", meaning: "作品", audio: "composition.wav" },
                { word: "concept", meaning: "概念", audio: "concept.wav" },
                { word: "contrast", meaning: "对比", audio: "contrast.wav" },
                { word: "craft", meaning: "工艺", audio: "craft.wav" },
                { word: "creative", meaning: "有创造力的", audio: "creative.wav" },
                { word: "critic", meaning: "评论家", audio: "critic.wav" },
                { word: "culture", meaning: "文化", audio: "culture.wav" },
                { word: "curve", meaning: "曲线", audio: "curve.wav" },
                { word: "decorate", meaning: "装饰", audio: "decorate.wav" },
                { word: "depth", meaning: "深度", audio: "depth.wav" },
                { word: "design", meaning: "设计", audio: "design.wav" },
                { word: "detail", meaning: "细节", audio: "detail.wav" },
                { word: "dimension", meaning: "方面", audio: "dimension.wav" },
                { word: "display", meaning: "展示", audio: "display.wav" },
                { word: "draft", meaning: "草稿", audio: "draft.wav" },
                { word: "draw", meaning: "画", audio: "draw.wav" },
                { word: "dye", meaning: "染料", audio: "dye.wav" },
                { word: "element", meaning: "元素", audio: "element.wav" },
                { word: "engrave", meaning: "雕刻", audio: "engrave.wav" },
                { word: "exhibit", meaning: "展览", audio: "exhibit.wav" },
                { word: "exhibition", meaning: "展览", audio: "exhibition.wav" },
                { word: "express", meaning: "表达", audio: "express.wav" },
                { word: "fabric", meaning: "织物", audio: "fabric.wav" },
                { word: "fade", meaning: "褪色", audio: "fade.wav" },
                { word: "figure", meaning: "数字", audio: "figure.wav" },
                { word: "font", meaning: "字体", audio: "font.wav" },
                { word: "form", meaning: "形式", audio: "form.wav" },
                { word: "frame", meaning: "框架", audio: "frame.wav" },
                { word: "fresco", meaning: "壁画", audio: "fresco.wav" },
                { word: "gallery", meaning: "画廊", audio: "gallery.wav" },
                { word: "glaze", meaning: "上釉", audio: "glaze.wav" },
                { word: "gradient", meaning: "渐变", audio: "gradient.wav" },
                { word: "graphic", meaning: "形象的", audio: "graphic.wav" },
                { word: "harmony", meaning: "和谐", audio: "harmony.wav" },
                { word: "heritage", meaning: "遗产", audio: "heritage.wav" },
                { word: "highlight", meaning: "强调", audio: "highlight.wav" },
                { word: "hue", meaning: "色调", audio: "hue.wav" },
                { word: "icon", meaning: "图标", audio: "icon.wav" },
                { word: "illustrate", meaning: "阐明", audio: "illustrate.wav" },
                { word: "image", meaning: "图像", audio: "image.wav" },
                { word: "imagination", meaning: "想像力", audio: "imagination.wav" },
                { word: "impression", meaning: "印象", audio: "impression.wav" },
                { word: "ink", meaning: "墨水", audio: "ink.wav" },
                { word: "inspire", meaning: "启发", audio: "inspire.wav" },
                { word: "install", meaning: "安装", audio: "install.wav" },
                { word: "interior", meaning: "内部的", audio: "interior.wav" },
                { word: "landscape", meaning: "景观", audio: "landscape.wav" },
                { word: "layer", meaning: "层", audio: "layer.wav" },
                { word: "layout", meaning: "布局", audio: "layout.wav" },
                { word: "light", meaning: "光", audio: "light.wav" },
                { word: "line", meaning: "线", audio: "line.wav" },
                { word: "marble", meaning: "大理石", audio: "marble.wav" },
                { word: "masterpiece", meaning: "杰作", audio: "masterpiece.wav" },
                { word: "medium", meaning: "中等的", audio: "medium.wav" },
                { word: "miniature", meaning: "微缩模型", audio: "miniature.wav" },
                { word: "mix", meaning: "混合", audio: "mix.wav" },
                { word: "modern", meaning: "现代的", audio: "modern.wav" },
                { word: "mosaic", meaning: "马赛克", audio: "mosaic.wav" },
                { word: "mould", meaning: "塑造", audio: "mould.wav" },
                { word: "mural", meaning: "壁画", audio: "mural.wav" },
                { word: "museum", meaning: "博物馆", audio: "museum.wav" },
                { word: "nude", meaning: "裸体画", audio: "nude.wav" },
                { word: "oil", meaning: "油", audio: "oil.wav" },
                { word: "original", meaning: "原来的", audio: "original.wav" },
                { word: "ornament", meaning: "装饰品", audio: "ornament.wav" },
                { word: "outline", meaning: "大纲", audio: "outline.wav" },
                { word: "paint", meaning: "画", audio: "paint.wav" },
                { word: "palette", meaning: "调色板", audio: "palette.wav" },
                { word: "pastel", meaning: "粉彩", audio: "pastel.wav" },
                { word: "pattern", meaning: "图案", audio: "pattern.wav" },
                { word: "perspective", meaning: "看法", audio: "perspective.wav" },
                { word: "photograph", meaning: "照片", audio: "photograph.wav" },
                { word: "pigment", meaning: "颜料", audio: "pigment.wav" },
                { word: "portfolio", meaning: "投资组合", audio: "portfolio.wav" },
                { word: "portrait", meaning: "肖像", audio: "portrait.wav" },
                { word: "pottery", meaning: "陶器", audio: "pottery.wav" },
                { word: "print", meaning: "打印", audio: "print.wav" },
                { word: "proportion", meaning: "部分", audio: "proportion.wav" },
                { word: "render", meaning: "渲染", audio: "render.wav" },
                { word: "replica", meaning: "复制品", audio: "replica.wav" },
                { word: "restore", meaning: "恢复", audio: "restore.wav" },
                { word: "saturate", meaning: "饱和", audio: "saturate.wav" },
                { word: "scale", meaning: "规模", audio: "scale.wav" },
                { word: "sculpt", meaning: "雕塑", audio: "sculpt.wav" },
                { word: "sculpture", meaning: "雕塑", audio: "sculpture.wav" },
                { word: "shade", meaning: "阴影", audio: "shade.wav" },
                { word: "shadow", meaning: "影子", audio: "shadow.wav" },
                { word: "shape", meaning: "形状", audio: "shape.wav" },
                { word: "sketch", meaning: "素描", audio: "sketch.wav" },
                { word: "studio", meaning: "工作室", audio: "studio.wav" },
                { word: "style", meaning: "风格", audio: "style.wav" },
                { word: "symbol", meaning: "象征", audio: "symbol.wav" },
                { word: "symmetry", meaning: "对称", audio: "symmetry.wav" },
                { word: "technique", meaning: "技术", audio: "technique.wav" },
                { word: "texture", meaning: "质地", audio: "texture.wav" },
                { word: "theme", meaning: "主题", audio: "theme.wav" },
                { word: "tint", meaning: "色调", audio: "tint.wav" },
                { word: "tone", meaning: "语气", audio: "tone.wav" },
                { word: "trace", meaning: "痕迹", audio: "trace.wav" },
                { word: "typography", meaning: "排版", audio: "typography.wav" },
                { word: "unique", meaning: "独特的", audio: "unique.wav" },
                { word: "visual", meaning: "视觉的", audio: "visual.wav" },
                { word: "vivid", meaning: "鲜艳的", audio: "vivid.wav" },
                { word: "watercolour", meaning: "水彩画", audio: "watercolour.wav" }
            ]
        }
    }
});
