registerWordbook('topic_gaming', {
    name: "游戏电竞",
    emoji: "🎮",
    group: 'topic',
    description: "电子游戏、电竞、游戏机制相关词汇",
    levels: {
        all: {
            name: "🎮 全部",
            words: [
                { word: "achievement", meaning: "成就", audio: "achievement.wav" },
                { word: "action", meaning: "动作", audio: "action.wav" },
                { word: "adventure", meaning: "冒险", audio: "adventure.wav" },
                { word: "aim", meaning: "瞄准", audio: "aim.wav" },
                { word: "alliance", meaning: "联盟", audio: "alliance.wav" },
                { word: "animation", meaning: "动画; 动画效果", audio: "animation.wav" },
                { word: "arcade", meaning: "街机", audio: "arcade.wav" },
                { word: "arena", meaning: "竞技场", audio: "arena.wav" },
                { word: "armour", meaning: "盔甲", audio: "armour.wav" },
                { word: "assist", meaning: "助攻", audio: "assist.wav" },
                { word: "attack", meaning: "攻击", audio: "attack.wav" },
                { word: "avatar", meaning: "游戏角色形象; 虚拟化身", audio: "avatar.wav" },
                { word: "badge", meaning: "徽章", audio: "badge.wav" },
                { word: "balance", meaning: "平衡", audio: "balance.wav" },
                { word: "ban", meaning: "禁用; 禁选", audio: "ban.wav" },
                { word: "battle", meaning: "战斗", audio: "battle.wav" },
                { word: "beta", meaning: "测试版", audio: "beta.wav" },
                { word: "bonus", meaning: "额外奖励", audio: "bonus.wav" },
                { word: "boss", meaning: "首领怪; Boss", audio: "boss.wav" },
                { word: "bot", meaning: "电脑玩家; AI对手", audio: "bot.wav" },
                { word: "buff", meaning: "增益", audio: "buff.wav" },
                { word: "build", meaning: "出装方案; 构建", audio: "build.wav" },
                { word: "campaign", meaning: "战役; 剧情模式", audio: "campaign.wav" },
                { word: "capture", meaning: "占领; 夺取", audio: "capture.wav" },
                { word: "casual", meaning: "休闲玩家的; 轻度的", audio: "casual.wav" },
                { word: "champion", meaning: "英雄; 冠军角色", audio: "champion.wav" },
                { word: "character", meaning: "角色", audio: "character.wav" },
                { word: "cheat", meaning: "作弊; 秘籍", audio: "cheat.wav" },
                { word: "checkpoint", meaning: "存档点", audio: "checkpoint.wav" },
                { word: "clan", meaning: "战队", audio: "clan.wav" },
                { word: "clash", meaning: "对战; 冲突", audio: "clash.wav" },
                { word: "class", meaning: "职业", audio: "class.wav" },
                { word: "classic", meaning: "经典的", audio: "classic.wav" },
                { word: "combat", meaning: "战斗", audio: "combat.wav" },
                { word: "combo", meaning: "连招", audio: "combo.wav" },
                { word: "command", meaning: "指令; 操作指令", audio: "command.wav" },
                { word: "competitive", meaning: "竞技的; 排位的", audio: "competitive.wav" },
                { word: "console", meaning: "游戏机", audio: "console.wav" },
                { word: "controller", meaning: "手柄", audio: "controller.wav" },
                { word: "craft", meaning: "制作; 合成", audio: "craft.wav" },
                { word: "crash", meaning: "崩溃; 闪退", audio: "crash.wav" },
                { word: "create", meaning: "创造", audio: "create.wav" },
                { word: "crew", meaning: "队伍; 组队", audio: "crew.wav" },
                { word: "critical", meaning: "暴击的", audio: "critical.wav" },
                { word: "custom", meaning: "自定义", audio: "custom.wav" },
                { word: "damage", meaning: "伤害", audio: "damage.wav" },
                { word: "debug", meaning: "调试", audio: "debug.wav" },
                { word: "deck", meaning: "卡组", audio: "deck.wav" },
                { word: "defend", meaning: "防御", audio: "defend.wav" },
                { word: "demo", meaning: "试玩版", audio: "demo.wav" },
                { word: "deploy", meaning: "部署; 放置", audio: "deploy.wav" },
                { word: "dodge", meaning: "闪避", audio: "dodge.wav" },
                { word: "download", meaning: "下载", audio: "download.wav" },
                { word: "dragon", meaning: "龙", audio: "dragon.wav" },
                { word: "dungeon", meaning: "地牢", audio: "dungeon.wav" },
                { word: "elite", meaning: "精英", audio: "elite.wav" },
                { word: "emote", meaning: "表情动作", audio: "emote.wav" },
                { word: "enemy", meaning: "敌人", audio: "enemy.wav" },
                { word: "engine", meaning: "引擎", audio: "engine.wav" },
                { word: "epic", meaning: "史诗级", audio: "epic.wav" },
                { word: "equip", meaning: "装备", audio: "equip.wav" },
                { word: "escape", meaning: "逃脱", audio: "escape.wav" },
                { word: "event", meaning: "活动; 限时活动", audio: "event.wav" },
                { word: "execute", meaning: "处决; 斩杀", audio: "execute.wav" },
                { word: "expand", meaning: "扩展; 资料片", audio: "expand.wav" },
                { word: "experience", meaning: "经验值", audio: "experience.wav" },
                { word: "exploit", meaning: "利用漏洞", audio: "exploit.wav" },
                { word: "explore", meaning: "探索", audio: "explore.wav" },
                { word: "fantasy", meaning: "奇幻", audio: "fantasy.wav" },
                { word: "fight", meaning: "战斗; 格斗", audio: "fight.wav" },
                { word: "final", meaning: "最终的", audio: "final.wav" },
                { word: "fire", meaning: "开火; 射击", audio: "fire.wav" },
                { word: "forge", meaning: "锻造", audio: "forge.wav" },
                { word: "frame", meaning: "帧", audio: "frame.wav" },
                { word: "fury", meaning: "狂怒", audio: "fury.wav" },
                { word: "gear", meaning: "装备", audio: "gear.wav" },
                { word: "glitch", meaning: "Bug; 程序故障", audio: "glitch.wav" },
                { word: "grind", meaning: "刷经验; 肝", audio: "grind.wav" },
                { word: "guild", meaning: "公会", audio: "guild.wav" },
                { word: "health", meaning: "生命值", audio: "health.wav" },
                { word: "hero", meaning: "英雄", audio: "hero.wav" },
                { word: "hunt", meaning: "狩猎; 猎杀", audio: "hunt.wav" },
                { word: "inventory", meaning: "背包", audio: "inventory.wav" },
                { word: "item", meaning: "物品", audio: "item.wav" },
                { word: "jump", meaning: "跳", audio: "jump.wav" },
                { word: "kill", meaning: "击杀", audio: "kill.wav" },
                { word: "kingdom", meaning: "王国", audio: "kingdom.wav" },
                { word: "launch", meaning: "发售; 上线", audio: "launch.wav" },
                { word: "league", meaning: "联盟", audio: "league.wav" },
                { word: "legend", meaning: "传奇", audio: "legend.wav" },
                { word: "level", meaning: "等级", audio: "level.wav" },
                { word: "lobby", meaning: "大厅; 等待室", audio: "lobby.wav" },
                { word: "loot", meaning: "战利品", audio: "loot.wav" },
                { word: "magic", meaning: "魔法", audio: "magic.wav" },
                { word: "map", meaning: "地图", audio: "map.wav" },
                { word: "master", meaning: "大师; 精通", audio: "master.wav" },
                { word: "match", meaning: "比赛; 对局", audio: "match.wav" },
                { word: "mission", meaning: "任务", audio: "mission.wav" },
                { word: "mode", meaning: "模式", audio: "mode.wav" },
                { word: "monster", meaning: "怪物", audio: "monster.wav" },
                { word: "mount", meaning: "坐骑", audio: "mount.wav" },
                { word: "multiplayer", meaning: "多人游戏", audio: "multiplayer.wav" },
                { word: "nerf", meaning: "削弱", audio: "nerf.wav" },
                { word: "objective", meaning: "目标", audio: "objective.wav" },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "opponent", meaning: "对手", audio: "opponent.wav" },
                { word: "patch", meaning: "补丁; 更新补丁", audio: "patch.wav" },
                { word: "penalty", meaning: "惩罚", audio: "penalty.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "play", meaning: "玩", audio: "play.wav" },
                { word: "player", meaning: "玩家", audio: "player.wav" },
                { word: "point", meaning: "点数; 积分", audio: "point.wav" },
                { word: "portal", meaning: "传送门", audio: "portal.wav" },
                { word: "power", meaning: "能力; 战力", audio: "power.wav" },
                { word: "quest", meaning: "任务", audio: "quest.wav" },
                { word: "rage", meaning: "暴怒; 怒退", audio: "rage.wav" },
                { word: "raid", meaning: "突袭", audio: "raid.wav" },
                { word: "rank", meaning: "排名; 段位", audio: "rank.wav" },
                { word: "realm", meaning: "王国; 服务器", audio: "realm.wav" },
                { word: "release", meaning: "发布", audio: "release.wav" },
                { word: "replay", meaning: "回放", audio: "replay.wav" },
                { word: "respawn", meaning: "复活", audio: "respawn.wav" },
                { word: "reward", meaning: "奖励", audio: "reward.wav" },
                { word: "rival", meaning: "竞争对手", audio: "rival.wav" },
                { word: "role", meaning: "角色", audio: "role.wav" },
                { word: "round", meaning: "回合", audio: "round.wav" },
                { word: "rush", meaning: "突进; 速攻", audio: "rush.wav" },
                { word: "score", meaning: "分数", audio: "score.wav" },
                { word: "server", meaning: "服务器", audio: "server.wav" },
                { word: "shield", meaning: "盾牌", audio: "shield.wav" },
                { word: "shoot", meaning: "射击", audio: "shoot.wav" },
                { word: "siege", meaning: "围攻", audio: "siege.wav" },
                { word: "skill", meaning: "技能", audio: "skill.wav" },
                { word: "snipe", meaning: "狙击", audio: "snipe.wav" },
                { word: "solo", meaning: "单人; 单排", audio: "solo.wav" },
                { word: "spawn", meaning: "生成", audio: "spawn.wav" },
                { word: "speed", meaning: "速度", audio: "speed.wav" },
                { word: "spell", meaning: "法术; 技能", audio: "spell.wav" },
                { word: "sprint", meaning: "冲刺", audio: "sprint.wav" },
                { word: "stage", meaning: "关卡", audio: "stage.wav" },
                { word: "stamina", meaning: "耐力", audio: "stamina.wav" },
                { word: "strategy", meaning: "策略", audio: "strategy.wav" },
                { word: "stream", meaning: "直播", audio: "stream.wav" },
                { word: "strike", meaning: "打击; 连杀", audio: "strike.wav" },
                { word: "summon", meaning: "召唤", audio: "summon.wav" },
                { word: "survival", meaning: "生存", audio: "survival.wav" },
                { word: "sword", meaning: "剑", audio: "sword.wav" },
                { word: "talent", meaning: "天赋", audio: "talent.wav" },
                { word: "target", meaning: "目标", audio: "target.wav" },
                { word: "team", meaning: "团队", audio: "team.wav" },
                { word: "token", meaning: "代币", audio: "token.wav" },
                { word: "tower", meaning: "塔", audio: "tower.wav" },
                { word: "trade", meaning: "交易", audio: "trade.wav" },
                { word: "trap", meaning: "陷阱", audio: "trap.wav" },
                { word: "treasure", meaning: "宝藏", audio: "treasure.wav" },
                { word: "trigger", meaning: "触发", audio: "trigger.wav" },
                { word: "trophy", meaning: "奖杯", audio: "trophy.wav" },
                { word: "tutorial", meaning: "新手教程", audio: "tutorial.wav" },
                { word: "ultimate", meaning: "终极技能; 大招", audio: "ultimate.wav" },
                { word: "unlock", meaning: "解锁", audio: "unlock.wav" },
                { word: "update", meaning: "更新", audio: "update.wav" },
                { word: "upgrade", meaning: "升级", audio: "upgrade.wav" },
                { word: "versus", meaning: "对战; VS", audio: "versus.wav" },
                { word: "victory", meaning: "胜利", audio: "victory.wav" },
                { word: "virtual", meaning: "虚拟的", audio: "virtual.wav" },
                { word: "warrior", meaning: "战士", audio: "warrior.wav" },
                { word: "weapon", meaning: "武器", audio: "weapon.wav" },
                { word: "wizard", meaning: "巫师", audio: "wizard.wav" },
                { word: "zone", meaning: "区域; 安全区", audio: "zone.wav" }
            ]
        }
    }
});
