registerWordbook('topic_tech', {
    name: "科技互联网",
    emoji: "💻",
    group: 'topic',
    description: "计算机、互联网、人工智能相关词汇",
    levels: {
        all: {
            name: "💻 全部",
            words: [
                { word: "algorithm", meaning: "算法", audio: "algorithm.wav" },
                { word: "application", meaning: "应用", audio: "application.wav" },
                { word: "artificial", meaning: "人造的", audio: "artificial.wav" },
                { word: "automate", meaning: "自动化", audio: "automate.wav" },
                { word: "bandwidth", meaning: "带宽", audio: "bandwidth.wav" },
                { word: "battery", meaning: "电池", audio: "battery.wav" },
                { word: "binary", meaning: "二进制", audio: "binary.wav" },
                { word: "bluetooth", meaning: "蓝牙", audio: "bluetooth.wav" },
                { word: "broadcast", meaning: "播送", audio: "broadcast.wav" },
                { word: "browser", meaning: "浏览器", audio: "browser.wav" },
                { word: "bug", meaning: "漏洞", audio: "bug.wav" },
                { word: "cable", meaning: "电缆", audio: "cable.wav" },
                { word: "calculate", meaning: "计算", audio: "calculate.wav" },
                { word: "capacity", meaning: "容量", audio: "capacity.wav" },
                { word: "cellular", meaning: "蜂窝网络", audio: "cellular.wav" },
                { word: "chip", meaning: "芯片", audio: "chip.wav" },
                { word: "circuit", meaning: "电路", audio: "circuit.wav" },
                { word: "click", meaning: "点击", audio: "click.wav" },
                { word: "cloud", meaning: "云", audio: "cloud.wav" },
                { word: "code", meaning: "代码", audio: "code.wav" },
                { word: "compatible", meaning: "兼容的", audio: "compatible.wav" },
                { word: "component", meaning: "成分", audio: "component.wav" },
                { word: "compute", meaning: "计算", audio: "compute.wav" },
                { word: "connect", meaning: "连接", audio: "connect.wav" },
                { word: "convert", meaning: "转变", audio: "convert.wav" },
                { word: "cookie", meaning: "浏览器Cookie", audio: "cookie.wav" },
                { word: "crash", meaning: "碰撞", audio: "crash.wav" },
                { word: "cursor", meaning: "光标", audio: "cursor.wav" },
                { word: "cyber", meaning: "网络的", audio: "cyber.wav" },
                { word: "data", meaning: "数据", audio: "data.wav" },
                { word: "database", meaning: "数据库", audio: "database.wav" },
                { word: "debug", meaning: "调试", audio: "debug.wav" },
                { word: "decode", meaning: "解码", audio: "decode.wav" },
                { word: "default", meaning: "默认", audio: "default.wav" },
                { word: "delete", meaning: "删除", audio: "delete.wav" },
                { word: "desktop", meaning: "桌面", audio: "desktop.wav" },
                { word: "detect", meaning: "探测", audio: "detect.wav" },
                { word: "device", meaning: "设备", audio: "device.wav" },
                { word: "digital", meaning: "数字的", audio: "digital.wav" },
                { word: "display", meaning: "展示", audio: "display.wav" },
                { word: "domain", meaning: "领域", audio: "domain.wav" },
                { word: "download", meaning: "下载", audio: "download.wav" },
                { word: "drone", meaning: "无人机", audio: "drone.wav" },
                { word: "email", meaning: "电子邮件", audio: "email.wav" },
                { word: "embed", meaning: "嵌入", audio: "embed.wav" },
                { word: "encode", meaning: "编码", audio: "encode.wav" },
                { word: "encrypt", meaning: "加密", audio: "encrypt.wav" },
                { word: "engine", meaning: "引擎", audio: "engine.wav" },
                { word: "ethernet", meaning: "以太网", audio: "ethernet.wav" },
                { word: "export", meaning: "出口", audio: "export.wav" },
                { word: "file", meaning: "文件", audio: "file.wav" },
                { word: "filter", meaning: "筛选", audio: "filter.wav" },
                { word: "firewall", meaning: "防火墙", audio: "firewall.wav" },
                { word: "firmware", meaning: "固件", audio: "firmware.wav" },
                { word: "format", meaning: "格式", audio: "format.wav" },
                { word: "framework", meaning: "框架", audio: "framework.wav" },
                { word: "function", meaning: "功能", audio: "function.wav" },
                { word: "generate", meaning: "产生", audio: "generate.wav" },
                { word: "gigabyte", meaning: "吉字节", audio: "gigabyte.wav" },
                { word: "graphic", meaning: "形象的", audio: "graphic.wav" },
                { word: "hack", meaning: "黑客攻击", audio: "hack.wav" },
                { word: "hardware", meaning: "硬件", audio: "hardware.wav" },
                { word: "homepage", meaning: "主页", audio: "homepage.wav" },
                { word: "host", meaning: "主持人", audio: "host.wav" },
                { word: "icon", meaning: "图标", audio: "icon.wav" },
                { word: "import", meaning: "进口", audio: "import.wav" },
                { word: "index", meaning: "指数", audio: "index.wav" },
                { word: "input", meaning: "输入", audio: "input.wav" },
                { word: "install", meaning: "安装", audio: "install.wav" },
                { word: "integrate", meaning: "整合", audio: "integrate.wav" },
                { word: "intelligence", meaning: "智力", audio: "intelligence.wav" },
                { word: "interface", meaning: "界面", audio: "interface.wav" },
                { word: "internet", meaning: "互联网", audio: "internet.wav" },
                { word: "keyboard", meaning: "键盘", audio: "keyboard.wav" },
                { word: "laptop", meaning: "笔记本电脑", audio: "laptop.wav" },
                { word: "launch", meaning: "发射", audio: "launch.wav" },
                { word: "link", meaning: "关联", audio: "link.wav" },
                { word: "load", meaning: "加载", audio: "load.wav" },
                { word: "login", meaning: "登录", audio: "login.wav" },
                { word: "malware", meaning: "恶意软件", audio: "malware.wav" },
                { word: "memory", meaning: "记忆", audio: "memory.wav" },
                { word: "merge", meaning: "合并", audio: "merge.wav" },
                { word: "microchip", meaning: "微芯片", audio: "microchip.wav" },
                { word: "mobile", meaning: "移动的", audio: "mobile.wav" },
                { word: "modem", meaning: "调制解调器", audio: "modem.wav" },
                { word: "module", meaning: "模块", audio: "module.wav" },
                { word: "monitor", meaning: "监视器", audio: "monitor.wav" },
                { word: "mouse", meaning: "老鼠", audio: "mouse.wav" },
                { word: "navigate", meaning: "导航", audio: "navigate.wav" },
                { word: "network", meaning: "网络", audio: "network.wav" },
                { word: "node", meaning: "节点", audio: "node.wav" },
                { word: "offline", meaning: "离线", audio: "offline.wav" },
                { word: "online", meaning: "在线的", audio: "online.wav" },
                { word: "operate", meaning: "操作", audio: "operate.wav" },
                { word: "optimize", meaning: "优化", audio: "optimize.wav" },
                { word: "output", meaning: "输出", audio: "output.wav" },
                { word: "password", meaning: "密码", audio: "password.wav" },
                { word: "patch", meaning: "修补", audio: "patch.wav" },
                { word: "pixel", meaning: "像素", audio: "pixel.wav" },
                { word: "platform", meaning: "平台", audio: "platform.wav" },
                { word: "plugin", meaning: "插件", audio: "plugin.wav" },
                { word: "port", meaning: "港口", audio: "port.wav" },
                { word: "portal", meaning: "门户网站", audio: "portal.wav" },
                { word: "privacy", meaning: "隐私", audio: "privacy.wav" },
                { word: "process", meaning: "过程", audio: "process.wav" },
                { word: "processor", meaning: "处理器", audio: "processor.wav" },
                { word: "program", meaning: "程序", audio: "program.wav" },
                { word: "protocol", meaning: "协议", audio: "protocol.wav" },
                { word: "proxy", meaning: "代理", audio: "proxy.wav" },
                { word: "query", meaning: "查询", audio: "query.wav" },
                { word: "reboot", meaning: "重启", audio: "reboot.wav" },
                { word: "render", meaning: "渲染", audio: "render.wav" },
                { word: "robot", meaning: "机器人", audio: "robot.wav" },
                { word: "router", meaning: "路由器", audio: "router.wav" },
                { word: "scan", meaning: "扫描", audio: "scan.wav" },
                { word: "screen", meaning: "屏幕", audio: "screen.wav" },
                { word: "script", meaning: "脚本", audio: "script.wav" },
                { word: "scroll", meaning: "滚动", audio: "scroll.wav" },
                { word: "search", meaning: "搜索", audio: "search.wav" },
                { word: "secure", meaning: "安全的", audio: "secure.wav" },
                { word: "sensor", meaning: "传感器", audio: "sensor.wav" },
                { word: "server", meaning: "服务器", audio: "server.wav" },
                { word: "signal", meaning: "信号", audio: "signal.wav" },
                { word: "simulate", meaning: "模拟", audio: "simulate.wav" },
                { word: "smartphone", meaning: "手机", audio: "smartphone.wav" },
                { word: "software", meaning: "软件", audio: "software.wav" },
                { word: "spam", meaning: "垃圾邮件", audio: "spam.wav" },
                { word: "storage", meaning: "存储", audio: "storage.wav" },
                { word: "stream", meaning: "溪流", audio: "stream.wav" },
                { word: "surf", meaning: "上网浏览", audio: "surf.wav" },
                { word: "sync", meaning: "同步", audio: "sync.wav" },
                { word: "system", meaning: "系统", audio: "system.wav" },
                { word: "tablet", meaning: "药片", audio: "tablet.wav" },
                { word: "tech", meaning: "科技", audio: "tech.wav" },
                { word: "template", meaning: "模板", audio: "template.wav" },
                { word: "terminal", meaning: "终端", audio: "terminal.wav" },
                { word: "token", meaning: "令牌", audio: "token.wav" },
                { word: "toolbar", meaning: "工具栏", audio: "toolbar.wav" },
                { word: "trace", meaning: "痕迹", audio: "trace.wav" },
                { word: "traffic", meaning: "交通", audio: "traffic.wav" },
                { word: "transmit", meaning: "发送", audio: "transmit.wav" },
                { word: "update", meaning: "更新", audio: "update.wav" },
                { word: "upgrade", meaning: "升级", audio: "upgrade.wav" },
                { word: "upload", meaning: "上传", audio: "upload.wav" },
                { word: "username", meaning: "用户名", audio: "username.wav" },
                { word: "verify", meaning: "验证", audio: "verify.wav" },
                { word: "version", meaning: "版本", audio: "version.wav" },
                { word: "virtual", meaning: "虚拟的", audio: "virtual.wav" },
                { word: "virus", meaning: "病毒", audio: "virus.wav" },
                { word: "web", meaning: "网络", audio: "web.wav" },
                { word: "widget", meaning: "小组件", audio: "widget.wav" },
                { word: "wifi", meaning: "无线网络", audio: "wifi.wav" },
                { word: "wireless", meaning: "无线的", audio: "wireless.wav" },
                { word: "zip", meaning: "压缩", audio: "zip.wav" }
            ]
        }
    }
});
