registerWordbook('topic_sports', {
    name: "体育赛事",
    emoji: "⚽",
    group: 'topic',
    description: "竞技体育、赛事规则相关词汇",
    levels: {
        all: {
            name: "⚽ 全部",
            words: [
                { word: "ace", meaning: "发球得分", audio: "ace.wav" },
                { word: "advantage", meaning: "优势", audio: "advantage.wav" },
                { word: "amateur", meaning: "业余", audio: "amateur.wav" },
                { word: "arena", meaning: "竞技场", audio: "arena.wav" },
                { word: "assist", meaning: "助攻", audio: "assist.wav" },
                { word: "athlete", meaning: "运动员", audio: "athlete.wav" },
                { word: "athletics", meaning: "田径运动", audio: "athletics.wav" },
                { word: "attack", meaning: "进攻", audio: "attack.wav" },
                { word: "attempt", meaning: "尝试; 试举", audio: "attempt.wav" },
                { word: "award", meaning: "奖", audio: "award.wav" },
                { word: "badge", meaning: "徽章", audio: "badge.wav" },
                { word: "ball", meaning: "球", audio: "ball.wav" },
                { word: "ban", meaning: "禁止", audio: "ban.wav" },
                { word: "bar", meaning: "横杆", audio: "bar.wav" },
                { word: "basket", meaning: "篮; 篮筐", audio: "basket.wav" },
                { word: "bat", meaning: "球棒", audio: "bat.wav" },
                { word: "beat", meaning: "击败", audio: "beat.wav" },
                { word: "bench", meaning: "替补席", audio: "bench.wav" },
                { word: "bicycle", meaning: "自行车", audio: "bicycle.wav" },
                { word: "block", meaning: "拦截; 封盖", audio: "block.wav" },
                { word: "board", meaning: "滑板; 板", audio: "board.wav" },
                { word: "boot", meaning: "球鞋; 球靴", audio: "boot.wav" },
                { word: "bounce", meaning: "弹跳", audio: "bounce.wav" },
                { word: "bout", meaning: "一局比赛", audio: "bout.wav" },
                { word: "bowl", meaning: "投球; 保龄球", audio: "bowl.wav" },
                { word: "box", meaning: "拳击", audio: "box.wav" },
                { word: "captain", meaning: "队长", audio: "captain.wav" },
                { word: "catch", meaning: "接球", audio: "catch.wav" },
                { word: "champion", meaning: "冠军", audio: "champion.wav" },
                { word: "charge", meaning: "冲撞; 带球突破", audio: "charge.wav" },
                { word: "chase", meaning: "追赶", audio: "chase.wav" },
                { word: "cheat", meaning: "作弊", audio: "cheat.wav" },
                { word: "circuit", meaning: "巡回赛", audio: "circuit.wav" },
                { word: "climb", meaning: "攀登; 攀岩", audio: "climb.wav" },
                { word: "club", meaning: "俱乐部", audio: "club.wav" },
                { word: "coach", meaning: "教练", audio: "coach.wav" },
                { word: "compete", meaning: "参赛; 竞技", audio: "compete.wav" },
                { word: "competition", meaning: "竞赛", audio: "competition.wav" },
                { word: "competitor", meaning: "参赛选手", audio: "competitor.wav" },
                { word: "contest", meaning: "竞赛", audio: "contest.wav" },
                { word: "court", meaning: "球场", audio: "court.wav" },
                { word: "crew", meaning: "赛艇队", audio: "crew.wav" },
                { word: "cycle", meaning: "骑自行车", audio: "cycle.wav" },
                { word: "defeat", meaning: "击败", audio: "defeat.wav" },
                { word: "defend", meaning: "防守", audio: "defend.wav" },
                { word: "defence", meaning: "防守", audio: "defence.wav" },
                { word: "disqualify", meaning: "取消资格", audio: "disqualify.wav" },
                { word: "dive", meaning: "跳水; 鱼跃扑救", audio: "dive.wav" },
                { word: "dodge", meaning: "闪避", audio: "dodge.wav" },
                { word: "dominate", meaning: "称霸; 统治赛场", audio: "dominate.wav" },
                { word: "draft", meaning: "选秀", audio: "draft.wav" },
                { word: "draw", meaning: "平局", audio: "draw.wav" },
                { word: "drill", meaning: "训练", audio: "drill.wav" },
                { word: "endurance", meaning: "耐力", audio: "endurance.wav" },
                { word: "equip", meaning: "装备", audio: "equip.wav" },
                { word: "event", meaning: "赛事; 比赛项目", audio: "event.wav" },
                { word: "exercise", meaning: "锻炼", audio: "exercise.wav" },
                { word: "fan", meaning: "粉丝; 球迷", audio: "fan.wav" },
                { word: "fault", meaning: "发球失误", audio: "fault.wav" },
                { word: "field", meaning: "场地", audio: "field.wav" },
                { word: "final", meaning: "决赛", audio: "final.wav" },
                { word: "foul", meaning: "犯规", audio: "foul.wav" },
                { word: "goal", meaning: "进球; 球门", audio: "goal.wav" },
                { word: "golf", meaning: "高尔夫球", audio: "golf.wav" },
                { word: "guard", meaning: "后卫", audio: "guard.wav" },
                { word: "gym", meaning: "健身房", audio: "gym.wav" },
                { word: "hit", meaning: "击球; 安打", audio: "hit.wav" },
                { word: "hockey", meaning: "曲棍球", audio: "hockey.wav" },
                { word: "hurdle", meaning: "跨栏", audio: "hurdle.wav" },
                { word: "injury", meaning: "受伤", audio: "injury.wav" },
                { word: "judge", meaning: "裁判", audio: "judge.wav" },
                { word: "jump", meaning: "跳", audio: "jump.wav" },
                { word: "kick", meaning: "踢", audio: "kick.wav" },
                { word: "lap", meaning: "圈", audio: "lap.wav" },
                { word: "lead", meaning: "领先", audio: "lead.wav" },
                { word: "league", meaning: "联赛", audio: "league.wav" },
                { word: "loss", meaning: "败局", audio: "loss.wav" },
                { word: "marathon", meaning: "马拉松", audio: "marathon.wav" },
                { word: "match", meaning: "比赛", audio: "match.wav" },
                { word: "medal", meaning: "奖牌", audio: "medal.wav" },
                { word: "net", meaning: "网", audio: "net.wav" },
                { word: "offence", meaning: "进攻", audio: "offence.wav" },
                { word: "official", meaning: "裁判员", audio: "official.wav" },
                { word: "opponent", meaning: "对手", audio: "opponent.wav" },
                { word: "overtime", meaning: "加时赛", audio: "overtime.wav" },
                { word: "pass", meaning: "传球", audio: "pass.wav" },
                { word: "penalty", meaning: "罚球; 点球", audio: "penalty.wav" },
                { word: "pitch", meaning: "球场", audio: "pitch.wav" },
                { word: "play", meaning: "比赛; 参赛", audio: "play.wav" },
                { word: "player", meaning: "运动员; 球员", audio: "player.wav" },
                { word: "point", meaning: "分; 得分", audio: "point.wav" },
                { word: "pool", meaning: "泳池", audio: "pool.wav" },
                { word: "professional", meaning: "职业的", audio: "professional.wav" },
                { word: "qualify", meaning: "获得参赛资格", audio: "qualify.wav" },
                { word: "race", meaning: "比赛; 赛跑", audio: "race.wav" },
                { word: "racket", meaning: "球拍", audio: "racket.wav" },
                { word: "rank", meaning: "排名", audio: "rank.wav" },
                { word: "record", meaning: "纪录", audio: "record.wav" },
                { word: "referee", meaning: "裁判", audio: "referee.wav" },
                { word: "relay", meaning: "接力赛", audio: "relay.wav" },
                { word: "retire", meaning: "退役", audio: "retire.wav" },
                { word: "rival", meaning: "竞争对手", audio: "rival.wav" },
                { word: "round", meaning: "轮次; 回合", audio: "round.wav" },
                { word: "rugby", meaning: "橄榄球", audio: "rugby.wav" },
                { word: "run", meaning: "跑步", audio: "run.wav" },
                { word: "score", meaning: "得分; 比分", audio: "score.wav" },
                { word: "seed", meaning: "种子选手", audio: "seed.wav" },
                { word: "serve", meaning: "发球", audio: "serve.wav" },
                { word: "shoot", meaning: "射门; 投篮", audio: "shoot.wav" },
                { word: "sprint", meaning: "冲刺", audio: "sprint.wav" },
                { word: "squad", meaning: "大名单; 阵容", audio: "squad.wav" },
                { word: "stadium", meaning: "体育场", audio: "stadium.wav" },
                { word: "stamina", meaning: "耐力", audio: "stamina.wav" },
                { word: "strike", meaning: "击球", audio: "strike.wav" },
                { word: "substitute", meaning: "替补球员", audio: "substitute.wav" },
                { word: "swim", meaning: "游泳", audio: "swim.wav" },
                { word: "tackle", meaning: "铲球; 抢断", audio: "tackle.wav" },
                { word: "team", meaning: "队伍; 球队", audio: "team.wav" },
                { word: "tennis", meaning: "网球", audio: "tennis.wav" },
                { word: "throw", meaning: "投掷", audio: "throw.wav" },
                { word: "tie", meaning: "平局", audio: "tie.wav" },
                { word: "title", meaning: "冠军头衔", audio: "title.wav" },
                { word: "tournament", meaning: "锦标赛", audio: "tournament.wav" },
                { word: "track", meaning: "跑道; 赛道", audio: "track.wav" },
                { word: "train", meaning: "训练", audio: "train.wav" },
                { word: "transfer", meaning: "转会", audio: "transfer.wav" },
                { word: "trophy", meaning: "奖杯", audio: "trophy.wav" },
                { word: "victory", meaning: "胜利", audio: "victory.wav" },
                { word: "volleyball", meaning: "排球", audio: "volleyball.wav" },
                { word: "win", meaning: "赢", audio: "win.wav" }
            ]
        }
    }
});
