registerWordbook('topic_medical', {
    name: "医学用语",
    emoji: "🏥",
    group: 'topic',
    description: "医疗、疾病、药物、人体相关词汇",
    levels: {
        all: {
            name: "🏥 全部",
            words: [
                { word: "ache", meaning: "疼痛", audio: null },
                { word: "acute", meaning: "急性", audio: "acute.wav" },
                { word: "addict", meaning: "上瘾者", audio: null },
                { word: "adverse", meaning: "不利的", audio: "adverse.wav" },
                { word: "aging", meaning: "老化", audio: null },
                { word: "aid", meaning: "援助", audio: "aid.wav" },
                { word: "allergy", meaning: "过敏", audio: null },
                { word: "ambulance", meaning: "救护车", audio: "ambulance.wav" },
                { word: "anatomy", meaning: "解剖学", audio: null },
                { word: "antibiotic", meaning: "抗生素", audio: null },
                { word: "anxiety", meaning: "焦虑", audio: "anxiety.wav" },
                { word: "artery", meaning: "动脉", audio: null },
                { word: "bacteria", meaning: "细菌", audio: "bacteria.wav" },
                { word: "bandage", meaning: "绷带", audio: null },
                { word: "bleed", meaning: "流血", audio: "bleed.wav" },
                { word: "blind", meaning: "瞎的", audio: "blind.wav" },
                { word: "blood", meaning: "血", audio: "blood.wav" },
                { word: "bone", meaning: "骨", audio: "bone.wav" },
                { word: "brain", meaning: "脑", audio: "brain.wav" },
                { word: "breath", meaning: "气息", audio: "breath.wav" },
                { word: "bruise", meaning: "瘤伤", audio: null },
                { word: "burn", meaning: "烧伤", audio: "burn.wav" },
                { word: "calcium", meaning: "钙", audio: null },
                { word: "cancer", meaning: "癌症", audio: "cancer.wav" },
                { word: "capsule", meaning: "胶囊", audio: null },
                { word: "cardiac", meaning: "心脏的", audio: null },
                { word: "cell", meaning: "细胞", audio: "cell.wav" },
                { word: "checkup", meaning: "体检", audio: null },
                { word: "chest", meaning: "胸部", audio: "chest.wav" },
                { word: "chronic", meaning: "慢性的", audio: "chronic.wav" },
                { word: "clinic", meaning: "诊所", audio: "clinic.wav" },
                { word: "clinical", meaning: "临床", audio: "clinical.wav" },
                { word: "collapse", meaning: "坍塌", audio: "collapse.wav" },
                { word: "coma", meaning: "昏迷", audio: null },
                { word: "condition", meaning: "状况", audio: "condition.wav" },
                { word: "conscious", meaning: "有意识的", audio: "conscious.wav" },
                { word: "consult", meaning: "咨询", audio: "consult.wav" },
                { word: "contagious", meaning: "传染性的", audio: null },
                { word: "cure", meaning: "治愈", audio: "cure.wav" },
                { word: "deaf", meaning: "聋的", audio: null },
                { word: "deficiency", meaning: "不足", audio: "deficiency.wav" },
                { word: "depress", meaning: "使氮丧", audio: null },
                { word: "diagnose", meaning: "诊断", audio: "diagnose.wav" },
                { word: "diagnosis", meaning: "诊断", audio: "diagnosis.wav" },
                { word: "diet", meaning: "饮食", audio: "diet.wav" },
                { word: "disability", meaning: "残疾", audio: "disability.wav" },
                { word: "discharge", meaning: "释放", audio: "discharge.wav" },
                { word: "disease", meaning: "疾病", audio: "disease.wav" },
                { word: "disorder", meaning: "紊乱", audio: "disorder.wav" },
                { word: "dizzy", meaning: "头晕", audio: null },
                { word: "doctor", meaning: "医生", audio: "doctor.wav" },
                { word: "dose", meaning: "剂量", audio: "dose.wav" },
                { word: "drug", meaning: "药品", audio: "drug.wav" },
                { word: "emergency", meaning: "紧急情况", audio: "emergency.wav" },
                { word: "emotion", meaning: "情感", audio: "emotion.wav" },
                { word: "epidemic", meaning: "流行性", audio: "epidemic.wav" },
                { word: "examine", meaning: "检查", audio: "examine.wav" },
                { word: "exercise", meaning: "锻炼", audio: "exercise.wav" },
                { word: "exhaust", meaning: "耗尽", audio: null },
                { word: "fatal", meaning: "致命的", audio: "fatal.wav" },
                { word: "fatigue", meaning: "疲劳", audio: null },
                { word: "fever", meaning: "发烧", audio: "fever.wav" },
                { word: "flu", meaning: "流感", audio: "flu.wav" },
                { word: "fracture", meaning: "骨折", audio: null },
                { word: "gene", meaning: "基因", audio: "gene.wav" },
                { word: "genetic", meaning: "遗传的", audio: "genetic.wav" },
                { word: "germ", meaning: "细菌", audio: null },
                { word: "heal", meaning: "愈合", audio: "heal.wav" },
                { word: "health", meaning: "健康", audio: "health.wav" },
                { word: "heart", meaning: "心", audio: "heart.wav" },
                { word: "hormone", meaning: "激素", audio: null },
                { word: "hospital", meaning: "医院", audio: "hospital.wav" },
                { word: "hygiene", meaning: "卫生", audio: null },
                { word: "ill", meaning: "患病的", audio: "ill.wav" },
                { word: "immune", meaning: "免疫", audio: "immune.wav" },
                { word: "implant", meaning: "植入", audio: null },
                { word: "infant", meaning: "婴儿", audio: "infant.wav" },
                { word: "infect", meaning: "感染", audio: "infect.wav" },
                { word: "infection", meaning: "感染", audio: "infection.wav" },
                { word: "inflammation", meaning: "炎症", audio: null },
                { word: "inject", meaning: "注入", audio: "inject.wav" },
                { word: "injection", meaning: "注射", audio: "injection.wav" },
                { word: "injure", meaning: "损伤", audio: "injure.wav" },
                { word: "injury", meaning: "受伤", audio: "injury.wav" },
                { word: "intensive", meaning: "密集的", audio: "intensive.wav" },
                { word: "internal", meaning: "内部的", audio: "internal.wav" },
                { word: "kidney", meaning: "肾", audio: "kidney.wav" },
                { word: "laboratory", meaning: "实验室", audio: "laboratory.wav" },
                { word: "limb", meaning: "肢", audio: "limb.wav" },
                { word: "liver", meaning: "肝", audio: "liver.wav" },
                { word: "lung", meaning: "肺", audio: "lung.wav" },
                { word: "medicine", meaning: "药品", audio: "medicine.wav" },
                { word: "mental", meaning: "精神的", audio: "mental.wav" },
                { word: "metabolism", meaning: "新陈代谢", audio: null },
                { word: "microscope", meaning: "显微镜", audio: null },
                { word: "muscle", meaning: "肌肉", audio: "muscle.wav" },
                { word: "nerve", meaning: "神经", audio: "nerve.wav" },
                { word: "nurse", meaning: "护士", audio: "nurse.wav" },
                { word: "nutrition", meaning: "营养", audio: "nutrition.wav" },
                { word: "obesity", meaning: "肥胖", audio: "obesity.wav" },
                { word: "operate", meaning: "操作", audio: "operate.wav" },
                { word: "operation", meaning: "手术", audio: "operation.wav" },
                { word: "organ", meaning: "器官", audio: "organ.wav" },
                { word: "oxygen", meaning: "氧", audio: "oxygen.wav" },
                { word: "pain", meaning: "疼痛", audio: "pain.wav" },
                { word: "paralyse", meaning: "麻痹", audio: null },
                { word: "patient", meaning: "病人", audio: "patient.wav" },
                { word: "pharmacy", meaning: "药房", audio: null },
                { word: "physical", meaning: "身体的", audio: "physical.wav" },
                { word: "physician", meaning: "医生", audio: "physician.wav" },
                { word: "pill", meaning: "丸", audio: "pill.wav" },
                { word: "poison", meaning: "毒", audio: "poison.wav" },
                { word: "pregnant", meaning: "孕", audio: "pregnant.wav" },
                { word: "prescribe", meaning: "开处方", audio: "prescribe.wav" },
                { word: "prescription", meaning: "处方", audio: "prescription.wav" },
                { word: "pressure", meaning: "压力", audio: "pressure.wav" },
                { word: "prevent", meaning: "防止", audio: "prevent.wav" },
                { word: "procedure", meaning: "程序", audio: "procedure.wav" },
                { word: "protein", meaning: "蛋白质", audio: "protein.wav" },
                { word: "psychiatry", meaning: "精神病学", audio: null },
                { word: "pulse", meaning: "脉搏", audio: null },
                { word: "recover", meaning: "恢复", audio: "recover.wav" },
                { word: "recovery", meaning: "恢复", audio: "recovery.wav" },
                { word: "remedy", meaning: "补救", audio: null },
                { word: "resist", meaning: "抵抗", audio: "resist.wav" },
                { word: "scan", meaning: "扫描", audio: "scan.wav" },
                { word: "skin", meaning: "皮肤", audio: "skin.wav" },
                { word: "specialist", meaning: "专家", audio: "specialist.wav" },
                { word: "spine", meaning: "脊柱", audio: "spine.wav" },
                { word: "sterile", meaning: "无菌的", audio: null },
                { word: "stomach", meaning: "胃", audio: "stomach.wav" },
                { word: "stress", meaning: "压力", audio: "stress.wav" },
                { word: "stroke", meaning: "中风", audio: "stroke.wav" },
                { word: "surgery", meaning: "外科手术", audio: "surgery.wav" },
                { word: "surgeon", meaning: "外科医生", audio: "surgeon.wav" },
                { word: "survive", meaning: "存活", audio: "survive.wav" },
                { word: "swallow", meaning: "吞", audio: "swallow.wav" },
                { word: "symptom", meaning: "症状", audio: "symptom.wav" },
                { word: "syndrome", meaning: "综合症", audio: null },
                { word: "therapy", meaning: "治疗", audio: null },
                { word: "tissue", meaning: "组织", audio: "tissue.wav" },
                { word: "toxic", meaning: "有毒的", audio: "toxic.wav" },
                { word: "transplant", meaning: "移植", audio: null },
                { word: "treat", meaning: "对待", audio: "treat.wav" },
                { word: "treatment", meaning: "治疗", audio: "treatment.wav" },
                { word: "tumour", meaning: "肿瘤", audio: null },
                { word: "vaccine", meaning: "疫苗", audio: null },
                { word: "vein", meaning: "静脉", audio: "vein.wav" },
                { word: "virus", meaning: "病毒", audio: "virus.wav" },
                { word: "vitamin", meaning: "维他命", audio: "vitamin.wav" },
                { word: "ward", meaning: "病房", audio: "ward.wav" },
                { word: "wound", meaning: "伤口", audio: "wound.wav" },
                { word: "x-ray", meaning: "X射线", audio: null }
            ]
        }
    }
});
