registerWordbook('topic_finance', {
    name: "商务金融",
    emoji: "💰",
    group: 'topic',
    description: "金融、银行、投资、商务相关词汇",
    levels: {
        all: {
            name: "💰 全部",
            words: [
                { word: "account", meaning: "账户", audio: "account.wav" },
                { word: "accountant", meaning: "会计", audio: "accountant.wav" },
                { word: "acquire", meaning: "收购", audio: "acquire.wav" },
                { word: "annual", meaning: "年度的", audio: "annual.wav" },
                { word: "asset", meaning: "资产", audio: "asset.wav" },
                { word: "audit", meaning: "审计", audio: "audit.wav" },
                { word: "balance", meaning: "余额", audio: "balance.wav" },
                { word: "bankrupt", meaning: "破产的", audio: "bankrupt.wav" },
                { word: "bargain", meaning: "讨价还价; 交易", audio: "bargain.wav" },
                { word: "bear", meaning: "熊市", audio: "bear.wav" },
                { word: "benefit", meaning: "福利; 收益", audio: "benefit.wav" },
                { word: "bid", meaning: "出价", audio: "bid.wav" },
                { word: "bill", meaning: "账单", audio: "bill.wav" },
                { word: "bond", meaning: "债券", audio: "bond.wav" },
                { word: "bonus", meaning: "奖金", audio: "bonus.wav" },
                { word: "borrow", meaning: "借入; 借款", audio: "borrow.wav" },
                { word: "broker", meaning: "经纪人", audio: "broker.wav" },
                { word: "budget", meaning: "预算", audio: "budget.wav" },
                { word: "bull", meaning: "牛市", audio: "bull.wav" },
                { word: "capital", meaning: "资本", audio: "capital.wav" },
                { word: "cash", meaning: "现金", audio: "cash.wav" },
                { word: "charge", meaning: "收费", audio: "charge.wav" },
                { word: "check", meaning: "支票", audio: "check.wav" },
                { word: "claim", meaning: "索赔", audio: "claim.wav" },
                { word: "client", meaning: "客户", audio: "client.wav" },
                { word: "coin", meaning: "硬币", audio: "coin.wav" },
                { word: "collapse", meaning: "崩盘", audio: "collapse.wav" },
                { word: "commerce", meaning: "商业", audio: "commerce.wav" },
                { word: "commission", meaning: "佣金", audio: "commission.wav" },
                { word: "commodity", meaning: "商品", audio: "commodity.wav" },
                { word: "compensate", meaning: "补偿", audio: "compensate.wav" },
                { word: "compete", meaning: "竞争", audio: "compete.wav" },
                { word: "compound", meaning: "复利", audio: "compound.wav" },
                { word: "contract", meaning: "合同", audio: "contract.wav" },
                { word: "corporate", meaning: "公司的", audio: "corporate.wav" },
                { word: "cost", meaning: "成本", audio: "cost.wav" },
                { word: "coupon", meaning: "优惠券", audio: "coupon.wav" },
                { word: "crash", meaning: "崩盘", audio: "crash.wav" },
                { word: "credit", meaning: "信用", audio: "credit.wav" },
                { word: "currency", meaning: "货币", audio: "currency.wav" },
                { word: "custom", meaning: "关税; 海关", audio: "custom.wav" },
                { word: "customer", meaning: "顾客", audio: "customer.wav" },
                { word: "deal", meaning: "交易", audio: "deal.wav" },
                { word: "debt", meaning: "债务", audio: "debt.wav" },
                { word: "decline", meaning: "下降", audio: "decline.wav" },
                { word: "default", meaning: "违约", audio: "default.wav" },
                { word: "deficit", meaning: "赤字", audio: "deficit.wav" },
                { word: "demand", meaning: "需求", audio: "demand.wav" },
                { word: "deposit", meaning: "存款; 保证金", audio: "deposit.wav" },
                { word: "depreciate", meaning: "贬值", audio: "depreciate.wav" },
                { word: "discount", meaning: "折扣", audio: "discount.wav" },
                { word: "dividend", meaning: "股息", audio: "dividend.wav" },
                { word: "earnings", meaning: "收益", audio: "earnings.wav" },
                { word: "economy", meaning: "经济", audio: "economy.wav" },
                { word: "enterprise", meaning: "企业", audio: "enterprise.wav" },
                { word: "equity", meaning: "股权", audio: "equity.wav" },
                { word: "estimate", meaning: "估值; 预估", audio: "estimate.wav" },
                { word: "exchange", meaning: "外汇; 交易所", audio: "exchange.wav" },
                { word: "expense", meaning: "费用", audio: "expense.wav" },
                { word: "export", meaning: "出口", audio: "export.wav" },
                { word: "fee", meaning: "费用", audio: "fee.wav" },
                { word: "finance", meaning: "金融", audio: "finance.wav" },
                { word: "fiscal", meaning: "财政的", audio: "fiscal.wav" },
                { word: "forecast", meaning: "预测", audio: "forecast.wav" },
                { word: "fortune", meaning: "财富", audio: "fortune.wav" },
                { word: "franchise", meaning: "特许经营权", audio: "franchise.wav" },
                { word: "fraud", meaning: "欺诈; 金融诈骗", audio: "fraud.wav" },
                { word: "fund", meaning: "基金", audio: "fund.wav" },
                { word: "gain", meaning: "收益", audio: "gain.wav" },
                { word: "goods", meaning: "商品", audio: "goods.wav" },
                { word: "gross", meaning: "总额的; 毛利的", audio: "gross.wav" },
                { word: "growth", meaning: "增长", audio: "growth.wav" },
                { word: "guarantee", meaning: "保证", audio: "guarantee.wav" },
                { word: "hedge", meaning: "对冲", audio: "hedge.wav" },
                { word: "import", meaning: "进口", audio: "import.wav" },
                { word: "income", meaning: "收入", audio: "income.wav" },
                { word: "index", meaning: "指数", audio: "index.wav" },
                { word: "inflation", meaning: "通货膨胀", audio: "inflation.wav" },
                { word: "insure", meaning: "投保; 承保", audio: "insure.wav" },
                { word: "interest", meaning: "利息", audio: "interest.wav" },
                { word: "invest", meaning: "投资", audio: "invest.wav" },
                { word: "investor", meaning: "投资者", audio: "investor.wav" },
                { word: "invoice", meaning: "发票", audio: "invoice.wav" },
                { word: "lease", meaning: "租赁", audio: "lease.wav" },
                { word: "lend", meaning: "贷出", audio: "lend.wav" },
                { word: "leverage", meaning: "杠杆", audio: "leverage.wav" },
                { word: "liability", meaning: "负债", audio: "liability.wav" },
                { word: "liquid", meaning: "流动性的", audio: "liquid.wav" },
                { word: "loan", meaning: "贷款", audio: "loan.wav" },
                { word: "loss", meaning: "损失", audio: "loss.wav" },
                { word: "margin", meaning: "保证金; 利润率", audio: "margin.wav" },
                { word: "market", meaning: "市场", audio: "market.wav" },
                { word: "merge", meaning: "合并", audio: "merge.wav" },
                { word: "monopoly", meaning: "垄断", audio: "monopoly.wav" },
                { word: "mortgage", meaning: "抵押", audio: "mortgage.wav" },
                { word: "mutual", meaning: "共同基金的", audio: "mutual.wav" },
                { word: "negotiate", meaning: "谈判", audio: "negotiate.wav" },
                { word: "net", meaning: "净值; 净额", audio: "net.wav" },
                { word: "offset", meaning: "抵消", audio: "offset.wav" },
                { word: "overhead", meaning: "管理费用", audio: "overhead.wav" },
                { word: "partner", meaning: "合伙人", audio: "partner.wav" },
                { word: "patent", meaning: "专利", audio: "patent.wav" },
                { word: "penalty", meaning: "罚款; 违约金", audio: "penalty.wav" },
                { word: "pension", meaning: "养老金", audio: "pension.wav" },
                { word: "portfolio", meaning: "投资组合", audio: "portfolio.wav" },
                { word: "premium", meaning: "溢价", audio: "premium.wav" },
                { word: "price", meaning: "价格", audio: "price.wav" },
                { word: "principal", meaning: "本金", audio: "principal.wav" },
                { word: "profit", meaning: "利润", audio: "profit.wav" },
                { word: "property", meaning: "财产", audio: "property.wav" },
                { word: "purchase", meaning: "购买", audio: "purchase.wav" },
                { word: "quarter", meaning: "季度", audio: "quarter.wav" },
                { word: "quota", meaning: "配额", audio: "quota.wav" },
                { word: "rate", meaning: "利率; 汇率", audio: "rate.wav" },
                { word: "receipt", meaning: "收据", audio: "receipt.wav" },
                { word: "recession", meaning: "经济衰退", audio: "recession.wav" },
                { word: "refund", meaning: "退款", audio: "refund.wav" },
                { word: "regulate", meaning: "监管", audio: "regulate.wav" },
                { word: "rent", meaning: "租金; 租赁", audio: "rent.wav" },
                { word: "retail", meaning: "零售", audio: "retail.wav" },
                { word: "retire", meaning: "退休", audio: "retire.wav" },
                { word: "return", meaning: "回报; 收益率", audio: "return.wav" },
                { word: "revenue", meaning: "收入", audio: "revenue.wav" },
                { word: "risk", meaning: "风险", audio: "risk.wav" },
                { word: "salary", meaning: "薪水", audio: "salary.wav" },
                { word: "security", meaning: "证券", audio: "security.wav" },
                { word: "share", meaning: "股份", audio: "share.wav" },
                { word: "shortage", meaning: "短缺", audio: "shortage.wav" },
                { word: "speculate", meaning: "投机", audio: "speculate.wav" },
                { word: "stake", meaning: "股份; 权益", audio: "stake.wav" },
                { word: "stock", meaning: "股票", audio: "stock.wav" },
                { word: "subsidy", meaning: "补贴", audio: "subsidy.wav" },
                { word: "surplus", meaning: "盈余; 顺差", audio: "surplus.wav" },
                { word: "tariff", meaning: "关税", audio: "tariff.wav" },
                { word: "tax", meaning: "税", audio: "tax.wav" },
                { word: "tender", meaning: "投标", audio: "tender.wav" },
                { word: "trade", meaning: "贸易", audio: "trade.wav" },
                { word: "transaction", meaning: "交易", audio: "transaction.wav" },
                { word: "treasury", meaning: "财政部", audio: "treasury.wav" },
                { word: "turnover", meaning: "营业额", audio: "turnover.wav" },
                { word: "utility", meaning: "公用事业", audio: "utility.wav" },
                { word: "value", meaning: "价值", audio: "value.wav" },
                { word: "venture", meaning: "风险投资", audio: "venture.wav" },
                { word: "wage", meaning: "工资", audio: "wage.wav" },
                { word: "wealth", meaning: "财富", audio: "wealth.wav" },
                { word: "wholesale", meaning: "批发", audio: "wholesale.wav" },
                { word: "withdraw", meaning: "提取", audio: "withdraw.wav" },
                { word: "yield", meaning: "收益率", audio: "yield.wav" }
            ]
        }
    }
});
