#!/usr/bin/env python3
"""
Generate 19 scene-based wordbook JS files from Oxford 5000 CSV data.
Reads oxford_5000_cleaned.csv, maps words to scene categories,
and outputs registerWordbook() JS files for each scene.

Scenes: food, clothing, home, transport, health, shopping, nature,
        entertainment, travel, work, school, social,
        fitness, music, animals, plants, festivals, cooking, law
"""

import csv
import os

# --- Paths ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(SCRIPT_DIR, 'oxford_5000_cleaned.csv')
AUDIO_DIR = os.path.join(SCRIPT_DIR, 'tts_delivery', 'audio')
WORDBOOKS_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), 'wordbooks')

# --- Extra translations for words NOT in Oxford 5000 CSV ---
EXTRA_TRANSLATIONS = {
    'brochure': '手册',
    'excursion': '短途旅行',
    'safari': '狩猎旅行',
    'pilgrimage': '朝圣',
    'itinerary': '行程',
    'hostel': '旅社',
    'motel': '汽车旅馆',
    'inn': '旅馆',
    'paradise': '天堂',
    'postcard': '明信片',
    'sightseeing': '观光',
    'souvenir': '纪念品',
    'wander': '漫步',
    'visa': '签证',
    'baggage': '行李',
    'backpack': '背包',
    'landmark': '地标',
    'scenery': '风景',
    'voyage': '航行',
    'cereal': '谷物',
    'fridge': '冰箱',
    'garlic': '大蒜',
    'grill': '烧烤',
    'grocery': '杂货',
    'lettuce': '生菜',
    'microwave': '微波炉',
    'mushroom': '蘑菇',
    'olive': '橄榄',
    'organic': '有机的',
    'pasta': '意大利面',
    'peach': '桃子',
    'recipe': '食谱',
    'sausage': '香肠',
    'vinegar': '醋',
    'wheat': '小麦',
    'strawberry': '草莓',
    'snack': '零食',
    'toast': '吐司',
    'collar': '衣领',
    'costume': '服装',
    'elegant': '优雅的',
    'handbag': '手提包',
    'jumper': '毛衣',
    'purse': '钱包',
    'scarf': '围巾',
    'silk': '丝绸',
    'sleeve': '袖子',
    'stripe': '条纹',
    'sunglasses': '太阳镜',
    'underwear': '内衣',
    'vest': '背心',
    'wool': '羊毛',
    'zip': '拉链',
    'attic': '阁楼',
    'balcony': '阳台',
    'basement': '地下室',
    'chimney': '烟囱',
    'couch': '沙发',
    'cupboard': '橱柜',
    'curtain': '窗帘',
    'cushion': '垫子',
    'doorway': '门口',
    'drawer': '抽屉',
    'fireplace': '壁炉',
    'heater': '加热器',
    'landlord': '房东',
    'lawn': '草坪',
    'mat': '垫子',
    'pillow': '枕头',
    'plug': '插头',
    'rug': '地毯',
    'shelf': '架子',
    'shower': '淋浴',
    'sink': '水槽',
    'sofa': '沙发',
    'stairs': '楼梯',
    'tap': '水龙头',
    'terrace': '露台',
    'vacuum': '吸尘器',
    'wardrobe': '衣柜',
    'yard': '院子',
    'accelerate': '加速',
    'brake': '刹车',
    'cab': '出租车',
    'carriage': '车厢',
    'commute': '通勤',
    'crossing': '人行横道',
    'diesel': '柴油',
    'fare': '车费',
    'ferry': '渡轮',
    'gear': '齿轮',
    'harbour': '港口',
    'helicopter': '直升机',
    'highway': '高速公路',
    'junction': '交叉路口',
    'lorry': '卡车',
    'motorway': '高速公路',
    'petrol': '汽油',
    'platform': '站台',
    'rail': '铁轨',
    'runway': '跑道',
    'steer': '驾驶',
    'subway': '地铁',
    'terminal': '航站楼',
    'tire': '轮胎',
    'tunnel': '隧道',
    'van': '货车',
    'vehicle': '车辆',
    'ache': '疼痛',
    'allergy': '过敏',
    'ambulance': '救护车',
    'ankle': '脚踝',
    'bandage': '绷带',
    'chin': '下巴',
    'clinic': '诊所',
    'deaf': '聋的',
    'dentist': '牙医',
    'diabetes': '糖尿病',
    'dizzy': '头晕的',
    'dose': '剂量',
    'elbow': '肘',
    'forehead': '额头',
    'gym': '健身房',
    'headache': '头痛',
    'immune': '免疫的',
    'infection': '感染',
    'injection': '注射',
    'jaw': '下巴',
    'joint': '关节',
    'kidney': '肾脏',
    'liver': '肝脏',
    'lung': '肺',
    'nail': '指甲',
    'nerve': '神经',
    'pharmacy': '药房',
    'pill': '药片',
    'poison': '毒药',
    'pregnant': '怀孕的',
    'prescription': '处方',
    'rib': '肋骨',
    'spine': '脊柱',
    'surgeon': '外科医生',
    'swallow': '吞咽',
    'symptom': '症状',
    'throat': '喉咙',
    'thumb': '拇指',
    'toe': '脚趾',
    'tongue': '舌头',
    'vaccine': '疫苗',
    'virus': '病毒',
    'vitamin': '维生素',
    'waist': '腰',
    'ward': '病房',
    'wheelchair': '轮椅',
    'wound': '伤口',
    'wrist': '手腕',
    'coupon': '优惠券',
    'merchant': '商人',
    'wholesale': '批发',
    'penny': '便士',
    'refund': '退款',
    'retail': '零售',
    'bargain': '讨价还价',
    'receipt': '收据',
    'algebra': '代数',
    'arithmetic': '算术',
    'blackboard': '黑板',
    'encyclopedia': '百科全书',
    'handwriting': '笔迹',
    'headmaster': '校长',
    'notebook': '笔记本',
    'textbook': '课本',
    'undergraduate': '本科生',
    'affection': '感情',
    'awkward': '尴尬的',
    'empathy': '同理心',
    'enthusiasm': '热情',
    'envy': '嫉妒',
    'frustrate': '挫败',
    'grief': '悲伤',
    'irritate': '激怒',
    'jealous': '嫉妒的',
    'quarrel': '争吵',
    'sorrow': '悲伤',
    'tease': '取笑',
    'temper': '脾气',
    'rehearsal': '排练',
    'rhythm': '节奏',
    'sculpture': '雕塑',
    'ballet': '芭蕾',
    'volleyball': '排球',
    'yoga': '瑜伽',
    'recreation': '娱乐',
    'chess': '国际象棋',
    'check-in': '登记入住',
    'accommodation': '住宿',
    'heritage': '遗产',
    'hiking': '远足',
    'resort': '度假胜地',
    'tourism': '旅游业',
    # --- Additional missing translations ---
    # food
    'berry': '浆果',
    'candy': '糖果',
    'cherry': '樱桃',
    'cookie': '饼干',
    'corn': '玉米',
    'dessert': '甜点',
    'dine': '用餐',
    'grape': '葡萄',
    'honey': '蜂蜜',
    'kettle': '水壶',
    'lamb': '羊肉',
    'pea': '豌豆',
    'pie': '馅饼',
    'pizza': '比萨',
    'pork': '猪肉',
    'roast': '烤',
    'steak': '牛排',
    'supper': '晚餐',
    'tomato': '番茄',
    # clothing
    'shorts': '短裤',
    'stain': '污渍',
    'wallet': '钱包',
    # home
    'lock': '锁',
    'tile': '瓷砖',
    # health
    'cough': '咳嗽',
    'teeth': '牙齿',
    # shopping
    'cheque': '支票',
    'mall': '购物中心',
    'supply': '供应',
    # nature
    'breeze': '微风',
    'butterfly': '蝴蝶',
    'deer': '鹿',
    'dolphin': '海豚',
    'ecology': '生态学',
    'eruption': '喷发',
    'fog': '雾',
    'frost': '霜',
    'goat': '山羊',
    'jungle': '丛林',
    'mammal': '哺乳动物',
    'rabbit': '兔子',
    'rainbow': '彩虹',
    'reef': '礁石',
    'shark': '鲨鱼',
    'sunshine': '阳光',
    'thunder': '雷',
    'tiger': '老虎',
    'volcano': '火山',
    'whale': '鲸鱼',
    'wolf': '狼',
    # entertainment
    'athletics': '田径',
    'surf': '冲浪',
    # travel
    'customs': '海关',
    'luggage': '行李',
    'suitcase': '手提箱',
    # work
    'intern': '实习生',
    'overtime': '加班',
    # school
    'diploma': '文凭',
    'graduation': '毕业',
    'grammar': '语法',
    'quiz': '测验',
    'semester': '学期',
    'tutor': '家教',
    'vocabulary': '词汇',
    # social
    'bore': '使厌烦',
    'compliment': '赞美',
    'confuse': '使困惑',
    'hug': '拥抱',
    'thankful': '感激的',
    # fitness
    'abs': '腹肌',
    'aerobic': '有氧运动',
    'agile': '敏捷的',
    'barbell': '杠铃',
    'cardio': '有氧运动',
    'cramp': '抽筋',
    'curl': '弯举',
    'dash': '冲刺',
    'dumbbell': '哑铃',
    'endurance': '耐力',
    'flex': '屈伸',
    'grip': '握力',
    'handball': '手球',
    'hydrate': '补水',
    'instructor': '教练',
    'jog': '慢跑',
    'lunge': '弓步',
    'paddle': '球拍',
    'pedal': '踏板',
    'plank': '平板支撑',
    'rep': '次数',
    'rope': '跳绳',
    'row': '划船',
    'skip': '跳绳',
    'slam': '猛击',
    'spin': '动感单车',
    'squat': '深蹲',
    'stamina': '耐力',
    'stride': '步幅',
    'sweat': '汗水',
    'treadmill': '跑步机',
    'wrestle': '摔跤',
    # music
    'acoustic': '原声的',
    'alto': '中音',
    'amplifier': '放大器',
    'auditorium': '音乐厅',
    'bass': '低音',
    'bell': '铃',
    'blues': '蓝调',
    'bow': '琴弓',
    'brass': '铜管乐器',
    'carol': '颂歌',
    'cello': '大提琴',
    'choir': '合唱团',
    'chord': '和弦',
    'chorus': '合唱',
    'clarinet': '单簧管',
    'clap': '鼓掌',
    'composer': '作曲家',
    'conductor': '指挥',
    'disc': '唱片',
    'drum': '鼓',
    'duet': '二重奏',
    'echo': '回声',
    'encore': '返场',
    'ensemble': '合奏',
    'flute': '长笛',
    'folk': '民谣',
    'genre': '流派',
    'gig': '演出',
    'harp': '竖琴',
    'headphone': '耳机',
    'hip': '嘻哈',
    'horn': '圆号',
    'hymn': '赞美诗',
    'keyboard': '键盘',
    'loop': '循环',
    'loud': '响亮的',
    'lyric': '歌词',
    'melody': '旋律',
    'microphone': '麦克风',
    'percussion': '打击乐',
    'playlist': '播放列表',
    'pop': '流行音乐',
    'punk': '朋克',
    'rap': '说唱',
    'recording': '录音',
    'remix': '混音',
    'scale': '音阶',
    'soprano': '女高音',
    'soul': '灵魂乐',
    'speaker': '扬声器',
    'string': '弦乐',
    'symphony': '交响曲',
    'tempo': '节拍',
    'tenor': '男高音',
    'tune': '曲调',
    'violin': '小提琴',
    'vocal': '声乐的',
    # animals
    'alligator': '鳄鱼',
    'ape': '猿猴',
    'aquarium': '水族馆',
    'beak': '鸟嘴',
    'beetle': '甲虫',
    'buffalo': '水牛',
    'cage': '笼子',
    'camel': '骆驼',
    'chick': '小鸡',
    'claw': '爪子',
    'crocodile': '鳄鱼',
    'crow': '乌鸦',
    'dinosaur': '恐龙',
    'donkey': '驴',
    'dove': '鸽子',
    'duck': '鸭子',
    'eagle': '鹰',
    'endangered': '濒危的',
    'exotic': '异国的',
    'extinction': '灭绝',
    'falcon': '隼',
    'fin': '鱼鳍',
    'flock': '群',
    'fox': '狐狸',
    'frog': '青蛙',
    'fur': '皮毛',
    'goose': '鹅',
    'gorilla': '大猩猩',
    'hamster': '仓鼠',
    'hare': '野兔',
    'hawk': '鹰',
    'hen': '母鸡',
    'herd': '兽群',
    'hound': '猎犬',
    'ivory': '象牙',
    'kangaroo': '袋鼠',
    'kitten': '小猫',
    'leash': '牵引绳',
    'leopard': '豹',
    'lizard': '蜥蜴',
    'mare': '母马',
    'migrate': '迁徙',
    'mosquito': '蚊子',
    'mule': '骡子',
    'nest': '巢',
    'ostrich': '鸵鸟',
    'otter': '水獭',
    'owl': '猫头鹰',
    'ox': '公牛',
    'panda': '熊猫',
    'parrot': '鹦鹉',
    'paw': '爪子',
    'peacock': '孔雀',
    'penguin': '企鹅',
    'pigeon': '鸽子',
    'pony': '小马',
    'predator': '捕食者',
    'prey': '猎物',
    'puppy': '小狗',
    'rat': '老鼠',
    'reptile': '爬行动物',
    'rooster': '公鸡',
    'salmon': '三文鱼',
    'seal': '海豹',
    'shelter': '庇护所',
    'sparrow': '麻雀',
    'spider': '蜘蛛',
    'squirrel': '松鼠',
    'stray': '流浪的',
    'swan': '天鹅',
    'tame': '驯养',
    'tortoise': '陆龟',
    'trunk': '象鼻',
    'turkey': '火鸡',
    'turtle': '海龟',
    'tusk': '象牙',
    'vet': '兽医',
    'veterinarian': '兽医',
    'vulture': '秃鹰',
    'walrus': '海象',
    'zebra': '斑马',
    'zoo': '动物园',
    # plants
    'bamboo': '竹子',
    'bark': '树皮',
    'bloom': '开花',
    'blossom': '花朵',
    'botanical': '植物学的',
    'bouquet': '花束',
    'bud': '芽',
    'bulb': '球茎',
    'cabbage': '卷心菜',
    'cactus': '仙人掌',
    'cedar': '雪松',
    'chestnut': '栗子',
    'clover': '三叶草',
    'coconut': '椰子',
    'compost': '堆肥',
    'daisy': '雏菊',
    'elm': '榆树',
    'fern': '蕨类',
    'fertilizer': '肥料',
    'fig': '无花果',
    'flora': '植物群',
    'fungus': '真菌',
    'hay': '干草',
    'herb': '草药',
    'ivy': '常春藤',
    'lavender': '薰衣草',
    'lily': '百合花',
    'maple': '枫树',
    'melon': '瓜',
    'moss': '苔藓',
    'oak': '橡树',
    'orchid': '兰花',
    'palm': '棕榈树',
    'petal': '花瓣',
    'pine': '松树',
    'plum': '李子',
    'pollen': '花粉',
    'prune': '修剪',
    'pumpkin': '南瓜',
    'rye': '黑麦',
    'shrub': '灌木',
    'sunflower': '向日葵',
    'thorn': '刺',
    'tobacco': '烟草',
    'tulip': '郁金香',
    'vine': '藤蔓',
    'violet': '紫罗兰',
    'weed': '杂草',
    'willow': '柳树',
    # festivals
    'ancestor': '祖先',
    'anniversary': '周年',
    'assembly': '集会',
    'balloon': '气球',
    'banquet': '宴会',
    'bless': '祝福',
    'bride': '新娘',
    'carnival': '嘉年华',
    'confetti': '彩纸',
    'countdown': '倒计时',
    'crown': '皇冠',
    'eve': '前夕',
    'fairy': '仙女',
    'feast': '盛宴',
    'firework': '烟火',
    'float': '花车',
    'glow': '发光',
    'halloween': '万圣节',
    'lantern': '灯笼',
    'luck': '运气',
    'mask': '面具',
    'memorial': '纪念的',
    'miracle': '奇迹',
    'myth': '神话',
    'offering': '供品',
    'parade': '游行',
    'prayer': '祈祷',
    'procession': '游行队伍',
    'reunion': '团聚',
    'ribbon': '丝带',
    'ritual': '仪式',
    'saint': '圣人',
    'thanksgiving': '感恩节',
    'torch': '火炬',
    'treat': '款待',
    'tribute': '致敬',
    'valentine': '情人节',
    'wedding': '婚礼',
    'worship': '崇拜',
    'wrap': '包装',
    # cooking
    'baste': '浇汁',
    'blender': '搅拌机',
    'braise': '炖',
    'broil': '炒',
    'broth': '肉汤',
    'chilli': '辣椒',
    'cinnamon': '肉桂',
    'counter': '操作台',
    'cube': '切丁',
    'defrost': '解冻',
    'dice': '切粒',
    'dressing': '调料',
    'ginger': '姜',
    'grate': '擦磨',
    'gravy': '肉汁',
    'grease': '油脂',
    'grind': '研磨',
    'jar': '罐子',
    'knead': '揉面',
    'ladle': '长柄勺',
    'lid': '盖子',
    'marinade': '腌汁',
    'marinate': '腌制',
    'mash': '捣碎',
    'mince': '切碎',
    'mustard': '芥末',
    'paste': '糊状物',
    'peel': '削皮',
    'pinch': '一撒',
    'poach': '水煮',
    'portion': '一份',
    'refrigerate': '冷藏',
    'rinse': '冲洗',
    'shallow': '浅的',
    'simmer': '慢炖',
    'soak': '浸泡',
    'spatula': '铲刀',
    'spray': '喷洒',
    'sprinkle': '撒',
    'squeeze': '挤压',
    'steam': '蒸',
    'stew': '炖菜',
    'stock': '高汤',
    'stove': '炉子',
    'strain': '过滤',
    'tablespoon': '汤匙',
    'thaw': '解冻',
    'thermometer': '温度计',
    'toss': '拌',
    'trim': '修剪',
    'whip': '打发',
    'whisk': '打蛋器',
    # law
    'abolish': '废除',
    'acquit': '宣判无罪',
    'allege': '指控',
    'arbitrate': '仲裁',
    'arrest': '逮捕',
    'assault': '攻击',
    'attorney': '律师',
    'bail': '保释金',
    'breach': '违反',
    'bribe': '贿赂',
    'clause': '条款',
    'compensation': '赔偿',
    'comply': '遵守',
    'confess': '坦白',
    'confiscate': '没收',
    'convict': '定罪',
    'copyright': '版权',
    'custody': '监禁',
    'deceive': '欺骗',
    'defendant': '被告',
    'detain': '拘留',
    'dispute': '争议',
    'entitle': '给予权利',
    'exempt': '豁免',
    'extradite': '引渡',
    'felony': '重罪',
    'forge': '伪造',
    'guilty': '有罪的',
    'hearing': '听证会',
    'heir': '继承人',
    'imprison': '监禁',
    'indict': '起诉',
    'injustice': '不公',
    'innocent': '无罪的',
    'intellectual': '知识产权',
    'jail': '监狱',
    'jury': '陪审团',
    'juvenile': '少年的',
    'kidnap': '绑架',
    'lawsuit': '诉讼',
    'lawyer': '律师',
    'legitimate': '合法的',
    'licence': '许可证',
    'litigate': '诉讼',
    'misconduct': '不当行为',
    'murder': '谋杀',
    'oath': '宣誓',
    'pardon': '赦免',
    'parole': '假释',
    'plead': '辩护',
    'precedent': '先例',
    'prison': '监狱',
    'prosecute': '起诉',
    'repeal': '废除',
    'rob': '抢劫',
    'sentence': '判刑',
    'settle': '和解',
    'smuggle': '走私',
    'statute': '法规',
    'steal': '偷窃',
    'sue': '起诉',
    'suspect': '嫌疑人',
    'testify': '作证',
    'testimony': '证词',
    'theft': '盗窃',
    'tribunal': '法庭',
    'verdict': '裁决',
    'violate': '违反',
    'warrant': '搜查令',
    'witness': '证人',
    # --- Additional missing translations ---
    'arch': '拱; 弓步',
    'dodge': '闪避',
    'drill': '训练',
    'racket': '球拍',
    'sprint': '冲刺',
    'applause': '掌声',
    'performer': '表演者',
    'ant': '蚂蚁',
    'bull': '公牛',
    'polar': '极地的',
    'decay': '腐烂',
    'fertile': '肥沃的',
    'meadow': '草地',
    'pear': '梨',
    'rainforest': '雨林',
    'vegetation': '植被',
    'barbecue': '烧烤',
    'calendar': '日历',
    'dragon': '龙',
    'picnic': '野餐',
    'basin': '盆',
    'bankrupt': '破产的',
    'counsel': '律师; 忠告',
    'decree': '法令',
    'discriminate': '歧视',
    'legislate': '立法',
    'liability': '责任; 债务',
}

# --- Scene categories ---
SCENE_CATEGORIES = {
    'food': {
        'name': '食物饮料',
        'emoji': '\U0001f354',
        'description': '食物、饮料、烹饪相关词汇',
        'words': [
            'apple', 'banana', 'bean', 'beef', 'beer', 'berry', 'biscuit', 'bite', 'boil',
            'bottle', 'bowl', 'bread', 'breakfast', 'butter', 'cafe', 'cake', 'candy',
            'carrot', 'cereal', 'cheese', 'chef', 'cherry', 'chicken', 'chip', 'chocolate',
            'chop', 'coffee', 'cook', 'cookie', 'corn', 'cream', 'cup', 'dairy', 'delicious',
            'dessert', 'diet', 'dine', 'dinner', 'dish', 'drink', 'eat', 'egg', 'fat',
            'feed', 'fish', 'flavour', 'flour', 'food', 'fork', 'fresh', 'fridge', 'fruit',
            'fry', 'garlic', 'glass', 'grain', 'grape', 'grill', 'grocery', 'honey', 'hungry',
            'ingredient', 'jam', 'juice', 'kettle', 'kitchen', 'knife', 'lamb', 'lemon',
            'lettuce', 'lunch', 'meal', 'meat', 'menu', 'microwave', 'milk', 'mix',
            'mushroom', 'nut', 'oil', 'olive', 'onion', 'orange', 'organic', 'oven',
            'pan', 'pasta', 'pea', 'peach', 'pepper', 'pie', 'pizza', 'plate', 'pork',
            'pot', 'potato', 'pour', 'protein', 'raw', 'recipe', 'restaurant', 'rice',
            'roast', 'salad', 'salt', 'sandwich', 'sauce', 'sausage', 'slice', 'snack',
            'soup', 'spice', 'spoon', 'steak', 'stir', 'stomach', 'strawberry', 'sugar',
            'supper', 'sweet', 'taste', 'tea', 'toast', 'tomato', 'vegetable', 'vinegar',
            'water', 'wheat', 'wine',
        ]
    },
    'clothing': {
        'name': '服饰穿着',
        'emoji': '\U0001f455',
        'description': '衣服、鞋帽、配饰相关词汇',
        'words': [
            'belt', 'boot', 'button', 'cap', 'clothes', 'clothing', 'coat', 'collar',
            'comfortable', 'cotton', 'costume', 'designer', 'dress', 'elegant', 'fabric',
            'fashion', 'fit', 'formal', 'glove', 'handbag', 'hat', 'heel', 'jacket',
            'jeans', 'jewellery', 'jumper', 'label', 'leather', 'material', 'outfit',
            'pair', 'pants', 'pattern', 'pocket', 'purse', 'ring', 'scarf', 'shirt',
            'shoe', 'shop', 'shorts', 'silk', 'size', 'skirt', 'sleeve', 'sock',
            'stain', 'stripe', 'style', 'suit', 'sunglasses', 'sweater', 'tie', 'tight',
            'top', 'towel', 'trousers', 'underwear', 'uniform', 'vest', 'wallet', 'wear',
            'wool', 'zip',
        ]
    },
    'home': {
        'name': '家居房屋',
        'emoji': '\U0001f3e0',
        'description': '房屋、家具、家电相关词汇',
        'words': [
            'apartment', 'attic', 'balcony', 'basement', 'bathroom', 'bed', 'bedroom',
            'blanket', 'blind', 'brick', 'brush', 'build', 'carpet', 'ceiling', 'chair',
            'chimney', 'clean', 'clock', 'corridor', 'couch', 'cupboard', 'curtain',
            'cushion', 'decoration', 'desk', 'door', 'doorway', 'drawer', 'dust',
            'electricity', 'entrance', 'estate', 'fence', 'fireplace', 'flat', 'floor',
            'furniture', 'garage', 'garden', 'gate', 'hall', 'heater', 'home', 'house',
            'household', 'housing', 'iron', 'key', 'kitchen', 'lamp', 'landlord',
            'lawn', 'light', 'living', 'lock', 'mat', 'mirror', 'mortgage', 'neighbour',
            'oven', 'paint', 'path', 'pillow', 'pipe', 'plug', 'property', 'rent',
            'repair', 'roof', 'room', 'rug', 'shelf', 'shower', 'sink', 'sofa', 'stairs',
            'tap', 'tenant', 'terrace', 'tile', 'toilet', 'vacuum', 'wall', 'wardrobe',
            'wash', 'window', 'yard',
        ]
    },
    'transport': {
        'name': '交通出行',
        'emoji': '\U0001f697',
        'description': '交通工具、道路、出行相关词汇',
        'words': [
            'accelerate', 'accident', 'airline', 'airport', 'bicycle', 'bike', 'board',
            'brake', 'bridge', 'bus', 'cab', 'car', 'cargo', 'carriage', 'coach',
            'commute', 'crash', 'cross', 'crossing', 'cruise', 'cycle', 'delay',
            'deliver', 'departure', 'destination', 'diesel', 'direction', 'distance',
            'drive', 'driver', 'engine', 'exit', 'fare', 'ferry', 'flight', 'fuel',
            'garage', 'gear', 'harbour', 'helicopter', 'highway', 'jam', 'journey',
            'junction', 'lane', 'lorry', 'map', 'motorway', 'park', 'parking',
            'passenger', 'path', 'petrol', 'platform', 'port', 'rail', 'railway',
            'ride', 'road', 'route', 'runway', 'sail', 'seat', 'ship', 'signal',
            'speed', 'station', 'steer', 'stop', 'street', 'subway', 'taxi', 'terminal',
            'ticket', 'tire', 'traffic', 'train', 'transport', 'trip', 'truck', 'tunnel',
            'turn', 'van', 'vehicle', 'wheel',
        ]
    },
    'health': {
        'name': '健康身体',
        'emoji': '\U0001f3e5',
        'description': '身体、疾病、医疗、健身相关词汇',
        'words': [
            'ache', 'allergy', 'ambulance', 'ankle', 'appointment', 'arm', 'back',
            'bandage', 'blood', 'body', 'bone', 'brain', 'breath', 'breathe', 'burn',
            'cancer', 'chest', 'chin', 'clinic', 'cold', 'cough', 'cure', 'deaf',
            'dentist', 'depression', 'diabetes', 'diagnosis', 'diet', 'disability',
            'disease', 'dizzy', 'doctor', 'dose', 'drug', 'ear', 'elbow', 'emergency',
            'examine', 'exercise', 'eye', 'face', 'fat', 'fever', 'finger', 'fitness',
            'flu', 'foot', 'forehead', 'gym', 'hair', 'hand', 'head', 'headache',
            'heal', 'health', 'healthy', 'hear', 'heart', 'heel', 'hip', 'hospital',
            'hurt', 'ill', 'illness', 'immune', 'infection', 'injection', 'injury',
            'jaw', 'joint', 'kidney', 'knee', 'leg', 'lip', 'liver', 'lung', 'medicine',
            'mental', 'mouth', 'muscle', 'nail', 'neck', 'nerve', 'nose', 'nurse',
            'operate', 'operation', 'organ', 'pain', 'painful', 'patient', 'pharmacy',
            'physical', 'pill', 'poison', 'pregnant', 'prescription', 'pulse', 'recover',
            'recovery', 'relax', 'rib', 'shoulder', 'sick', 'skin', 'sleep', 'spine',
            'stomach', 'stress', 'stroke', 'surgeon', 'surgery', 'swallow', 'symptom',
            'teeth', 'therapy', 'throat', 'thumb', 'toe', 'tongue', 'tooth', 'treatment',
            'vaccine', 'virus', 'vitamin', 'waist', 'ward', 'weight', 'wheelchair',
            'wound', 'wrist',
        ]
    },
    'shopping': {
        'name': '购物消费',
        'emoji': '\U0001f6d2',
        'description': '购物、消费、金钱相关词汇',
        'words': [
            'account', 'afford', 'bargain', 'bill', 'brand', 'budget', 'buy', 'cash',
            'cent', 'change', 'charge', 'cheap', 'cheque', 'coin', 'consumer', 'cost',
            'coupon', 'credit', 'currency', 'customer', 'deal', 'debt', 'deliver',
            'delivery', 'demand', 'department', 'deposit', 'discount', 'dollar', 'earn',
            'exchange', 'expensive', 'export', 'fee', 'goods', 'guarantee', 'import',
            'income', 'insurance', 'invest', 'investment', 'item', 'loan', 'luxury',
            'mall', 'market', 'merchant', 'offer', 'online', 'order', 'owe', 'own',
            'package', 'pay', 'payment', 'penny', 'pound', 'price', 'produce', 'product',
            'profit', 'purchase', 'quality', 'quantity', 'receipt', 'refund', 'retail',
            'sale', 'save', 'sell', 'service', 'shelf', 'shop', 'shopping', 'spend',
            'store', 'supply', 'tax', 'trade', 'value', 'wallet', 'wholesale', 'worth',
        ]
    },
    'nature': {
        'name': '天气自然',
        'emoji': '\U0001f324\ufe0f',
        'description': '天气、动植物、环境相关词汇',
        'words': [
            'air', 'animal', 'atmosphere', 'autumn', 'bay', 'beach', 'bear', 'bee',
            'bird', 'blow', 'branch', 'breeze', 'butterfly', 'cat', 'cattle', 'cave',
            'chicken', 'climate', 'cloud', 'coast', 'cold', 'continent', 'cow',
            'creature', 'crop', 'deer', 'desert', 'dog', 'dolphin', 'drought',
            'dust', 'earth', 'earthquake', 'ecology', 'elephant', 'emission',
            'environment', 'eruption', 'evolution', 'farm', 'feather', 'field',
            'fish', 'flood', 'flower', 'fly', 'fog', 'forest', 'freeze', 'frost',
            'garden', 'globe', 'goat', 'grass', 'harvest', 'heat', 'hill', 'horse',
            'hurricane', 'ice', 'insect', 'island', 'jungle', 'lake', 'landscape',
            'leaf', 'lion', 'mammal', 'monkey', 'moon', 'mountain', 'mud', 'nature',
            'ocean', 'pet', 'pig', 'planet', 'plant', 'pollution', 'pond', 'rabbit',
            'rain', 'rainbow', 'recycle', 'reef', 'river', 'rock', 'root', 'sand',
            'sea', 'season', 'seed', 'shark', 'sheep', 'shell', 'shore', 'sky',
            'snake', 'snow', 'soil', 'species', 'spring', 'star', 'storm', 'stream',
            'summer', 'sun', 'sunshine', 'temperature', 'thunder', 'tide', 'tiger',
            'tree', 'tropical', 'valley', 'volcano', 'warm', 'waste', 'wave', 'weather',
            'whale', 'wildlife', 'wind', 'winter', 'wolf', 'wood', 'worm',
        ]
    },
    'entertainment': {
        'name': '娱乐爱好',
        'emoji': '\U0001f3ad',
        'description': '音乐、体育、艺术、游戏相关词汇',
        'words': [
            'act', 'action', 'actor', 'actress', 'adventure', 'album', 'art', 'artist',
            'athletics', 'audience', 'ballet', 'band', 'baseball', 'basketball', 'beat',
            'camera', 'camp', 'captain', 'celebrate', 'champion', 'channel', 'chess',
            'cinema', 'climb', 'club', 'coach', 'comedy', 'compete', 'competition',
            'concert', 'contest', 'creative', 'dance', 'director', 'drama', 'draw',
            'drawing', 'entertainment', 'episode', 'exhibition', 'fan', 'fiction',
            'film', 'football', 'fun', 'gallery', 'game', 'goal', 'golf', 'guitar',
            'hero', 'hobby', 'holiday', 'instrument', 'jazz', 'joke', 'kick', 'league',
            'leisure', 'match', 'medal', 'media', 'movie', 'museum', 'music', 'musical',
            'novel', 'opera', 'orchestra', 'outdoor', 'paint', 'painting', 'party',
            'perform', 'performance', 'photo', 'photograph', 'photography', 'piano',
            'play', 'player', 'plot', 'poem', 'poet', 'poetry', 'pool', 'race',
            'recreation', 'record', 'rehearsal', 'relax', 'rhythm', 'rock', 'role',
            'run', 'scene', 'score', 'screen', 'sculpture', 'series', 'show', 'sing',
            'singer', 'ski', 'soccer', 'song', 'sport', 'stadium', 'stage', 'star',
            'studio', 'surf', 'swim', 'team', 'tennis', 'theatre', 'tour', 'tournament',
            'video', 'volleyball', 'yoga',
        ]
    },
    'travel': {
        'name': '旅行酒店',
        'emoji': '\u2708\ufe0f',
        'description': '旅游、住宿、观光相关词汇',
        'words': [
            'abroad', 'accommodation', 'adventure', 'airline', 'airport', 'arrival',
            'attraction', 'backpack', 'baggage', 'beach', 'board', 'book', 'border',
            'brochure', 'cabin', 'camera', 'camp', 'cancel', 'check-in', 'coast',
            'confirm', 'cruise', 'culture', 'currency', 'customs', 'delay', 'depart',
            'departure', 'destination', 'embassy', 'excursion', 'explore', 'fare',
            'ferry', 'flight', 'foreign', 'guide', 'harbour', 'heritage', 'hiking',
            'holiday', 'hostel', 'hotel', 'inn', 'island', 'itinerary', 'journey',
            'landmark', 'language', 'leisure', 'local', 'luggage', 'map', 'monument',
            'motel', 'museum', 'overseas', 'pack', 'palace', 'paradise', 'passenger',
            'passport', 'photo', 'pilgrimage', 'port', 'postcard', 'reception',
            'reservation', 'resort', 'return', 'route', 'ruin', 'safari', 'scenery',
            'sightseeing', 'souvenir', 'suitcase', 'temple', 'terminal', 'ticket',
            'tour', 'tourism', 'tourist', 'translate', 'trip', 'vacation', 'visa',
            'visit', 'voyage', 'wander',
        ]
    },
    'work': {
        'name': '工作职场',
        'emoji': '\U0001f4bc',
        'description': '职业、办公、商务相关词汇',
        'words': [
            'accountant', 'agency', 'agenda', 'ambition', 'applicant', 'application',
            'apply', 'appoint', 'appointment', 'assistant', 'authority', 'boss',
            'brand', 'business', 'candidate', 'career', 'chairman', 'client',
            'colleague', 'commission', 'committee', 'company', 'conference', 'consultant',
            'contract', 'cooperate', 'corporate', 'corporation', 'deal', 'deadline',
            'demand', 'department', 'deputy', 'director', 'dismiss', 'document',
            'duty', 'earn', 'economy', 'efficiency', 'employ', 'employee', 'employer',
            'employment', 'enterprise', 'entrepreneur', 'executive', 'experience',
            'export', 'factory', 'firm', 'hire', 'human', 'import', 'income',
            'industry', 'intern', 'interview', 'invest', 'investment', 'job', 'labour',
            'lead', 'leadership', 'manage', 'management', 'manager', 'manufacture',
            'marketing', 'meeting', 'negotiate', 'network', 'occupation', 'office',
            'operate', 'organization', 'overtime', 'partner', 'partnership', 'pension',
            'position', 'profession', 'professional', 'profit', 'project', 'promote',
            'promotion', 'proposal', 'qualify', 'recruit', 'reference', 'resign',
            'responsibility', 'resume', 'retire', 'retirement', 'role', 'salary',
            'schedule', 'sector', 'shift', 'skill', 'staff', 'strategy', 'succeed',
            'success', 'supervisor', 'task', 'team', 'trade', 'training', 'union',
            'volunteer', 'wage', 'work', 'worker', 'workplace',
        ]
    },
    'school': {
        'name': '学校教育',
        'emoji': '\U0001f3eb',
        'description': '学校、学习、考试相关词汇',
        'words': [
            'academic', 'academy', 'algebra', 'arithmetic', 'assignment', 'biology',
            'blackboard', 'book', 'campus', 'certificate', 'chapter', 'chemistry',
            'class', 'classroom', 'college', 'composition', 'concentrate', 'course',
            'curriculum', 'debate', 'degree', 'dictionary', 'diploma', 'discipline',
            'education', 'elementary', 'encyclopedia', 'engineering', 'essay', 'exam',
            'examination', 'exercise', 'experiment', 'faculty', 'fail', 'geography',
            'grade', 'graduate', 'graduation', 'grammar', 'handwriting', 'headmaster',
            'history', 'homework', 'instruction', 'knowledge', 'language', 'learn',
            'lecture', 'lesson', 'level', 'library', 'literature', 'major', 'mark',
            'master', 'mathematics', 'memory', 'minor', 'note', 'notebook', 'paragraph',
            'pass', 'pen', 'pencil', 'philosophy', 'physics', 'practice', 'primary',
            'principal', 'professor', 'program', 'progress', 'project', 'pupil',
            'qualification', 'quiz', 'read', 'reading', 'register', 'research',
            'result', 'review', 'revision', 'scholar', 'scholarship', 'school',
            'science', 'secondary', 'semester', 'skill', 'student', 'study', 'subject',
            'teach', 'teacher', 'term', 'test', 'textbook', 'theory', 'tutor',
            'undergraduate', 'university', 'vocabulary', 'write', 'writing',
        ]
    },
    'social': {
        'name': '社交情感',
        'emoji': '\U0001f4ac',
        'description': '情感、社交、人际关系相关词汇',
        'words': [
            'admire', 'affection', 'afraid', 'agree', 'alone', 'anger', 'angry',
            'annoy', 'anxious', 'apologize', 'argue', 'argument', 'ashamed',
            'attitude', 'attract', 'awkward', 'blame', 'bore', 'bother', 'brave',
            'calm', 'care', 'celebrate', 'cheer', 'comfort', 'communicate',
            'communication', 'community', 'companion', 'complain', 'compliment',
            'concern', 'confidence', 'confident', 'confuse', 'congratulate',
            'conversation', 'cry', 'culture', 'curious', 'date', 'delight',
            'depressed', 'desire', 'disappoint', 'emotion', 'emotional', 'empathy',
            'encourage', 'enthusiasm', 'envy', 'excuse', 'family', 'fear', 'feel',
            'feeling', 'forgive', 'friend', 'friendly', 'friendship', 'frustrate',
            'generous', 'gentle', 'grateful', 'greet', 'grief', 'guilt', 'happiness',
            'happy', 'hate', 'honest', 'hope', 'hug', 'humour', 'impress', 'inspire',
            'introduce', 'invite', 'irritate', 'jealous', 'joy', 'kind', 'kiss',
            'laugh', 'lonely', 'love', 'marry', 'mood', 'neighbour', 'nervous',
            'offend', 'opinion', 'passion', 'patient', 'personality', 'pity', 'pleased',
            'polite', 'praise', 'pride', 'promise', 'proud', 'quarrel', 'regret',
            'reject', 'relationship', 'relief', 'respect', 'romance', 'romantic',
            'rude', 'sad', 'satisfy', 'shame', 'share', 'shock', 'shy', 'sincere',
            'smile', 'social', 'sorrow', 'sorry', 'sympathy', 'tease', 'temper',
            'tender', 'thankful', 'trust', 'upset', 'welcome', 'wish', 'worry',
        ]
    },
    'fitness': {
        'name': '\u8fd0\u52a8\u5065\u8eab',
        'emoji': '\U0001f3cb\ufe0f',
        'description': '\u7403\u7c7b\u3001\u5065\u8eab\u5668\u6750\u3001\u8fd0\u52a8\u52a8\u4f5c\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'abs', 'aerobic', 'agile', 'arch', 'athletics', 'balance', 'ball',
            'band', 'bar', 'barbell', 'basketball', 'bat', 'bench', 'bend',
            'bicycle', 'block', 'body', 'bounce', 'bowl', 'box', 'breathe',
            'burn', 'cardio', 'catch', 'chase', 'chest', 'circuit', 'climb',
            'club', 'coach', 'compete', 'cool', 'core', 'court', 'cramp',
            'cross', 'curl', 'cycle', 'dash', 'defend', 'dive', 'dodge',
            'drill', 'dumbbell', 'endurance', 'energy', 'equipment', 'exercise',
            'extend', 'fat', 'field', 'fit', 'fitness', 'flex', 'football',
            'goal', 'golf', 'grip', 'gym', 'handball', 'health', 'heart',
            'hockey', 'hydrate', 'injury', 'instructor', 'interval', 'jog',
            'jump', 'kick', 'knee', 'lap', 'lean', 'leg', 'lift', 'lunge',
            'marathon', 'mat', 'match', 'medal', 'motion', 'muscle', 'net',
            'pace', 'paddle', 'pass', 'pedal', 'pitch', 'plank', 'play',
            'pool', 'pose', 'press', 'protein', 'pull', 'pulse', 'punch',
            'push', 'race', 'racket', 'recover', 'rep', 'rest', 'ring',
            'rope', 'row', 'rugby', 'run', 'serve', 'set', 'shoot',
            'ski', 'skip', 'slam', 'soccer', 'speed', 'spin', 'sprint',
            'squat', 'stadium', 'stamina', 'step', 'stretch', 'stride',
            'strike', 'stroke', 'surf', 'sweat', 'swim', 'swing', 'team',
            'tennis', 'throw', 'track', 'train', 'trainer', 'treadmill',
            'trophy', 'volleyball', 'walk', 'warm', 'weight', 'wrestle', 'yoga',
        ]
    },
    'music': {
        'name': '\u97f3\u4e50\u4e50\u5668',
        'emoji': '\U0001f3b5',
        'description': '\u4e50\u5668\u540d\u79f0\u3001\u97f3\u4e50\u672f\u8bed\u3001\u6d41\u6d3e\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'acoustic', 'album', 'alto', 'amplifier', 'applause', 'arrange',
            'audience', 'auditorium', 'band', 'bass', 'beat', 'bell', 'blow',
            'blues', 'bow', 'brass', 'broadcast', 'carol', 'cello', 'chamber',
            'channel', 'choir', 'chord', 'chorus', 'clarinet', 'classic',
            'classical', 'clap', 'compose', 'composer', 'composition', 'concert',
            'conduct', 'conductor', 'dance', 'digital', 'disc', 'download',
            'drum', 'duet', 'dynamic', 'echo', 'electric', 'electronic',
            'encore', 'ensemble', 'fade', 'fan', 'festival', 'flute', 'folk',
            'frequency', 'genre', 'gig', 'guitar', 'harmony', 'harp',
            'headphone', 'hip', 'horn', 'hymn', 'instrument', 'jazz', 'key',
            'keyboard', 'live', 'loop', 'loud', 'lyric', 'march', 'master',
            'melody', 'microphone', 'mix', 'note', 'opera', 'orchestra',
            'organ', 'original', 'percussion', 'perform', 'performance',
            'performer', 'piano', 'pitch', 'play', 'playlist', 'pop',
            'practice', 'producer', 'punk', 'rap', 'record', 'recording',
            'rehearsal', 'release', 'remix', 'rhythm', 'rock', 'scale',
            'score', 'sing', 'singer', 'solo', 'song', 'soprano', 'soul',
            'sound', 'speaker', 'stage', 'stream', 'string', 'studio',
            'symphony', 'tempo', 'tenor', 'tone', 'tour', 'track', 'tune',
            'violin', 'vocal', 'voice', 'volume',
        ]
    },
    'animals': {
        'name': '\u5ba0\u7269\u52a8\u7269',
        'emoji': '\U0001f43e',
        'description': '\u52a8\u7269\u79cd\u7c7b\u3001\u5ba0\u7269\u62a4\u7406\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'adopt', 'alligator', 'ant', 'ape', 'aquarium', 'bat', 'beak',
            'bear', 'beast', 'bee', 'beetle', 'bird', 'bite', 'breed',
            'buffalo', 'bug', 'bull', 'butterfly', 'cage', 'camel', 'cat',
            'cattle', 'chick', 'chicken', 'claw', 'collar', 'cow', 'creature',
            'crocodile', 'crow', 'deer', 'dinosaur', 'dog', 'dolphin', 'donkey',
            'dove', 'duck', 'eagle', 'elephant', 'endangered', 'evolve',
            'exotic', 'extinction', 'falcon', 'farm', 'feather', 'feed',
            'fin', 'fish', 'flock', 'fly', 'fox', 'frog', 'fur', 'goat',
            'goose', 'gorilla', 'habitat', 'hamster', 'hare', 'hawk', 'hen',
            'herd', 'horn', 'horse', 'hound', 'hunt', 'insect', 'ivory',
            'kangaroo', 'kitten', 'lamb', 'leash', 'leopard', 'lion', 'lizard',
            'mammal', 'mare', 'migrate', 'monkey', 'mosquito', 'mouse', 'mule',
            'nest', 'ostrich', 'otter', 'owl', 'ox', 'panda', 'parrot',
            'paw', 'peacock', 'penguin', 'pet', 'pig', 'pigeon', 'polar',
            'pony', 'predator', 'prey', 'puppy', 'rabbit', 'rat', 'reptile',
            'rooster', 'salmon', 'seal', 'shark', 'sheep', 'shell', 'shelter',
            'snake', 'sparrow', 'species', 'spider', 'squirrel', 'stray',
            'swan', 'tail', 'tame', 'tiger', 'tortoise', 'trunk', 'turkey',
            'turtle', 'tusk', 'vet', 'veterinarian', 'vulture', 'walrus',
            'whale', 'wild', 'wildlife', 'wing', 'wolf', 'worm', 'zebra', 'zoo',
        ]
    },
    'plants': {
        'name': '\u690d\u7269\u82b1\u5349',
        'emoji': '\U0001f33f',
        'description': '\u82b1\u3001\u6811\u3001\u679c\u852c\u690d\u7269\u540d\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'agriculture', 'apple', 'bamboo', 'bark', 'bean', 'berry', 'bloom',
            'blossom', 'botanical', 'bouquet', 'branch', 'bud', 'bulb', 'bush',
            'cabbage', 'cactus', 'carrot', 'cedar', 'cherry', 'chestnut',
            'climate', 'clover', 'coconut', 'compost', 'corn', 'cotton',
            'crop', 'cultivate', 'daisy', 'decay', 'dig', 'drain', 'drought',
            'ecology', 'elm', 'exotic', 'farm', 'fern', 'fertile', 'fertilizer',
            'fig', 'flora', 'flour', 'flower', 'forest', 'fruit', 'fungus',
            'garden', 'garlic', 'grain', 'grape', 'grass', 'greenhouse', 'grow',
            'harvest', 'hay', 'herb', 'ivy', 'jungle', 'lavender', 'lawn',
            'leaf', 'lemon', 'lettuce', 'lily', 'maple', 'meadow', 'melon',
            'moss', 'mushroom', 'nature', 'nut', 'oak', 'olive', 'onion',
            'orange', 'orchid', 'organic', 'palm', 'peach', 'pear', 'pea',
            'petal', 'pine', 'plant', 'plum', 'pollen', 'potato', 'prune',
            'pumpkin', 'rainforest', 'rice', 'root', 'rose', 'rye', 'seed',
            'shrub', 'soil', 'species', 'stem', 'strawberry', 'sunflower',
            'thorn', 'timber', 'tobacco', 'tomato', 'tree', 'tropical', 'tulip',
            'vegetation', 'vine', 'violet', 'water', 'weed', 'wheat', 'willow',
            'wood',
        ]
    },
    'festivals': {
        'name': '\u8282\u65e5\u6587\u5316',
        'emoji': '\U0001f384',
        'description': '\u4e2d\u897f\u65b9\u8282\u65e5\u3001\u4e60\u4fd7\u3001\u5e86\u5178\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'ancestor', 'anniversary', 'annual', 'applause', 'assembly',
            'atmosphere', 'balloon', 'banquet', 'barbecue', 'bell', 'bless',
            'bow', 'bride', 'calendar', 'candle', 'candy', 'carol', 'carnival',
            'celebrate', 'celebration', 'ceremony', 'charity', 'cheer',
            'chocolate', 'church', 'clap', 'concert', 'confetti', 'congratulate',
            'costume', 'countdown', 'crown', 'culture', 'custom', 'dance',
            'decorate', 'decoration', 'dessert', 'display', 'donation', 'dragon',
            'dress', 'drum', 'eve', 'event', 'exchange', 'fairy', 'family',
            'fan', 'feast', 'festival', 'firework', 'flag', 'float', 'flower',
            'folk', 'fortune', 'fun', 'gather', 'gift', 'glow', 'god',
            'greet', 'guest', 'halloween', 'harvest', 'heritage', 'holiday',
            'honour', 'hymn', 'invite', 'joy', 'lantern', 'legend', 'light',
            'luck', 'magic', 'march', 'mask', 'memorial', 'memory', 'miracle',
            'moon', 'music', 'myth', 'occasion', 'offering', 'parade', 'party',
            'peace', 'photograph', 'picnic', 'prayer', 'present', 'procession',
            'pumpkin', 'receive', 'reception', 'reunion', 'ribbon', 'ritual',
            'saint', 'season', 'sing', 'spirit', 'star', 'symbol', 'temple',
            'thanksgiving', 'toast', 'torch', 'tradition', 'treat', 'tribute',
            'turkey', 'valentine', 'volunteer', 'wedding', 'wish', 'worship',
            'wrap',
        ]
    },
    'cooking': {
        'name': '\u70f9\u996a\u53a8\u623f',
        'emoji': '\U0001f373',
        'description': '\u70f9\u996a\u65b9\u6cd5\u3001\u53a8\u5177\u3001\u8c03\u6599\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'bake', 'barbecue', 'basin', 'baste', 'beat', 'blend', 'blender',
            'boil', 'bone', 'bottle', 'bowl', 'braise', 'bread', 'broil',
            'broth', 'brown', 'brush', 'burn', 'butter', 'cabinet', 'carve',
            'chilli', 'chop', 'cinnamon', 'clean', 'coat', 'combine', 'cook',
            'counter', 'cream', 'crush', 'cube', 'cup', 'cut', 'deep',
            'defrost', 'dice', 'dish', 'dissolve', 'drain', 'dressing', 'dry',
            'egg', 'extract', 'fat', 'fill', 'filter', 'flame', 'flavour',
            'flour', 'fold', 'food', 'fork', 'freeze', 'fresh', 'fridge',
            'fry', 'ginger', 'glass', 'grate', 'gravy', 'grease', 'grill',
            'grind', 'heat', 'herb', 'honey', 'ingredient', 'jar', 'juice',
            'kettle', 'knife', 'knead', 'ladle', 'lid', 'liquid', 'marinade',
            'marinate', 'mash', 'measure', 'melt', 'microwave', 'mince', 'mix',
            'mustard', 'oil', 'oven', 'pan', 'paste', 'peel', 'pepper',
            'pinch', 'plate', 'poach', 'portion', 'pot', 'pour', 'preserve',
            'press', 'raw', 'recipe', 'reduce', 'refrigerate', 'rinse',
            'roast', 'roll', 'salt', 'sauce', 'season', 'serve', 'shallow',
            'simmer', 'sink', 'slice', 'smoke', 'soak', 'soup', 'spatula',
            'spice', 'spoon', 'spray', 'sprinkle', 'squeeze', 'steam', 'stew',
            'stir', 'stock', 'stove', 'strain', 'sugar', 'tablespoon',
            'taste', 'temperature', 'tender', 'thaw', 'thermometer', 'toast',
            'toss', 'trim', 'vinegar', 'warm', 'wash', 'water', 'whip',
            'whisk',
        ]
    },
    'law': {
        'name': '\u6cd5\u5f8b\u6cd5\u89c4',
        'emoji': '\u2696\ufe0f',
        'description': '\u65e5\u5e38\u6cd5\u5f8b\u672f\u8bed\u76f8\u5173\u8bcd\u6c47',
        'words': [
            'abolish', 'abuse', 'accuse', 'acquit', 'act', 'allege', 'amend',
            'appeal', 'appoint', 'arbitrate', 'arrest', 'assault', 'attorney',
            'authority', 'bail', 'ban', 'bankrupt', 'bar', 'bind', 'blame',
            'breach', 'bribe', 'burden', 'case', 'charge', 'civil', 'claim',
            'clause', 'client', 'code', 'commit', 'compensation', 'complaint',
            'comply', 'confess', 'confiscate', 'consent', 'constitution',
            'contract', 'convict', 'copyright', 'corrupt', 'counsel', 'court',
            'crime', 'criminal', 'custody', 'damage', 'deceive', 'decree',
            'defence', 'defendant', 'detain', 'discriminate', 'dispute',
            'dissolve', 'document', 'draft', 'duty', 'enforce', 'entitle',
            'estate', 'evidence', 'execute', 'exempt', 'extradite', 'federal',
            'felony', 'file', 'fine', 'forge', 'fraud', 'freedom', 'guilty',
            'hearing', 'heir', 'illegal', 'imprison', 'indict', 'inherit',
            'injustice', 'innocent', 'inspect', 'insurance', 'intellectual',
            'investigate', 'jail', 'judge', 'jury', 'justice', 'juvenile',
            'kidnap', 'law', 'lawsuit', 'lawyer', 'legal', 'legislate',
            'legitimate', 'liability', 'licence', 'litigate', 'mandate',
            'misconduct', 'murder', 'negotiate', 'oath', 'offence', 'offend',
            'pardon', 'parole', 'patent', 'penalty', 'petition', 'plead',
            'police', 'precedent', 'prison', 'prosecute', 'prove', 'punish',
            'regulate', 'release', 'remedy', 'repeal', 'right', 'rob', 'rule',
            'sanction', 'sentence', 'settle', 'smuggle', 'statute', 'steal',
            'sue', 'suspect', 'testify', 'testimony', 'theft', 'trial',
            'tribunal', 'verdict', 'victim', 'violate', 'warrant', 'witness',
        ]
    },
}


def load_csv_translations(csv_path):
    """Load term -> translation mapping from oxford_5000_cleaned.csv"""
    translations = {}
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            term = row['term'].strip().lower()
            translation = row['translation'].strip()
            # Keep the first occurrence (some words may appear multiple times with different CEFR)
            if term not in translations:
                translations[term] = translation
    return translations


def check_audio(word, audio_dir):
    """Check if audio file exists for a word, return filename or None."""
    filename = f"{word}.wav"
    filepath = os.path.join(audio_dir, filename)
    if os.path.isfile(filepath):
        return filename
    return None


def escape_js_string(s):
    """Escape a string for use inside JS double-quoted string."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def generate_wordbook_js(scene_id, scene_data, translations, audio_dir):
    """Generate JS file content for a single scene wordbook."""
    words_js_lines = []
    missing_words = []
    audio_found = 0
    audio_missing = 0

    for word in scene_data['words']:
        word_lower = word.strip().lower()

        # Look up translation: first CSV, then EXTRA_TRANSLATIONS
        meaning = translations.get(word_lower)
        if meaning is None:
            meaning = EXTRA_TRANSLATIONS.get(word_lower)
        if meaning is None:
            meaning = EXTRA_TRANSLATIONS.get(word)
        if meaning is None:
            missing_words.append(word)
            meaning = word  # fallback: use the word itself

        # Check audio
        audio_file = check_audio(word_lower, audio_dir)
        # Also try with the original casing / hyphenated form
        if audio_file is None and word != word_lower:
            audio_file = check_audio(word, audio_dir)

        audio_str = f'"{escape_js_string(audio_file)}"' if audio_file else 'null'

        if audio_file:
            audio_found += 1
        else:
            audio_missing += 1

        word_escaped = escape_js_string(word_lower)
        meaning_escaped = escape_js_string(meaning)

        words_js_lines.append(
            f'                {{ word: "{word_escaped}", meaning: "{meaning_escaped}", audio: {audio_str} }}'
        )

    # Build the full JS content
    name_escaped = escape_js_string(scene_data['name'])
    emoji_escaped = escape_js_string(scene_data['emoji'])
    desc_escaped = escape_js_string(scene_data['description'])

    words_block = ',\n'.join(words_js_lines)

    js_content = f"""registerWordbook('scene_{scene_id}', {{
    name: "{name_escaped}",
    emoji: "{emoji_escaped}",
    group: 'scene',
    description: "{desc_escaped}",
    levels: {{
        all: {{
            name: "{emoji_escaped} \u5168\u90e8",
            words: [
{words_block}
            ]
        }}
    }}
}});
"""
    return js_content, missing_words, audio_found, audio_missing


def main():
    # Load CSV translations
    print(f"Loading CSV from: {CSV_PATH}")
    translations = load_csv_translations(CSV_PATH)
    print(f"Loaded {len(translations)} terms from CSV.")

    # Ensure output directory exists
    os.makedirs(WORDBOOKS_DIR, exist_ok=True)
    print(f"Output directory: {WORDBOOKS_DIR}")
    print(f"Audio directory: {AUDIO_DIR}")
    print()

    total_words = 0
    total_audio_found = 0
    total_audio_missing = 0
    all_missing = {}

    for scene_id, scene_data in SCENE_CATEGORIES.items():
        js_content, missing_words, audio_found, audio_missing = generate_wordbook_js(
            scene_id, scene_data, translations, AUDIO_DIR
        )

        output_path = os.path.join(WORDBOOKS_DIR, f'scene_{scene_id}.js')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(js_content)

        word_count = len(scene_data['words'])
        total_words += word_count
        total_audio_found += audio_found
        total_audio_missing += audio_missing

        status = f"  scene_{scene_id}.js  =>  {word_count:>3} words  |  audio: {audio_found} found, {audio_missing} missing"
        if missing_words:
            status += f"  |  NO TRANSLATION: {missing_words}"
            all_missing[scene_id] = missing_words
        print(status)

    print()
    print(f"{'='*60}")
    print(f"SUMMARY")
    print(f"{'='*60}")
    print(f"Total scenes generated:  {len(SCENE_CATEGORIES)}")
    print(f"Total words across all:  {total_words}")
    print(f"Total audio found:       {total_audio_found}")
    print(f"Total audio missing:     {total_audio_missing}")

    if all_missing:
        print()
        print(f"Words with NO translation (using word as fallback):")
        for sid, words in all_missing.items():
            print(f"  {sid}: {words}")

    print()
    print("Done! All scene wordbook files generated.")


if __name__ == '__main__':
    main()
